### ISSUE TITLE
Broken configuration in api security audit docs

### ISSUE THREAD

**Issue by tgtshanika** [wso2/docs-apim#1001]
Broken config in Step 2 https://apim.docs.wso2.com/en/latest/learn/api-security/configuring-api-security-audit/#enable-audit-api-for-all-tenants

**Comment by Mariangela** [comment]
@sanjulamadurapperuma , please share your input on this Git issue.

**Comment by sanjulamadurapperuma** [comment]
This issue has been fixed in [wso2/docs-apim#993](https://github.com/wso2/docs-apim/pull/993) and [wso2/docs-apim#1000](https://github.com/wso2/docs-apim/pull/1000)

**Comment by Mariangela** [comment]
I am closing this issue as this has already been fixed.
