### ISSUE TITLE
TM Health check ports are incorrect

### ISSUE THREAD

**Issue by tgtshanika** [wso2/docs-apim#1006]
https://apim.docs.wso2.com/en/latest/install-and-setup/installation-guide/basic-health-checks/#basic-health-checks

1) TM Health check ports are incorrect. The health check ports in TM has to be corrected as 7611 -> 9611 and remove 7711
2) Broken curl commands
3) Incorrect link for product profiles page

**Comment by Mariangela** [comment]
@tgtshanika , can you be more specific for the comment "Broken curl commands".
 Is this applicable to 3.0.0, 3.1.0 and master branches?

**Comment by tgtshanika** [comment]
<img width="791" alt="Screen Shot 2020-06-08 at 8 00 21 PM" src="https://user-images.githubusercontent.com/4471756/84042508-cb6eb080-a9c2-11ea-9058-5effc69d5a14.png">

**Comment by Mariangela** [comment]
Fix for

https://github.com/wso2/docs-apim/pull/1378 | 3.0.0
-- | --
https://github.com/wso2/docs-apim/pull/1377 | 3.1.0
https://github.com/wso2/docs-apim/pull/1376 | master
