### ISSUE TITLE
Steps for product profile optimizations is missing info

### ISSUE THREAD

**Issue by msm1992** [wso2/docs-apim#1023]
**Description:**
In APIM 3.1.0 after profile optimization, the DB is changes to mysql with following DB configurations.

Thus, we have to have copied the connector jar to lib folder and created dbs before executing server startup script. It is worthwhile to mention, that the user is required to copy mysql connector jar to lib folder, create databases and change this DB configs to match their environment (with correct host, username and password)

```
[database.apim_db]
type = "mysql"
hostname = "localhost"
name = "apimgt_db"
port = "3306"
username = "root"
password = "root"

[database.shared_db]
type = "mysql"
hostname = "localhost"
name = "shared_db"
port = "3306"
username = "root"
password = "root"
```

**Affected Product Version:**
APIM 3.1.0

**Steps to reproduce:**
Follow the steps in https://apim.docs.wso2.com/en/3.1.0/install-and-setup/deploying-wso2-api-manager/distributed-deployment/product-profiles/ doc.

**Comment by Mariangela** [comment]
@msm1992 , need more clarity in this regard.

**Comment by Mariangela** [comment]
@msm1992 , thanks for the clarification with regard to this issue. Please let us know whether this issue is applicable to the APIM 3.0.0 docs as well.

Fixed in -

https://github.com/wso2/docs-apim/pull/1423 | 3.1.0
-- | --
https://github.com/wso2/docs-apim/pull/1424 | master
