### ISSUE TITLE
APIM 3.1.0 docs points to API MGW 3.0.1 instead of 3.1.0

### ISSUE THREAD

**Issue by lahirus** [wso2/docs-apim#1028]
**Description:**
Doc at 
https://apim.docs.wso2.com/en/latest/

APIM 3.1.0 docs points to API MGW 3.0.1 instead of 3.1.0

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 3.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Fixed in -
- 3.1.0 - https://github.com/wso2/docs-apim/pull/1037
- 3.2.0 -  https://github.com/wso2/docs-apim/pull/1038
