### ISSUE TITLE
Irrelevant migrated doc page from 2.x

### ISSUE THREAD

**Issue by tmkasun** [wso2/docs-apim#1030]
**Description:**

I found this page\[1\] in the search result, Which is no longer valid documentation for 3.x

\[1\]: https://apim.docs.wso2.com/en/latest/learn/tutorials/create-and-publish-an-api/#create-and-publish-an-api

**Affected Product Version:**

- 3.1.0 Docs
- 3.0.0 Docs

**Comment by Mariangela** [comment]
Fixed in -
- 3.0.0 - https://github.com/wso2/docs-apim/pull/1039
- 3.1.0 - https://github.com/wso2/docs-apim/pull/1038
- 3.2.0 - https://github.com/wso2/docs-apim/pull/1037
