### ISSUE TITLE
Typo error in Basic Auth documentation

### ISSUE THREAD

**Issue by niranjanghule** [wso2/docs-apim#1043]
**Description:**
The word "resources" is misspelled in documentation of Basic Auth.
Its incorrectly written as "resourses". It should be "resources".
![wso2_error](https://user-images.githubusercontent.com/10476564/79457199-73907a80-800d-11ea-9448-3ef62226a5d4.PNG)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@niranjanghule , thanks for reporting!


I fixed this issue in the following docs:
- API-M 2.1.0 - https://docs.wso2.com/display/AM210/Basic+Auth
- API-M 2.2.0 - https://docs.wso2.com/display/AM220/Basic+Auth
- API-M 2.5.0 - https://docs.wso2.com/display/AM250/Basic+Auth
- API-M 2.6.0 - https://docs.wso2.com/display/AM210/Basic+Auth
- It was not applicable to API-M 3.0.0 and above
