### ISSUE TITLE
Link not working 

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/docs-apim#1051]
**Description:**
Url "Configuring API Manager for SSO" in the doc https://apim.docs.wso2.com/en/3.1.0/learn/api-security/oauth2/grant-types/saml-extension-grant/ is not working.

**Comment by chamilaadhi** [comment]
Also command line tool in the **Download the command-line tool from here and extract the ZIP file.** is not working as well

**Comment by Mariangela** [comment]
> Also command line tool in the **Download the command-line tool from here and extract the ZIP file.** is not working as well

Fixed in https://github.com/wso2/docs-apim/pull/1048

**Comment by Mariangela** [comment]
> **Description:**
> Url "Configuring API Manager for SSO" in the doc https://apim.docs.wso2.com/en/3.1.0/learn/api-security/oauth2/grant-types/saml-extension-grant/ is not working.

Fixed in -

https://github.com/wso2/docs-apim/pull/1218 | master
-- | --
https://github.com/wso2/docs-apim/pull/1216 | 3.1.0
https://github.com/wso2/docs-apim/pull/1217 | 3.0.0
