### ISSUE TITLE
Arrow buttons are broken

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#1054]
**Description:**
Mushthaq Rumy reported as follows
Arrow buttons are broken in the docs. 
<img width="293" alt="Screenshot 2020-04-15 at 10 16 37" src="https://user-images.githubusercontent.com/5195851/79566157-b450c800-80cf-11ea-99fc-1b97197d26ab.png">

This is applicable to docs when the version appears in the URL. Example:
https://apim.docs.wso2.com/en/3.0.0/learn/design-api/create-api/create-a-rest-api/
https://apim.docs.wso2.com/en/3.1.0/learn/design-api/create-api/create-a-rest-api/

**Comment by erangatl** [comment]
This is due to a path resolving issue with the version number. Resolved with the help of the digital operations team. 
This redirection we need to do manually for every version release.
