### ISSUE TITLE
Page not found in 3.0.0 redirection is wrong

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#1056]
**Description:**
When there is a page not available in 3.0.0 it takes the user to the 3.1.0 page not found page.

Clicked on this
<img width="1679" alt="Screen Shot 2020-04-17 at 8 56 12 PM" src="https://user-images.githubusercontent.com/5195851/79585947-20422900-80ee-11ea-8d83-43d31f99290a.png">

Redirected to this
<img width="1680" alt="Screen Shot 2020-04-17 at 8 55 00 PM" src="https://user-images.githubusercontent.com/5195851/79585983-2df7ae80-80ee-11ea-9b3b-71c65ebe1b17.png">

**Comment by erangatl** [comment]
Fixed
https://apim.docs.wso2.com/en/3.0.0/learn/analytics/adding-third-party-non-osgi-libraries/test
https://apim.docs.wso2.com/en/3.1.0/learn/design-api/create-api/create-a-rest-api/test

For future releases also, this needs to be fixed by the digital operations team

**Comment by Mariangela** [comment]
@erangatl , thanks loads for looking into this issue and resolving it.
