### ISSUE TITLE
bot detection documentation isssue

### ISSUE THREAD

**Issue by kalevivek11** [wso2/docs-apim#1059]
### Description:
i am following link
https://apim.docs.wso2.com/en/latest/learn/api-security/threat-protection/bot-detection/
### Steps to reproduce:
below the image on the portal is not as per YAML file of the worker, the description is mismatched
![image](https://user-images.githubusercontent.com/10954248/79432292-3e723100-7fe9-11ea-954b-7b2806536086.png)

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by Mariangela** [comment]
@nadeepoornima , please share your input with regard to this git issue.

**Comment by nadeepoornima** [comment]
Seems like it there is the wrong description for the AM_DB data source config in the deployment.yaml. The description belongs to the Micro Gateway data source description. The description should correctly like "The data source used for AM_DB which shared from APIM". Others are ok.

**Comment by Mariangela** [comment]
Fixed in -
- 3.1.0 - https://github.com/wso2/docs-apim/pull/1067
- Master branch - https://github.com/wso2/docs-apim/pull/1068
