### ISSUE TITLE
Doc Feedback: Need step document

### ISSUE THREAD

**Issue by arijit-chaudhury** [wso2/docs-apim#1060]
Location : https://apim.docs.wso2.com/en/latest/develop/product-apis/devportal-v1/
I am new in WSO2 and trying to use the rest APIs for user self signup taking help from "https://apim.docs.wso2.com/en/latest/develop/product-apis/devportal-v1/#/Sign%20Up/post_self_signup" and unfortunately every time I am getting error 404 not found (Invalid URL., RESOURCE = /api/am/store/v1.0/self-signup). Is there step document on how to invoke these REST APIs? Like first I need to enable some configuration then generate the token and third call the REST API with the token.
Thanks.

**Comment by Mariangela** [comment]
@fazlan-nazeem , can you please share your input with regard to this git issue.

**Comment by chamilaadhi** [comment]
@arijit-chaudhury are you invoking the gateway ports for this api? (8243 or 8280 port) . Normally **Invalid URL., RESOURCE =**  errors come from the gateway nodes when you access an invalid resource.

For the above endpoint to work, you need to access the 9443 port instead of 8243/8280 port

**Comment by fazlan-nazeem** [comment]
Hi @arijit-chaudhury I hope you mean a doc like this https://docs.wso2.com/display/AM260/apidocs/publisher/#guide

This is also tracked in the git issue https://github.com/wso2/docs-apim/issues/889 and we are hoping to fix the rest api guide with those steps soon.

**Comment by arijit-chaudhury** [comment]
Hi Fazlan,
I am trying to create user in WSO2 API Manager 3.1.0 by using REST API. Previously I was using WSO2 API Manager 2.6.0 and by using jaggery apps API (add-user.jag) I was able to create user to access store. Now after upgrade to version 3.1 the jaggery apps APIs are not working. So I am looking for REST APIs to do the same in APIM 3.1. As I shared the link https://apim.docs.wso2.com/en/latest/develop/product-apis/devportal-v1/#/Sign%20Up/post_self_signup in my last chat I was tried with localhost:9443 but having error of 404 resource not found. The link you have shared is for version 2.6.0, that I am not looking for. 
Do you have any guideline how to access the REST APIs of version 3.1?
Regards.

**Comment by Mariangela** [comment]
@arijit-chaudhury , the API-M 3.1.0 REST API docs have been added and a getting started guide has been added with PR [1].

[1] https://github.com/wso2/docs-apim/pull/1130
