### ISSUE TITLE
Incorrect file pattern provided for configuring Log rollover based on file size

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/docs-apim#1061]
**Description:**
The file pattern provided for configuring logs rollover based on file size is incorrect. According to the provided file pattern for configuring carbon logs and audit logs for size based rollover,  a new log file is created each second even though the configured file size is not reached.
In addition , the file name provided in the file pattern for audit logs also should be corrected.

[1] - [https://apim.docs.wso2.com/en/latest/administer/product-administration/monitoring/logging/managing-log-growth/](https://apim.docs.wso2.com/en/latest/administer/product-administration/monitoring/logging/managing-log-growth/l)

**Comment by Mariangela** [comment]
@shilmyhasan , can you please provide the solution to fix this issue by mentioning specifics as to what needs to be added to fix this issue (Such as if the file name is incorrect what is the correct file name etc.) .

**Comment by shilmyhasan** [comment]
The time pattern appended to the file pattern "**wso2carbon-%d{MM-dd-yyyy HH-mm-ss}.log**" should be corrected as "**wso2carbon-%d{MM-dd-yyyy}-%i.log**"

So the file pattern provided for size base rollover of carbon log files looks as follows 

- appender.CARBON_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/wso2carbon-%d{MM-dd-yyyy HH-mm-ss}.log

should be corrected as

- appender.CARBON_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/wso2carbon-%d{MM-dd-yyyy}-%i.log

Also in the file pattern for provied audit logs both file name and the patter are wrong,  provided pattern in doc is as follows.

- appender.AUDIT_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/wso2carbon-%d{MM-dd-yyyy HH-mm-ss}.log


corrected as

- appender.AUDIT_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/audit-%d{MM-dd-yyyy}-%i.log

**Comment by Mariangela** [comment]
@shilmyhasan , is this applicable to both APIM 3.1.0 and 3.0.0 as well?

**Comment by shilmyhasan** [comment]
Tested only in 3.1.0 but the same logic should be applicable in 3.0.0 as well

**Comment by Mariangela** [comment]
Fixed in -
- 3.1.0 - https://github.com/wso2/docs-apim/pull/1067
- 3.2.0 - https://github.com/wso2/docs-apim/pull/1071

**Comment by Mariangela** [comment]
Fixed in 3.0.0 - https://github.com/wso2/docs-apim/pull/1072
