### ISSUE TITLE
Need to add information about configuring Analytics dashboard with APIM distributed setup.

### ISSUE THREAD

**Issue by Gayanthakaushal** [wso2/docs-apim#1062]
**Description:**
Need to provide the steps to configure the Analytics component with a distributed APIM setup.

**Suggested Labels:**
3.0.0 3.1.0

**Comment by Mariangela** [comment]
@Gayanthakaushal , @ruks confirmed that we already have the content in API-M 3.1.0 [1]. If you have any further concerns, we can close this Git issue.


[1] https://apim.docs.wso2.com/en/latest/install-and-setup/deploying-wso2-api-manager/configure-apim-analytics/configure-worker/active-active/

**Comment by Mariangela** [comment]
Closing this Git issue as @ruks has confirmed that we already have the documentation.
