### ISSUE TITLE
Doc Feedback: Step 5, point 2 should explicitly state the Trust Store alias

### ISSUE THREAD

**Issue by gspadotto** [wso2/docs-apim#1069]
Hi, 
 in the page "Configuring WSO2 Identity Server as Key Manager", step 5, point 2
it should be highlighted that the public key of the IS should be imported in APIM's
trust store under the specific alias "gateway_certificate_alias", as explained in
the page "JWT Access Tokens".

This is to avoid that someone whose only goal is to set up IS-as-KM 
wastes time because this requirement is not highlighted in the steps he/she is following.

Location : https://apim.docs.wso2.com/en/3.0.0/install-and-setup/deploying-wso2-api-manager/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/

**Comment by Mariangela** [comment]
@tharindu1st , can you please share your input in this regard.

**Comment by tharindu1st** [comment]
@Mariangela  +1 on doing this change as a note

**Comment by Mariangela** [comment]
Fixed in 
- https://github.com/wso2/docs-apim/pull/1072 | 3.0.0
- https://github.com/wso2/docs-apim/pull/1067 | 3.1.0
- https://github.com/wso2/docs-apim/pull/1071 | 3.2.0
