### ISSUE TITLE
Improve the docs on backend secured with OAuth2

### ISSUE THREAD

**Issue by pubudu538** [wso2/docs-apim#1078]
**Description:**
In the doc, we say as the following.

You cannot call backend services secured with OAuth through APIs created in the API Publisher. At the moment, you can call only services secured with username/password (Basic Auth/ Digest Auth).

Via an extension point, you can call a backend which is secured via OAuth2. This feature will be available in the product OOB in the next release.

https://apim.docs.wso2.com/en/latest/learn/design-api/endpoints/endpoint-types/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@pubudu538 , we need more clarification in this regard. We will reach out to you soon.

**Comment by Sarangan0219** [comment]
This has been updated in 3.0.0 and 3.1.0 docs.
In addition to this, we can point to this article https://medium.com/@athiththan11/wso2-api-manager-oauth2-protected-endpoint-aa51c62f0ad7 in Configuring OAuth2 Protected Endpoints.

WDYT @pubudu538 ?

**Comment by samgnaniah** [comment]
Looks like this is fixed so I'm closing this.
