### ISSUE TITLE
Add External IDP configuration for SAML SSO

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/docs-apim#1080]
**Description:**

The documentation https://apim.docs.wso2.com/en/3.0.0/learn/extensions/saml2-sso/configuring-external-idp-through-identity-server-for-sso/ has configurations for external IDP via WSO2 IS. We have to add documentation on configuring external IDP SAML SSO without involving the WSO2 IS.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
apim 3.0.0, apim 3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
This is not applicable for API-M 3.1.0, because we have [1].

[1] https://apim.docs.wso2.com/en/3.1.0/install-and-setup/sso/okta-as-an-external-idp-using-saml/

**Comment by Mariangela** [comment]
@tgtshanika , please comment whether this Git issue is still applicable for API-M 3.0.0.

**Comment by tgtshanika** [comment]
This is fixed in https://apim.docs.wso2.com/en/latest/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-oidc/ and https://apim.docs.wso2.com/en/latest/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-saml/
