### ISSUE TITLE
Doc Feedback: Duplicate enable_user_claims entry

### ISSUE THREAD

**Issue by gspadotto** [wso2/docs-apim#1082]
Location : https://apim.docs.wso2.com/en/latest/reference/config-catalog/#jwt-configurations There are two entries for the "enable_user_claims" configuration key that are almost identical.

Maybe they should be merged into one:

> enable_user_claims	
> string

> Default: FALSE
> Possible Values: TRUE/FALSE
> If TRUE, user store claims will be included in the generated JWT.

**Comment by Mariangela** [comment]
@tharindu1st , please provide your input.
