### ISSUE TITLE
Need to update REST API docs in APIM 3.1.0 version

### ISSUE THREAD

**Issue by npamudika** [wso2/docs-apim#1088]
**Description:**
In APIM 3.1.0 doc space, the REST API versions has not been updated.

The correct version should be **v0.16**.

Please update the following pages accordingly.

1. https://apim.docs.wso2.com/en/3.1.0/develop/product-apis/publisher-v0.15/
2. https://apim.docs.wso2.com/en/3.1.0/develop/product-apis/devportal-v0.15/
3. https://apim.docs.wso2.com/en/3.1.0/develop/product-apis/admin-v1/

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/1130
