### ISSUE TITLE
Improvements to monetization document

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/docs-apim#1090]
**Description:**
**Issue 1**
The doc [1] provided the following instruction for configuring workflows
![image](https://user-images.githubusercontent.com/24529961/80103806-22473480-8593-11ea-802d-35b66ed49ec7.png)
Most of the customers get this step wrong by adding a new subscription creation workflow executor without commenting the existing default workflow executors. Its better to add a note that the existing default workflow executors should be commented or deleted.

**Issue 2**
The link provided here(in orange letters) does not work.
![image](https://user-images.githubusercontent.com/24529961/80104108-e06abe00-8593-11ea-801a-d4b237369710.png)

[1] [https://apim.docs.wso2.com/en/latest/learn/api-monetization/monetizing-an-api/](https://apim.docs.wso2.com/en/latest/learn/api-monetization/monetizing-an-api/)

**Suggested Assignees:**
@Mariangela

**Comment by Mariangela** [comment]
Fixed in 

https://github.com/wso2/docs-apim/pull/1377 | 3.1.0
-- | --
https://github.com/wso2/docs-apim/pull/1376 | master
https://github.com/wso2/docs-apim/pull/1378 | 3.0.0
