### ISSUE TITLE
Recommendations on token persistence

### ISSUE THREAD

**Issue by lkokila** [wso2/docs-apim#1091]
**Description:**
The recommended approach regarding Synchronous/Asynchronous token persistence should be included in the following document. 

[1]. https://apim.docs.wso2.com/en/3.0.0/learn/api-security/oauth2/token-persistence/#token-persistence

**Affected Product Version:**
APIM-3.0.0/ APIM-3.1.0

**Comment by Mariangela** [comment]
@bhathiya , please share your input and feedback on the info required to resolve this Git issue.

**Comment by bhathiya** [comment]
@Mariangela let's get a copy of this and update.

https://is.docs.wso2.com/en/5.9.0/setup/token-persistence/#asynchronous-token-persistence
