### ISSUE TITLE
Doc Feedback: Monetization

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#1105]
Location : https://apim.docs.wso2.com/en/latest/learn/api-monetization/monetizing-an-api/

1.image is not displayed near "Stripe account after creating a paid business plan"

2. Step 5 - Monitor usage of a monetized API¶
changed/charged

**Comment by Mariangela** [comment]
Fixed in 

https://github.com/wso2/docs-apim/pull/1378 | 3.0.0
-- | --
https://github.com/wso2/docs-apim/pull/1377 | 3.1.0
https://github.com/wso2/docs-apim/pull/1376 | master
