### ISSUE TITLE
Monitoring Message Flows doc

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/docs-apim#1107]
**Description:**

Monitoring Message Flows is no longer valid for 3.1.0  as the carbon console does not have monitor tab in 3.1.0. 
[1] https://apim.docs.wso2.com/en/latest/administer/product-administration/monitoring/monitoring-message-flows/#!

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@pubudu538 , shouldn't this be listed as a removed feature after this page is removed?

**Comment by pubudu538** [comment]
+1 to include this feature under removed features.

**Comment by Mariangela** [comment]
@amilam , can you please provide a description that we can use to list this removed feature in [1]

[1] https://apim.docs.wso2.com/en/latest/getting-started/about-this-release/#what-has-changed-in-this-release

**Comment by Mariangela** [comment]
Fixed in -

https://github.com/wso2/docs-apim/pull/1109 | 3.1.0
-- | --
https://github.com/wso2/docs-apim/pull/1110 | 3.2.0
