### ISSUE TITLE
WSO2 API Manager 2.6.0 - Strict-Transport-Security: max-age=0; includeSubDomains

### ISSUE THREAD

**Issue by ritheshkarra1015** [wso2/docs-apim#1108]
**Description:**
We have set Strict-Transport-Security Max age in WSO2 configuration as per below document. Even though Max Age is showing 0 in response headers.

https://docs.wso2.com/display/ADMIN44x/Securing+Carbon+Applications#SecuringCarbonApplications-Forwebapplications

**Suggested Labels:**
WSO2 - Security Headers - HSTS

*Affected Product Version:**
API Manager 2.6.0

**OS, DB, other environment details and versions:**    
Ubuntu 16.04.05

Also, setting access-allow-control-origin while publishing the API is showing empty in response headers.

HTTP/1.1 200 OK 
Date: Fri, 17 Apr 2020 08:35:22 GMT 
Content-Type: application/json; charset=utf-8 
Transfer-Encoding: chunked Connection: keep-alive transaction_id: f266d3a8-fa64-47fe-9e23-8f4f472e6357 
Access-Control-Allow-Origin: 
Access-Control-Allow-Methods: DELETE,PUT,GET 
X-Content-Type-Options: nosniff X-Download-Options: noopen version: 2.1.8 
Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,Authorization 
X-Frame-Options: SAMEORIGIN 
Strict-Transport-Security: max-age=0; includeSubDomains 
ETag: W/"1b5a-viq2vbW3PILYNl8rhLJnW9kqDaY" 
Access-Control-Allow-Credentials: true 
Content-Encoding: gzip Vary: Origin, Accept-Encoding 
X-XSS-Protection: 1; mode=block cache-control: no-cache

Please help me in how to set Origin Host and STS in WSO2 API manager in 2.6.0

**Comment by Mariangela** [comment]
@pubudu538 , please share your input in this regard.

**Comment by Mariangela** [comment]
@bhathiya , please share your feedback in this regard.

**Comment by ritheshkarra** [comment]
Hi Team,

Can someone help me on this ?

**Comment by Mariangela** [comment]
I am closing this Git issue as this is related to API-M 2.6.0.

@[ritheshkarra](https://github.com/ritheshkarra) , it will be good if you can join us via WSO2's official Slack channels for better communication. 
WSO2's official Slack channel allows you to directly talk to our developers regarding issues or concerns about the products and also get feedback faster.

[wso2-apim.slack.com](https://wso2-apim.slack.com/) : [Join](https://join.slack.com/t/wso2-apim/shared_invite/enQtNzEzMzk5Njc5MzM0LTgwODI3NmQ1MjI0ZDQyMGNmZGI4ZjdkZmI1ZWZmMjNkY2E0NmY3ZmExYjkxYThjNzNkOTU2NWJmYzM4YzZiOWU?src=sidebar)
