### ISSUE TITLE
Unseen source IP address alert image is outdated

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/docs-apim#1112]
**Description:**
![alerts-unseen-source-ip](https://user-images.githubusercontent.com/19996612/80451273-0b149800-8941-11ea-9998-36ecd6425a42.png)
The above image in [1] is outdated. We no longer use the api name n the alert. So the api name should be removed from the image.

Examples for the the correct alert message will be as follows:
`A request from a old IP (127.0.0.1) detected by user:user1@abc.com using application:DefaultApplication owned by user1@abc.com.`

`A request from a new IP (127.0.0.1) detected by user:user1@abc.com using application:DefaultApplication owned by user1@abc.com.`

[1] https://apim.docs.wso2.com/en/latest/learn/analytics/managing-alerts-with-real-time-analytics/alert-types/#unseen-source-ip-address

**Suggested Labels:**

**Suggested Assignees:**
@Mariangela @shaniR 

**Affected Product Version:**
2.6.0
3.0.0
3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
I have sent a request to get the image redrawn. I will update the pages after I get the updated image.

**Comment by Mariangela** [comment]
Fixed in 

https://github.com/wso2/docs-apim/pull/1216 | 3.1.0
-- | --
https://github.com/wso2/docs-apim/pull/1217 | 3.0.0
https://github.com/wso2/docs-apim/pull/1218 | master
