### ISSUE TITLE
APIM 3.0.0 Publisher API documentation swagger payloads are incorrect

### ISSUE THREAD

**Issue by ujitha** [wso2/docs-apim#1124]
**Description:**
APIM 3.0.0 documentation Publisher API swagger[1]. When we use the payload it gives an error, it seems payload is incorrect. Event though I didn't try the other resources it appears Same payload is shown there too. Could you please fixed this and provide the correct payload in the swagger.

[1]https://apim.docs.wso2.com/en/3.0.0/develop/product-apis/publisher-v1/#/APIs/post_apis

**Suggested Labels:**
APIM-3.0.0 Doc

**Affected Product Version:**
APIM 3.0.0

**Comment by Mariangela** [comment]
@bhathiya , please share your feedback in this regard.

**Comment by dinusha92** [comment]
Hi @ujitha , thanks for bringing this up to attention. Yes, we notice that some of the values in the payload are incorrect. We will revise it and update.
