### ISSUE TITLE
Direct wrong document when click the "WSO2 SI Documentation" link in the Analytics Configuration Doc - APIM 3.0.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/docs-apim#1127]
**Description:**
I followed the Analytics configuring Document[1] of APIM 3.0.0. Here[1], there is a link for "WSO2 SI Documentation" as the below image.
![screenshot](https://user-images.githubusercontent.com/15210142/80733052-d06e5380-8b2a-11ea-9467-3803d917d6db.png)

When clicked this, it will not go to that SI documentation set. It is redirecting to the same page, the Analytics Configuring page[1]. 

Therefore this link should change by putting the correct link to the WSO2 SI Documentation.
This has noticed by a customer and please fix this soon.

[1]. https://apim.docs.wso2.com/en/3.0.0/learn/analytics/configuring-apim-analytics/

**Suggested Labels:**

Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM Analytics 3.0.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
Follow the steps which, have mentioned the above description.

**Related Issues:**

N/A

**Comment by Mariangela** [comment]
Fixed in -

https://github.com/wso2/docs-apim/pull/1135 | 3.0.0
-- | --
https://github.com/wso2/docs-apim/pull/1137 | 3.1.0
https://github.com/wso2/docs-apim/pull/1138 | 3.2.0/master
