### ISSUE TITLE
Incorrect Steps For Configuring Keystores in APIM Analytics

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/docs-apim#1129]
**Description:**
It was identified that the instructions for [Configuring Keystores in APIM Analytics](https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-keystores-in-apim-analytics/) are incorrect. Please note the following mistakes.

- Bug: `Securevault configuration` requests to set the private key password instead of the alias.
- Missing Step: It is required to set the correct keystore password for the `Djavax.net.ssl.keyStorePassword` system property in the `<ANALYTICS_HOME>/wso2/<profile>/bin/carbon.sh`.
- Missing Step: It is required to provide the keystore and private key password in the base64 encoded format in the `<ANALYTICS_HOME>/conf/<profile>/master-keys.yaml` file.

**Suggested Labels:**
Type/Bug, Priority/Highest

**Comment by Mariangela** [comment]
@RAVEENSR , please confirm whether this fix can be added in 3.0.0 as well.

**Comment by RAVEENSR** [comment]
> @RAVEENSR , please confirm whether this fix can be added in 3.0.0 as well.

Yes we can

**Comment by Mariangela** [comment]
Fixed in

https://github.com/wso2/docs-apim/pull/1230 | 3.1.0
-- | --
https://github.com/wso2/docs-apim/pull/1231 | master

@fazlan-nazeem and @RAVEENSR  , this document was not available in 3.0.0, should we add the entire content available in 3.1.0 in the 3.0.0 docs?

**Comment by Mariangela** [comment]
@fazlan-nazeem and @RAVEENSR  , this document was not available in 3.0.0, should we add the entire content available in 3.1.0 in the 3.0.0 docs?

**Comment by RAVEENSR** [comment]
Yes, we should add the entire section to 3.0.0.

**Comment by Mariangela** [comment]
Fixed in [1] for 3.0.0

[1] https://github.com/wso2/docs-apim/pull/1237
