### ISSUE TITLE
Need to update Theme customization page to work with AM 3.1.0

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/docs-apim#1132]
Related page:
https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/advanced-customization/

For AM 3.1.0 onwards and for AM 3.0.0 latest WUM updated pack, we ship the react related source code with the pack. As a result, we do not need to download the source and add it as mentioned in the doc.

**Comment by Mariangela** [comment]
@ruthryi , can you please do a full doc review on this page [1] for 3.1.0 and push your changes to the 3.1.0 branch and the master branch.


[1] https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/advanced-customization/

**Comment by Mariangela** [comment]
Changed the status as Ruthryi is currently working on this task.

**Comment by ruthryi** [comment]
Fixed with above PRs
