### ISSUE TITLE
Need to update REST API docs for V1

### ISSUE THREAD

**Issue by msm1992** [wso2/docs-apim#1139]
**Description:**
Please add these[1][2][3] API doc changes to REST API docs hosted at 
- https://apim.docs.wso2.com/en/latest/develop/product-apis/publisher-apis/publisher-v1/publisher-v1/ and https://apim.docs.wso2.com/en/latest/develop/product-apis/devportal-apis/devportal-v1/devportal-v1/ : for APIM 3.1.0
- https://apim.docs.wso2.com/en/3.0.0/develop/product-apis/publisher-v1/ and https://apim.docs.wso2.com/en/3.0.0/develop/product-apis/devportal-v1/ : for APIM 3.0.0

[1]. https://github.com/wso2-support/carbon-apimgt/pull/2004
[2]. https://github.com/wso2-support/carbon-apimgt/pull/2008
[3]. https://github.com/wso2-support/carbon-apimgt/pull/2007

**Affected Product Version:**
APIM 3.1.0, APIM 3.0.0

**Comment by Mariangela** [comment]
Fixed in 3.0.0 and 3.1.0.
