### ISSUE TITLE
Broken links under Adding Dynamic Endpoint section

### ISSUE THREAD

**Issue by chaminda** [wso2/docs-apim#1147]
**Description:**

Endpoint Types link in [1] is not redirecting to an valid page.

![image](https://user-images.githubusercontent.com/7115693/81439030-5c1b5c00-918b-11ea-9fa7-b3177e86c4ca.png)

[1] https://apim.docs.wso2.com/en/latest/learn/api-gateway/message-mediation/adding-dynamic-endpoints/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0, 3.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Fixed in

https://github.com/wso2/docs-apim/pull/1212 | 3.0.0
-- | --
https://github.com/wso2/docs-apim/pull/1211 | 3.1.0
https://github.com/wso2/docs-apim/pull/1213 | master
