### ISSUE TITLE
Broken Links 2.1.0 to 3.0.0 migration docs - analytics migration

### ISSUE THREAD

**Issue by chaminda** [wso2/docs-apim#1149]
**Description:**
 Getting 'page not found' when click the blow link in [1].

<img width="741" alt="image" src="https://user-images.githubusercontent.com/7115693/81526216-a1e74880-9374-11ea-80c2-a7f216075eb0.png">

[1] https://apim.docs.wso2.com/en/3.0.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300/#disabling-versioning-in-the-registry-configuration

**Comment by chaminda** [comment]
Please review and merge: https://github.com/wso2/docs-apim/pull/1180

**Comment by Mariangela** [comment]
Fixed in -

https://github.com/wso2/docs-apim/pull/1244 | 3.0.0
-- | --
https://github.com/wso2/docs-apim/pull/1245 | 3.1.0 (similar issue)
https://github.com/wso2/docs-apim/pull/1246 | master (similar issue)
