### ISSUE TITLE
Add Traffic Manager configuration in Key Manager deployment.toml file - Deploying WSO2 API-M in a Distributed Setup

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/docs-apim#1158]
**Description:**
Please add a note about configuring traffic manager host name and receiver ports in key manager deployment.toml file [1].

```
[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://Traffic-Manager-host:9611"]
traffic_manager_auth_urls = ["ssl://Traffic-Manager-host:9711"]
```
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/#step-62-configure-and-start-the-key-manager

**Suggested Labels:**
apim-distributed-setup

**Affected Product Version:**
API-M 3.0.0, API-M 3.1.0

**Comment by Mariangela** [comment]
@fazlan-nazeem , need more clarification in this regard.

**Comment by Krishanx92** [comment]
Fixed in latest documentations.
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/#!
