### ISSUE TITLE
Missing upgrade documentation to APIM 3.1.0

### ISSUE THREAD

**Issue by johnnybicgood** [wso2/docs-apim#1159]
The documentation page for upgrading to 3.1.0 is missing in Administer section.
https://apim.docs.wso2.com/en/latest/administer/updating-wso2-api-manager/

**Comment by shaniR** [comment]
We are currently working on it. The docs will be ready by next week. In the meantime, could we know from which version you are migrating from, so that we could prioritize the docs?

**Comment by johnnybicgood** [comment]
I am using 2.6.0. Thank you.

**Comment by dinusha92** [comment]
Hi @johnnybicgood , the documentation for upgrading to 3.1.0 is in Install and Setup > Upgrading WSO2 API Manager section.
Please refer the link below.
This is the same for other APIM 3.X versions as well. 
https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310/
https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320/
https://apim.docs.wso2.com/en/3.0.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300/

**Comment by dinusha92** [comment]
Since the docs are available we are closing the ticket. Thanks for reporting the issue.
