### ISSUE TITLE
Update Distributed Deployment pattern diagram

### ISSUE THREAD

**Issue by menakaj** [wso2/docs-apim#1170]
**Description:**
In the Distributed Deployment Overview Page, the deployment diagram needs to be updated with the new architecture.

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m/

New Diagram
![image](https://user-images.githubusercontent.com/10165411/81806568-45358a80-953a-11ea-8e19-5264bd797673.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamilaadhi** [comment]
Images are re-drawn and docs are updated with them
