### ISSUE TITLE
Blocker: No information on how to generate the Oauth2 token to invoke publisher APIs

### ISSUE THREAD

**Issue by shammijayasinghe** [wso2/docs-apim#1172]
**Description:**
In the document [1], We dont have the information on how to generate the Oauth2 token. Without that we can not use the publisher API at all. Fix this ASAP.

Similar documentation in AM 2.6.0 [2]

 

 

[1]https://apim.docs.wso2.com/en/3.0.0/develop/product-apis/publisher-v1/#/page-header

[2]https://docs.wso2.com/display/AM260/apidocs/publisher/#guide

**Suggested Labels:**
APIM 3.0.0

**Suggested Assignees:**
@Mariangela 

**Affected Product Version:**
APIM 3.0.0

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/1507
