### ISSUE TITLE
No documentation for 'Installing as a Windows Service' in APIM-Analytics 3.0.0

### ISSUE THREAD

**Issue by ug205** [wso2/docs-apim#1173]
**Description:**
No documentation for 'Installing as a Windows Service' in APIM-Analytics 3.0.0. 

**Affected Product Version:**
APIM-Analytics-3.0.0

**Comment by ruks** [comment]
@Mariangela Can you please check whether this doc is already available?

**Comment by ruks** [comment]
Close the issues since there are not any activities recently.
