### ISSUE TITLE
Need to change the 'Subscribing for Alerts' doc in APIM Analytics 2.1.0 

### ISSUE THREAD

**Issue by ug205** [wso2/docs-apim#1203]
**Description:**
In the documentation [1] it is mentioned that
"An API Manager publisher/subscriber can enable/disable alert types based on the alerts that he/she wants to receive individually, as well as specify a list of email addresses to which the alerts should be sent."

But for a user with only internal/publisher role assigned, the MANAGE ALERT TYPES option is not visible in the API publisher.
The option is visible for the role internal/creator.

[1].https://docs.wso2.com/display/AM210/Subscribing+for+Alerts#f2836e5d599547c59bbda4caa9c29154

**Suggested Labels:**
apim-analytics

**Affected Product Version:**
apim-analytics-2.1.0
apim-2.1.0

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
