### ISSUE TITLE
Missing DB related information in documentation

### ISSUE THREAD

**Issue by himasha** [wso2/docs-apim#1221]
Could we please add the following points in APIM documentation for latest (3.1) ?
1. Minimum db storage/sizing requirements under prerequisites. (For each db the min required storage in GB etc)  
.2. Analytics databases that are used in APIM analytics in a similar structure as [1]. 
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-databases/overview/

**Comment by Mariangela** [comment]
@fazlan-nazeem , could you please provide input on the requested information, so that it can be added to the documentation.
