### ISSUE TITLE
FAQ section and some other topics under Reference are not shown.

### ISSUE THREAD

**Issue by menakaj** [wso2/docs-apim#1235]
**Description:**
The link of the Reference tab is directed to Config Catalog and the other left menu items are not shown.

https://apim.docs.wso2.com/en/latest/reference/ConfigCatalog/

If we search for some content, it will display the correct menu.
https://apim.docs.wso2.com/en/latest/reference/faq/#why-cant-i-see-all-the-apis-that-i-published-on-the-developer-portal

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Fixed in 

https://github.com/wso2/docs-apim/pull/1373 | 3.0.0
-- | --
https://github.com/wso2/docs-apim/pull/1374 | 3.1.0
https://github.com/wso2/docs-apim/pull/1375 | master
