### ISSUE TITLE
Invalid startup order - APIM distributed setup.

### ISSUE THREAD

**Issue by chaminda** [wso2/docs-apim#1252]
**Description:**
Please correct the mentioned order in [1] which is not valid according the the dependencies of the latest product versions.

[1] 
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/product-profiles/#starting-an-api-m-profile

**Comment by mcvidanagama** [comment]
1. Traffic Manager
2. Key Manager
3. Publisher
4. Developer Portal
5. Gateway

**Comment by Mariangela** [comment]
@fazlan-nazeem , please confirm the start-up order.

**Comment by fazlan-nazeem** [comment]
Yes, the mentioned order by @mcvidanagama is correct.

**Comment by Mariangela** [comment]
Fixed in:

https://github.com/wso2/docs-apim/pull/1371 | master
-- | --
https://github.com/wso2/docs-apim/pull/1372 | 3.0.0
https://github.com/wso2/docs-apim/pull/1370 | 3.1.0
