### ISSUE TITLE
Links for the "Upgrading Process" and  "Upgrading to Log4j2" are wrong.

### ISSUE THREAD

**Issue by mcvidanagama** [wso2/docs-apim#1255]
**Description:**
In 
Install and Setup -> Upgrading WSO2 API Manager
there are multiple pages for migrating from older versions to 3.1.0
3.0.0 to 3.1.0
2.6.0 to 3.1.0
2.5.0 to 3.1.0
2.2.0 to 3.1.0
2.1.0 to 3.1.0
2.0.0 to 3.1.0
1.10.0 to 3.1.0
1.8.0/1.9.0/1.9.1 to 3.1.0

In each and every above page there is a link to Upgrading Process and there is a link to Upgrading to Log4j2
Those links are wrong and goes to 404 page not found.

Currently those links are set to
https://apim.docs.wso2.com/en/latest/upgrading-wso2-api-manager/upgrading-process
and
https://apim.docs.wso2.com/en/latest/upgrading-wso2-api-manager/upgrading-to-log4j2

Which should be corrected as 
https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-process
and 
https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-to-log4j2

**Affected Product Version:**
3.1.0 migration docs

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/1266
