### ISSUE TITLE
Confusing realm_manager.datasource config.

### ISSUE THREAD

**Issue by vinok88** [wso2/docs-apim#1269]
**Description:**
In the migration doc [1], in Step 1.4 we request to add the following config,
```
[realm_manager]
data_source = "WSO2USER_DB"
```
How do we decide the correct value for the `data_source` ?
Is this mandatory or when should we add this?

The doc is not clear for above queries. As per my findings, this config is required if we have configured `[database.user]` datasource config only. The `data_source` value should be always `WSO2USER_DB`.
Please correct the doc.

[1] - https://apim.docs.wso2.com/en/3.0.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300/
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0, 3.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@Krishanx92 , please provide input in this regard.

**Comment by shaniR** [comment]
Fixed with https://github.com/wso2/docs-apim/commit/b3f260172c7f6f863034239499e94864f5b199a2
