### ISSUE TITLE
Missing datasource config details in the migration doc

### ISSUE THREAD

**Issue by vinok88** [wso2/docs-apim#1270]
**Description:**
In the doc [1], we provide a brief introduction to the mapping between new data sources for user and registry data in a note in Step 1.3. But we need to be clear on different data sources we had. These are the mappings as per my findings.
```
USER_DB    -> [database.user]
REGISTRY_DB_GOV - [database.shared]
REGISTRY_DB_CONF_APIM - [database.conf]
API_MGT_DB - [database.apim_db]
MB_STORE_DB - This DB is now not used, not required to migrate. We internally manage this with a H2 now. No configuration required.
```
Please provide precise information. One should be pretty clear on these when doing a migration.

[1] - https://apim.docs.wso2.com/en/3.0.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0, 3.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@Krishanx92 , can you please confirm and mention how best we can incorporate this information into the docs.

**Comment by shaniR** [comment]
fixed wth https://github.com/wso2/docs-apim/pull/1438/commits/1a1fdb46e2c850a228c56b153e5c787a15fc18a5 & https://github.com/wso2/docs-apim/pull/1448/commits/0f5cfca09a2eb9f0ff065d0f2c547dac4b8f631f
