### ISSUE TITLE
Broken link in distributed deployment to product profiles.

### ISSUE THREAD

**Issue by vinok88** [wso2/docs-apim#1277]
**Description:**
LInk in [1] to product profiles in broken.

[1] - https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/#step-61-configure-the-common-configurations

**Suggested Labels:**

priority/high, type/bug

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Fixed in 
https://github.com/wso2/docs-apim/pull/1282 - 3.1.0
https://github.com/wso2/docs-apim/pull/1279 - master
https://github.com/wso2/docs-apim/pull/1280 - 3.0.0
