### ISSUE TITLE
Doc Feedback: Analytics is not the same as Streaming integrator

### ISSUE THREAD

**Issue by pedroruizaf** [wso2/docs-apim#1290]
Location : https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/

The documentation states: 
"Step 2 - Download and install WSO2 API-M Analytics
To download WSO2 API-M Analytics go to the WSO2 API Manager page, click Download to expand the installation options.Navigate to the Other Resources section, and click Analytics.
As the process of installing API-M Analytics is identical to installing WSO2 Enterprise Integrator 7.0.x - Streaming Integrator (WSO2 SI), for more information go to the WSO2 SI documentation".

The download from WSO2 API Manager > Other resources, downloads a zip file.
The documentation from Enterprise integrator refers to an installer to install the Streaming integrator. This is misleading as the zip file contains the source code and the files are not the same as the ones depicted in the Streaming integrator documentation.

I'm not sure if I need to use a Streaming integrator rather than the download of Analytics. Will this work?

Also, the docker image for the Streaming integrator seems to be stalled and incomplete as one cannot use the bash in the resulting docker container.

**Comment by Mariangela** [comment]
@fazlan-nazeem , can you please respond to this query and let us know if there is a doc gap based on this Git issue.

**Comment by fazlan-nazeem** [comment]
Yes, we have to remove references of Streaming Integrator from all the places. APIM Analytics is not based on Streaming integrator.

**Comment by Mariangela** [comment]
@fazlan-nazeem , is this applicable to 3.0.0 as well?
