### ISSUE TITLE
Recommendations on message tracing

### ISSUE THREAD

**Issue by lkokila** [wso2/docs-apim#1292]
**Description:**
According to the following EI document [1], It is not recommended to Enabling message tracing in production deployments. The same applies to the API-Manager runtime as well. But there is no information about the recommendation in the following APIM message tracing documentation [2] referring to APIM-3.1.0.

[1] https://docs.wso2.com/display/EI640/Publishing+ESB+Data+to+the+Analytics+Profile
[2] https://apim.docs.wso2.com/en/latest/learn/api-gateway/message-tracing/#message-tracing

**Comment by Mariangela** [comment]
Fixed in

https://github.com/wso2/docs-apim/pull/1377 | 3.1.0
-- | --
https://github.com/wso2/docs-apim/pull/1376 | master
https://github.com/wso2/docs-apim/pull/1378 | 3.0.0
