### ISSUE TITLE
Incorrect configuration to enable DEBUG logs

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/docs-apim#1303]
**Description:**
The following configuration provided in the documentation [1] to enable DEBUG logs for the "APILogMessageHandler" component is incorrect. 
![enable_debug_logs](https://user-images.githubusercontent.com/38277473/83951882-7ad84580-a852-11ea-8543-871989ff1f6b.png)

The provided configurations are in accordance with the log4j logging format and that should be corrected to be in accordance with the log4j2 logging format.

**Affected Product Version:**
APIM-3.1.0

[1] https://apim.docs.wso2.com/en/latest/develop/extending-api-manager/extending-gateway/writing-custom-handlers/#using-apilogmessagehandler

**Comment by Mariangela** [comment]
@fazlan-nazeem , would you be able to provide input in this regard please.

**Comment by pubudu538** [comment]
Fixed in https://github.com/wso2/docs-apim/issues/1826. Duplicate issue.
