### ISSUE TITLE
Documentation on supported cipher suites

### ISSUE THREAD

**Issue by tgtshanika** [wso2/docs-apim#1312]
**Description:**
Doc on https://docs.wso2.com/display/ADMIN44x/Supported+Cipher+Suites

This doc has to be linked from https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/configuring-transport-level-security/#disabling-weak-ciphers-for-the-tomcat-transport

**Comment by samgnaniah** [comment]
This looks like it is fixed so I am closing this issue.
