### ISSUE TITLE
An overview page for APIM product installation 

### ISSUE THREAD

**Issue by tgtshanika** [wso2/docs-apim#1313]
An overview page should be added under https://apim.docs.wso2.com/en/latest/install-and-setup/install/installing-the-product/ to list all the possible installation types. This overview can be linked from some other docs with installation guide references,

**Comment by Mariangela** [comment]
Fixed in 

https://github.com/wso2/docs-apim/pull/1333 | 3.1.0
-- | --
https://github.com/wso2/docs-apim/pull/1334 | master
https://github.com/wso2/docs-apim/pull/1335 | 3.0.0
