### ISSUE TITLE
No documentation on how to configure trustore in deployment toml

### ISSUE THREAD

**Issue by mcvidanagama** [wso2/docs-apim#1329]
if customor dont want to use default client-truststore.jks file. Correct configuration is like below. But cannot find in any documentation.
[truststore]
type= “JKS”
file = “modified-client-truststore.jks”
password= “modified_password”

**Comment by shaniR** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/1438/commits/ce0949fb9a6beb5439dda0c523b9b57f2443b756 & https://github.com/wso2/docs-apim/pull/1448/commits/b3f260172c7f6f863034239499e94864f5b199a2
