### ISSUE TITLE
Add a note on keystore types in new configuration model to the migration step.

### ISSUE THREAD

**Issue by mcvidanagama** [wso2/docs-apim#1330]
Eg: If the customer migrating from 2.1.0, there we had only one type of keystore(no primary and internal separation), and if the customer had used customer keystore, and also if they want to have the same in new environment, then they should have three entries for keystore as keystore.tls, keystore.primary and keystore.internal
This information should be clear in the migration doc.

Eg: Step5 in https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310/#step-2-upgrade-api-manager-to-310

Adding a reference link to

**Comment by shaniR** [comment]
fixed with https://github.com/wso2/docs-apim/pull/1438/commits/1391ae22ac75a782f8a166371d1d32d0ce4604de & https://github.com/wso2/docs-apim/pull/1448/commits/4d4958719cd4dabab9cad3e9ce2f65754448a39f
