### ISSUE TITLE
Additional Note: Do we need to remove or comment the registry indexing config after performing the registry indexing in the migration Process.

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/docs-apim#1331]
**Description:**
In the migration process, we need to do the registry indexing, and for that, we have to put the below config to the deployment.toml file.
```
[indexing]
re_indexing= 1
```
Most of the time, customers are asking **Do we need to remove or commented that config after completing the "re-indexing" task?** 

The **answer** is **we do not remove or comment the above config after completing registry re-indexing task,** and we can keep that as it is. 

Therefore please **add a note, by describing this point in the migration documents[1][2](Step 3, 8th point: re-indexing) of APIM 3.x.x series**. 

Please update note in each level migration documents like 2.1.0 to 3.x.x, 2.2.0 to 3.x.x, 2.5.0 to 3.x.x, 2.6.0 to 3.x.x.

[1]. https://apim.docs.wso2.com/en/3.0.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300/#step-2-upgrade-api-manager-to-300
[2]. https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310/#step-2-upgrade-api-manager-to-310

**Suggested Labels:**
**Moderate** 

**Suggested Assignees:**

**Affected Product Version:**
APIM 3.0,0 and APIM 3.1.0

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
