### ISSUE TITLE
Step 8 is missing in APIM 3.0.0 IS as KM doc

### ISSUE THREAD

**Issue by tgtshanika** [wso2/docs-apim#1332]
**Description:**

In step 8, the user should be pointed to relevant docs on deploying an all in one single, active-active and distributed deployment.

https://apim.docs.wso2.com/en/3.0.0/install-and-setup/deploying-wso2-api-manager/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/#step-8-configure-the-other-api-m-components

**Comment by Mariangela** [comment]
@ruthryi , can you please work on this issue. It is applicable to the 3.0.0, 3.1.0 and 3.2.0 docs.
