### ISSUE TITLE
Mutual SSL : File not Found: Version-3.0.0

### ISSUE THREAD

**Issue by sajal1512** [wso2/docs-apim#1336]
**Description:**
Exporting Certificate for mutual SSl erro file not found

**Suggested Labels:**
https://apim.docs.wso2.com/en/3.0.0/administer/product-security/mutual-ssl-between-api-gateway-and-backend/

Some miss print or problem in writing step-4 and step-5 of Mutual SSL in exporting certificates. wso2PubCert.crt should be same in both steps 4 and step 5. Extension should be .crt, .cert, .cer, but both should be same in Step4 and step5.

**Steps to reproduce:**
wso2PubCert.crt should be same in both steps 4 and step 5. Extension should be .crt, .cert, .cer, but both should be same in Step4 and step5.

**Comment by Chamindu36** [comment]
This issue is in progress.
