### ISSUE TITLE
Need to update APIM 3.1.0 docs for Login page customization

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/docs-apim#1338]
**Description:**
The doc [1] should be changed to suit API Manager 3.1.0 as follows.

----

It is possible to customize different sections like header and footer in the JSP pages including Login and Signup in API Manager.

The JSP pages in the following webapps can be customized.

_<API-M_HOME>/repository/deployment/server/webapps/authenticationendpoint_
_<API-M_HOME>/repository/deployment/server/webapps/accountrecoveryendpoint_

The following sections in a web page are made extensible.

**Title
Header
Footer
Cookie Policy Content
Privacy Policy Content**

Follow the steps below to customize them.

Create a folder named _**extensions**_ in _<API-M_HOME>/repository/resources_ directory.

Copy the files that you need to customize, into the new extensions folder from the _includes_ folder which is available in _<API-M_HOME>/repository/deployment/server/webapps/authenticationendpoint_ directory.

You can choose from _**header.jsp, product-title.jsp, product-footer.jsp, cookie-policy-content.jsp**_ and _**privacy-policy-content.jsp**_. If you copy the **header.jsp**, please make sure to copy the **product-title.jsp** file as well.

**Note**

Make sure to keep the name of the respective files as _header.jsp, product-title.jsp, product-footer.jsp, cookie-policy-content.jsp_ and _privacy-policy-content.jsp_.

Customize those copied files with your content. 

For example, if you want to customize the header, footer and title sections of the login and signup pages of WSO2 API Manager, change or edit the **_headerTitle, pageTitle_** and **_footerText_** in the following lines in _**header.jsp**_ file with your content. If you are doing this, please make sure to add the **product-title.jsp** file to the extensions folder along with the header.jsp file.

```
String headerTitle = "API Manager";
String pageTitle = "WSO2 API Manager";
String footerText = "WSO2 API Manager";
String faviconSrc = "libs/theme/assets/images/favicon.ico";
String logoSrc = null;
String logoHeight = "50";
String logoWidth = "50";
String logoAltText = "";
File customCSSFile = null;
String customCSS = "";
String tenantThemeDirectoryName = "";
boolean showCookiePolicy = true;
boolean showPrivacyPolicy = true;
String cookiePolicyText = null;
String privacyPolicyText = null;
```

The changes will be applied during the API Manager server startup.

**Info**

If a particular file is not present in the _<API-M_HOME>/repository/resources/extensions_ folder, the relevant file from the _<API-M_HOME>/repository/deployment/server/webapps/authenticationendpoint/includes or <API-M_HOME>/repository/deployment/server/webapps/accountrecoveryendpoint/includes_ folder will be used.

[1] https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-login-pages-for-dev-portal-and-publisher/#customizing-different-sections-of-identity-server-related-jsp-pages

**Comment by ljuillerat** [comment]
Seems like the _customAssets_ feature to store custom icons stuff is not documented

**Comment by kavishkafernando** [comment]
@ljuillerat  I will add that section and update the documentation as well.

**Comment by pubudu538** [comment]
@Jayanie is working on this issue.
