### ISSUE TITLE
'Invoke an API Secured with Mutual SSL from the Developer Portal' section is missing.

### ISSUE THREAD

**Issue by chaminda** [wso2/docs-apim#1339]
**Description:**
The section **'Invoke an API Secured with Mutual SSL from the Developer Portal'** is missing from the document.[1]

[1] https://apim.docs.wso2.com/en/latest/learn/api-security/api-authentication/secure-apis-using-mutual-ssl/#SecuringAPIswithMutualSSL-InvokeanAPIsecuredwithMutualSSLfromtheDeveloperPortal

**Comment by Mariangela** [comment]
@msm1992 , in commit [1] you have removed the "Invoke an API Secured with Mutual SSL from the Developer Portal' section. Can you please clarify whether we need to add this section back.

[1] https://github.com/wso2/docs-apim/commit/d0d898187ff938e43c6480ff713eed7d3e2f49a0

**Comment by msm1992** [comment]
Since the instructions brought forward from the previous versions did not work as instructed, we decided to remove it from the doc and add the postman based approach as the try out method in the 3.1.0 doc.
If we need to add the removed section again, then we need to revise the steps.

**Comment by shaniR** [comment]
This cannot be done via the dev portal. Hence as a solution the invoking using postman has been introduced.
