### ISSUE TITLE
MessageTracing document still referring to DAS

### ISSUE THREAD

**Issue by fjunior87** [wso2/docs-apim#1340]
**Description:**
In the message tracing documentation[1] is still referring to DAS, but it should now be updated to reflect the new APIM Analytics.

 
[1] https://apim.docs.wso2.com/en/latest/learn/api-gateway/message-tracing/#message-tracing
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Chamindu36** [comment]
This Git issue has been duplicated by https://github.com/wso2/docs-apim/issues/1609
