### ISSUE TITLE
The distributed deployment documentation has to be reorganized

### ISSUE THREAD

**Issue by tgtshanika** [wso2/docs-apim#1348]
**Description:**
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/

Some of the content in distributed deployment is outdated and the doc has to be reorganized.
- The connection details should be moved to a different doc
- The configs have to be verified

**Comment by chamilaadhi** [comment]
3.2 doc is updated with the latest architectural changes https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/
