### ISSUE TITLE
Update the readme with the changes that needs to be done to serve mkdocs in dirty reload

### ISSUE THREAD

**Issue by TanyaM** [wso2/docs-apim#1353]
**Description:**
In order to serve the mkdocs in dirty reload `mkdocs serve --dirtyreload`, attribute **strict** needs to be set to **false** in the mkdocs.yml file. 
This information needs to be added to the readme file.

**Comment by Mariangela** [comment]
Fixed in

https://github.com/wso2/docs-apim/pull/1376 | master
-- | --
https://github.com/wso2/docs-apim/pull/1377 | 3.1.0
