### ISSUE TITLE
Configure the reverse proxy settings in the product(APIM-2.6.0)

### ISSUE THREAD

**Issue by dumindurox777** [wso2/docs-apim#1382]
**Description:**
The following configuration is provided in the documentation [1] in APIM 3.1.0 to Configure the load balancer settings in the product.
Above configuration, details are not available on api manager 2.6.0 official doccumentation[2].
In order to add that details to api manager 2.6.0 official doccumentation[2].I hope the below details is required.
When using a load balancer, you need to configure the proxy host and the port to be able to work with the Proxy Server configuration.
To do that add the following to the <APIM_Home>/repository/conf/tomcat/catalina-server.xml file as shown below with property proxyPort="443”.

    <Connector protocol="org.apache.coyote.http11.Http11NioProtocol"
                   .
                    proxyPort="443”
                   .
                   .                   .
                   URIEncoding="UTF-8"/>

**Affected Product Version:**
APIM-2.6.0

This information needs to be added in APIM 2.6.0 documentation [2].
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer/

[2] https://docs.wso2.com/display/AM260/Configuring+the+Proxy+Server+and+the+Load+Balancer

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
