### ISSUE TITLE
SOAP envelopes are not sent to backend when REST API is created using SOAP 1.1 wsdl

### ISSUE THREAD

**Issue by vithu30** [wso2/docs-apim#1386]
SOAP envelopes are not sent to backend when REST API is created using SOAP 1.1 wsdl. This is because, the message type is set as "text/xml" in in-sequence and format is not set in endpoint configuration.

**Comment by ruwiniwj** [comment]
Tagging https://github.com/wso2/product-apim/issues/7130

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
