### ISSUE TITLE
[3.1] Image not loading 

### ISSUE THREAD

**Issue by himasha** [wso2/docs-apim#1387]
The diagram of this page is not loading https://apim.docs.wso2.com/en/latest/learn/design-api/publish-api/publish-to-multiple-external-api-stores/#publish-to-multiple-external-developer-portals

**Suggested Labels:**
priority:highest

**Suggested Assignees:**

**Affected Product Version:**
3.1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Fixed in 

https://github.com/wso2/docs-apim/pull/1378 | 3.0.0
-- | --
https://github.com/wso2/docs-apim/pull/1377 | 3.1.0
