### ISSUE TITLE
"disableRoleValidationAtScopeCreation" system property not documented properl

### ISSUE THREAD

**Issue by shaniR** [wso2/docs-apim#1392]
**Description:**
Reported by @johannnallathamby 

The "disableRoleValidationAtScopeCreation" system property seems not to be documented under a suitable section. It is currently only documented under the QuickStartGuide section which is not right.

This property is becoming a very critical property to know about when we combine identity federation with API Manager use cases. But not a lot of folks inside WSO2 even are aware of this property and that may be because it is documented in the wrong place.

I am not sure what would be the correct section to document this, as this property is relevant to all kinds of identity federation scenarios with APIM. If you had such a section in the APIM docs that would have been the ideal place to document this

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
Fixed in https://github.com/wso2/docs-apim/issues/1927
