### ISSUE TITLE
Need to correct the configuration of APIM-Analytics documentation.

### ISSUE THREAD

**Issue by Gayanthakaushal** [wso2/docs-apim#1393]
**Description:**
Step 4 - Configure the databases section of this document[1], it has mentioned that APIM-Analytics component is compatible with Postgres 9.5 and later. But in the future, there is a possibility to release a new Postgres version which is not compatible with APIM-Analytics-2.6.0. Therefore we need to add tested Postgres versions only for this documentation.

**Affected Product Version:**
APIM-Analytics-2.6.0

[1] - https://docs.wso2.com/display/AM260/Configuring+APIM+Analytics#standardsetup

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
