### ISSUE TITLE
APIM 3.x migrations - Turning off registry versioning section, confusing 

### ISSUE THREAD

**Issue by vinok88** [wso2/docs-apim#1403]
**Description:**
Turning off registry versioning: In which api manager profile/component should it be configured the suggested changes in terms of a distributed setup?

Also, it asks to turn off versioning in the old product and restart it. But the actual requirement is to run those provided scripts against the backup DB taken from the old setup for migration. We do not need to play with the old setup.

https://apim.docs.wso2.com/en/3.0.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300/
https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0, 3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by TheRasanjana** [comment]
I am working on this.
