### ISSUE TITLE
Enabling notification for resources in GREG when the reg_db is shared and mounted with APIM

### ISSUE THREAD

**Issue by shiranmohomad** [wso2/docs-apim#1407]
**Description:**
We were able to identify that APIM server startup is broken when we have a shared registry db between APIM and GREG. this issue occurred after enabling the notifications for resources in GREG. 

In order to overcome these issues we can change the following configurations in the registry-event-broker.xml in the GREG pack as below.

<img width="975" alt="Screen Shot 2020-06-24 at 5 17 47 PM" src="https://user-images.githubusercontent.com/54354635/85550493-a7f06a80-b63e-11ea-94e6-14e587ef8981.png">

**Steps to reproduce:**
* Share a registry database between an APIM and GREG.
* Mount the registry in the registry.xml
* Enable notifications for resources in the GREG carbon console as below.
<img width="1162" alt="Screen Shot 2020-06-24 at 11 26 07 AM" src="https://user-images.githubusercontent.com/54354635/85549988-24367e00-b63e-11ea-9104-e3f01b1af305.png">

**Comment by chamilaadhi** [comment]
We do not have any official documentation or instructions on sharing GREG with wso2 API manager
