### ISSUE TITLE
Invalid links found on SSO page

### ISSUE THREAD

**Issue by chaamini** [wso2/docs-apim#1430]
Hi,

The links for the following in https://apim.docs.wso2.com/en/latest/develop/extending-api-manager/saml2-sso/configuring-single-sign-on-with-saml2/#! leads to invalid URLs.

- Configuring Identity Server as IDP for SSO
- Configuring External IDP through Identity Server for SSO

Shall we fix this broken links?

**Comment by Mariangela** [comment]
@chaamini , thanks for reporting!

Fixed in

https://github.com/wso2/docs-apim/pull/1435 | 3.1.0
-- | --
https://github.com/wso2/docs-apim/pull/1436 | master
Checked and it is N/A | 3.0.0
