### ISSUE TITLE
Language review needed on page

### ISSUE THREAD

**Issue by YohannaFernando** [wso2/docs-apim#1440]
**Description:**
There are some typos on page  https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/styling-api-details-info-section/

**Suggested Labels:**
Documentation

**Suggested Assignees:**
Mariangela Hill, Shani Ranasinghe, Ruthryi Kulasekaran

**Affected Product Version:**
3.1

**Comment by Mariangela** [comment]
@ruthryi , please review page [1] in 3.1.0 and 3.2.0 only after you have finished the current tasks that you are working on.

[1] https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/styling-api-details-info-section/
