### ISSUE TITLE
Define Specific Runtime Artifact Directories For Persistence

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/docs-apim#1453]
**Description:**
Current [documentation](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts/#persistent-runtime-artifacts) states the <AM_HOME>/repository/deployment/server persistent runtime artifact directory needs to be persisted (and shared), especially in a deployment with high availability.

But some of the sub directories within this directory need not be persisted as no changes occur to files within these directories, during the product runtime.

Hence, only the relevant directories need to be persisted (and shared) in a default production grade deployment. These directories are as follows:

- <AM_HOME>/repository/deployment/server/synapse-configs
- <AM_HOME>/repository/deployment/server/executionplans
- <AM_HOME>/repository/deployment/server/userstores [optional]

**Suggested Labels:**
Type/Docs, Type/Improvement

**Suggested Assignees:**
@Mariangela 

**Affected Product Version:**
WSO2 API Manager version `3.1.0` and below documentation

**Comment by chirangaalwis** [comment]
Further noticed that the sub step **d** of the [documentation](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/#step-65-configure-and-start-the-gateway) for a distributed setup of API Manager also requests to share `<AM_HOME>/repository/deployment/server` directory in the Gateway deployment whereas it should ideally be the `synapse-configs` directory which should be shared.

**Comment by Krishanx92** [comment]
Duplicate https://github.com/wso2/docs-apim/issues/1556
