### ISSUE TITLE
Doc Feedback: Depreacated Answer for adding authentication headers to messages going out of the api gateway to the backend

### ISSUE THREAD

**Issue by Thumimku** [wso2/docs-apim#1457]
Location : https://apim.docs.wso2.com/en/latest/reference/faq/#how-can-i-add-authentication-headers-to-messages-going-out-of-the-api-gateway-to-the-backend

For version 3.1.0, we need to configure deployment.toml file like 
```
[apim.oauth_config]
enable_outbound_auth_header = true
```
Please change the docs

**Comment by Mariangela** [comment]
Fixed in

https://github.com/wso2/docs-apim/pull/1462 | master
-- | --
https://github.com/wso2/docs-apim/pull/1464 | 3.1.0
https://github.com/wso2/docs-apim/pull/1465 | 3.0.0
