### ISSUE TITLE
Add troubleshoot note in doc space - Changing keystores in API Manager

### ISSUE THREAD

**Issue by vithu30** [wso2/docs-apim#1467]
**Description:**
Add a note regarding with information which will help to troubleshoot the issue.

The below mentioned steps needs to be executed, after changing the default keystores come with product, if following error is seen in the log:
```
FATAL - ServiceBusInitializer Couldn't initialize the ESB...
java.lang.IllegalArgumentException: KeyStore File repository/resources/security/xxxx.jks not found
```
1. Login to management console and browse following location
```
/_system/config/repository/esb/inbound/inbound-endpoints
```
2. Remove the above mentioned registry resource and restart the server

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager/#configuring-keystores-in-wso2-api-manager

**Comment by chamilaadhi** [comment]
added for all versions
