### ISSUE TITLE
Curl command for WSS endpoint invocation for Websocket APIs not working

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/docs-apim#1471]
**Description:**
The curl command specified in documentation [1], should be changed to 

```
wscat -n -c wss://localhost:8099/echowebsocket/1.0.0 -H "Authorization: Bearer [accesstoken]"
```

There are 2 places in that document to fix. The order of -c and -n should change. -n should come before -c.

[1] https://apim.docs.wso2.com/en/latest/learn/tutorials/create-and-publish-websocket-api/#step-3-invoke-a-websocket-api

**Comment by tmkasun** [comment]
Checked in APIM 3.0.0, 3.1.0, 3.2.0 and `next`, the issue has been already fixed in all the above versions. hence closing the issue
