### ISSUE TITLE
Additional sections required in the swagger by API Manager is not documented.

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/docs-apim#1477]
**Description:**
_Example:_
In API Manager 3.0.0, the following section is required to define scopes in the API.

```
 "securityDefinitions": {
    "default": {
      "scopes":
            {
                "get_database_scope_ATLANTIS": "get_database_scope_ATLANTIS",
                 .......
       },
      "x-scopes-bindings":{
          "get_database_scope_ATLANTIS":"AEBackendService_role,ASJenkinsService_role,ASTestAdmin_role"
       },
   ....
}   
```
However, this is not described anywhere.

_Why it is required:_ When customers are publishing APIs using the swagger definitions, sometimes, they generate the swagger definition by code. This means, they will need to be aware of these sections in order to properly do so.

**Suggested Labels:**
Swagger

**Comment by YasasRangika** [comment]
This issue is in progress

**Comment by Chamindu36** [comment]
This issue is in progress.
