### ISSUE TITLE
Usages of the access token is not present in web socket API documentation.

### ISSUE THREAD

**Issue by riyazathali** [wso2/docs-apim#1481]
**Description:**

Usages of the access token are not present in the web socket documentation[1] that is any details about the usage of the token to authorize the request and also during the publishing of the WS API is not present any section to decide the type of the token to use.

But, this kind of small part is already there in consuming a REST API.[2]
[1] https://docs.wso2.com/display/AM260/Create+a+WebSocket+API
[2] https://docs.wso2.com/display/AM260/Invoke+an+API+using+the+Integrated+API+Console

**Affected Product Version:**
APIM 2.6.0

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
