### ISSUE TITLE
[APIM-3.1.0] Updates to the UI customization pages

### ISSUE THREAD

**Issue by lkokila** [wso2/docs-apim#1487]
**Description:**
The following page [1] which contains details about styling the Logo and the Header of the Developer Portal needs to mention in which file the custom configurations should be applied. The customizations should be applied in the following file. 

`<API-M_HOME>/repository/deployment/server/jaggeryapps/devportal/site/public/theme/defaultTheme.js`

In the following document [2], it's mentioned that the changes should be done in the above file. But it easily misleads someone following the document to update the following file instead. 

`<API-M_HOME>/repository/deployment/server/jaggeryapps/devportal/source/src/defaultTheme.js`

It would be better to add a note mentioning the above file can be used as a reference and the actual customization should be applied in the defaultTheme.js file in the theme directory. 

[1]. https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/styling-the-logo-and-header/

[2]. https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme/

**Affected Product Version:**: APIM-3.1.0

**Comment by pubudu538** [comment]
@Jayanie is working on this issue.
