### ISSUE TITLE
Remove hazelcast related docs from 3.x

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/docs-apim#1488]
Following doc needs to be removed from all 3.x docs.

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/working-with-hazelcast-clustering/#enabling-hazelcast-clustering

**Comment by Krishanx92** [comment]
@Mariangela @shaniR Shall we remove these docs from 3.x version? Since users still trying to configure using hazelcast.

**Comment by nadeepoornima** [comment]
@Mariangela @shaniR Shall we remove these docs? Since users still trying to configure using hazelcast when creating a new deployment for migration.

**Comment by Mariangela** [comment]
https://github.com/wso2/docs-apim/pull/1789 - This addresses part of this Git issue.
