### ISSUE TITLE
Verify text and messages in the UIs 3.2.0

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#1497]
**Description:**
Verify text and messages in the UIs 3.2.0

**Comment by Mariangela** [comment]
@tmkasun , please share input on which files need to be reviewed etc.

**Comment by tmkasun** [comment]
I think we need to review the text and messages in the UIs, Like for example in Admin portal case,

![image](https://user-images.githubusercontent.com/3313885/86949958-179d4400-c16d-11ea-8193-e232a2e56ae5.png)


We need to verify the text in menus, section headers, descriptions, button text, etc where the text or messages is embedded in the app(things we have written not coming from user input).
Ideally, these pre-defined texts or messages should be coming from relevant localization file, For example, we provide default English locale file for all the 3 portals, [here](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/site/public/locales/en.json) is the locale file for `admin portal`.

If you fond any mistake/error in the messages or text and willing to fix the issue, You can locate the corresponding message ID from the locale file and search for that ID in the source code for the usage.

For example, In the above screenshot 

I18n ID for the text 
```
Applicable per access token generated for an application
```
is [`"Dashboard.rateLimiting.card.applicationPolicies.description"`](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/site/public/locales/en.json#L179)

and the usage or the definition of the message in the source code is [here](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.admin.feature/src/main/resources/admin/source/src/app/components/AdminPages/Dashboard/RateLimitingCard.jsx#L75) in the `RateLimitingCard.jsx` file.

refer to this [wiki page](https://github.com/wso2/carbon-apimgt/wiki/How-internationalization-(i18n)-works-in-API-Manager-React-Apps) For more info about how i18n works in portals
