### ISSUE TITLE
Doc Feedback: type is wrong ?

### ISSUE THREAD

**Issue by scivray47** [wso2/docs-apim#1498]
Location : https://apim.docs.wso2.com/en/latest/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store/

The doc says : 

> [user_store]
class="org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager"
type = "database"

But the doc here https://apim.docs.wso2.com/en/latest/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store/ says type is "read_only_ldap"

That a bit confusing.

**Comment by chamilaadhi** [comment]
Fixed and merged to all branches
