### ISSUE TITLE
Revoking OAuth2 applications steps only works for admin users

### ISSUE THREAD

**Issue by 1akshitha** [wso2/docs-apim#1521]
**Description:**
Steps mentioned in the https://docs.wso2.com/display/AM260/Revoke+OAuth2+Application only works for Admin user.
Since non-admin users cannot view the service providers from the management console, revocation is not possible for non-admin users. 
They can use the Store REST API to regenerate the client secret.

https://docs.wso2.com/display/AM260/apidocs/store/#!/operations#ApplicationIndividual#applicationsRegenerateConsumersecretPost

**Affected Product Version:**
All versions

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
