### ISSUE TITLE
Corrections for Common Runtime and Configuration Artifacts in the official documentation

### ISSUE THREAD

**Issue by selakap** [wso2/docs-apim#1523]
**Description:**
Below mentioned wso2 apim official documentation [1] has pointed out that in 260 version (apim 260 analytics) the below paths as persistent locations.

**Persistent Runtime Artifacts**
- <API-M_ANALYTICS_HOME>/repository/deployment/server
- <API-M_ANALYTICS_HOME>/repository/data
- <API-M_ANALYTICS_HOME>/repository/conf/analytics/

**Persistent Configuration Artifacts**
- <API-M_ANALYTICS_HOME>/repository/resources
- <API-M_ANALYTICS_HOME>/repository/conf
- <API-M_ANALYTICS_HOME>/bin

But in the SP based apim 260 analytics pack, we can not find above mentioned **/repository** directory, and this needs to be corrected with relevant locations.

1. https://docs.wso2.com/display/AM260/Common+Runtime+and+Configuration+Artifacts

**Suggested Labels:**
Blocker

**Affected Product Version:**
 wso2am-analytics-2.6.0

**Comment by sanethmaduranga** [comment]
The same issue still persists in the APIM-3.2.0[1] as well.

[1] - https://apim.docs.wso2.com/en/latest/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts/
