### ISSUE TITLE
Need to add the configuration details of changing the username and the password in analytics documents

### ISSUE THREAD

**Issue by tgtshanika** [wso2/docs-apim#1524]
> **Description:**
> We need to add the configuration details of changing the username and the password in analytics documents. We are able to find those details in the SP documentation [1]. But we have missed them in the analytics documentation [2].
> 
> [1] https://docs.wso2.com/display/SP430/User+Management+via+the+IdP+Client+Interface
> [2] https://docs.wso2.com/display/AM260/Working+with+Analytics
> 
> Thanks,
> Rizmeer

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
