### ISSUE TITLE
[3.1.0] Add a documentation for APIM analytics Encryption with Secure Vault

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/docs-apim#1531]
**Description:**
Currently we don't have a documentation in APIM doc space related to APIM analytics password encrytion with secure vault.

With APIM 3.1.0 analytics, we use Streaming Integrator product and the documentation [1] we have is a bit hard to cooperate when it comes to APIM 3.1.0 due to different paths and commands.

The most convenient documentation we have at the moment is from Stream processor [2].

So we need to add a doc section under in APIM analytics 3.1.0 documentation [3] for this to have it in a single place when configuring analytics.

**Suggested Labels:**
[3.1.0], [New_doc]

**Affected Product Version:**

APIM 3.1.0

[1] https://ei.docs.wso2.com/en/latest/streaming-integrator/admin/protecting-sensitive-data-via-the-secure-vault/#securing-sensitive-data-in-deployment-configurations
[2] https://docs.wso2.com/display/SP430/Protecting+Sensitive+Data+via+the+Secure+Vault
[3] https://apim.docs.wso2.com/en/latest/learn/analytics/overview-of-api-analytics/

**Comment by Mariangela** [comment]
**Assignees**
@Sarangan0219

**Comment by maneeshaheshan** [comment]
Hi @Sarangan0219,

Please add a note for auth.config section in deployment.yaml of analytics worker profile where the default password is already base64 encoded to avoid any misunderstandings.

**Comment by shaniR** [comment]
Closing the issue as the PR is merged.
