### ISSUE TITLE
Need to remove additional "/" of the Stream Processor Server URL config in Analytic Standard Setup Doc of APIM Analytics 2.6.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/docs-apim#1541]
**Description:**

According to this document[1], when setting up the standard set up of APIM 2.6.0 with APIM Analytics 2.6.0, It has guided to put the Stream Processor Server URL as follows.
```
<protocol>://<hostname>:<port>/
```
This can found under Step 3 - Configure WSO2 API Manager to publish statistics of this doc[1]. Please refer the following screenshot. 

![StreamProcessorURL](https://user-images.githubusercontent.com/15210142/87631869-dc46da80-c755-11ea-8b55-f77dbd5c6f8f.png)

Due to this "/" after the port value has caused to create the below error.
```
ERROR {org.wso2.carbon.databridge.agent.endpoint.DataEndpoint} -  Unable to send events to the endpoint.  {org.wso2.carbon.databridge.agent.endpoint.DataEndpoint}
org.wso2.carbon.databridge.agent.exception.DataEndpointException: Cannot borrow client for tcp://localhost:7612/
```
Therefore, please correct that config as follows. Remove that last "/" in the config.

```
<protocol>://<hostname>:<port>
```

[1]. https://docs.wso2.com/display/AM260/Configuring+APIM+Analytics#standardsetup

**Suggested Labels:**

Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.6.0 and APIM Analytics 2.6.0

**OS, DB, other environment details and versions:**    
No

**Steps to reproduce:**
- Configure the APIM 2.6.0 with APIM Analytics 2.6.0 by following the standard set up document.
- Configure the Stream Process Server URL with that "/" after port and start the APIM server. 
- Then you will see the error above mentioned.

**Related Issues:**

No

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
