### ISSUE TITLE
Add the fix for the publisher v1 API post /apis request payload in the carbon-apimgt repo

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#1542]
**Description:**
The fixes done via the following PRs have not been done in the respective branches in the carbon-apimgt repo. Therefore, whenever new changes are added in the carbon-apimgt repo and the docs-apim repo needs to be updated, the following changes gets erased. Please add these changes to the actual carbon-apimgt repo.

https://github.com/wso2/docs-apim/pull/1401
https://github.com/wso2/docs-apim/pull/1399
https://github.com/wso2/docs-apim/pull/1398

**Related Issue**
https://github.com/wso2/docs-apim/issues/1124

**Comment by Mariangela** [comment]
@dinusha92 , please take into consideration the change done based on the review comment in [1].

```
example: ["MicroGW1", "MicroGW2"]
```

[1] https://github.com/wso2/docs-apim/pull/1539

**Comment by dinusha92** [comment]
Hmm..I think I have fixed that in my PR https://github.com/wso2/docs-apim/pull/1398/files#diff-53c4f72289e0a07a82cdc5e2f41402efR6860.

**Comment by Mariangela** [comment]
@Sarangan0219 , please look into this.

**Comment by Sarangan0219** [comment]
@Mariangela Ack
