### ISSUE TITLE
Move graphQL query analysis docs to rate-limitting section

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/docs-apim#1544]
Currently, the following doc is in API Security section. We have to move this doc to the Rate-Limitting section.

https://apim.docs.wso2.com/en/next/learn/api-security/graphql-query-analysis/graphql-query-analysis/

**Comment by isharac** [comment]
Already restructured.
https://apim.docs.wso2.com/en/3.2.0/learn/rate-limiting/graphql-api/overview-query-limits-for-graphql/#graphql-rate-limiting-overview
https://apim.docs.wso2.com/en/4.0.0/design/rate-limiting/graphql-api/overview-query-limits-for-graphql/#!
