### ISSUE TITLE
Documentation for config [apim.notification] not found in 3.1.0 docs

### ISSUE THREAD

**Issue by lahirus** [wso2/docs-apim#1545]
**Description:**
3.1.0 docs at https://apim.docs.wso2.com/en/latest/ doesn't have any mention of following config found in deployment.toml

#[apim.notification]
#from_address = "APIM.com"
#username = "APIM"
#password = "APIM+123"
#hostname = "localhost"
#port = 3025
#enable_start_tls = false
#enable_authentication = true

**Affected Product Version:**
3.1.0 docs

**Comment by Sarangan0219** [comment]
This Configuration has been added to the docs and config catalog. Hence this issue can be closed.
