### ISSUE TITLE
A misleading query parameter in Publisher rest API to GET apis

### ISSUE THREAD

**Issue by 1akshitha** [wso2/docs-apim#1546]
**Description:**
We can use the Publisher Rest API to get All the APIs in the API manager. In the GET APIs resource, a query parameter is mentioned as tenatDomain[1] and in the doc, it says that we can retrieve APIs of other tenants. In a normal setup, this parameter does not work and only works during migration (checked the code and we need a special environment variable to enable this parameter). Otherwise it will only set the super tenant. Having this query param in the doc is misleading.

[1] - https://docs.wso2.com/display/AM260/apidocs/publisher/#!/operations#APICollection#apisGet

**Affected Product Version:**
2.6.0

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
