### ISSUE TITLE
[Urgent-3.1] Incorrect stripe IMPL jar provided in 3.1 doc

### ISSUE THREAD

**Issue by himasha** [wso2/docs-apim#1550]
**Description:**
Under [1]  'configure API Manager' step b, the stripe impl jar(org.wso2.apim.monetization.impl-1.0.0.jar) should be linked to the latest for Monetization to work.
[1] https://apim.docs.wso2.com/en/latest/learn/api-monetization/monetizing-an-api/#c-configure-wso2-api-manager

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruthryi** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/1595
