### ISSUE TITLE
 Configure the Artifact Synchronization

### ISSUE THREAD

**Issue by ErandiPraboda** [wso2/docs-apim#1556]
**Description:**
The following document recommends mounting complete <API-M_HOME>/repository/deployment/server folder when using NFS but since it is causing some issues when it comes to the in-place wum update it would be better if we can recommend only the necessary folders to be mounted as follows.

https://apim.docs.wso2.com/en/next/install-and-setup/setup/single-node/configuring-an-active-active-deployment/#step-5-configure-the-artifact-synchronization

<APIM_HOME>/repository/deployment/server/userstores - If you have configured a secondary user store in the super tenant you have to back up this folder.
<APIM_HOME>/repository/deployment/server/executionplans
<APIM_HOME>/repository/deployment/server/synapse-configs
<APIM_HOME>/repository/tenants - If you are using tenancy

**Comment by Mariangela** [comment]
@ErandiPraboda , pls add the link to the document that you are referring to.

**Comment by ErandiPraboda** [comment]
@Mariangela Hill please find the attached document. Sorry for the inconvenience.
