### ISSUE TITLE
CI/CD need to use Open API instead of swagger 2.0 in the example

### ISSUE THREAD

**Issue by shaniR** [wso2/docs-apim#1568]
**Description:**
 CI/CD with WSO2 API Manager page uses Swagger 2.0  in the example. We should use OpenAPI perhaps?

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Chamindu36** [comment]
This issue is in progress.
