### ISSUE TITLE
Provide the link or reference 

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/docs-apim#1577]
**Description:**
The current quick start page provides instructions on how to publish a new API. As an example, wso2 using a mock HTTP API and there is a note on HTTPS on the requirement of importing the cert. 

If the referral link shared in the note itself, it will be helpful to locate the instruction right away!

<img width="758" alt="Screen Shot 2020-07-29 at 12 43 55 AM" src="https://user-images.githubusercontent.com/3397321/88772127-21dfac00-d135-11ea-9abd-21d6f1341fe7.png">

**Suggested Labels:**
Improvement, Suggestions

**Comment by shaniR** [comment]
Closing the issue, as the fix is provided.
