### ISSUE TITLE
Masking in APIM

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/docs-apim#1606]
**Description:**
Current Documentation Does not contain any details related to masking the sensitive data in the log. However, the admin doc and is doc contain that information. Therefore, Please create or update a page in aim doc with the information of masking

https://docs.wso2.com/display/ADMIN44x/Masking+Sensitive+Information+in+Logs
https://is.docs.wso2.com/en/latest/setup/masking-sensitive-information-in-logs/

**Suggested Labels:**
Improvement

**Comment by Mariangela** [comment]
@RakhithaRR , please work on this task as discussed offline.

**Comment by Mariangela** [comment]
@RakhithaRR has fixed this issue in the above mentioned PRs.
