### ISSUE TITLE
Doc Feedback: WSO2 API Manager Analytics Management Console - Not Found

### ISSUE THREAD

**Issue by vvidovic** [wso2/docs-apim#1608]
Location : https://apim.docs.wso2.com/en/latest/learn/api-gateway/message-tracing/

Under [Publishing event tracing data to API Manager Analytics](https://apim.docs.wso2.com/en/latest/learn/api-gateway/message-tracing/#publishing-event-tracing-data-to-api-manager-analytics) unavailable address, [WSO2 API Manager Analytics](https://localhost:9444/carbon) is mentioned twice.

However, after a quick setup, this console URL returns error 404 (Not Found) with the message: 
> Problem accessing: /carbon. Reason: Not Found

I can see that port 9444 is mentioned in other documentation pages as "MSF4J HTTPS Port used to upload analytics data from the microgateway" so it makes sense that analytics management console is not available there. However, it seems it is not possible to follow steps to publish & see message data in analytics.

At what address should "WSO2 API Manager Analytics Management Console" be available?
Should that information be available from the analytics dashboard?

Thanks,
Vedran

**Comment by Mariangela** [comment]
@ruks , can you please share your views.

**Comment by ruks** [comment]
from APIM analytics 2.6.0 onwards there is no management console. All the configurations are moved to deployment.yaml file of each runtime.
