### ISSUE TITLE
Update MessageTracing documentation to reflect the current APIM Analytics

### ISSUE THREAD

**Issue by fjunior87** [wso2/docs-apim#1609]
**Description:**
The documentation for message tracing[1] is still referring to DAS. It needs to update the newer versions of APIM Analytics as it refers to some files and instructions that does not exist in the current version. For example:

> Copy the DAS_MESSAGE_TRACE_1.0.0.json file and add it to the ><APIM_ANALITICS_HOME>/repository/deployment/server/eventstreams directory to deploy the same definition in WSO2 API Manager Analytics.

We don't have this file anymore.

[1]https://apim.docs.wso2.com/en/latest/learn/api-gateway/message-tracing/#message-tracing

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 3.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/docs-apim/issues/1608

**Comment by jaadds** [comment]
In the 3.X releases we don't have a support for this.  Recommendation is to use [Open Tracing](https://apim.docs.wso2.com/en/latest/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing/#enabling-tracing-with-opentracing) and [Observability](https://apim.docs.wso2.com/en/latest/administer/logging-and-monitoring/monitoring/working-with-observability/#working-with-observability)  to achieve this. There's a discussion going onto decide whether this should be supported as is. Until a conclusion is made, doc will be removed.
