### ISSUE TITLE
Doc Feedback: invalid "WSO2 ESB" link

### ISSUE THREAD

**Issue by vvidovic** [wso2/docs-apim#1619]
Location : https://apim.docs.wso2.com/en/latest/getting-started/overview/#api-gateway

*WSO2 ESB* link is not properly created - missing a '(' character after a ']' character:
> The API Gateway is a runtime, backend component (an API proxy ) developed using [WSO2 ESB]https://apim.docs.wso2.com/en/latest/getting-started/about-this-release/)

**Comment by shaniR** [comment]
closing issue since the PR is merged.
