### ISSUE TITLE
Documentation on adding a custom proxy path to APIM portals

### ISSUE THREAD

**Issue by tgtshanika** [wso2/docs-apim#1621]
Updating the content in [1] and adding the steps to 

1. Proxy API dev portal, publisher and admin portal fronting a loadbalancer
2. The configuration required to be added in settings.js file of each portal app
3. The changes needs to be done in service provider level

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path/#page-header

**Comment by dushaniw** [comment]
This is fixed in https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path/#access-wso2-api-manager-through-a-custom-proxy-path for 3.2.0.
