### ISSUE TITLE
Documentation on Open API vendor specific extensions

### ISSUE THREAD

**Issue by tgtshanika** [wso2/docs-apim#1623]
WSO2 API Manager has it's own set of vendor-specific extensions such as x-auth-type, scopes etc. Reference documentation is required to be added to APIM doc space including the following.
1. The vendor-specific extensions (x-auth-type, x-scopes-bindings, x-scopes-mappings)
2. How to define them in API definition

**Comment by Chamindu36** [comment]
This issue is in progress.
