### ISSUE TITLE
Need a documentation on how to setup a user for the admin portal

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/docs-apim#1624]
Atm, we we say a user with admin role can log in to the admin portal.  Some users may not want to set admin role for users for this. So we need a document on describing how to set up a user and a role to log in to the admin portal.

Steps that needed to be mentioned are
- create a role 
- login to the admin portal and go to the permission UI
- create a new 'role to permission' mapping for this new role. set **apim:admin** permission for this role
- assign this role to a new user

**Comment by Mariangela** [comment]
**Assignees**
@Sarangan0219
