### ISSUE TITLE
Update documentation on application sharing

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/docs-apim#1625]
Need to update the screenshots and few descriptions on the docs regarding application sharing (https://apim.docs.wso2.com/en/latest/learn/consume-api/manage-application/sharing-applications/sharing-applications/#sharing-applications) and application owner change (https://apim.docs.wso2.com/en/latest/learn/consume-api/manage-application/advanced-topics/changing-the-owner-of-an-application/#changing-the-owner-of-an-application).
The images still show the old UIs.

**Comment by Mariangela** [comment]
Assignee = @Sarangan0219
