### ISSUE TITLE
MySQL user Grants for regadmin

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/docs-apim#1626]
**Description:**
API Manager Documentation for Mysql DataSource only explaining only about user apimadmin but not regadmin. Ideally it is better to explain about user regadmin too.

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql/#changing-to-mysql

**Suggested Labels:**

**Suggested Assignees:**

**Comment by chamilaadhi** [comment]
@TheRasanjana is working on this
