### ISSUE TITLE
Wrong DB name in the mysql Documentation 

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/docs-apim#1627]
**Description:**
New databases are apim_db and shared_db. However, Grands are given to "regdb". Therefore, Error 1044 is thrown when 

```
User@MacBook-Pro ~ % mysql -u apimadmin -p -p -Dapim_db < '/Users/sivajothyvanjikumaran/WSO2/product_testing/wso2am-3.2.0/dbscripts/apimgt/mysql.sql';

Enter password:
ERROR 1044 (42000): Access denied for user 'apimadmin'@'localhost' to database 'apim_db'
```

Therefore doc needs to be correct with the correct sample database.

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql/#changing-to-mysql

**Comment by chamilaadhi** [comment]
@TheRasanjana is working on this
