### ISSUE TITLE
Viewing Alerts page should be updated

### ISSUE THREAD

**Issue by chathuranga95** [wso2/docs-apim#1651]
**Description:**
View alerts has moved to Analytics Dashboard. Therefore, [this](https://apim.docs.wso2.com/en/next/learn/analytics/managing-alerts-with-real-time-analytics/viewing-alerts/) doc should be removed or updated according to the analytics dashboard.

**Affected Product Version:**
APIM 3.2.0

**Comment by RAVEENSR** [comment]
This Viewing Alerts page is already removed from aPIM 3.2.0 doc space.

**Comment by RAVEENSR** [comment]
This Viewing Alerts page is removed from the the master branch as well.
