### ISSUE TITLE
[APIM 3.1.0] Admin portal(/admin) SSO documentation not found

### ISSUE THREAD

**Issue by dumindurox777** [wso2/docs-apim#1668]
**Description:**

2.1.0 documentation had for publisher/store, which was used for the admin portal as well. But 3.1.0 documentaion don't have any references for the admin portal SSO configurations.

It can be archive using similar configs in site.json in the admin jaggery app on <API-M_HOME>/repository/deployment/server/jaggeryapps/admin/site/conf/ directory.

 ```
 "ssoConfiguration": {
    "enabled": "true",
    "issuer": "API_WORKFLOW_ADMIN",
    "identityProviderURL": "https://localhost:9444/samlsso",
    "keyStorePassword": "",
    "identityAlias": "",
    "keyStoreName": "",
    "verifyAssertionValidityPeriod": "true",
    "audienceRestrictionsEnabled": "true",
    "responseSigningEnabled": "true",
    "assertionSigningEnabled": "true",
    "assertionEncryptionEnabled": "false",
    "signRequests" : "true",
    "idpInit" : "false",
    "idpInitSSOURL" : "https://localhost:9443/samlsso?spEntityID=API_WORKFLOW_ADMIN",
    "externalLogoutPage" : "https://localhost:9443/samlsso?slo=true",
    "loginUserNameAttribute" : ""
  }
```

**Affected Product Version:
APIM-3.1.0**

This information needs to be added in APIM 3.1.0 documentation

[1] https://docs.wso2.com/display/AM210/Configuring+API+Manager+for+SSO#ConfiguringAPIManagerforSSO-Step2-ConfiguringPublisher/StoreforSSO

**Comment by isharac** [comment]
fix for 3.2.0 https://github.com/wso2/docs-apim/pull/1825
