### ISSUE TITLE
Configuring Workflows for Tenants

### ISSUE THREAD

**Issue by ErandiPraboda** [wso2/docs-apim#1674]
**Description:**
The following document does not contain the correct configuration related to APIM 3.1 and APIM 3.0.  
Eg: Document says to do the DB configuration in master-datasources.xml where it should be corrected as deployment.toml in APIM 3.x versions. 
https://apim.docs.wso2.com/en/latest/develop/extending-api-manager/extending-workflows/configuring-workflows-for-tenants/#configuring-workflows-for-tenants

**Affected Product Version:**
APIM 3.0, APIM 3.1

**Comment by uvindra** [comment]
Fixed in
https://github.com/wso2/docs-apim/pull/1848
https://github.com/wso2/docs-apim/pull/1847
https://github.com/wso2/docs-apim/pull/1846
