### ISSUE TITLE
Doc Feedback: confusing content 

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#1681]
Location : https://apim.docs.wso2.com/en/next/learn/consume-api/manage-application/generate-keys/generate-api-keys/

This page title says generate-api-keys and the doc title says 'Application Keys'

And it starts saying 'An API Access Token/Key ..'

This looks bit confusing.

**Comment by erangatl** [comment]
This issue is already fixed in master by changing the page title to "Application Keys

![image](https://user-images.githubusercontent.com/20179540/102961604-b98dce80-450a-11eb-95fe-fc8b701edffc.png)
