### ISSUE TITLE
Admin Portal statistics doc should be updated since a feature has moved

### ISSUE THREAD

**Issue by chathuranga95** [wso2/docs-apim#1683]
### Description:
`API Availability` feature has moved to Analytics Dashboard. Therefore, [this](https://apim.docs.wso2.com/en/next/learn/analytics/analyzing-apim-statistics-with-batch-analytics/viewing-api-statistics/#admin-portal-statistics) doc should be updated according to the analytics dashboard.

### Affected Product Version:
APIM 3.2.0

**Comment by vithu30** [comment]
Hi @chathuranga95,
The mentioned link has been removed from the doc space - `https://apim.docs.wso2.com/en/next/learn/analytics/analyzing-apim-statistics-with-batch-analytics/viewing-api-statistics/#admin-portal-statistics`.

Now, the `API Availability` is moved to analytics section.

**Comment by chathuranga95** [comment]
Closing the issue since the doc is now moved.
