### ISSUE TITLE
Update security documentation

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/docs-apim#1719]
**Description:**
1. OAuth2 grant types link should be corrected to a proper hyperlink.

![Screenshot from 2020-08-16 09-10-10](https://user-images.githubusercontent.com/60866295/90325996-5611f400-dfa0-11ea-9fa5-e5c6ab17648a.png)

2. Role-Based Access Control using XACML  screenshots need to be updated for 3.2.0. 
![Screenshot from 2020-08-16 09-11-47](https://user-images.githubusercontent.com/60866295/90326007-8ce80a00-dfa0-11ea-97cf-bcbeb23abfab.png)

3. Redundant note description for `x-wso2-auth-header`
![Screenshot from 2020-08-16 09-15-09](https://user-images.githubusercontent.com/60866295/90326045-0c75d900-dfa1-11ea-8867-2d7d6ba423a9.png)

**Affected Product Version:**

APIM 3.2.0

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/1807/
