### ISSUE TITLE
[3.2.0] Docs missing for Introspect configurations of third-party Key Managers

### ISSUE THREAD

**Issue by athiththan11** [wso2/docs-apim#1724]
**Description:**

The 3.2.0 doc space is missing documentation related to configuring `Introspect` configurations for the third-party key managers in the Admin portal.

Following Git issue is produced due to missing configurations [issue#9084](https://github.com/wso2/product-apim/issues/9084)

**Comment by isharac** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/1753
