### ISSUE TITLE
Doc Feedback:Need to change the balcklisting whitelisting terms

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#1730]
Location : https://apim.docs.wso2.com/en/latest/learn/rate-limiting/blacklisting-whitelisting/

Need to change blacklisting whitelisting terms used in the doc to deny listing and allow listing

**Comment by Chamindu36** [comment]
https://github.com/wso2/docs-apim/issues/1806

**Comment by Mariangela** [comment]
This Git issue has been duplicated by https://github.com/wso2/docs-apim/issues/1806
