### ISSUE TITLE
Review doc Monitoring Server Health

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/docs-apim#1778]
**Description:**

There are formatting issues. (notes...)
Some links are missing/not working.
https://apim.docs.wso2.com/en/3.0.0/administer/product-administration/monitoring/monitoring-server-health/#MonitoringServerHealth-DeployingtheAPI
There is `<enableLifecycleChecklistItems>true</enableLifecycleChecklistItems>` in governance.xml which might need to be configured for this. Add this param to the doc as well.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0, 3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
**Assignees:**
@Sarangan0219
