### ISSUE TITLE
Doc Feedback:Blacklist whitelist terms need to change to allowlist/denylist

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#1806]
Location : https://apim.docs.wso2.com/en/latest/learn/rate-limiting/blacklisting-whitelisting/

**Comment by isharac** [comment]
This is fixed in 3.2.0
https://apim.docs.wso2.com/en/next/learn/rate-limiting/access-control/

**Comment by Chamindu36** [comment]
This issue is in progress

**Comment by uvindra** [comment]
Closing the issue since it is already fixed in 3.2.0
