### ISSUE TITLE
[3.2.0] Doc Feedback - Improve URL directions in QSG and install and setup

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/docs-apim#1823]
**Description:**

1. [Setup and Install ](https://apim.docs.wso2.com/en/latest/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-linux-or-os-x/)  in QSG is redirecting to 3.1.0 docs. Need to redirect to 3.2.0 docs.

![Screenshot from 2020-08-28 11-35-38](https://user-images.githubusercontent.com/60866295/91527072-a3884c80-e922-11ea-8155-9822e92ed061.png)

2. Links in the **Environment compatibility** section are redirecting to 3.1.0 docs.

![Screenshot from 2020-08-31 08-27-24](https://user-images.githubusercontent.com/60866295/91678701-e127e800-eb63-11ea-9f37-9187e86e310c.png)

**Affected Product Version:**

APIM 3.2.0

**Comment by shaniR** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/1861 & https://github.com/wso2/docs-apim/pull/1860
