### ISSUE TITLE
Log4j2 update missed in custom handler doc

### ISSUE THREAD

**Issue by lahirus** [wso2/docs-apim#1826]
**Description:**

Log4j version is changed to Log4j2. So following is wrong at https://apim.docs.wso2.com/en/latest/develop/extending-api-manager/extending-gateway/writing-custom-handlers/#using-apilogmessagehandler

File name and config should be updated to match Log4j2 

Copy the following code into the <APIM_HOME>/repository/conf/log4j.properties file to enable printing DEBUG logs.

```
log4j.logger.org.wso2.carbon.apimgt.gateway.handlers.logging.APILogMessageHandle
```
**Affected Product Version:**
3.1.0

**Comment by dinusha92** [comment]
could not find a reference to APIM 3.0.0 doc space.
