### ISSUE TITLE
Doc Feedback: the link is not working or missing

### ISSUE THREAD

**Issue by rajputvishwas** [wso2/docs-apim#1832]
Location : https://apim.docs.wso2.com/en/next/learn/analytics/configuring-apim-analytics/

While following standard set up for Analytics - Under Step-6- Configuring Keystores

When you open the link " Adding CA-signed certificates to keystores" it displays error message page not found

**Comment by RakhithaRR** [comment]
This issue is not present in 3.2.0 and master branches.

**Comment by samgnaniah** [comment]
This is fixed now.
