### ISSUE TITLE
Create a doc on providing permission to other users(other than default which is super tenant admin) to create dashboards in analytics   

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/docs-apim#1838]
**Description:**
Create a doc on providing permission to other users(other than default which is super tenant admin) to create dashboards in analytics.

This doc should mention about this[1] configuration which is in the dashboard deployment.yaml file.

[1] https://github.com/wso2-support/analytics-apim/blob/support-3.1.0/product/distribution/carbon-home/conf/dashboard/deployment.yaml#L404

**Comment by Meruja** [comment]
Doc for 3.2.0 has been updated with the config to provide permission to other users to create dashboard.
