### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by pandulakb** [wso2/docs-apim#1843]
Location1 : https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/identity-management-for-the-api-dev-portal/
Location2 : https://apim.docs.wso2.com/en/latest/learn/design-api/api-versioning/enabling-notifications/#enabling-notifications

Please include the "signature" property to the configuration (in all the places we define output_adapter.email), as it can be use to specify the sender's name, which will appear in the email.

**Sample configuration**:
```
[output_adapter.email]
from_address = "noreply@example.com"
signature = "do not reply"
username = "admin@example.com"
password = "password"
hostname = "smtp.example.com"
```

**Comment by Mariangela** [comment]
Assignee = @Sarangan0219
