### ISSUE TITLE
[3.2.0] Doc Feedback : Improve the doc content of  WSO2 API Manager Deployment Patterns.

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/docs-apim#1845]
**Description:**

Detailed descriptions for all the deployment patterns about their Workflows and interactions can be added in  [WSO2 API Manager Deployment Patterns](https://apim.docs.wso2.com/en/next/install-and-setup/setup/deployment-patterns/) 

**Affected Product Version:**

APIM 3.2.0

**Comment by kavishkafernando** [comment]
Each deployment pattern diagram includes the interactions with other components in detail. It also provides a single line description of when we can use a specific deployment pattern. Since the diagram provides a detailed understanding we will close this issue.
