### ISSUE TITLE
Formatting issues in Token API page

### ISSUE THREAD

**Issue by TanyaM** [wso2/docs-apim#1850]
**Description:**
Please see the screenshot below from the [Token API ](https://apim.docs.wso2.com/en/3.2.0/develop/product-apis/token-api/)page 

<img width="882" alt="Screen Shot 2020-09-04 at 4 23 09 PM" src="https://user-images.githubusercontent.com/3957104/92232726-a3f98800-eecc-11ea-8375-5c7af245501e.png">

**Comment by shaniR** [comment]
@ruthryi  can this be closed?
