### ISSUE TITLE
Broken image in "Admin Services" page

### ISSUE THREAD

**Issue by TanyaM** [wso2/docs-apim#1851]
**Description:**
Image in the following screenshot is broken in [Admin Services](https://apim.docs.wso2.com/en/next/develop/wso2-admin-services/) page.

<img width="1048" alt="Screen Shot 2020-09-04 at 6 12 18 PM" src="https://user-images.githubusercontent.com/3957104/92240515-61d74300-eeda-11ea-811e-78131d712509.png">

**Comment by shaniR** [comment]
@ruthryi  can this be closed?

**Comment by shaniR** [comment]
PR has been merged.
