### ISSUE TITLE
Issue in database query in Upgrading API Manager from 2.6.0 to 3.1.0 documentation

### ISSUE THREAD

**Issue by Ashi1993** [wso2/docs-apim#1898]
**Description:**
In **Step 2 - Upgrade API Manager to 3.1.0** in the **Upgrading API Manager from 2.6.0 to 3.1.0** documentation, the MSSQL database script for  upgrading WSO2AM_DB database from APIM 2.6.0 to 3.1.0 following line should be changed to given to the below.

Currently available lines 
```
IF NOT EXISTS (SELECT * FROM SYS.indexes WHERE name = 'IDX_PT' and object_id = OBJECT_ID('IDN_UMA_PERMISSION_TICKET'))
CREATE INDEX IDX_PT ON IDN_UMA_PERMISSION_TICKET(NAME, PT);
```

Should be changed to following 
```
IF NOT EXISTS (SELECT * FROM SYS.indexes WHERE name = 'IDX_PT' and object_id = OBJECT_ID('IDN_UMA_PERMISSION_TICKET'))
CREATE INDEX IDX_PT ON IDN_UMA_PERMISSION_TICKET (PT);
```

**Suggested Labels:**
APIM 3.1.0, Migration, MSSQL

**Comment by pubudu538** [comment]
This is only applicable for APIM v3.1.0 as we have fixed in the other versions.
