### ISSUE TITLE
Navigation links are not working

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/docs-apim#1906]
Navigations links to "API properties", "distributed API Manager deployment", and "additional property" in the following page are not working.

Location : https://apim.docs.wso2.com/en/next/develop/extending-api-manager/extending-gateway/customizing-api-template-for-gateway/

**Comment by msm1992** [comment]
4.4.0 : https://github.com/wso2/docs-apim/pull/8541
master : https://github.com/wso2/docs-apim/pull/8548
