### ISSUE TITLE
Doc Feedback: multiple guidelines for configuring IS as key manager

### ISSUE THREAD

**Issue by pouyan021** [wso2/docs-apim#1918]
Location : https://apim.docs.wso2.com/en/next/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/

There are two different guidelines for configuring IS as keymanager through wso2 docs, only one of them are latest and one of them labeled next, which of them should one follow as they are completely different?

**Comment by Sarangan0219** [comment]
Now Both the docs are updated with the simmilar content.
The Docs labeled as **next** corresponds to the docs for the next APIM (APIM 4.0.0) release. 
So it is recommended to refer to the **latest** docs  (Corresponds to APIM - 3.2.0).

**Comment by kavishkafernando** [comment]
Will close the issue as per previous comment.
