### ISSUE TITLE
Image of the Mutual SSL diagram  is not loading

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/docs-apim#1922]
**Description:**
Doc [1] is not loading the image of the Mutual SSL diagram 

![Screen Shot 2020-09-18 at 10 44 07 AM](https://user-images.githubusercontent.com/29066805/93559086-86342480-f99c-11ea-9d81-f19c0e450a5d.jpg)

[1] https://apim.docs.wso2.com/en/latest/learn/api-security/api-authentication/secure-apis-using-mutual-ssl/

**Comment by ruthryi** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/2219
