### ISSUE TITLE
Document to disable role valiadation on Scope creation

### ISSUE THREAD

**Issue by Thumimku** [wso2/docs-apim#1927]
### Description:
we can disable role validation in scope creation by adding
```
-DdisableRoleValidationAtScopeCreation=true \
```
in wso2server.sh file.

But I am unable to see this info in APIM docs. If so plkease add.

**Comment by tharindu1st** [comment]
@Mariangela please find the 2.6.0 relavent doc

**Comment by isharac** [comment]
Master branch fix https://github.com/wso2/docs-apim/pull/2635/commits/110410de248a61f270769862a3113e64ff8c6b54
