### ISSUE TITLE
[deployment.toml] "file" in the truststore configuration need to be changed as "file_name"

### ISSUE THREAD

**Issue by pandulakb** [wso2/docs-apim#1939]
Location : 
https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310/
https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310/
https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310/
https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310/
https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310/
https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310/

New Configuration :
[truststore]
type= "JKS"
file_name = "modified-client-truststore.jks"
password= "modified_password"

Please double check with the product team.

**Comment by msm1992** [comment]
This issue is already fixed in 3.2.0 and latest migration documents, issue has been fixed in 3.1.0 and 3.0.0 with https://github.com/wso2/docs-apim/pull/2660 and https://github.com/wso2/docs-apim/pull/2662
