### ISSUE TITLE
"Installing on Linux or OS X" page is not responsive

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/docs-apim#195]
**Description:**
[Installing on Linux or OS X](https://apim.docs.wso2.com/en/3.0.0/SetupAndInstall/InstallationGuide/installation-prerequisites/_Installing_on_Linux_or_OS_X_) page is not responsive. 

**Affected Product Version:**
APIM 3.0.0 docs

**OS, DB, other environment details and versions:**    
Chrome 78.0.3904.70 (Official Build) (64-bit)

**Steps to reproduce:**
Go to [installation-prerequisites](https://apim.docs.wso2.com/en/3.0.0/SetupAndInstall/InstallationGuide/installation-prerequisites/#!) page and click on "Installing on Linux or OS X".

**Comment by shaniR** [comment]
The page has been moved to the following location, and is not referenced from the installation prerequisites page .
https://apim.docs.wso2.com/en/3.0.0/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-linux-or-os-x/
