### ISSUE TITLE
[Doc] [2.1.0] Need Publisher sub theme documentation

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#1954]
Godwin reported as follows:
We have documentation[1] how to apply sub theme for Store. But we don't have same for Publisher. 

Harsha Mentioned as follows:
It is possible do the theming for publisher in the same way as well. The Section Uploading through the Admin Portal is not there for publisher theme change.

[1] https://docs.wso2.com/display/AM210/Adding+a+New+API+Store+Theme

**Comment by amilam** [comment]
Is there a need to keep this issue open given that this is not applicable to 3.x product family? But, if we close this, we need to make sure the 3.x docs have covered the same concepts properly.

**Comment by chanaka3d** [comment]
We have covered these topics with the 3.x documentation.

https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme/
