### ISSUE TITLE
Added "ś" character in the MSSQL AM DB migration script of the APIM 2.0.0 to APIM 3.1.0 document

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/docs-apim#1955]
**Description:**

In the migartion document of APIM 2.0.0 to APIM 3.1.0[1], have added "ś" at the last query of MSSQL script of the AM DB migartion. 
**Query**:
```
IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[AM_SECURITY_AUDIT_UUID_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE AM_SECURITY_AUDIT_UUID_MAPPING (
    API_ID INTEGER NOT NULL,
    AUDIT_UUID VARCHAR(255) NOT NULL,
    PRIMARYśKEY (API_ID),
    FOREIGN KEY (API_ID) REFERENCES AM_API(API_ID)
);
```
This term is "PRIMARYśKEY (API_ID)," wrong and needs to remove this "ś" to execute this query correctly.  Otherwise, the execution of the script is failing due to this.
**Correct query**:
```
IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[AM_SECURITY_AUDIT_UUID_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE AM_SECURITY_AUDIT_UUID_MAPPING (
    API_ID INTEGER NOT NULL,
    AUDIT_UUID VARCHAR(255) NOT NULL,
    PRIMARY KEY (API_ID),
    FOREIGN KEY (API_ID) REFERENCES AM_API(API_ID)
);
```
Due to customers are using please correct this soon. 
[1]. https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310/ 

**Suggested Labels:**

urgent

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.0.0 to APIM 3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shaniR** [comment]
Resolved with  https://github.com/wso2/docs-apim/pull/1956
