### ISSUE TITLE
[APIM 3.0] Quick Start Guide refers to  a tab called 'test'  which should be 'try out'

### ISSUE THREAD

**Issue by himasha** [wso2/docs-apim#196]
**Description:**
Step 8 in https://apim.docs.wso2.com/en/latest/GettingStarted/quick-start-guide/ is referring to a tab called 'test' which is actually called 'try_out' . Also need to update the screenshot as well.
<img width="173" alt="Screen Shot 2019-10-30 at 1 49 50 PM" src="https://user-images.githubusercontent.com/9687840/67840571-2df1fb00-fb1c-11e9-8e06-530069f7b112.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shaniR** [comment]
Fixed in PR https://github.com/wso2/docs-apim/pull/423
