### ISSUE TITLE
[2.6.0] Docs for password change using store

### ISSUE THREAD

**Issue by dinusha92** [wso2/docs-apim#1965]
**Description:**

We have the fature to change the password from the store. But it is not mentioned in the docs.
Appreciate if we could document and add it to the doc space as customers are trying out this.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@dinusha92 , is the UI of the store in 2.6.0 not intuitive enough in this aspect? Does the user need to know anything specific when using this feature?

**Comment by shaniR** [comment]
@dinusha92  any input?

**Comment by Mariangela** [comment]
I am closing this Git issue as this is related to API-M 2.6.0, which is a relatively older version of WSO2 API-M.

[1] https://wso2.com/products/support-matrix/
