### ISSUE TITLE
Doc Feedback: flow breaks

### ISSUE THREAD

**Issue by bhathiya** [wso2/docs-apim#1987]
Location : https://apim.docs.wso2.com/en/latest/develop/product-apis/getting-started/guide-publisher-v1/

The getting started page only talks about getting a token. Therefore, at the end of each getting started page, the user kind of stuck. We should redirect the user to the next step  and the end. (we can link both configure page and corresponding APIs page)

**Comment by Mariangela** [comment]
@msm1992 , please confirm whether this issue has been fixed in the revamped REST API docs.

**Comment by msm1992** [comment]
During the redocly-integration we have removed the getting started section in docs altogether and added the token generation instruction in the API details page itself. So now when we go to the respective API we have token generation instructions followed by details about available API resources.

**Comment by Sarangan0219** [comment]
This issue can be close as this has been fixed (https://github.com/wso2/docs-apim/issues/1139) in the latest 3.2.0 pack.

**Comment by sanjeewa-malalgoda** [comment]
Suggestion - please consider adding bold colored section to document.

Next you must use the above client id and secret to obtain the access token. We will be using the password grant type for this, you can use any grant type you desire. You also need to add the proper scope when getting the access token. **As an example we can consider view API details. To view API details you will need to obtain an access token with apim:api_view scope. Likewise based on the operation you will have to obtain token with specific scopes.**
All possible scopes for publisher REST API can be viewed in OAuth2 Security section of this document and scope for each resource is given in authorization section of resource documentation. Following is the format of the request if you are using the password grant type.
