### ISSUE TITLE
Doc Feedback: Brief explanation requires on artifact synchronisation using NFS file share.

### ISSUE THREAD

**Issue by rajputvishwas** [wso2/docs-apim#1997]
Location : https://apim.docs.wso2.com/en/next/install-and-setup/setup/single-node/configuring-an-active-active-deployment/

I am trying to setup active-active deployment using wso2 apim 3.2.0. Wherein step-5 explains how to achieve artifact synchronisation. I have created NFS file share. How do I configure two nodes to point to this NFS drive? It would be great if you provide some sample configurations, similar to rsync one.

WSO2 APIM version: 3.2.0
OS: RHEL 7

**Comment by Mariangela** [comment]
@RakhithaRR fixed this issue.
