### ISSUE TITLE
 Available aggregation tables in WSO2 API-M Analytics link is not working for 3.2.0 Documentation 

### ISSUE THREAD

**Issue by ug205** [wso2/docs-apim#2015]
**Description:**
The page is not found for the link https://apim.docs.wso2.com/en/latest/page-not-found/#api-manager-aggregate-tables when navigated from https://apim.docs.wso2.com/en/latest/develop/analytics-rest-api/#constructing-a-siddhi-query-to-fetch-data in APIM Analytics 3.2.0 documentation.
  

**Suggested Labels:**
APIM-Analytics-3.2.0

**Affected Product Version:**
APIM-Analytics-3.2.0

**Comment by Mariangela** [comment]
Solution:
New link should be: https://apim.docs.wso2.com/en/latest/learn/analytics/analytics-event-streams-and-aggregations/#api-manager-aggregate-tables

Check redirection for https://apim.docs.wso2.com/en/3.2.0/learn/analytics/analyzing-apim-statistics-with-batch-analytics/introducing-the-wso2-api-manager-statistics-model
