### ISSUE TITLE
Update axis2.xml, carbon.xml configuration values related to deployment.toml

### ISSUE THREAD

**Issue by pubudu538** [wso2/docs-apim#2018]
**Description:**
At the moment configuration catalog only has configurations related to API manager can be found in https://apim.docs.wso2.com/en/next/reference/config-catalog/. THis does not contain any configuration related to axis2, carbon, etc. Basically these are coming from the Kernel. We need to add these configs.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharac** [comment]
related issue https://github.com/wso2/docs-apim/issues/1933
