### ISSUE TITLE
Change location - customizing-the-developer-portal/advanced-customization

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#2039]
**Description:**

PR [1] mentions that these changes can be used to customize not only the Developer Portal, but also the Publisher. Therefore, the placing of the page [2] needs to be changed.

[1] https://github.com/wso2/docs-apim/pull/1902
[2] https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/advanced-customization

**Comment by Mariangela** [comment]
@chanaka3d , please confirm the new steps introduced in [1].

**Comment by chanaka3d** [comment]
The title needs to reflect that the same can be applied to publisher and admin apps as well.
