### ISSUE TITLE
[3.1.0] Missing configurations in deployment.toml for APIKEY validation

### ISSUE THREAD

**Issue by akila95fernando** [wso2/docs-apim#2041]
**Description:**

Location : https://apim.docs.wso2.com/en/3.1.0/learn/api-security/api-authentication/secure-apis-using-api-keys/#prerequisites-for-api-keys

we have have enabled the facility to create custom keystore to sign the JWT of APIKey. In order to successfully apply the feature we need to add following configurations in deployment.toml file 

[apim.devportal]
api_key_alias = <alias_name>
api_key_keystore = <keystore_name>

With the above introduced change, APIKEY validations process is changed as follows,

- If the api_key_keystore is not configured then Internal Keystore will be used for signing and the api_key_alias should point to the public certificate alias of the corresponding private key of internal Keystore.

- If the internal Keystore also not configured, then as a default behavior that will point to primary Keystore and that will be used for signing and the api_key_alias need not to be configured since that points the public certificate alias of the primary's private key in case not configured.

These information are not reflected in the documentation and need to add these.

**Affected Product Version:**
APIM 3.1.0

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/2063
