### ISSUE TITLE
Confusing sentence

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#2044]
# Description
The following sentence is confusing. Please rephrase it.

"The JWT generated by default in JWT generation where Gateway Generates the Backend JWT by retrieving claims from the invoked JWT."

Location : https://apim.docs.wso2.com/en/latest/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt/

**Comment by Mariangela** [comment]
@rmsamitha , is it correct to rephrase this sentence as follows?

By default, the JWT generated in the JWT generation process resides where the Gateway generates the Backend JWT, by retrieving claims from the invoked JWT.

**Comment by Mariangela** [comment]
@pubudu538 , can you help to reword this sentence in a more meaningful manner. Because in an offline discussion Samitha mentioned that my version also is too complicated.

**Comment by pubudu538** [comment]
By default, the backend JWT is generated by the gateway. When generating the backend JWT, it retrieves the claims from the invoked JWT.
