### ISSUE TITLE
Image has outdated left menu

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#2046]
**Description:**
[1] This image needs to be cropped because the left menu is outdated
https://apim.docs.wso2.com/en/3.2.0/assets/img/learn/enable-cors.png

https://apim.docs.wso2.com/en/latest/learn/design-api/advanced-topics/enabling-cors-for-apis

[2] This image needs to be cropped because the left menu is outdated
https://apim.docs.wso2.com/en/3.2.0/assets/img/learn/load-balance-and-fail-over.png

https://apim.docs.wso2.com/en/latest/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens

**Comment by tmkasun** [comment]
Fixed in [3.2.0](https://github.com/wso2/docs-apim/pull/2643) and [Master](https://github.com/wso2/docs-apim/pull/2642), Hence closing the issue
