### ISSUE TITLE
Need to add the way of creating non-secure APIs.

### ISSUE THREAD

**Issue by Gayanthakaushal** [wso2/docs-apim#2062]
**Description:**
For the APIM-3.x versions, we can create APIs in a non-secure manner(These APIs can invoke without using an Access Token). But the official document does not have steps on how to create non-secure APIs. 
These steps need to add under the step-8 of this document[1]

**Suggested Labels:**
APIM-3.0.0, APIM-3.1.0, APIM-3.2.0

[1] - https://apim.docs.wso2.com/en/3.1.0/learn/design-api/create-api/create-a-rest-api/#create-a-rest-api

**Comment by Mariangela** [comment]
@Gayanthakaushal , please provide the solution as mentioned offline.

**Comment by Meruja** [comment]
The issue has been fixed in 3.x.x. by https://github.com/wso2/docs-apim/pull/2225, https://github.com/wso2/docs-apim/pull/2226 and https://github.com/wso2/docs-apim/pull/2227

**Comment by shaniR** [comment]
@Meruja  please send this fix to the master branch as well.

**Comment by msm1992** [comment]
This issue has been fixed in master with https://github.com/wso2/docs-apim/pull/2268/commits/ea60bcc3e23bd5f748ed9d3528303d6ddf9fbfcf. Hence resolving this ticket.
