### ISSUE TITLE
Doc not available - Changing a Password via the Management Console

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#2065]
**Description:**
Page [1] states as follows:
"To change the password from Management Console (<https://localhost:9443/carbon>), follow the steps in [Changing a Password](https://docs.wso2.com/display/ADMIN44x/Changing+a+Password) corresponding to API Manager."

Content in [2] is not available in the APIM docs.

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md

[2] https://docs.wso2.com/display/ADMIN44x/Changing+a+Password

**Comment by Mariangela** [comment]
@ruthryi , as discussed please work on this task.

**Comment by Mariangela** [comment]
@pubudu538 , do we still encourage users to follow the steps in [1] to change their password? As in, should this content be moved to the APIM docs as now we do not point to the ADMIN guide anymore?

[1] https://docs.wso2.com/display/ADMIN44x/Changing+a+Password

**Comment by pubudu538** [comment]
Yes, we need to add this to our docs.

**Comment by ruthryi** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/2235
