### ISSUE TITLE
Doc in 3.2 using screenshots from 2.6 

### ISSUE THREAD

**Issue by lpastor74** [wso2/docs-apim#2072]
### Description:
In doc 
https://apim.docs.wso2.com/en/latest/reference/samples/api-development-sample/collaborative-api-development-sample/#collaborative-api-development-sample

Pictures are from 2.6 

### Steps to reproduce:
go to 
https://apim.docs.wso2.com/en/latest/reference/samples/api-development-sample/collaborative-api-development-sample/#collaborative-api-development-sample

**Comment by pubudu538** [comment]
Hi Laslo,

Thank you for creating this issue related to docs. I have transferred this issue to docs-apim repo. Please create issues related to docs in docs-apim.

Thank you!
Pubudu.

**Comment by lpastor74** [comment]
got it.. my bad .. I clicked on the wrong button

**Comment by pubudu538** [comment]
It is totally fine Laslo!

**Comment by Mariangela** [comment]
@Sarangan0219 , please fix this issue.

**Comment by Mariangela** [comment]
**Assignees**
@Sarangan0219

**Comment by Sarangan0219** [comment]
Reported issues regarding sample-scenarios in https://github.com/wso2/product-apim/issues/9464

**Comment by dinusha92** [comment]
Since the same has been mentioned in https://github.com/wso2/docs-apim/issues/1388 , we will be closing this issue.
