### ISSUE TITLE
Removal of info on opaque access tokens

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#2076]
**Description:**
The Key Concepts page [1] states the following:
"Access Token                       - Used in OAuth2.0 bearer token-based authentication to allow a consumer to access an API. It is a string that is passed as an HTTP header of an API request. WSO2 API Manager supports JWT formatted self-contained access tokens and regular opaque access tokens."

Based on PR [2] 
- we need to remove the following from [1].
   "and regular opaque access tokens"
- we need to add a description with regard to the removal of opaque access tokens in the About this release page

This is applicable to 3.2.0 and master branches

[1] https://apim.docs.wso2.com/en/latest/getting-started/key-concepts/
[2] https://github.com/wso2/docs-apim/pull/1962

**Comment by Mariangela** [comment]
@ChamodDamitha , please provide a description with regard to the removal of opaque access tokens that can be added in the About this release page.

**Comment by vithu30** [comment]
Screenshots in the doc - [1] also needs to be updated.

[1] https://apim.docs.wso2.com/en/latest/learn/consume-api/manage-subscription/subscribe-to-an-api/

**Comment by vithu30** [comment]
Fixed in 3.2.0 with https://github.com/wso2/docs-apim/pull/2083
Fixed in master with https://github.com/wso2/docs-apim/pull/2084
