### ISSUE TITLE
Incorrect statement when importing APIs using CI/CD pipeline

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/docs-apim#2087]
**Description:**
Need to remove the following line in document [1] as it is incorrect.
`When you import an API, regardless the status of the imported API it will be added with the created state and you need to sign in to the Publisher and publish the API.`

The status of the API is preserved when importing an API as the --preserveStatus flag is set to true by default.

[1] - https://docs.wso2.com/display/AM260/Migrating+the+APIs+to+a+Different+Environment

**Comment by Mariangela** [comment]
Updated in [1] based on the offline discussion that I had with Kavishka.

@kavishkafernando , please let us know if any further changes are required in the documentation in this regard.

[1] https://docs.wso2.com/display/AM260/Migrating+the+APIs+to+a+Different+Environment
