### ISSUE TITLE
Reference to Swagger in invoke-an-api-using-the-integrated-api-console.md

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#2092]
**Description:**

Page [1] refers to Swagger as opposed to OpenAPI.

[1] https://apim.docs.wso2.com/en/latest/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console/

**Comment by Mariangela** [comment]
@pubudu538 , to fix this issue -

1.) Is it correct to replace the wording "Swagger" with "OpenAPI" in the entire documentation?

2.) Do we use the OpenAPI 2.0 specification [1] for APIM 3.2.0?

[1] https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by Sarangan0219** [comment]
Shall we merge these changes to https://apim.docs.wso2.com/en/latest/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console/ too. (To resolve  https://github.com/wso2/docs-apim/issues/1346)
