### ISSUE TITLE
Missing doc for edge case in Analytics migration 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/docs-apim#2101]
**Description:**
Missing to add not for when the external IDP using in the setup as it has not been receiving the tenant domain of the users to the analytics dashboard after migration. It should be selected the "Use tenant domain at local subject identifier" in Analytics SP configuration.

<img width="1139" alt="migration-analytics-fedarated-authentication" src="https://user-images.githubusercontent.com/29066805/96450259-96595100-1233-11eb-86b1-68e44b2bd8e6.png">

**Affected Product Version:**
3.1.0,3.2.0

**Comment by Mariangela** [comment]
@RakhithaRR , isn't this fix applicable to master? If yes can you pls send a PR to master as well.
