### ISSUE TITLE
Redraw privatejet-mode/architecture image

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#2120]
**Description:**

Redraw /assets/img/learn/privatejet-mode/architecture.png which goes in /learn/design-api/publish-api/publish-an-api-to-a-cloud-cluster-in-privatejet-mode.md

<img width="794" alt="Screenshot 2020-10-22 at 19 17 11" src="https://user-images.githubusercontent.com/5195851/96880817-3bc22e00-149b-11eb-922a-c22a7f0be189.png">

**Comment by Mariangela** [comment]
@pubudu538 please clarify the following:

Is it ok to change "_ " >>> "_" as mentioned below:

- "Deploy API custom resource kind" >>> "Deploy API custom resource"
- "Swagger as a ConfigMap" >>> "OpenID (a.k.a Swagger) as a ConfigMap"

**Comment by pubudu538** [comment]
It should be OpenAPI(a.k.a Swagger) as a ConfigMap. Other changes looks good
