### ISSUE TITLE
Serach bar of the restful api documentaion (3.1.0) is disapearing when scroll down 

### ISSUE THREAD

**Issue by selakap** [wso2/docs-apim#2137]
**Description:**
The search bar of [1] (and other related docs) is visible only when scrolled to the top. If Scrolling down it hides the search bar.

![Screenshot from 2020-10-22 10-38-42](https://user-images.githubusercontent.com/38026978/97151543-a45c2400-1795-11eb-8869-0a5b156bd75c.jpg)

![Screenshot from 2020-10-22 10-38-53](https://user-images.githubusercontent.com/38026978/97151555-a9b96e80-1795-11eb-8cbc-6d339ad80523.jpg)

1. https://apim.docs.wso2.com/en/3.1.0/develop/product-apis/publisher-apis/publisher-v1/publisher-v1/

**Affected Product Version:**
3.1.0

**Comment by malinthaprasan** [comment]
Yes I think because it is covered by one of our UI element (menu) when scrolling. We might need to slight positioning changes to the redocly rendering UI elements. @dushansilva any idea on this

**Comment by dushansilva** [comment]
might be able to do something with CSS to improve, can't confirm exactly since that component is generated from redoctly library is generated from the library.

**Comment by shaniR** [comment]
This will be fixed with the PR https://github.com/wso2/docs-apim/pull/2220, https://github.com/wso2/docs-apim/pull/2221 & https://github.com/wso2/docs-apim/pull/2222
