### ISSUE TITLE
Missing information in 3rd party KM config guide

### ISSUE THREAD

**Issue by shirolk** [wso2/docs-apim#2141]
**Description:**
There are a few missing points in 3rd party KM configs which should be fixed 

1. WSO2 IS KM documentation
 - The following config was missing from the deployment.toml list of settings in IS 
[[resource.access_control]]
context = "(.)/keymanager-operations/dcr/register(.)"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"

PR created for this : [PR2140](https://github.com/wso2/docs-apim/pull/2140)

- Need to mention as an additional note that the same user who is creating the application on dev_portal need to be created on IS side as well. 

- Also, the keymanager-operations.war was copied from APIM instead of the webapp in the download mentioned in step 5 under configuring WSO2 IS

2. Auth0 KM documentation
- The place to get the audience was not clear 

PR Created : [PR2139](https://github.com/wso2/docs-apim/pull/2139)

**Comment by shaniR** [comment]
Closing this off as the PR's have been merged.
