### ISSUE TITLE
The drawer menu of the restful API documentation (3.1.0) is not working as expected

### ISSUE THREAD

**Issue by selakap** [wso2/docs-apim#2170]
**Description:**
The drawer menu of the restful API documentation (3.1.0) (eg:[1]) is not working as expected

![Screenshot from 2020-10-22 10-38-09](https://user-images.githubusercontent.com/38026978/97562802-39feea00-1a08-11eb-8b4c-01b4f02e6649.jpg)

1. https://apim.docs.wso2.com/en/3.1.0/develop/product-apis/publisher-apis/publisher-v1/publisher-v1/

**Affected Product Version:**
wso2 apim 3.1.0

**Comment by shaniR** [comment]
This will be fixed with the PR https://github.com/wso2/docs-apim/pull/2220, https://github.com/wso2/docs-apim/pull/2221 & https://github.com/wso2/docs-apim/pull/2222
