### ISSUE TITLE
Wrong positioning of throttle condition group configs

### ISSUE THREAD

**Issue by ChamodDamitha** [wso2/docs-apim#2188]
**Description:**
Below configs in the config catalogue (https://apim.docs.wso2.com/en/latest/reference/config-catalog/) should come under `[apim.throttling]` which are currently wrongly listed under `[apim.throttling.url_group]`
- enable_header_based_throttling
- enable_jwt_claim_based_throttling

Additionally, the below config should be added as well
- enable_query_param_based_throttling

**Affected Product Version:**
3.2.0

**Comment by Mariangela** [comment]
**Assignees**
@Sarangan0219
