### ISSUE TITLE
Doc Feedback:  Incorrect information

### ISSUE THREAD

**Issue by bhathiya** [wso2/docs-apim#2214]
Location : https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup/

This contains conflicting information. 

"In a multi-tenanted API Manager setup, self signup to the Developer Portal is enabled by default to all tenants. This will work out-of-the-box for super tenant(carbon.super). But in order to make it work for tenants the following steps should be carried out."

**Comment by chamilaadhi** [comment]
@TheRasanjana is working on this
