### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by awedi** [wso2/docs-apim#224]
Location : https://apim.docs.wso2.com/en/latest/Learn/Tutorials/create-and-publish-an-api/

Concern: The tutorials contain the screenshots and instructions from APIM 2.6

**Comment by shaniR** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/1449
https://github.com/wso2/docs-apim/pull/1448
& https://github.com/wso2/docs-apim/pull/1438
