### ISSUE TITLE
Doc Feedback: APIM Default Ports (7611 & 7711)

### ISSUE THREAD

**Issue by pandulakb** [wso2/docs-apim#2241]
Location : https://apim.docs.wso2.com/en/latest/install-and-setup/setup/reference/default-product-ports/

7611 - Authenticate data published when Thrift data publisher is used for throttling.
7711 - Port for secure transport when Thrift data publisher is used for throttling.

Why does the documentation specifying these default ports being used for Throttling as well as Analytics?
I cannot see anywhere in the docs which relate these ports to throttling. 
Please check with the APIM team, and correct if necessary.

**Comment by pubudu538** [comment]
When it comes to data publishing we have two implementations such as binary and thrift [1]. In throttling by default, we use the binary type, and ports are 9611/9711. You can change this type to thrift for throttling data publishing and then the ports are 7611/7711. For some cases, we have users who use both types. 


[1] - https://apim.docs.wso2.com/en/latest/reference/config-catalog/#api-m-throttling-configurations

**Comment by pubudu538** [comment]
This is for APIM ports
7611 - TCP port to receive throttling events. Required when Thrift data publisher is used for throttling.
7711 - SSL port for secure transport to receive throttling events. Required when Thrift data publisher is used for throttling.

9611 - TCP port to receive throttling events. Required when Binary data publisher is used for throttling.
9711 - SSL port for secure transport to receive throttling events. Required when Binary data publisher is used for throttling.

This is for analytics
7612 - TCP port to receive analytics events. Thrift data publisher is used.
7712 - SSL port for secure transport to receive analytics events. Thrift data publisher is used.
