### ISSUE TITLE
Disable the "Change Password" feature from devportal UI

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/docs-apim#2249]
**Description:**
Below configuration can be used to disable the "Change Password" feature from the devportal
```
[apim]
enable_change_password = false
```

This needs to add on top of all the other [apim.**] tags in the deployment.toml file.

**Affected Product Version:**
APIM 3.2.0

**Comment by rmsamitha** [comment]
This feature is only available from 3.2.0. So need to fix in 3.2.0 and master docs only.

**Comment by pubudu538** [comment]
@Jayanie is working on this
