### ISSUE TITLE
Provide a sample configuration for Jaeger

### ISSUE THREAD

**Issue by dunithd** [wso2/docs-apim#2250]
Location : https://apim.docs.wso2.com/en/latest/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing/

It would be better to include a Jaeger server configuration values with sample values or sensible defaults. For an absolute beginner who's new to Jaeger, getting to know the proper hostname and port for the first time would be tricky.

**Comment by Mariangela** [comment]
**Assignnee**
@RakhithaRR

**Comment by pubudu538** [comment]
This is fixed in all the applicable versions. Hence resolving.
