### ISSUE TITLE
Token Expiration time is not working with IS 5.10 due to missing information in the documentation. 

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/docs-apim#2256]
**Description:**
**APIM 3.2.0 Documentation**
**Doc issue 01: Missing resource.access_control configurations.**
In the "Configure WSO2 IS as a Key Manager" section [1] we have the below configuration which is required to perform an update.
```
[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "PUT"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"

[[resource.access_control]]
context = "(.)/keymanager-operations/dcr/register(.)"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"
```
But in the "Configuring WSO2 Identity Server as a Key Manager" section [2] we don't have the above configurations. 

These missing configurations will results in 401 ERROR when updating the token expiry time. 

**Doc issue 02: When we downloading the WSO2 IS Connector, the files we are downloading as below.**

- wso2is.key.manager.core-1.0.16.1.jar
- wso2is.notification.event.handlers_1.0.16.1.jar
- MD5 (keymanager-operations.war) = 729dd8abd25f366eb781a15eb5b7590a

But the correct versions of the jar files should be as below.

- wso2is.key.manager.core_1.0.16.jar
- wso2is.notification.event.handlers_1.0.16.jar
- MD5 (keymanager-operations.war) = 248452e2acddea08a9a7f1d6ee783deb 

Documentation should point to the correct versions, otherwise, it will result in 500 ERROR.

[1] - https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-wso2is-connector/
[2] - https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/

**Comment by chamilaadhi** [comment]
this is fixed
