### ISSUE TITLE
Update the rsync-for-carbon-depsync.sh

### ISSUE THREAD

**Issue by ruthryi** [wso2/docs-apim#2259]
**Description:**
According to https://github.com/wso2/docs-apim/issues/2247 the synapse-configs and executionplans folders needs to be shared across the nodes. 

The script for synchronization with rsync needs to be updated according to this in the page below:
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster/#artifact-synchronization-with-rsync

**Comment by TheRasanjana** [comment]
I am working on this.

**Comment by TheRasanjana** [comment]
We have removed the **Artifact synchronization with rsync** section after discussion as it's no longer in use.
Issue : https://github.com/wso2/docs-apim/issues/2699

**Comment by chamilaadhi** [comment]
closing since pr is merged in #2699
