### ISSUE TITLE
Configure separate user with necessary permissions

### ISSUE THREAD

**Issue by wggihan** [wso2/docs-apim#2275]
**Description:**
Want to create another user only for inter components communication with bare minimum permissions. This information couldn't find in the current documentation.

**Comment by chamilaadhi** [comment]
@wggihan we normally configure admin user credentials to communicate between components. These configurations are only accessible for a user who can ssh into the server. In production systems, passwords in the config files are encrypted as well. So the credentials are secured as well.
So there is no need to create a user with minimal permissions.
