### ISSUE TITLE
[3.x][REST API V1] Wrong version in the Client-registration example 

### ISSUE THREAD

**Issue by menakaj** [wso2/docs-apim#2279]
**Description:**
In the Rest api docs (publisherv1 and storev1), the client-registration example uses the version as v0.1. This version does not exist in the apim. And it is hard for someone to find out the correct version that should be used.

Hence this should be fixed in the documentation.[1][2]

[1] https://apim.docs.wso2.com/en/3.0.0/develop/product-apis/getting-started/guide-devportal-v1
[2] https://apim.docs.wso2.com/en/3.0.0/develop/product-apis/getting-started/guide-publisher-v1/
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by msm1992** [comment]
This issue is fixed in 3.0.0 with https://github.com/wso2/docs-apim/pull/2281 and in 3.1.0 publisher v1 with https://github.com/wso2/docs-apim/pull/2624. Issue is already fixed in the remaining 3.1.0 and 3.2.0 docs.
