### ISSUE TITLE
APIM Analytics 3.1.0 Dashboards are shown in APIM 3.2.0 Analytics Dashboard portal when migrated from 3.1.0 to 3.2.0

### ISSUE THREAD

**Issue by ug205** [wso2/docs-apim#2286]
**Description:**

The following three APIM 3.1.0 Dashboards are shown in APIM 3.2.0 Analytics Dashboard portal when migrated from 3.1.0 to 3.2.0
APIM Admin
APIM Publisher
APIM Developer Portal

A step should be added to remove records related to these dashboards from the DASHBOARD_DB in the migration documentation.

**Suggested Labels:**
apim-analytics-3.2.0

**Affected Product Version:**
apim-analytics-3.2.0

**Steps to reproduce:**

Migrate from APIM Analytics 3.1.0 to APIM Analytics 3.2.0

**Comment by Mariangela** [comment]
@ruwiniwj , please let us know the exact change that is needed in the docs to fix this issue.

**Comment by ruwiniwj** [comment]
We can add a note saying that only the ANALYTICS_DB  needs to be migrated and the other DBs need to be either pointed to new DBs or be cleaned. @TanyaM there wouldn't be an issue with using new DBs for other DBs right?

**Comment by TanyaM** [comment]
> We can add a note saying that only the ANALYTICS_DB needs to be migrated and the other DBs need to be either pointed to new DBs or be cleaned. @TanyaM there wouldn't be an issue with using new DBs for other DBs right?

In the default case we can use fresh DB's for Dashboard DB and Permission DB, but we might need to add a note specifying the steps if there are custom dashboards.

**Comment by ruwiniwj** [comment]
For custom dashboards are recommended approach is to export and import them right?

**Comment by Mariangela** [comment]
@RakhithaRR , can you look into this issue please.
