### ISSUE TITLE
[APIM][3.1.0][3.2.0] - Default search in publisher and devportal is not the API name search

### ISSUE THREAD

**Issue by saranki** [wso2/docs-apim#2288]
**Description:**
In the document [1, 2] it is mentioned that the default search is name search. But the default search in APIM publisher or devportal is a content search. If you don't specify a search prefix such as name, context, version, etc, then it is considered as a content search. So when it is considered as a content search, both API and document media types are considered. But if you want to search only the APIs based on their names, then you need to run the search query with the name: prefix.

[1] [https://apim.docs.wso2.com/en/3.1.0/learn/consume-api/discover-apis/search/#search](https://apim.docs.wso2.com/en/3.1.0/learn/consume-api/discover-apis/search/#search)
[2] [https://apim.docs.wso2.com/en/latest/learn/consume-api/discover-apis/search/](https://apim.docs.wso2.com/en/latest/learn/consume-api/discover-apis/search/)

**Affected Product Version:**
wso2am-3.1.0, wso2am-3.2.0 

**Steps to reproduce:**
1. Create multiple APIs with and without similar API names. 
- Similar names:  E.g: remedyAPI1, remedyAPI2, etc.
- Different names: E.g: test, testAPI, etc.
2. Search the APIs in the publisher by just entering a few characters of the API name. E.g: "te".
3. The APIs will not be filtered based on the name.
**Case 1: Without the "name" keyword**

![image](https://user-images.githubusercontent.com/20519000/100188493-52cbc400-2f10-11eb-9181-7f053c182b46.png)

4. Search the APIs in the publisher by entering a few characters of the API name with the keyword **name:**. E.g: **name:t**

**Case 2: With the "name" keyword**

![image](https://user-images.githubusercontent.com/20519000/100188733-d4bbed00-2f10-11eb-867a-c47a7a196c9f.png)

5. Unless we use **name:<api-name or api-name-phrase>** the API name based filtering is nor working as expected.

**Comment by tmkasun** [comment]
Hi @saranki,

I think we used the term `Unified Search` when developing this search feature for APIM 3.0.0 by @msm1992 . Shall we use the term `Unified Search` instead of saying `Content Search` ?
@bhathiya @tgtshanika @chanaka3d  WDYT ?

**Comment by bhathiya** [comment]
+1
