### ISSUE TITLE
'Monetizing an API' documentation issues - API Manager 3.2.0

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/docs-apim#2295]
**Description:**
The documentation [1] which includes details on configuring API Monetization with Stripe billing engine, has several issues due to the following reasons.
- Stripe configurations are not up-to-date with the latest released Stipe billing engine version
- API Manager REST API versions are incorrect for the APIM-3.2.0 version

It would be better if the above configurations are updated in the documentation [1] as the existing details are misleading.

**Suggested Assignees:**
@ruthryi 

**Affected Product Version:**
APIM-3.2.0

[1] https://apim.docs.wso2.com/en/latest/learn/api-monetization/monetizing-an-api/#monetizing-an-api

**Comment by Mariangela** [comment]
@RakhithaRR , please work on this task.
