### ISSUE TITLE
[APIM300]Provide a doc to create users with specific permissions

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-apim#2303]
**Description:**
Provide a doc for Managing users and roles with specific permissions. 

**Affected Product Version:**
APIM300

**Comment by chamilaadhi** [comment]
we already have a doc for apim 3.0.0 on this. please refer to https://apim.docs.wso2.com/en/3.0.0/administer/product-administration/managing-users-and-roles/introduction-to-user-management/ section
