### ISSUE TITLE
Document the relevant admin services for api manager

### ISSUE THREAD

**Issue by erandidesilva** [wso2/docs-apim#2305]
To use api manager functionalities some admin services are needed to be invoked. [1] is an example where the RemoteTenantManager admin service will be used to create tenants. It would be really useful for the developer to know what fields are mandatory and what fields are not. Hence a proper documentation on related admin services will be beneficial for the user.

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product
