### ISSUE TITLE
Specify the permissions needs to be given to worker and manager nodes - rsync

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-apim#2317]
**Description:**
Document: https://docs.wso2.com/display/AM210/Using+Puppet+Modules+to+Set+up+WSO2+API-M+with+Pattern+6
Step 5 - Update the clustering related configurations
step 4

Through the puppet script, wso2user is created. In order to do the rsync correctly, specify which permissions need to be given to which users, to which directories. 

**Suggested Labels:**
AM2xx 
Priority/High
Bug

**Affected Product Version:**
AM2xx

**OS, DB, other environment details and versions:**    
Ubuntu 14.04

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product
