### ISSUE TITLE
Invoking the Endpoint - Kerberos OAuth2 Grant

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-apim#2325]
**Description:**
Document: [Kerberos OAuth2 Grant](https://docs.wso2.com/display/AM2xx/Kerberos+OAuth2+Grant#69c8ee30ff1b4f30a15b43efd39f25c3)
Section: Configuring Kerberos Grant with API Manager
Step 8

curl -v -X POST -H "Authorization: Basic <base64-encoded-client-id>:<client-secret-value>" -k -d "grant_type=kerberos&kerberos_realm=<kerberos-realm>&kerberos_token=<kerberos-token>&scope=<scope>" -H "Content-Type:application/x-www-form-urlencoded" https://localhost:8243/token

Explain how to get these values:
- kerberos-realm
- kerberos-token
- scope

**Suggested Labels:**
Type/Docs
Severity/Major
Priority/High

**Suggested Assignees:**
N/A

**Affected Product Version:**
AM2xx docs

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product
