### ISSUE TITLE
Better to have a sample on Geographical Distributed wide API Management  

### ISSUE THREAD

**Issue by chalitha87** [wso2/docs-apim#2337]
**Description:**
Geographical Distributed wide API Management is widely used use case.
It's better if we have a sample on this area. 

**Suggested Labels:**
Type/Docs
Type/Improvement
Priority/Normal
Affected/2.2.0
**Affected Product Version:**
WSO2 API Manager 2.2.0

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
