### ISSUE TITLE
Need Information on how we sync information on APIM product which deployed different data centers

### ISSUE THREAD

**Issue by chalitha87** [wso2/docs-apim#2339]
**Description:**
Please include information on how we can sync the throttling policies and deployment data in two different data centers or multi regions.

**Suggested Labels:**
Type/Docs
Type/Improvement
Severity/Critical
Priority/High

**Comment by pubudu538** [comment]
This is a bit of an advanced topic. So we have covered this from a library article. You could refer to this document https://wso2.com/library/article/deploying-wso2-api-manager-in-a-multi-dc-environment/ for this information
