### ISSUE TITLE
Please include some reference on how we can do database replication in multi regional environment. 

### ISSUE THREAD

**Issue by chalitha87** [wso2/docs-apim#2340]
**Description:**
When we deploy APIM product in Multi regional environment, It's required to have database replication.
Please include these information into our official document.

**Suggested Labels:**
Type/Docs
Type/Improvement
Severity/Critical
Priority/High

**Comment by chamilaadhi** [comment]
This is a bit of an advanced topic. So we have covered this from a library article. You could refer this document https://wso2.com/library/article/deploying-wso2-api-manager-in-a-multi-dc-environment/ for this information
