### ISSUE TITLE
Please include some guideline of minimal resources required for multi regional distributed setup.

### ISSUE THREAD

**Issue by chalitha87** [wso2/docs-apim#2341]
**Description:**
It's better if we can have a guild-line in the document what are minimal requirement of resources needed for a multi regional setup.
Number of Traffic managers
Number of analytic nodes.
Number of gateway and keymager

**Suggested Labels:**
Type/Docs
Type/Improvement
Severity/Critical
Priority/High

**Comment by Chamindu36** [comment]
There is no such minimum requirement to set up a distributed setup. In general, people use multi dc deployment for High availability(HA) requirements. The number of nodes that they should have on their deployment, depends on how much HA they want. So there is no restriction as a minimum requirement. But as a good practice, in a distributed setup, it is recommended for each DC to have their own components like Traffic Manager(TM), Gateway (GW) without needing to make cross DC calls. The minimum requirements for the deployment of a node are already specified in the documentation. Hence, we can close this issue.
