### ISSUE TITLE
Please remove the url format from remoteInstance attribute in registry mounting config.

### ISSUE THREAD

**Issue by chalitha87** [wso2/docs-apim#2342]
**Description:**
Please remove the link in the value of remoteInstance Url in [1] under registry mounting 
configuration.

[1] https://docs.wso2.com/display/AM210/Distributed+Deployment+of+API+Manager

**Suggested Labels:**
Type/Docs
Type/Bug
Severity/Minor
Priority/Normal
Affected/2.2.0

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
