### ISSUE TITLE
Providing information for the way to get rid of ssl warnings for MySQL5.7 users.

### ISSUE THREAD

**Issue by chaminda** [wso2/docs-apim#2347]
**Description:**
Documents should provide information for the way to get rid of ssl warnings which appeared on the server console for MySQL5.7 users who don't want to use ssl. By setting **useSSL=false** to the jdbc url, this can be disappeared.

```java
jdbc:mysql://localhost:3306/apimdb?autoReconnect=true&amp;useSSL=false
```

**Affected Product Version:**
APIM2xx
**OS, DB, other environment details and versions:**   
MySQL5.7

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
