### ISSUE TITLE
[UX][DOC] No proper documentation found on delete tenant data which is removed using admin service

### ISSUE THREAD

**Issue by dakshika** [wso2/docs-apim#2366]
**Description:**
No proper documentation found on delete tenant data which is removed using admin service

https://docs.wso2.com/display/AM210/Managing+Tenants

Above doc contain the tenant deletion process and it mentioned that "If you perform operations such as tenant deletion, even though the tenant details are removed, any data stored in registry, file system, other databases, etc. will not be removed. Such data will need to be removed manually."

The manual process isn't documented or not linked

**Affected Product Version:**
2.1.0

**Comment by amitvineti** [comment]
@dakshika @kavishkafernando - tenant deletion does not work on APIM 2.6.0 . I followed the steps and could not delete the tenant - getting following error:

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <soapenv:Fault>
         <faultcode>soapenv:Server</faultcode>
         <faultstring>Error deleting tenant with domain: amit.vineti.com and tenant id: 1.</faultstring>
         <detail>
            <ns:TenantMgtAdminServiceStratosException xmlns:ns="http://services.mgt.tenant.carbon.wso2.org">
               <StratosException xsi:type="ax2919:StratosException" xmlns="http://services.mgt.tenant.carbon.wso2.org" xmlns:ax2921="http://api.user.carbon.wso2.org/xsd" xmlns:ax2914="http://beans.mgt.tenant.carbon.wso2.org/xsd" xmlns:ax2915="http://beans.common.stratos.carbon.wso2.org/xsd" xmlns:ax2919="http://exception.common.stratos.carbon.wso2.org/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
            </ns:TenantMgtAdminServiceStratosException>
         </detail>
      </soapenv:Fault>
   </soapenv:Body>
</soapenv:Envelope>

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
