### ISSUE TITLE
[Doc] Explain all property values in email adapter Config

### ISSUE THREAD

**Issue by Minoli** [wso2/docs-apim#2376]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Help and Documentation - Is necessary documentation provided? 

***Related task:***
Notify subscribers about new API version

***Issue:***
Only mail.smtp.from , mail.smtp.user, mail.smtp.password property values have descriptions. Add descriptions for other properties as well. 

***Doc Link:***
[1] https://docs.wso2.com/display/AM210/Enabling+Notifications	

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0

**Comment by Mariangela** [comment]
@RakhithaRR , shall we address this issue for 3.0.0, 3.1.0 and 3.2.0. We can add the details in the configure file and point off from the respective page [2]

[1] https://apim.docs.wso2.com/en/latest/reference/config-catalog/
[2] https://apim.docs.wso2.com/en/latest/learn/design-api/api-versioning/enabling-notifications/#enabling-notifications

**Comment by RakhithaRR** [comment]
This issue can be closed as the docs have been updated with the above PRs.
