### ISSUE TITLE
[Doc] Broken link to APIExecutor

### ISSUE THREAD

**Issue by Minoli** [wso2/docs-apim#2384]
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Help and Documentation -Is the content upto date and accurate? 

***Related task:***
Introduce organization specific life cycle states

***Issue:***
link to org.wso2.carbon.apimgt.impl.executors.APIExecutor returns a 404 error page.

***Doc Link:***
[1] https://docs.wso2.com/display/AM2xx/Customize+API+Life+Cycle

**Suggested Labels:**
Bug, Docs

**Affected Product Version:**
2.1.0 update 14

**Comment by erangatl** [comment]
https://docs.wso2.com/display/AM200/Customize+API+Life+Cycle
https://docs.wso2.com/display/AM210/Customize+API+Life+Cycle
![image](https://user-images.githubusercontent.com/20179540/102975047-7bea6f00-4525-11eb-9e90-8410519d10d2.png)

Broken link
https://github.com/wso2/carbon-apimgt/blob/release-1.10.x/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/executors/APIExecutor.java

**Comment by erangatl** [comment]
Fixed
