### ISSUE TITLE
Incorrect information on configuring APIM Analytics

### ISSUE THREAD

**Issue by joyrathnayake** [wso2/docs-apim#240]
Location : https://apim.docs.wso2.com/en/latest/GettingStarted/overview/

In the latest APIM Documentation, Configuring Analytics points to the older version of the documentation (2.6.0). Older approach of configuring Analytics does not work as we have a new configuration model (single-file configuration)

**Comment by shaniR** [comment]
This is fixed https://apim.docs.wso2.com/en/latest/Learn/Analytics/configuring-apim-analytics/
