### ISSUE TITLE
[Doc ] Migration Guide.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/docs-apim#2400]
**Description:**

In the doc [1], under step 5, is it meant to say 

Follow the instructions mentioned in the Upgrading from **2.1.0 to 2.2.0 tab** ?. 

In the following line, it is mentioned to skip step 6 of 2.
But please make it clear,  it mentioning step 6 of 2. Its confusing as step 2 to 6.

[1] - https://docs.wso2.com/display/AM220/Upgrading+from+the+Previous+Release+when+WSO2+IS+is+the+Key+Manager

**Suggested Labels:**
Type/Doc

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
