### ISSUE TITLE
[Doc] Update download link for IS 5.5.0 Key manager pack

### ISSUE THREAD

**Issue by Minoli** [wso2/docs-apim#2406]
**Description:**
Configuring Identity Server as IDP for SSO-> Sharing the user store [1] 
Step 4: The download link for the WSO2 Identity Server 5.5.0 as a Key Manager does not point to pre-packaged Key Manager pack. The link should point to https://wso2.com/api-management/install/

[1] https://docs.wso2.com/display/AM220/Configuring+Identity+Server+as+IDP+for+SSO

**Suggested Labels:**
Doc

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
