### ISSUE TITLE
[Doc] Update the APIM download link 

### ISSUE THREAD

**Issue by Minoli** [wso2/docs-apim#2409]
**Description:**
Configure Facebook login with Identity Server [1]
Step 1:  download link points to old wso2 download page

[1] https://docs.wso2.com/display/AM220/Log+in+to+the+API+Store+using+Social+Media

**Suggested Labels:**
Doc

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
