### ISSUE TITLE
API Manager 3.2.0 Documentation Improvements needed

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#2413]
**Description:**

Kamidu Sachith Punchihewa reported as follows:

In the documentation page [1] we are explaining how the wso2 api manager can be installed as a linux service. But the instructions provided will not be applicable with redhat linux distributions such as fedora. This is because those distributions do not contain update-rc.d package for service management, they have chkconfig in place. In order to support the redhat based linux OS we need to use chkconfig for register services and the service definition must include the chkconfig's run level information.
In my opinion it will be better if we can introduce the above information as a note or in a similar manner. What do you think?

**Comment by Mariangela** [comment]
@pubudu538 , is it sufficient to add the following note in [1] at the top of the page?

`The following instructions are not applicable to Red Hat Linux distributions such as Fedora because those distributions contain the chkconfig package instead of the update-rc.d package for service management. 
To support the Red Hat based Linux OS you need to use chkconfig for the register services and you need to also include the service definition in the chkconfig's run level information.`

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/install/installing-the-product/installing-the-binary/installing-as-a-linux-service/

**Comment by pubudu538** [comment]
This looks good. Additionally, we can point to chkconfig - https://linux.die.net/man/8/chkconfig

**Comment by Mariangela** [comment]
@pubudu538 , is this fix applicable to 3.0.0 and 3.1.0 docs as well?

**Comment by pubudu538** [comment]
Yes, this is applicable for both v3 and v3.1.0.

**Comment by Mariangela** [comment]
Fixed in the API-M master, 3.2.0, 3.1.0 and 3.0.0 branches.
