### ISSUE TITLE
[3.0.0][3.1.0] Websocket WSS WSCAT Commands

### ISSUE THREAD

**Issue by athiththan11** [wso2/docs-apim#2423]
### Issue

The `wscat` commands for `wss` described in [Invoke a Websocket API](https://apim.docs.wso2.com/en/3.0.0/learn/tutorials/create-and-publish-websocket-api/#step-3-invoke-a-websocket-api) of [3.0.0](https://apim.docs.wso2.com/en/3.0.0/learn/tutorials/create-and-publish-websocket-api/#step-3-invoke-a-websocket-api) and [3.1.0](https://apim.docs.wso2.com/en/3.1.0/learn/tutorials/create-and-publish-websocket-api/#step-3-invoke-a-websocket-api) are as following

```sh
wscat -c -n wss://localhost:8099/echowebsocket/1.0.0 -H "Authorization: Bearer [accesstoken]"
```

When using the above command, the `wscat` responds back with the following error-trace in the logs

```sh
error: getaddrinfo ENOTFOUND -n
```

### Fix

To overcome, refactor the commands of the `WSS` as following (the `-n` flag needs to be either before the `-c` flag or at the end of the command)

```sh
# option 01
wscat -n -c wss://localhost:8099/echowebsocket/1.0.0 -H "Authorization: Bearer [accesstoken]"

# option 02
wscat -c wss://localhost:8099/echowebsocket/1.0.0 -H "Authorization: Bearer [accesstoken]" -n
```

**Comment by Mariangela** [comment]
This fix is not applicable to 3.2.0
