### ISSUE TITLE
Add more details regarding the Dev Portal customization

### ISSUE THREAD

**Issue by stefanonegri** [wso2/docs-apim#2443]
**Description:**
A prospect could not find detailed documentation regarding the different possibility to customize the Developer Portal. Can the page [1] be enriched with more details on how the Dev Portal is structured, etc?

[1] https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme/ can be 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@chanaka3d , can you please look into this issue?
