### ISSUE TITLE
Screenshots are not updated in "Create and Publish a GraphQL API" page 

### ISSUE THREAD

**Issue by TanyaM** [wso2/docs-apim#2479]
**Description:**
Some of the screenshots in the [Create and Publish a GraphQL API](https://apim.docs.wso2.com/en/latest/learn/tutorials/create-and-publish-a-graphql-api/#create-and-publish-a-graphql-api) page is not updated.

For example see the screenshot below.

<img width="785" alt="test" src="https://user-images.githubusercontent.com/3957104/101466731-7ad31280-3967-11eb-8979-67fe65ba17bf.png">

**Affected Product Version:**
3.2.0

**Comment by erangatl** [comment]
Fixed with 
https://github.com/wso2/docs-apim/pull/2621
https://github.com/wso2/docs-apim/pull/2639
