### ISSUE TITLE
"GraphQL Rate Limiting" pages need to be reviewed

### ISSUE THREAD

**Issue by TanyaM** [wso2/docs-apim#2483]
**Description:**
Quoting few below which are either grammatically incorrect, have punctuation mistakes or capitalizing issues etc.
Please go through the entire sub section as there are multiple mistakes.

[Overview](https://apim.docs.wso2.com/en/latest/learn/rate-limiting/graphql-api/overview-query-limits-for-graphql/) Page

<img width="852" alt="Screen Shot 2020-12-08 at 4 21 43 PM" src="https://user-images.githubusercontent.com/3957104/101475155-05207400-3972-11eb-8c11-3ce0fbef569c.png">
--
<img width="850" alt="Screen Shot 2020-12-08 at 4 23 59 PM" src="https://user-images.githubusercontent.com/3957104/101475147-0356b080-3972-11eb-9331-7e7f9dedde75.png">

[Query Depth Limit](https://apim.docs.wso2.com/en/latest/learn/rate-limiting/graphql-api/query-depth-limitation/) Page
<img width="774" alt="Screen Shot 2020-12-08 at 4 27 00 PM" src="https://user-images.githubusercontent.com/3957104/101475498-811abc00-3972-11eb-9c96-43d3803e8b96.png">

---
<img width="816" alt="Screen Shot 2020-12-08 at 4 27 52 PM" src="https://user-images.githubusercontent.com/3957104/101475505-8415ac80-3972-11eb-9bb5-ba6da8e508b3.png">
-----
<img width="792" alt="Screen Shot 2020-12-08 at 4 31 24 PM" src="https://user-images.githubusercontent.com/3957104/101482154-47e74980-397c-11eb-94f5-fc02cd5b3515.png">

**Affected Product Version:**
3.2.0

**Comment by Chamindu36** [comment]
This issue is in progress
