### ISSUE TITLE
[APIM][3.2.0]-Unsupported access token types

### ISSUE THREAD

**Issue by saranki** [wso2/docs-apim#2507]
**Description:**
When creating an application via REST API in wso2am-3.2.0 it is mentioned that in the request payload we can set the "tokenType" as either JWT or OAUTH. But in wso2am-3.2.0 the out-of-the-box generation of the opaque access token feature has been removed. But when we set the token type as OAUTH in the request payload, the response gives the token type as JWT. 
According to the implementation, the token type that is set in the request payload while creating an application is not being consiodered as the default and the only supported tokenType JWT will be set automatically. 
https://apim.docs.wso2.com/en/latest/develop/product-apis/devportal-apis/devportal-v1/devportal-v1/#tag/Applications/paths/~1applications/post

**Affected Product Version:**
wso2am-3.2.0

**Steps to reproduce:**
1. Create an application via REST API with the following payload.
```
{
  "name": "fon-demo-app",
  "throttlingPolicy": "Unlimited",
  "description": "Container application to hold subscribed services for demo",
  "tokenType": "OAUTH",
  "groups": [],
  "attributes": {},
  "subscriptionScopes": []
}
```
2. You will get the following response with tokenType as JWT.
```
{
   "applicationId":"88e4c362-952f-4468-910d-82a9e587d67d",
   "name":"fon-demo-app",
   "throttlingPolicy":"Unlimited",
   "description":"Container application to hold subscribed services for demo",
   "tokenType":"JWT",
   "status":"APPROVED",
   "groups":[
.
.
}
```

**Comment by Sarangan0219** [comment]
Yes we should not mention OAUTH in our 3.2.0 docs.
