### ISSUE TITLE
Confusions in Role Permissions in Admin Portal

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/docs-apim#2517]
**Description:**
A customer has confused the role permissions in management console with the role-scope assignments in the admin portal. The docs related to this should be updated as mentioned in https://github.com/wso2/product-apim/issues/9572

**Suggested Labels:**
CEXP

**Affected Product Version:**
3.2.0

**Comment by chamilaadhi** [comment]
fixed from https://github.com/wso2/docs-apim/pull/2520
