### ISSUE TITLE
Wrong package name for TokenRevocationNotifierImpl class

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/docs-apim#2521]
**Description:**
In the documentation [1], the package name of the TokenRevocationNotifierImpl class should be org.wso2.carbon.apimgt.notification. (Instead of org.wso2.carbon.apimgt.keymgt.events)

`org.wso2.carbon.apimgt.notification.TokenRevocationNotifierImpl`

Also need to change the sample code block which is shown when click on the **View Sample** link.

[1] https://apim.docs.wso2.com/en/latest/reference/config-catalog/#api-m-token-revocation

**Comment by isharac** [comment]
fix in 3.2.0 space #2525

**Comment by Sumudu-Sahan** [comment]
Issue is still there.
![Screenshot from 2020-12-23 14-27-35](https://user-images.githubusercontent.com/18566908/102978877-3df04980-452b-11eb-8e02-6c32a54a4355.png)
