### ISSUE TITLE
[APIM-3.2.0] - Wrong image displaying the token type dropdown list in application creation

### ISSUE THREAD

**Issue by saranki** [wso2/docs-apim#2524]
**Description:**
In wso2am-3.2.0, the OOTB generating opaque access token feature is removed. Therefore, when creating an application the token type dropdown box which contains OAUTH and JWT options is removed from the APIM pack. But in the following document, under the topic "Try Authorization Code Grant" the 2nd point has an image that displays the "Token Type" dropdown box which should be removed.
https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/grant-types/authorization-code-grant/#try-authorization-code-grant

![image](https://user-images.githubusercontent.com/20519000/102704169-e38e8900-429d-11eb-91eb-79334f67ceb3.png)

**Affected Product Version:**
wso2am-3.2.0

**Comment by isharac** [comment]
Ixed with https://github.com/wso2/docs-apim/pull/2525

**Comment by isharac** [comment]
fix in 3.2.0 space #2525
