### ISSUE TITLE
Update docs on registry mounting in IS as KM

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#26]
**Description:**

Pubudu Gunatilaka reported as follows:
For APIM with IS as KM, we create a single database called regdb. This is where we mount both config and government mounts for both the products. As config registry has to be shared only with the specific product nodes, it should contain a separate product-specific path. 

For APIM [1] it is..
`
<mount path="/_system/config" overwrite="true">
   <instanceId>gov</instanceId>
   <targetPath>/_system/config</targetPath>
</mount>
`
In that case, IS should be something like this...
`
<mount path="/_system/config" overwrite="true">
   <instanceId>gov</instanceId>
   <targetPath>/_system/is/config</targetPath>
</mount>
`
Currently, when configuring databases for IS as KM we have the same mount config which is used for API Manager. When a user follows this doc, they ended up having the same mount target path for both IS as KM and APIM. This could lead to issues. Shall we update the docs? @Mariangela Hills  @Shani Ranasinghe  @Ruthryi Kulasekaran  @WSO2 Documentation 

Maybe we can follow the same pattern for the target path of APIM. /_system/apim/config ?

[1] - https://docs.wso2.com/display/AM260/Installing+and+Configuring+the+Databases
[2] - https://docs.wso2.com/display/AM260/Configuring+the+Databases+for+IS+as+the+Key+Manager

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
- Changed <targetPath>/_system/config</targetPath> to <targetPath>/_system/is/config</targetPath> in [1].

-  Changed <targetPath>/_system/config</targetPath> to <targetPath>/_system/apim/config</targetPath> in [2].

[1] https://docs.wso2.com/display/AM260/Configuring+the+Databases+for+IS+as+the+Key+Manager
[2] https://docs.wso2.com/display/AM260/Installing+and+Configuring+the+Databases

**Comment by bhathiya** [comment]
@tharindu1st please review.

**Comment by tharindu1st** [comment]
Hi @bhathiya 
This was being fixed recently in apim, therefore, its no need to have that part as different config mounts.

**Comment by Mariangela** [comment]
@tharindu1st , is that why a page with similar content as [1] is not available in APIM 3.0.0 docs?

[1] https://docs.wso2.com/display/AM260/Configuring+the+Databases+for+IS+as+the+Key+Manager

**Comment by tharindu1st** [comment]
@Mariangela yes, that's why we have different content
