### ISSUE TITLE
ProductAPIs section should have small overview of product APIs

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#272]
Location : https://apim.docs.wso2.com/en/latest/Develop/ProductAPIs/publisher-v1/

**Comment by pubudu538** [comment]
@malinthaprasan

**Comment by shaniR** [comment]
An overview page listing the available API's have been added at https://apim.docs.wso2.com/en/3.0.0/develop/product-apis/restful-apis/. In addition to this, the 3.1.0 space also includes getting started guides for each API. 
Please feel free to reopen if the information in the doc is not adequate.
