### ISSUE TITLE
Doc Feedback: Title of the page should be "WSO2 Admin Portal API"

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#273]
Location : https://apim.docs.wso2.com/en/latest/Develop/ProductAPIs/admin-v1/
The title should be corrected to reflect that this is about Admin portal API

**Comment by Mariangela** [comment]
This has been fixed in https://apim.docs.wso2.com/en/latest/Develop/ProductAPIs/admin-v1/
