### ISSUE TITLE
Doc Feedback: "WSO2" in the title of all the product API pages is redundant 

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#274]
Location : https://apim.docs.wso2.com/en/latest/Develop/ProductAPIs/publisher-v1/

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/1130 for 3.1.0

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/1517 for 3.0.0.

This issue has already been fixed in Master.
