### ISSUE TITLE
Doc Feedback: Unnecessary character in API Visibility title  

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#276]
Location : https://apim.docs.wso2.com/en/latest/GettingStarted/key-concepts/
<img width="698" alt="Screen Shot 2019-11-01 at 12 04 46 PM" src="https://user-images.githubusercontent.com/525801/68049582-87833280-fca0-11e9-9d5c-c8c5c6797bb2.png">

**Comment by shaniR** [comment]
Closing since it's fixed.
