### ISSUE TITLE
Doc Feedback:Formatting improvements 

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#277]
Location : https://apim.docs.wso2.com/en/latest/GettingStarted/quick-start-guide/

1.  The link should be hyperlinks(it is nice if it opens a new tab on click). E.g  https://localhost:9443/publisher ,https://www.mocky.io/, https://www.mocky.io/v2/5185415ba171ea3a00704eed, https://localhost:9443/devportal, ..etc

2. It is nice to have commands in a separate box with the ability to easily copy. E.g
`./apictl add-env -e dev --registration https://localhost:9443/client-registration/v0.15/register --apim https://localhost:9443 --token https://localhost:8243/token`

Please evaluate all other pages with this improvement.

**Comment by shaniR** [comment]
This is fixed for quick start guide. Will incorporate the same changes across the pages when reviewing
