### ISSUE TITLE
Doc Feedback: Too much left and right Margin

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#278]
Location : https://apim.docs.wso2.com/en/latest/Learn/DesignAPI/CreateAPIProduct/api-product-overview/
<img width="1440" alt="Screen Shot 2019-11-01 at 12 21 23 PM" src="https://user-images.githubusercontent.com/525801/68050504-79361600-fca2-11e9-9bee-b3bcec5c1f50.png">

**Comment by Mariangela** [comment]
@erangatl , could you please comment on the Git issue from a UX point of view.

**Comment by erangatl** [comment]
This is a fixed layout and margins are set according to the device with.

Primary content area has an optimum line length (100 cpl) for better readability.
![image](https://user-images.githubusercontent.com/20179540/74164689-2200f380-4c4a-11ea-93c1-38dc4cbcd8f9.png)


For those who prefers longer lines, we have given the capability of collapsing the TOC and expand the content.
![image](https://user-images.githubusercontent.com/20179540/74165335-f29eb680-4c4a-11ea-88ef-80a0336a9733.png)
