### ISSUE TITLE
Doc Feedback: "Enabling Monetization of APIs-" link Doesn't work

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#279]
Location : https://apim.docs.wso2.com/en/latest/Learn/APIMonetization/configuring-api-monetization-category-labels/

And remove '-' as well.

**Comment by shaniR** [comment]
The new doc for instructions on monitizing an API is at https://apim.docs.wso2.com/en/latest/Learn/APIMonetization/monetizing-an-api/
