### ISSUE TITLE
Doc Feedback: Download link for api-import-export-2.6.0-v10.war doesn't work

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#280]
Location : https://apim.docs.wso2.com/en/latest/Learn/CICDPipeline/initializing-projects-using-the-cli-tool/

**Comment by shaniR** [comment]
The content has been re written and can be found at https://apim.docs.wso2.com/en/latest/Learn/APIController/getting-started-with-wso2-api-controller/
