### ISSUE TITLE
Doc Feedback: Inconsistent font emphasize 

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#281]
Location : https://apim.docs.wso2.com/en/latest/Learn/CICDPipeline/initializing-projects-using-the-cli-tool/

<img width="716" alt="Screen Shot 2019-11-01 at 12 37 21 PM" src="https://user-images.githubusercontent.com/525801/68051443-a08de280-fca4-11e9-8592-91657a1bede6.png">

**Comment by shaniR** [comment]
The content has be re-written, https://apim.docs.wso2.com/en/latest/Learn/APIController/getting-started-with-wso2-api-controller/
