### ISSUE TITLE
Doc Feedback: Formatting issues with note,tips and warning boxes

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#282]
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/PerfromanceTuningAndTestResults/tuning-performance/
<img width="1440" alt="Screen Shot 2019-11-01 at 1 43 20 PM" src="https://user-images.githubusercontent.com/525801/68055353-b227b800-fcad-11e9-8d7a-c6f88683b707.png">

<img width="1440" alt="Screen Shot 2019-11-01 at 1 44 24 PM" src="https://user-images.githubusercontent.com/525801/68055384-c370c480-fcad-11e9-969e-4375ab873969.png">

**Comment by ajanthan** [comment]
It is there in multiple locations. Please do a complete review.

**Comment by Mariangela** [comment]
@ajanthan , this page has been removed as the content needs to be updated further.
