### ISSUE TITLE
Doc Feedback: XML format issue

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#283]
<img width="746" alt="Screen Shot 2019-11-01 at 1 47 04 PM" src="https://user-images.githubusercontent.com/525801/68055558-26625b80-fcae-11e9-9b2d-020228d5e86b.png">
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/PerfromanceTuningAndTestResults/tuning-performance/

**Comment by Mariangela** [comment]
This page has been updated and moved to a different location in the doc structure. Please find the new link below.

https://apim.docs.wso2.com/en/latest/InstallAndSetup/PerfromanceTuningAndTestResults/tuning-performance/
