### ISSUE TITLE
Doc Feedback: Table format Issue

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#284]
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/PerfromanceTuningAndTestResults/tuning-performance/
<img width="646" alt="Screen Shot 2019-11-01 at 1 48 54 PM" src="https://user-images.githubusercontent.com/525801/68055665-67f30680-fcae-11e9-8e56-aa86dca3b9ef.png">

**Comment by Mariangela** [comment]
We have removed this page as the content needs to be updated.
