### ISSUE TITLE
Doc Feedback:Format issues

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#285]
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/UpgradingFromAPreviousRelease/upgrading-from-the-previous-release/
<img width="725" alt="Screen Shot 2019-11-01 at 1 55 05 PM" src="https://user-images.githubusercontent.com/525801/68056016-565e2e80-fcaf-11e9-9cc9-b1f4d4147c56.png">

**Comment by ajanthan** [comment]
<img width="725" alt="Screen Shot 2019-11-01 at 1 57 13 PM" src="https://user-images.githubusercontent.com/525801/68056119-958c7f80-fcaf-11e9-852d-a7b285912c87.png">

**Comment by ajanthan** [comment]
<img width="719" alt="Screen Shot 2019-11-01 at 1 58 24 PM" src="https://user-images.githubusercontent.com/525801/68056167-afc65d80-fcaf-11e9-8c1b-04d455c93573.png">

**Comment by ajanthan** [comment]
Formatting of this page needs a complete review

**Comment by Mariangela** [comment]
@ajanthan , thanks for reporting.

The updated pages can be found in [1] and the subsequent pages.

[1] https://apim.docs.wso2.com/en/latest/InstallAndSetup/UpgradingWSO2APIManager/upgrading-process/
