### ISSUE TITLE
Doc Feedback: Unnecessary Content  

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#286]
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/product-profiles/
<img width="1440" alt="Screen Shot 2019-11-01 at 2 04 26 PM" src="https://user-images.githubusercontent.com/525801/68056599-c7521600-fcb0-11e9-9126-df11f57a5a29.png">

**Comment by ajanthan** [comment]
<img width="712" alt="Screen Shot 2019-11-01 at 2 06 52 PM" src="https://user-images.githubusercontent.com/525801/68056631-dfc23080-fcb0-11e9-953b-e31ed63b8145.png">

**Comment by Mariangela** [comment]
This has been fixed in [1]
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/deploying-wso2-api-manager/distributed-deployment/product-profiles/
