### ISSUE TITLE
Access token expired error response is present in the APIM documentation

### ISSUE THREAD

**Issue by AshenJayasuriya** [wso2/docs-apim#2861]
**Description:**
The error code 900903 is not using for the expired access token scenarios. For all expired, invalid and inactive tokens we use the 900901 response. But in the API Manager 3.1.0 documentation[1], the error code 900903 is still present.
![image](https://user-images.githubusercontent.com/5976358/103226603-83a97980-4952-11eb-932f-0b95d80570a7.png)

**Affected Product Version:**
APIM 3.1.0

[1] https://apim.docs.wso2.com/en/3.1.0/troubleshooting/error-handling/#api-handlers-error-codes

**Comment by YasasRangika** [comment]
This issue is in progress
