### ISSUE TITLE
Doc Feedback: Incorrect Title

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#287]
<img width="1440" alt="Screen Shot 2019-11-01 at 2 08 05 PM" src="https://user-images.githubusercontent.com/525801/68056758-2e6fca80-fcb1-11e9-858a-4da08f7f3d1f.png">
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/admin-adding-a-custom-proxy-path/

`admin_` is not needed.

**Comment by shaniR** [comment]
This doc has been removed.
