### ISSUE TITLE
Doc Feedback:Spaces in config file names

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#288]
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/changing-the-default-api-m-databases/
<img width="712" alt="Screen Shot 2019-11-01 at 2 12 05 PM" src="https://user-images.githubusercontent.com/525801/68056963-c40b5a00-fcb1-11e9-8c0c-09517f27df74.png">

**Comment by shaniR** [comment]
This doc has been removed. In place of it, more structured content can be found at  https://apim.docs.wso2.com/en/latest/InstallAndSetup/SettingUpDatabases/overview/
