### ISSUE TITLE
Doc Feedback: List items format issue

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#289]
### The config snippets should be under each database type.
<img width="695" alt="Screen Shot 2019-11-01 at 2 15 07 PM" src="https://user-images.githubusercontent.com/525801/68057092-28c6b480-fcb2-11e9-9c97-f7462ef07975.png">

Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/changing-the-default-api-m-databases/

**Comment by ajanthan** [comment]
<img width="683" alt="Screen Shot 2019-11-01 at 2 23 10 PM" src="https://user-images.githubusercontent.com/525801/68057483-42b4c700-fcb3-11e9-822f-3341cca6bdcd.png">

**Comment by Mariangela** [comment]
This issue has been already fixed in [1] and the other pages related to Changing Default Databases

[1] https://apim.docs.wso2.com/en/latest/InstallAndSetup/SettingUpDatabases/overview/
