### ISSUE TITLE
Doc Feedback: Inconsistent formatting 

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#290]
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/changing-the-default-api-m-databases/
<img width="394" alt="Screen Shot 2019-11-01 at 2 18 23 PM" src="https://user-images.githubusercontent.com/525801/68057231-8a871e80-fcb2-11e9-817c-d99bdff56769.png">

**Comment by shaniR** [comment]
This has been fixed in the new content. https://apim.docs.wso2.com/en/latest/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mysql/
