### ISSUE TITLE
Doc Feedback: Wrong items in tested DB for analytics

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#291]
**It looks like a fomatting issue.**

<img width="708" alt="Screen Shot 2019-11-01 at 2 20 46 PM" src="https://user-images.githubusercontent.com/525801/68057375-eb165b80-fcb2-11e9-828b-acf6ead305a4.png">
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/changing-the-default-api-m-databases/

**Comment by shaniR** [comment]
This section has been added into a new page https://apim.docs.wso2.com/en/latest/Learn/Analytics/configuring-apim-analytics/#step-4-configure-databases
