### ISSUE TITLE
Doc Feedback: Number the list items instead of '-' 

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#292]
<img width="1440" alt="Screen Shot 2019-11-01 at 2 26 13 PM" src="https://user-images.githubusercontent.com/525801/68057658-cf5f8500-fcb3-11e9-8af7-a9b166255e3d.png">
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/common-runtime-and-configuration-artifacts/

**Comment by Meruja** [comment]
Fixed with wso2/docs-apim/pull/581

**Comment by Mariangela** [comment]
This has been fixed in [1]

[1] https://apim.docs.wso2.com/en/latest/administer/product-configurations/common-runtime-and-configuration-artifacts/
