### ISSUE TITLE
Doc Feedback: Image formatting issue

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#293]
<img width="813" alt="Screen Shot 2019-11-01 at 2 29 44 PM" src="https://user-images.githubusercontent.com/525801/68057763-2a917780-fcb4-11e9-88d1-23e1b0ef0594.png">

- The image should be left-aligned
- '3' should be removed as indicated in the screenshot

Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/revoke-oauth2-application/

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/736
