### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#2937]
Location : https://apim.docs.wso2.com/en/latest/learn/design-api/advanced-topics/enabling-cors-for-apis/

In step4 , note should it be response caching or cors?

Please refer to the image.
<img width="767" alt="Screen Shot 2021-01-14 at 11 58 45 AM" src="https://user-images.githubusercontent.com/8057793/104553054-f9565a80-565f-11eb-89b4-e096f2ed2be3.png">

**Comment by hisanhunais** [comment]
Fixed in 3.1.0 with https://github.com/wso2/docs-apim/pull/1827
