### ISSUE TITLE
[3.1.0] Modify the documentation for APIM analytics configurations

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/docs-apim#2939]
**Description:**
In [1], It says to configure 'receiver_urls' and [[apim.analytics.url_group]] both in order to specify the urls and not required to use both the properties. So shall we mentioned in the ticket to use one property for configuring purposes.

**Suggested Labels:**
CEXP, Priority/High

**Affected Product Version:**
API Manager 3.1.0

[1] https://apim.docs.wso2.com/en/3.1.0/learn/analytics/configuring-apim-analytics/

Regards
Maneesha

**Comment by Chamindu36** [comment]
This issue is in progress.

**Comment by Chamindu36** [comment]
The fixes had been added to all relevant versions with the attached Pull requests. Hence, we can close this issue.
