### ISSUE TITLE
Doc Feedback:formatting issues

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#294]
Location : https://apim.docs.wso2.com/en/latest/Administer/jmx-monitoring/

**Comment by ajanthan** [comment]
List items should be properly formatted rather than listed with '-'
<img width="539" alt="Screen Shot 2019-11-01 at 2 34 24 PM" src="https://user-images.githubusercontent.com/525801/68057961-ca4f0580-fcb4-11e9-9c4a-f42f622eba0d.png">

**Comment by ajanthan** [comment]
Table items are not formatted correctly 


<img width="716" alt="Screen Shot 2019-11-01 at 2 35 32 PM" src="https://user-images.githubusercontent.com/525801/68057987-ebaff180-fcb4-11e9-9e46-56db4a063014.png">

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/740

**Comment by Mariangela** [comment]
Latest doc link is as follows:
https://apim.docs.wso2.com/en/latest/administer/product-administration/monitoring/jmx-based-monitoring/
