### ISSUE TITLE
Problems with enabling the size based logging(APIM-3.2.0) 

### ISSUE THREAD

**Issue by dumindurox777** [wso2/docs-apim#2940]
Description:
`org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : SizeBasedTriggeringPolicy contains an invalid element or attribute "modulate" Ignored FQCN: org.apache.logging.log4j.spi.AbstractLogge`

The above error is caused by setting the following property to enable size based rollover according to document [1].
Its unnecessary to set "modulate" property to size based triggering policy. When the above property is set, its trying to pass an invalid argument to size based triggering policy, which results in the error message above.

<img width="600" alt="Screen Shot 2021-01-14 at 7 30 09 PM" src="https://user-images.githubusercontent.com/29389251/104600469-09d9f580-569f-11eb-8aa5-24bccd30b57e.png">

`appender.CARBON_LOGFILE.policies.size.modulate = true`

Therefore the step b in section under **Managing the growth of Carbon logs** in the documentation[1] should be remove from the document and update according to that.

**Affected Product Version:**
APIM-3.2.0

This information needs to be added in APIM 3.2.0 documentation [2].
[1]  https://apim.docs.wso2.com/en/latest/administer/logging-and-monitoring/logging/managing-log-growth/#

**Comment by Chamindu36** [comment]
This issue is in progress.
