### ISSUE TITLE
Doc Feedback: The Title should not use underscore naming 

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#295]
<img width="223" alt="Screen Shot 2019-11-01 at 2 37 53 PM" src="https://user-images.githubusercontent.com/525801/68058112-519c7900-fcb5-11e9-89ae-013136989138.png">
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/WorkingWithTransports/admin-introduction-to-transports/

**Comment by ajanthan** [comment]
It is there in multiple location. Please do a complete review.

**Comment by shaniR** [comment]
These have been fixed,
