### ISSUE TITLE
Doc Feedback: Forget password screenshot uses old UIs

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-apim#296]
Location : https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/identity-management-for-the-api-store/

Now in APIM 3.0.0, the default login screen is following.

<img width="493" alt="Screen Shot 2019-11-01 at 2 53 25 PM" src="https://user-images.githubusercontent.com/525801/68058810-6bd75680-fcb7-11e9-83f0-6f6bee14f54c.png">

But the screenshots on the page show different(old UIs). Better to use the default UIs since the majority of the users are going to stick to that.

<img width="719" alt="Screen Shot 2019-11-01 at 2 51 23 PM" src="https://user-images.githubusercontent.com/525801/68058922-d5effb80-fcb7-11e9-9c09-413b4bf6b1e1.png">

**Comment by Mariangela** [comment]
This has been fixed in [1]

[1] https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/identity-management-for-the-api-dev-portal/
