### ISSUE TITLE
[310] Fix HA terminology in APIM Analytics

### ISSUE THREAD

**Issue by lahirus** [wso2/docs-apim#2975]
**Description:**
We are using HA for failover everywhere in docs as well as in configurations while Active-Active is also HA.

Can we fix this in docs?

"When using WSO2 API-M Analytics 3.1.0, when publishing to an HA setup of APIM analytics, you need to separate the Receiver URLs by the pipe symbol (|) because the analytics events are published in a failover manner where only one node handles the processing at any given time." 

[1] https://apim.docs.wso2.com/en/3.1.0/learn/analytics/configuring-apim-analytics/#step-3-configure-wso2-api-manager-to-publish-statistics

**Comment by Chamindu36** [comment]
This issue is in progress

**Comment by Chamindu36** [comment]
This fix has been added to all the relevant branches, Hence we can close this issue.
