### ISSUE TITLE
Revamp Getting Started page in CTL Docs

### ISSUE THREAD

**Issue by npamudika** [wso2/docs-apim#3031]
**Description:**
The doc page [1] should be revamped by moving following sections to another page titled "Managing APIM Related Operations with CTL" or another.

- Add APIs/API Products/Applications in an environment
- Get APIs/API Products/Applications in an environment
- Delete an API/API Product/Application in an environment
- Change status of an API in an environment
- Formatting the outputs of get
       - Available formatting options

[1] https://apim.docs.wso2.com/en/next/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller

**Comment by Chamindu36** [comment]
As per the offline discussion on this issue, this is the new directory structure that has been suggested.

```
└── API Controller
    ├── Advanced Topics
    │   ├── Configuring Different Endpoint Types
    │   ├── Configuring Environment Specific Parameters
    │   ├── Configuring Git Integration
    │   ├── Creating Custom Users to Perform API Controller Operations
    │   └── Using Dynamic Data in API Controller Projects
    ├── Building a Jenkins CI_CD Pipeline for Dev First Approach
    ├── CICD with WSO2 API Manager
    ├── Getting Started with WSO2 API Controller
    ├── Managing APIs_API Products
    │   ├── Importing APIs Via Dev First Approach
    │   ├── Managing APIs_APIProducts (list,delete,add,changestatus)
    │   ├── Migrating API Products (with or without dependent APIs) to Different Environments
    │   └── Migrating APIs to Different Environments
    └── Managing Applications
        ├── Managing Applications(list,delete,add)
        └── Migrating Apps to Different Environments
```
