### ISSUE TITLE
Doc Feedback: update according to the latest changes

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#3065]
Location : https://apim.docs.wso2.com/en/latest/develop/extending-api-manager/extending-key-management/writing-custom-grant-types/

Since APIM 3.2.0 we have separated some classes in keymgt package to tokenmgt  we need to update this doc accordingly.
Please refer below image for the changed package names.
<img width="465" alt="Screen Shot 2021-02-01 at 5 52 55 PM" src="https://user-images.githubusercontent.com/8057793/106458477-74b86880-64b6-11eb-87ca-1ca29ff3017f.png">

Wec need to change the extended classes to tokenmgt classes for Vanila pack users.

ut for wum users we need to use respective classes from IS as we totally decoupled with the IS.

**Comment by dushaniw** [comment]
Need to add this separately for GA and U2 updated packs in 3.2.0 docs
