### ISSUE TITLE
Heading structure in the custom JWT generation is misleading

### ISSUE THREAD

**Issue by TanyaM** [wso2/docs-apim#3089]
Location : https://apim.docs.wso2.com/en/latest/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt/

Heading structure should be changed as follows.

**Configuring JWT**

**Changing the JWT encoding to Base64URL encoding**

**Expiry time of the JWT**

**Customizing JWT Generation**
 * Customizing the JWT generation - (Opaque (Reference) Access Tokens)
    * Customizing the JWT generation completely
    * Customizing the user-related claims in JWT
* Customizing the JWT generation - (JWT (Self Contained) Access Tokens)

P.S. Change wording as required. But maintain the level of the headings.

**Comment by Mariangela** [comment]
Fixed in 3.1.0, 3.2.0 and 4.0.0
