### ISSUE TITLE
Update API operator link (GIT tag) to point to the latest released version

### ISSUE THREAD

**Issue by himasha** [wso2/docs-apim#3115]
### Description:
Need to update the QSG and the operator doc space links in [1]

[1] https://apim.docs.wso2.com/en/latest/learn/kubernetes-operators/k8s-wso2am-operator/
### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by dinusha92** [comment]
Closing the issues since this is fixed with the above referenced PR.
