### ISSUE TITLE
Consistent naming convention needed for WSO2 API Controller (APICTL)

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/docs-apim#3156]
**Description:**
In the Getting Started page we have used "WSO2 API Controller(CTL)" [1] and all the other pages we have used like "WSO2 API Controller (apictl)" [2]. We need to change all the place to "WSO2 API Controller (APICTL)".

[1] https://apim.docs.wso2.com/en/latest/learn/api-controller/getting-started-with-wso2-api-controller/
[2] https://apim.docs.wso2.com/en/latest/learn/api-controller/importing-apis-via-dev-first-approach/

**Comment by wasuradananjith** [comment]
The lowercase **apictl** is more suitable than the uppercase one since it gives a snapshot of the apictl command to the user at once and it is similar like kubectl where the Kubernetes guys have used in their docs [1].

Eg:- **WSO2 API Controller (apictl)**

[1] https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by wasuradananjith** [comment]
This has been fixed for APIM 4.0.0 docs (master) via https://github.com/wso2/docs-apim/pull/3311. If we are doing the changes to other older versions make sure not to change the titles, otherwise, it will break the links that the users maintain in their side.

**Comment by samgnaniah** [comment]
Closing this since it is done in the more recent versions of the docs.
