### ISSUE TITLE
Doc Feedback: Location : https://apim.docs.wso2.com/en/latest/learn/api-gateway/message-mediation/passing-a-custom-authorization-token-to-the-backend/

### ISSUE THREAD

**Issue by glauciomkw** [wso2/docs-apim#3159]
Hi,

This page was not found: https://apim.docs.wso2.com/en/3.2.0/learn/consume-api/manage-application/generate-keys/obtain-access-token/application-access-tokens/
I found this page through this link: https://apim.docs.wso2.com/en/latest/learn/api-gateway/message-mediation/passing-a-custom-authorization-token-to-the-backend/ in session 5 (tip to generate access token).

**Comment by Mariangela** [comment]
@glauciomkw, thank you for reporting this issue!

The correct link should be as follows:
https://apim.docs.wso2.com/en/3.2.0/learn/consume-api/manage-application/generate-keys/generate-api-keys/#generate-application-keys

We have now fixed this issue in the API-M documentation.

Regards,
Mariangela
