### ISSUE TITLE
Updating docs to support in-place updates on profile optimized packs

### ISSUE THREAD

**Issue by rmsamitha** [wso2/docs-apim#3198]
**Description:**
There was an issue that in-place updates tool cannot be run, on a profile optimized pack. A fix will be done on WUM to support in-place tool execution on a profile optimized pack.
For this new process to succeed, an APIM server should be started with below options, whenever it is started in a profile. (so when starting it will optimize the pack too and then start)

`-Dprofile=<preferred-profile> --optimize --skipConfigOptimization`

e.g. `sh wso2server.sh -Dprofile=api-publisher --optimize --skipConfigOptimization`

`--optimize` option is used so that if the pack is in-place updated even after initial optimization,  the product pack would have fetched irrelevant files for this profile. So by this option, the pack will be profile optimized again.

`--skipConfigOptimization` option is used above to prevent configuration optimization at server startup in this approach.

So this should be changed in [1] under step 5 under "Method 1- Optimizing before starting the server"
This should be fixed in all the version where in-place update tool is supported.

[1] https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/distributed-deployment/product-profiles/#method-1-optimizing-before-starting-the-server

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by bhathiya** [comment]
Shall we change the order to below?

`-Dprofile=<preferred-profile> --optimize --skipConfigOptimization`

**Comment by rmsamitha** [comment]
> Shall we change the order to below?
> 
> `-Dprofile=<preferred-profile> --optimize --skipConfigOptimization`

+1. Changed the issue description accordingly
