### ISSUE TITLE
Doc Feedback: Unable to access Website link.

### ISSUE THREAD

**Issue by muneebrehman-github** [wso2/docs-apim#321]
Facing Issue and cannot access below link.

Location : https://apim.docs.wso2.com

![image](https://user-images.githubusercontent.com/55014869/68120338-de01a280-ff26-11e9-80a7-4bbf25d97376.png)

**Comment by shaniR** [comment]
Thank you for reporting. We are sorry for the late reply. Hopefully it worked shortly afterwards. 
Let us know if you require any further assistance.
