### ISSUE TITLE
Formatting issues in performance pages

### ISSUE THREAD

**Issue by nirmal070125** [wso2/docs-apim#327]
**Description:**

https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/PerfromanceTuningAndTestResults/tuning-performance/#apim-level-settings

- xmls not formatted
- tables are having formatting issues

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shaniR** [comment]
Closing this issue as it is tracked via the following two issues.
https://github.com/wso2/docs-apim/issues/284
https://github.com/wso2/docs-apim/issues/283
