### ISSUE TITLE
Grant types page is empty

### ISSUE THREAD

**Issue by nirmal070125** [wso2/docs-apim#328]
**Description:**

https://apim.docs.wso2.com/en/latest/Learn/ConsumeAPI/ManageApplication/grant-type/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shaniR** [comment]
The content has be filled in and the page https://apim.docs.wso2.com/en/latest/Learn/ConsumeAPI/ManageApplication/grant-type/ is now pointing to https://apim.docs.wso2.com/en/latest/Learn/APISecurity/OAuth2DeepDive/GrantTypes/password-grant/
