### ISSUE TITLE
Update API Manager Configurations with 'Assert identity using mapped local subject identifier'

### ISSUE THREAD

**Issue by athiththan11** [wso2/docs-apim#3286]
**Description:**

The API Manager Docs (following Doc sections) need to be updated with the `Assert identity using mapped local subject identifier` configurations to work with the SSO configurations as expected (as fixed/updated in [https://github.com/wso2/docs-apim/pull/3259](https://github.com/wso2/docs-apim/pull/3259)).

- [Configuring-Identity-Server-as-External-IDP-using-SAML](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-saml/#step-2-configure-the-service-provider)
- [Configuring-WSO2-API-Manager-apps-as-SAML](https://apim.docs.wso2.com/en/latest/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso/#configuring-wso2-api-manager-apps-as-saml-20-sso-service-providers)

**Affected Product Version:**

- APIM 3.2.0

**Related Issues:**

- [https://github.com/wso2/docs-apim/pull/3259](https://github.com/wso2/docs-apim/pull/3259)

**Comment by samgnaniah** [comment]
This issue looks like it's fixed so I'm closing this.
