### ISSUE TITLE
Subscription Availability dropdown is not available in wso2am-3.2.0 version

### ISSUE THREAD

**Issue by saranki** [wso2/docs-apim#3292]
**Description:**
The Subscription Availability dropdown option in publisher is not available in wso2am-3.2.0 but available in wso2am-3.1.0.

**Affected Product Version:**
wso2am-3.2.0

**Steps to reproduce:**
1. Created a new tenant
2. Created an API with Visibility on Developer Portal is public
3. Check the Subscription Availability dropdown in the subscriptions section according to the documentation. But Subscription Availability dropdown is not visible in the subscriptions section
![image](https://user-images.githubusercontent.com/20519000/110523272-de700600-8137-11eb-8b8d-d6c013b42e3c.png)
4. When the same steps were followed in wso2am-3.1.0 the subscription dropdown list got displayed
![image](https://user-images.githubusercontent.com/20519000/110523300-e92a9b00-8137-11eb-909d-74a132739ace.png)

**Related Issues:**
https://github.com/wso2/product-apim/issues/9559

**Solution:**
In the deployment.toml file the following needs to be added. This needs to be documented in https://apim.docs.wso2.com/en/latest/learn/design-api/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal/#control-subscription-availability-in-developer-portal
```
[apim.devportal]
enable_cross_tenant_subscriptions = true
```
![image](https://user-images.githubusercontent.com/20519000/110523593-550d0380-8138-11eb-884b-1672b894b56a.png)

**Comment by HeshanSudarshana** [comment]
Closing since the PR is merged for 3.2.0 and available for 4.0.0.
