### ISSUE TITLE
Update token endpoints in token revocation docs

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/docs-apim#3306]
**Description:**
Need to update the token revocation endpoint to `oauth2/revoke` for APIM-4.0.0 in the token revocation docs [1].

[1] - https://github.com/wso2/docs-apim/blob/master/en/docs/design/api-security/oauth2/token-revocation.md

**Comment by Mariangela** [comment]
This will be addressed in https://github.com/wso2/docs-apim/issues/4123
