### ISSUE TITLE
API Manager publishing via multiple gateways is not working

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/docs-apim#3355]
**Description:**
Following the documented steps in [1] for publishing via multiple gateways is not working for APIM 3.2.0.

The following configuration should also be added to the configurations that should be done under Gateway nodes.

```
[apim.throttling] 
service_url = "https://localhost:9443/services/"
throttle_decision_endpoints = ["tcp://localhost:5672"]
```

Remove the following configuration from the config section that should be added to Gateway Nodes.

```
[apim.oauth_config]
revoke_endpoint = "https://localhost:8243/services"
```
Change the Key manager configuration section under Gateway nodes to following.

```
[apim.key_manager]
service_url = "https://localhost:9443/services/"
username = "admin"
password = "admin"
```

Change the configuration that should be added to the Publisher, Store, KM and TM nodes to the following.

```
[[apim.gateway.environment]]
name = "Production Gateway"
type = "production"
display_in_api_console = true
description = "Production Gateway Environment"
show_as_token_endpoint_url = true
service_url = "https://localhost:9444/services/"
username= "admin"
password= "admin"
http_endpoint = "http://localhost:8281"
https_endpoint = "https://localhost:8244"

[[apim.gateway.environment]]
name = "Production and Sandbox"
type = "hybrid"
display_in_api_console = true
description = "Hybrid Gateway Environment"
show_as_token_endpoint_url = true
service_url = "https://localhost:9445/services/"
username= "admin"
password= "admin"
http_endpoint = "http://localhost:8282"
https_endpoint = "https://localhost:8245"
```

[1] https://apim.docs.wso2.com/en/latest/learn/design-api/publish-api/publish-through-multiple-api-gateways/#step-1-publish-an-api-via-multiple-api-gateways

**Comment by Mariangela** [comment]
@tharindu1st , please confirm the last point that Tharika mentioned.

**Comment by Mariangela** [comment]
Tharindu commented as follows:

1. Remove following configuration from Step4.
[apim.oauth_config]
revoke_endpoint = "https://localhost:8243/services/"

2. Add the following configuration to 2nd and 3rd (Gateway) node.
[apim.throttling] 
service_url = "https://tm.wso2.com:9446/services/"
throttle_decision_endpoints = ["tcp://localhost:5672"]

**Comment by tharikaGitHub** [comment]
@Mariangela I have updated the configurations in the issue description with what needs to be changed. Let's add that to the documentation.
