### ISSUE TITLE
Remove carbon permission assignment when creating new roles and configuring

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/docs-apim#3367]
**Description:**
From https://github.com/wso2/carbon-apimgt/pull/10106, carbon permission requirements for roles are removed. Hence remove the permission assignment step in [1] 

[1] https://apim.docs.wso2.com/en/latest/administer/managing-users-and-roles/managing-user-roles/

**Comment by Mariangela** [comment]
@malinthaprasan , can this issue be closed? Or is there still more work pending in this regard?
