### ISSUE TITLE
Internal Links with in a page are not loading directly as expected

### ISSUE THREAD

**Issue by chaamini** [wso2/docs-apim#337]
When trying loading following link [1] the page does not load with the selected topic rather the page is loading from the top
[1]https://apim.docs.wso2.com/en/latest/SetupAndInstall/DeployingWSO2APIManager/deployment-patterns/#DeploymentPatterns-Pattern4

**Comment by shaniR** [comment]
Try this https://apim.docs.wso2.com/en/latest/InstallAndSetup/DeployingWSO2APIManager/deployment-patterns/#pattern-4.
