### ISSUE TITLE
Updated docs after APIM directory and file name refactoring

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#3390]
**Description:**
Update documentation that has the following links after [1] is fixed.
<API-M_HOME>/repository/deployment/server/jaggeryapps/devportal/site/public/theme/defaultTheme.js
<API-M_HOME>/repository/deployment/server/jaggeryapps/publisher/site/public/conf/userThemes.js
<API-M_HOME>/repository/deployment/server/jaggeryapps/admin/site/public/conf/defaultTheme.js

**Related Issues:**
[1] https://github.com/wso2/product-apim/issues/10460
https://github.com/wso2/docs-apim/pull/3267

**Comment by Mariangela** [comment]
[2] Partly fixes this issue

[2] https://github.com/wso2/docs-apim/pull/4253

**Comment by Mariangela** [comment]
@samgnaniah , I have a feeling that this issue was addressed by one of the PRs that you sent recently. Please check and close this issue while citing the other issue ID.

**Comment by samgnaniah** [comment]
This is fixed now.
