### ISSUE TITLE
Passing Enduser Attributes to the Backend Using JWT is not working as per the documentation

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#34]
**Description:**

Francisco Ribeiro reported as follows:

I tried to build a custom JWT Generator using the documentation for APIM 260[1], but faced some issues:

1. In the documentation there is no instruction on how to build the class and generate the jar file, I followed [2] in order to have a pom.xml that I could use;
2. After creating the maven project, it was not able to build the project due to some compilation errors, as seen below:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project CustomJWTGenerator: Compilation failure: Compilation failure:

[ERROR] /Users/francisco/IntegrationStudio/workspace/CustomJWTGenerator/src/main/java/org/wso2/carbon/test/CustomTokenGenerator.java:[3,37] cannot find symbol

[ERROR] symbol:   class APIConstants

[ERROR] location: package org.wso2.carbon.apimgt.keymgt

[ERROR] /Users/francisco/IntegrationStudio/workspace/CustomJWTGenerator/src/main/java/org/wso2/carbon/test/CustomTokenGenerator.java:[4,41] package org.wso2.carbon.apimgt.keymgt.dto does not exist

[ERROR] /Users/francisco/IntegrationStudio/workspace/CustomJWTGenerator/src/main/java/org/wso2/carbon/test/CustomTokenGenerator.java:[12,55] cannot find symbol

[ERROR] symbol:   class TokenValidationContext

[ERROR] location: class org.wso2.carbon.test.CustomTokenGenerator

[ERROR] /Users/francisco/IntegrationStudio/workspace/CustomJWTGenerator/src/main/java/org/wso2/carbon/test/CustomTokenGenerator.java:[35,37] cannot find symbol

[ERROR] symbol:   class APIKeyValidationInfoDTO

[ERROR] location: class org.wso2.carbon.test.CustomTokenGenerator

[ERROR] -> [Help 1]
`

To fix that I needed to update the import list and the populateStandardClaims method to be like this:
`	public Map<String, String> populateStandardClaims(TokenValidationContext validationContext)

            throws APIManagementException {

		

        Map<String, String> claims = super.populateStandardClaims(validationContext);

        boolean isApplicationToken =

        		validationContext.getValidationInfoDTO().getUserType().equalsIgnoreCase(APIConstants.ACCESS_TOKEN_USER_TYPE_APPLICATION) ? true : false;

        String dialect = getDialectURI();

        if (claims.get(dialect + "/enduser") != null) {

            if (isApplicationToken) {

                claims.put(dialect + "/enduser", "null");

                claims.put(dialect + "/enduserTenantId", "null");

            } else {

                String enduser = claims.get(dialect + "/enduser");

                if (enduser.endsWith("@carbon.super")) {

                    enduser = enduser.replace("@carbon.super", "");

                    claims.put(dialect + "/enduser", enduser);

                }

            }

        }

 

        return claims;

 

    }
`

3. The changes above fixed the compilation issues, but after adding the jar file to the APIM installation, it was not adding the custom claims to the JWT. The issue was because of the populateCustomClaims method signature. In order to fix it, I needed to change it  from:
`
public Map populateCustomClaims(APIKeyValidationInfoDTO keyValidationInfoDTO, String apiContext, String version, String accessToken)

            throws APIManagementException {
`

To:
`
public Map<String, String> populateCustomClaims(TokenValidationContext tokenValidationContext) throws APIManagementException {
`

The final working class can be found at[3].

Could we get the code presented in the documentation fixed? 

[1] https://docs.wso2.com/display/AM260/Passing+Enduser+Attributes+to+the+Backend+Using+JWT
[2] https://dzone.com/articles/custom-jwt-generator-in-wso2-api-manager
[3]https://gist.github.com/fjunior87/5d33a961162382089cf6c08dbc152bca

**Suggested Labels:**
API-M 2.6.0

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Updated in [1].

[1] https://docs.wso2.com/display/AM260/Passing+Enduser+Attributes+to+the+Backend+Using+JWT

**Comment by Mariangela** [comment]
This change needs to be made in the API-M 3.0.0 docs as well.

**Comment by Mariangela** [comment]
@Arshardh , please confirm whether the changes mentioned in this Git issue, which has been done in the APIM 2.6.0 docs [1], should be applied to the APIM 3.0.0 [2] docs.

[1] https://docs.wso2.com/pages/diffpagesbyversion.action?pageId=97563670&selectedPageVersions=2&selectedPageVersions=1
[2] https://apim.docs.wso2.com/en/latest/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt/

**Comment by Arshardh** [comment]
Yes @Mariangela, we should apply this to 3.0.0 dos as well.

**Comment by Mariangela** [comment]
Fixed in API-M 3.0.0 as well
- https://github.com/wso2/docs-apim/pull/798
- https://github.com/wso2/docs-apim/pull/798/commits/21656b015870353cf39520a553d19d0ab240411f
- https://apim.docs.wso2.com/en/latest/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt/
