### ISSUE TITLE
Kafka connector documentation needs to update with new connection model

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/docs-apim#3402]
**Description:**

Please refer to the https://github.com/wso2/micro-integrator/issues/2157

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Closing this as issue already exists.
