### ISSUE TITLE
Configuration mentioned at Hashicope Vault doc doesn't work

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/docs-apim#3404]
**Description:**
Please refer to https://github.com/wso2/micro-integrator/issues/2126

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Closing this as issue already exists.
