### ISSUE TITLE
Wrong instructions to create a topic and start consumer

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/docs-apim#3406]
**Description:**
Please refer to https://github.com/wso2/micro-integrator/issues/2158

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
This is a duplicate of https://github.com/wso2/docs-apim/issues/3649
