### ISSUE TITLE
[4.0.0] Outdated screenshots in create rest API doc

### ISSUE THREAD

**Issue by dinusha92** [wso2/docs-apim#3421]
**Description:**

https://apim.docs.wso2.com/en/next/design/create-api/create-a-rest-api/

In the aforementioned documentation, the screenshots are outdated.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dinusha92** [comment]
Same with QSG doc. https://apim.docs.wso2.com/en/next/get-started/quick-start-guide/quick-start-guide/

**Comment by samgnaniah** [comment]
This seems to be fixed now. Closing this.

**Comment by Mariangela** [comment]
The APIM QSG has been rechecked and updated in [1]

[1] https://github.com/wso2/docs-apim/issues/4541

**Comment by samgnaniah** [comment]
This is updated and fixed now.
