### ISSUE TITLE
[4.0.0] Cannot find deny policies documentation.

### ISSUE THREAD

**Issue by dinusha92** [wso2/docs-apim#3428]
**Description:**

In 4.0.0 doc space, I could not fine deny policies section. Even though I navigated to throttling related doc section, deny policies were not there.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Chamindu36** [comment]
The deny policies section can be found on the **Denying Requests** section[1] on the **Access control** [2] page. Hence, we can close this issue.

[1]. https://apim.docs.wso2.com/en/latest/design/rate-limiting/access-control/#denying-requests
[2]. https://apim.docs.wso2.com/en/latest/design/rate-limiting/access-control/
