### ISSUE TITLE
Create API UI's in docs need to be updated

### ISSUE THREAD

**Issue by dnwick** [wso2/docs-apim#3429]
**Description:**
https://apim.docs.wso2.com/en/4.0.0-dev/design/create-api/create-a-rest-api/ outdated

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Issue already exists so closing this.
