### ISSUE TITLE
Publish your API link is redirecting to wrong url

### ISSUE THREAD

**Issue by dnwick** [wso2/docs-apim#3431]
**Description:**
https://apim.docs.wso2.com/en/4.0.0-dev/design/create-api/create-a-rest-api/ here Publish your API is redirecting to page not found and should go to https://apim.docs.wso2.com/en/4.0.0-dev/deploy-and-publish/publish-on-dev-portal/publish-an-api/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
This is fixed now so closing this. Thanks for reporting this.
