### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/docs-apim#3432]
**Description:**

Broken links in the following [1].
<img width="1414" alt="Screenshot 2021-03-30 at 12 28 44" src="https://user-images.githubusercontent.com/17607360/112946757-871bef00-9153-11eb-9840-0829f638e2d6.png">

[1] - https://apim.docs.wso2.com/en/4.0.0-dev/deploy-and-publish/deploy-on-gateway/api-gateway/message-mediation/adding-dynamic-endpoints/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
The links on this page are now working in the latest GA version.
Thanks for reporting.
