### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by imaadhrizni** [wso2/docs-apim#345]
**Description:**
Invalid placeholder text on Step 2 at https://apim.docs.wso2.com/en/latest/Learn/APIGateway/MessageMediation/convert-a-json-message-to-soap-and-soap-to-json/

<img width="1679" alt="apim-docs" src="https://user-images.githubusercontent.com/11399574/68271757-a3634b80-0087-11ea-962c-6b1e7d42c312.png">

**Comment by Mariangela** [comment]
This page has been removed, so this Git issue is not applicable anymore.

@Krishanx92 , can you please give us more context as to why this page has been removed.

**Comment by Krishanx92** [comment]
> This page has been removed, so this Git issue is not applicable anymore.
> 
> @Krishanx92 , can you please give us more context as to why this page has been removed.

APIM-3.0.0 support soap to rest feature. hence removed.
