### ISSUE TITLE
Doc Feedback: Missing Portions and Invalid Link

### ISSUE THREAD

**Issue by imaadhrizni** [wso2/docs-apim#346]
Location : https://apim.docs.wso2.com/en/latest/Learn/APISecurity/Authorization/role-based-access-control-using-xacml/

1) First Paragraph hyperlink with text "OAuth 2.0 scope" results in not found
2) Section "Enabling role-based access control" all copy-paste commands are showing either "!!! tip" or "!!! note"

**Comment by Meruja** [comment]
fixed with wso2/docs-apim/pull/593

**Comment by Mariangela** [comment]
This has been fixed in https://apim.docs.wso2.com/en/latest/Learn/APISecurity/Authorization/role-based-access-control-using-xacml/
