### ISSUE TITLE
Need to fix typos in Async API publish tutorial and its better if we can have the final steps on how to test this also

### ISSUE THREAD

**Issue by dnwick** [wso2/docs-apim#3503]
**Description:**
In following [1] "To enable the Streaming Integrator to publish asynchronous APIs, follow thge steps below" contains the typo "thge" 

[1]https://github.com/wso2/docs-apim/blob/master/en/docs/use-cases/streaming-usecase/exposing-stream-as-managed-api-in-service-catalogue.md

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
This is fixed now.
