### ISSUE TITLE
Try out in Postman downloads a collection with 3.2.0 as name

### ISSUE THREAD

**Issue by TheNiron** [wso2/docs-apim#3531]
**Description:**

**Try out in Postman** downloads collection with 3.2.0 as name

<img width="782" alt="Screen Shot 2021-04-08 at 2 30 34 PM" src="https://user-images.githubusercontent.com/32265029/114000255-73ba0380-9878-11eb-9591-1862ef1202db.png">

https://apim.docs.wso2.com/en/4.0.0-dev/reference/product-apis/publisher-apis/publisher-v2/publisher-v2/#section/Authentication

**Suggested Labels:**
API-M-4.0.0

**Affected Product Version:**
API-M-4.0.0

**Comment by dushansilva** [comment]
This has already been fixed, hence closing issue
