### ISSUE TITLE
Remove Search with Microgateway Labels

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/docs-apim#3539]
**Description:**
Remove usage of Microgateway Labels
path: consume/discover-apis/search/
![image](https://user-images.githubusercontent.com/23183042/114029220-ea65f980-9896-11eb-8eb0-fa3c03aa54a7.png)

**Comment by Mariangela** [comment]
This has been fixed in APIM 4.0.0 and 4.1.0
https://apim.docs.wso2.com/en/4.1.0/consume/discover-apis/search/
https://apim.docs.wso2.com/en/4.0.0/consume/discover-apis/search/
