### ISSUE TITLE
SI tooling starting shell file name is wrong

### ISSUE THREAD

**Issue by dnwick** [wso2/docs-apim#3552]
**Description:**
In [1] following should be changed to tooling.sh and tooling.bat
For Windows: streaming-integrator-tooling.bat
For Linux: ./streaming-integrator-tooling.sh

[1]https://apim.docs.wso2.com/en/4.0.0-dev/develop/streaming-apps/streaming-integrator-studio-overview/#starting-streaming-integrator-tooling

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Duplicated by https://github.com/wso2/docs-apim/issues/3551
