### ISSUE TITLE
[MI] Docs improvements for working with the MI Dashboard

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/docs-apim#3553]
**Description:**
### Issue1
In the documentation at https://apim.docs.wso2.com/en/4.0.0-dev/observe/mi-observe/working-with-monitoring-dashboard/
we need to mention how to configure the dashboard to use a user store existent in the MI-user store. This should be there before https://apim.docs.wso2.com/en/4.0.0-dev/observe/mi-observe/working-with-monitoring-dashboard/#start-the-mi-dashboard

### Issue2
And according to my understanding the order of headings should be:
1. Configure the MI servers
2. Configure the Dashboard
3. Start the MI Dashboard
4. Start the Micro Integrator
5. Sign in to the Dashboard

so that the MI server gets registered just after starting the MI server. Or else we will have to wait for the next heartbeat.

### Issue3
Before logging into the dashboard we need to verify that at least one node is connected to the dashboard. That is by the presence of the following log:
```
New node 057b435b-0760-4107-9ac5-e3f5db4cc040 in group : default is registered. Inserting heartbeat information
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Closing this as this seems fixed.
