### ISSUE TITLE
Configuring the Primary User Stores links are broken

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/docs-apim#3559]
**Description:**
Broken links in **Configuring the Primary User Store**

https://apim.docs.wso2.com/en/4.0.0-dev/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store/

Clicking in any of the following link will end up in page not found page
![image](https://user-images.githubusercontent.com/32265029/114259180-1493e600-9981-11eb-95b5-55d037581a2f.png)

![image](https://user-images.githubusercontent.com/32265029/114259193-237a9880-9981-11eb-9d44-45c9e267ebff.png)

**Suggested Labels:**
API-M-4.0.0

**Suggested Assignees:**

**Affected Product Version:**
API-M-4.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
These seem to be fixed in the GA [1]. Therefore, closing this PR.
Please reopen if you find any other issues.

[1] https://apim.docs.wso2.com/en/latest/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store/
