### ISSUE TITLE
Need to replace "Production and Sandbox' to "Default" in all the places.

### ISSUE THREAD

**Issue by chashikajw** [wso2/docs-apim#3560]
**Description:**

Need to replace "Production and Sandbox' to "Default" in all the places.

Ex: https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/

![image](https://user-images.githubusercontent.com/21282060/114261864-77759380-99fa-11eb-9d28-82101a9cc816.png)

**Affected Product Version:**
API-M-4.0.0

**Comment by Mariangela** [comment]
@chashikajw when `name = "Production and Sandbox"` is changed to `name = "Production and Sandbox"` in all the places,

- Does `type = "hybrid"` remain the same?
- Does `description = "This is a hybrid gateway that handles both production and sandbox token traffic."` remain the same?
- Does the mention of `Production and Sandbox` shown below need to be changed as well.
<img width="1067" alt="Screenshot 2021-06-15 at 13 03 57" src="https://user-images.githubusercontent.com/5195851/122011968-4ccd0000-cdda-11eb-9dc9-6326bb8d38ba.png">

**Comment by chashikajw** [comment]
- Only the name = "Production and Sandbox" should be changed to name = "Default".
- hybrid remains the same
- no need to change the description.

**Comment by Mariangela** [comment]
@chashikajw , does this need to be changes to "Default" as well.
<img width="1678" alt="Screenshot 2021-06-15 at 13 57 49" src="https://user-images.githubusercontent.com/5195851/122019758-c0bed680-cde1-11eb-9d67-e4ff17c0fc62.png">

https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub/#event-hub-configuration

**Comment by chashikajw** [comment]
Yes need to change  as "Default"

**Comment by Mariangela** [comment]
The latter mentioned PR fixes this issue partly. This still needs to be fixed in the config catalog and the REST API docs.

**Comment by Mariangela** [comment]
Closing this issue as the rest of this task will be handled via the following two Git issues.

- REST API docs - https://github.com/wso2/docs-apim/issues/4212
- Config Catalog - https://github.com/wso2/docs-apim/issues/4213
