### ISSUE TITLE
Reword sentence in 'Initializing projects using the CLI Tool' page

### ISSUE THREAD

**Issue by dakshitha** [wso2/docs-apim#36]
**Description:**
The text "Select a generated archive suitable for your platform (i.e., Mac, Windows, Linux) and extract it the CLI tool that you downloaded to a desired location and cd into it." at https://docs.wso2.com/display/AM260/Initializing+projects+using+the+CLI+Tool#InitializingprojectsusingtheCLITool-LoggingintoAPIManagerviatheCLItool should be reworded to say something like "..and extract this archive which contains the CLI tool.. " 

**Suggested Labels:**
CLITool

**Suggested Assignees:**

**Affected Product Version:**
2.6.0

__

**Comment by shaniR** [comment]
fixed on 2.6.0.
