### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by joaoemilio** [wso2/docs-apim#360]
Location : https://apim.docs.wso2.com/en/latest/SetupAndInstall/InstallationGuide/InstallingTheProduct/installing-on-linux-or-os-x/

The document says that latest version is 2.2 update 1

**Comment by shaniR** [comment]
This has been fixed https://apim.docs.wso2.com/en/latest/InstallAndSetup/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-linux-or-os-x/
