### ISSUE TITLE
[API-M-4.0.0] Wrong reference in readme instructions

### ISSUE THREAD

**Issue by binodmx** [wso2/docs-apim#3677]
**Description:**
Wrong reference in readme instructions in **Step 3 - Install the pip packages > 3**  
_3. Navigate to the folder containing the repo that you cloned in step 4.1 on a terminal window._ should be corrected as  
_3. Navigate to the folder containing the repo that you cloned in step 3.2 on a terminal window._
![image](https://user-images.githubusercontent.com/36144069/115687598-f7dfb100-a377-11eb-9c36-b8553f1579df.png)

**Affected Product Version:**
4.0.0

**Comment by Mariangela** [comment]
@samgnaniah , this needs to be fixed in 4.0.0. You have sent a fix to master as opposed to 4.0.0

**Comment by samgnaniah** [comment]
> @samgnaniah , this needs to be fixed in 4.0.0. You have sent a fix to master as opposed to 4.0.0

Fixed in 4.0.0 with https://github.com/wso2/docs-apim/pull/4488
