### ISSUE TITLE
Missing info about adding an environment first before logging into the API Manager using the CLI Tool

### ISSUE THREAD

**Issue by dakshitha** [wso2/docs-apim#37]
**Description:**

 In [1], under Logging into API Manager via the CLI tool section, we have asked the user to first login to API Manager by executing the command _apimcli login DEV -u USER -p PASSWORD123_ , where DEV is the name of the environment. When I execute this, the CLI tells me that I have to first add an environment, for which the instructions are not given. We need to tell the user how to add an environment first or point to links on how they can do it.

--
[1] - https://docs.wso2.com/display/AM260/Initializing+projects+using+the+CLI+Tool#1fc7c0bd431e48dc8eba2805d5120a90

**Suggested Labels:**
CLITool

**Suggested Assignees:**

**Affected Product Version:**
2.6.0

**Comment by Mariangela** [comment]
This change has been done in https://docs.wso2.com/display/AM260/Initializing+projects+using+the+CLI+Tool
