### ISSUE TITLE
[APIM-4.0.0][Improvement] Improve Revision docs

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-apim#3755]
Need more information about this feature and how it works and in what cases you would use the various options.

Current doc: https://apim.docs.wso2.com/en/4.0.0/design/create-api/create-api-revisions/

Currently the doc only covers the how to use part but doesn't tell the user what to do next when you use this feature. We need a more comprehensive and complete document that covers "why" you would use this feature and in which scenario.

Linked issue: https://github.com/wso2/docs-apim/issues/3696

**Comment by 1akshitha** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/3766
