### ISSUE TITLE
Enable loggin documentation needs improvement

### ISSUE THREAD

**Issue by dushansachinda** [wso2/docs-apim#379]
**Description:**

  APIM 3.0.0 loggin does not adhere to current product architecute or log4j2 references
https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/Monitoring/Logging/setting-up-logging/
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 3.0.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

Developers required to enable debug logs for components, we have tried options like below but didn't work, so please improve documentation around this

logger.carbon_oauth2.name = org.wso2.carbon.identity.oauth2
logger.carbon_oauth2.level = DEBUG

logger.carbon_apimgt.name = org.wso2.carbon.apimgt.impl
logger.carbon_apimgt.level = DEBUG

logger.carbon_oauth.name = org.wso2.carbon.identity.oauth
logger.carbon_oauth.level = DEBUG

Secondly, loggin feature missing from product admin UI
![Snip20191107_55](https://user-images.githubusercontent.com/5661226/68441558-61b7cb00-0183-11ea-9a3a-38afb9e5f7f6.png)

**Comment by Mariangela** [comment]
@bhathiya , please share your input on this issue.

**Comment by bhathiya** [comment]
I think we now have updated the docs properly with all the details. 

@dushansachinda do you see any issues now?

Btw, logging UI was removed intensionally.

**Comment by Mariangela** [comment]
@dushansachinda , I am closing this issue as this seems to be already fixed. Please do re-open the issue if you have any further concerns in this regard.
