### ISSUE TITLE
Remove references on Admin API v0.17 from APIM 4.0.0 docs

### ISSUE THREAD

**Issue by msm1992** [wso2/docs-apim#3790]
**Description:**
Need to remove info on $subject.
<img width="902" alt="Screenshot 2021-05-03 at 11 28 48" src="https://user-images.githubusercontent.com/28379317/116845240-e82b5c80-ac02-11eb-85ae-309725cc69ed.png">

Update API listing at https://apim.docs.wso2.com/en/4.0.0/reference/product-apis/overview/ 
Remove doc at https://apim.docs.wso2.com/en/4.0.0/reference/product-apis/admin-apis/admin-v0.17/admin-v0.17/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruthryi** [comment]
This was fixed with : https://github.com/wso2/docs-apim/pull/5962
