### ISSUE TITLE
Details and Screenshots in JSON Schema Validator Page are Outdated

### ISSUE THREAD

**Issue by npamudika** [wso2/docs-apim#3821]
**Description:**
The steps and the screenshot in https://apim.docs.wso2.com/en/4.0.0/design/api-security/api-request-response-schema-validation/json-schema-validator/ needs to be updated with the new UI.

**Comment by prasa7** [comment]
Fix with https://github.com/wso2/docs-apim/pull/4665

**Comment by prasa7** [comment]
Closing based on the above image
