### ISSUE TITLE
Implicit Grant Type doc page is not vailable

### ISSUE THREAD

**Issue by npamudika** [wso2/docs-apim#3883]
**Description:**
In https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/grant-types/overview/#oauth2-grant-types, the link to Implicit grant type page is not found. Need to add the Implicit grant type doc page and correct the link.

**Comment by msm1992** [comment]
@npamudika Implicit grant type was deprecated in 3.2.0 and is removed from 4.0.0. Please refer the note at https://apim.docs.wso2.com/en/3.2.0/learn/api-security/oauth2/grant-types/implicit-grant/

**Comment by npamudika** [comment]
Ack. Thanks @msm1992. Let's remove the "Implicit Grant" point from https://apim.docs.wso2.com/en/4.0.0/design/api-security/oauth2/grant-types/overview/#oauth2-grant-types
