### ISSUE TITLE
Doc Feedback: Quick setup instruction for Apim analytics doesn't work

### ISSUE THREAD

**Issue by amuslimova** [wso2/docs-apim#391]
Location : https://apim.docs.wso2.com/en/latest/Learn/Analytics/configuring-apim-analytics/
It seems that some steps are missing, as with the instructions provided on page I'm able to connect Api manager and analytics (at least I see 'INFO {org.wso2.carbon.databridge.core.DataBridge} - user admin connected' log message), but dashboard doesn't show any statistics, and there are no error messages neither in worker log, nor in dashboard

**Comment by TanyaM** [comment]
@amuslimova : Could you please let us know whether you tried the Quick setup or the standard setup?

**Comment by amuslimova** [comment]
@TanyaM Thank you for reply, looks like there was a problem because of the different folders for APIM and Analytics. Now I see some statistics on dashboard
