### ISSUE TITLE
Doc Feedback: Tick images are missing in the page

### ISSUE THREAD

**Issue by dunithd** [wso2/docs-apim#3914]
Location: https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/deploying-apis-in-api-gateway-vs-choreo-connect/

Tick images in **security comparison** and the **feature comparison** tables are broken.

**Comment by Mariangela** [comment]
Duplicates https://github.com/wso2/docs-apim/issues/4315
