### ISSUE TITLE
Doc Feedback: 

### ISSUE THREAD

**Issue by amuslimova** [wso2/docs-apim#392]
Location : https://apim.docs.wso2.com/en/latest/Learn/Analytics/AnalyzingAPIMStatisticsWithBatchAnalytics/viewing-api-statistics/
Links to 'API Store statistics' and 'Admin Portal Statistics' instructions don't work

**Comment by TanyaM** [comment]
@amuslimova : Thank you for the feedback. This doc was under work-in-progress and now the content has been completed. 
Please re-check and let us know if you find any issues.
