### ISSUE TITLE
[APIM4.0] Incorrect links in the Install and Setup Overview page

### ISSUE THREAD

**Issue by jrathnayake** [wso2/docs-apim#3929]
**Description:**
There is an incorrect link on the Install and Setup Overview page. In the "Setting up" section, the first link - "Applying WSO2 WUM Updates" point to a wrong landing page - WSO2 API Manager Deployment Overview

**Steps to reproduce:**
- Go to https://apim.docs.wso2.com/en/latest/install-and-setup/install-and-setup-overview/
- Click the link Applying WSO2 WUM Updates in the Setting up section

**Comment by nilminiwso2** [comment]
Fixed by https://github.com/wso2/docs-apim/pull/4018/files

Thanks for reporting.
