### ISSUE TITLE
[APIM4.0] Incorrect links in the Documentation Home Page

### ISSUE THREAD

**Issue by jrathnayake** [wso2/docs-apim#3930]
**Description:**
Incorrect links in the Documentation Home page. 

**Steps to reproduce:**
- Go to Home page - https://apim.docs.wso2.com/en/latest/
- Click the "Overview" link and it navigates to "Key Concepts" page (https://apim.docs.wso2.com/en/latest/get-started/key-concepts/)

**Comment by nilminiwso2** [comment]
Fixed by https://github.com/wso2/docs-apim/pull/4018/files

Thanks for reporting.
