### ISSUE TITLE
[APIM4.0] Link to wrong Analytics documentation

### ISSUE THREAD

**Issue by jrathnayake** [wso2/docs-apim#3931]
**Description:**
When we go to the "Architecture and Key Components" page, under the "API Analytics" section, there is a link called "Working with Analytics" which leads to an older version of the Analytics documentation page. 

**Steps to reproduce:**
- Go to the "Architecture and Key Components" page (https://apim.docs.wso2.com/en/latest/get-started/architecture/)
- Navigate to the "Analytics" section
- Click "Working with Analytics" which leads to https://apim.docs.wso2.com/en/4.0.0/observe/api-manager-analytics/configuring-apim-analytics

**Comment by Mariangela** [comment]
Duplicated by https://github.com/wso2/docs-apim/issues/4038
