### ISSUE TITLE
Missing Image in Alerts Page

### ISSUE THREAD

**Issue by msm1992** [wso2/docs-apim#3934]
**Description:**
<img width="923" alt="Screenshot 2021-05-10 at 09 29 57" src="https://user-images.githubusercontent.com/28379317/117604236-7dce6b00-b172-11eb-933b-837cdf93585a.png">

https://apim.docs.wso2.com/en/latest/observe/api-manager-analytics/configure-analytics/configure-alerts/#create-traffic-alert

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Fixed in https://apim.docs.wso2.com/en/latest/api-analytics/configure-alerts/#create-traffic-alert
