### ISSUE TITLE
Broken link in MG docs

### ISSUE THREAD

**Issue by msm1992** [wso2/docs-apim#3941]
**Description:**
link to Disabling Security in https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/api-authentication/ gives 'Page Not Found'

Link should be updated to https://mg.docs.wso2.com/en/4.0.0/how-tos/security/api-authentication/disabling-security/

**Comment by samgnaniah** [comment]
This seems to be fixed now.
