### ISSUE TITLE
Misuse of {MI_HOST} instead of {MI_PORT}

### ISSUE THREAD

**Issue by AyeshW** [wso2/docs-apim#3945]
**Description:**
 
In the following document, under Configure service metadata -> serviceUrl {MI_HOST} is used instead of {MI_PORT}.
[https://apim.docs.wso2.com/en/latest/tutorials/integration-tutorials/service-catalog-tutorial/](https://apim.docs.wso2.com/en/latest/tutorials/integration-tutorials/service-catalog-tutorial/)

Typo in [https://apim.docs.wso2.com/en/latest/tutorials/integration-tutorials/service-catalog-tutorial/#step-6-build-and-run-the-service](https://apim.docs.wso2.com/en/latest/tutorials/integration-tutorials/service-catalog-tutorial/#step-6-build-and-run-the-service) info

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
PR: https://github.com/wso2/docs-apim/pull/3937

Remaining Work: Need to update the config catalog.

**Comment by nilminiwso2** [comment]
Fix PR: https://github.com/wso2/docs-apim/pull/4035
Merged to master: https://github.com/wso2/docs-apim/pull/4037
