### ISSUE TITLE
Doc Feedback: Incorrect link in migration guide

### ISSUE THREAD

**Issue by maksym-synkevych** [wso2/docs-apim#3946]
>Follow Step 2 and 3 under Step 2 - Upgrade API Manager to 3.2.0 to backup and upgrade the WSO2 API-M WSO2AM_DB from 2.0.0 to 3.2.0. This will be used as the identity_db in IS 5.10.0.

Link leads to WSO2 AM upgrade from 3.0.0 to 3.2.0 and migration scripts will not work for 2.0.0

Location : https://apim.docs.wso2.com/en/3.2.0/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-5100/

**Comment by Mariangela** [comment]
@tharindu1st , please share your feedback.

**Comment by hisanhunais** [comment]
Issue doesn't exist in 4.0.0 and master
