### ISSUE TITLE
Follow-up on Installation Documentation

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#3948]
**Description:**
Follow-up on Installation Documentation.

**Comment by nilminiwso2** [comment]
PR #1  for 'Running the MI Dashboard' and related changes - https://github.com/wso2/docs-apim/pull/3999/files

**Comment by nilminiwso2** [comment]
PRs: 
- https://github.com/wso2/docs-apim/pull/4127
- https://github.com/wso2/docs-apim/pull/4093
