### ISSUE TITLE
Update performance and capacity planning doc for APIM 3.0.0

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#398]
**Description:**
Need to add the latest performance and capacity planning doc for APIM 3.0.0

[1] https://apim.docs.wso2.com/en/latest/SetupAndInstall/PerfromanceTuningAndTestResults/wso2-api-m-performance-and-capacity-planning/

**Comment by Mariangela** [comment]
@bhathiya , can you assign someone to this task, please so that we can get the required information?

**Comment by bhathiya** [comment]
@chamilaadhi Please advise.

**Comment by chamilaadhi** [comment]
@Mariangela can you check this https://apim.docs.wso2.com/en/latest/install-and-setup/perfromance-tuning-and-test-results/tuning-performance/

**Comment by Mariangela** [comment]
@chamilaadhi has added the required content for 3.0.0 in [1].

[1] https://github.com/wso2/docs-apim/pull/1219
