### ISSUE TITLE
Improve Securing APIs with Mutual SSL Documentation

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/docs-apim#3996]
**Description:**
In documentation [1] the following is mentioned

![image](https://user-images.githubusercontent.com/30709975/118218458-13306e80-b495-11eb-9806-18486fc5550c.png)

This gives an impression that the configuration should be applied only if the default header is changed.

However when we use Mutual SSL with a **default versioned API**, the "X-WSO2-CLIENT-CERTIFICATE" header will be created in base64 encoded format based on the parameters sent along with the request.

eg: curl -k -X POST "https://localhost:8243/test123/resource1" -H "accept: application/json" --cacert localhost.pem --key domain.key --cert domain.crt

Due to this, the request fails with "401 Unauthorized" as the following configuration is not available in the deployment.toml file.

```
[apimgt.mutual_ssl]
certificate_header = "X-WSO2-CLIENT-CERTIFICATE"
enable_client_validation = false
```
[1] https://apim.docs.wso2.com/en/3.1.0/learn/api-security/api-authentication/secure-apis-using-mutual-ssl/

**Comment by Mariangela** [comment]
@sashansamarajeewa  , how do you propose that the docs are updated?

**Comment by sashansamarajeewa** [comment]
Improvements have been from the product level to address the issues related to the usage of Mutual SSL with a default versioned API. Hence the documentation update will not be required.
