### ISSUE TITLE
Create staging server

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#4055]
**Description:**
Look at the possibility of setting up a staging server

**Comment by Mariangela** [comment]
Had a call with Lakindu and Shani on this today.

**Comment by Mariangela** [comment]
In the meeting Shani suggested that we can use the master branch as the dev branch, have a vhost to access the URL and turn off Google indexing.

**Comment by Mariangela** [comment]
Bhathiya suggested that we have a separate branch for 4.0.0 dev and create a staging server based on that. Furthermore, it was decided to only have staging for 4.0.0 at the moment.

**Comment by Mariangela** [comment]
@samgnaniah , I assigned you to this task as discussed in our last TW sync up.

**Comment by samgnaniah** [comment]
Closing this as this suggestion was rejected.
