### ISSUE TITLE
Incorrect and missing "Mutual SSL Between API Gateway and Backend" configurations.

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/docs-apim#4114]
**Description:**

In the documentation [1] under the "Configure API Manager to enable dynamic SSL profiles" section, it is mentioned to create a file called <APIM_HOME>/repository/deployment/server/multi_ssl_profiles.xml. But this filename must be sslprofiles.xml. If the name is not sslProfiles.xml, these configurations won't be applied. 

The "interval" parameter is there so that we can configure how often the SSL profiles file is read by the server to make the newly added certs affected without a server restart. There is no mention of the usage of the "interval" parameter on the docs page. 

By-design. The `<server>` config means the endpoint related for SSL validation. Port number requires implicitly to be mentioned in the config to work.
- Correct : `<server>www.google.com:443<server>`
- Incorrect : `<server>www.google.com<server>`

[1] - https://apim.docs.wso2.com/en/3.1.0/learn/api-gateway/mutual-ssl-between-api-gateway-and-backend/#test-mutual-ssl-between-api-gateway-and-backend

**Affected Product Version:**
APIM 3.x.x

**Comment by samgnaniah** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/4452
