### ISSUE TITLE
Hide the following pages under Viewing API Analytics until they're done

### ISSUE THREAD

**Issue by jaadds** [wso2/docs-apim#4115]
**Description:**
Following docs are available with no content, but WIP banner. Until they are done please hide the pages.

https://apim.docs.wso2.com/en/latest/observe/api-manager-analytics/analytics-usecases/finding-faulty-apis/
https://apim.docs.wso2.com/en/latest/observe/api-manager-analytics/analytics-qos/
https://apim.docs.wso2.com/en/latest/observe/api-manager-analytics/querying-apim-analytics/
https://apim.docs.wso2.com/en/latest/observe/api-manager-analytics/troubleshooting-analytics/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
In addition, hide the following pages as well:
https://apim.docs.wso2.com/en/latest/observe/api-manager-analytics/analytics-pages/analytics-pages-cache/
https://apim.docs.wso2.com/en/latest/observe/api-manager-analytics/analytics-pages/analytics-pages-alerts/
https://apim.docs.wso2.com/en/latest/observe/api-manager-analytics/configure-analytics/configure-microgateway/

**Comment by Mariangela** [comment]
@ruthryi , as discussed offline, please hide these pages from the left navigation as soon as possible.
