### ISSUE TITLE
Doc Feedback:Incorrect revoke endpoint

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#4123]
Location : https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/token-revocation/

Revoke Endpoint URL should point to https://localhost:9443/oauth2/revoke

**Comment by Mariangela** [comment]
@isharac is this only applicable to this page OR should this be changed in all the pages in the APIM 4.0.0. documentation.
<img width="675" alt="Screenshot 2021-06-22 at 13 10 21" src="https://user-images.githubusercontent.com/5195851/122883999-54048880-d35b-11eb-8a40-a060c91aeeb7.png">

**Comment by isharac** [comment]
yes, we need to change in all the places.

**Comment by Mariangela** [comment]
This has been updated in the docs. However, the config catalog needs to be updated.

**Comment by Mariangela** [comment]
@ruthryi , please add this change in the config catalog.
