### ISSUE TITLE
Doc Feedback: Outdated content

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#4124]
Location : https://apim.docs.wso2.com/en/latest/consume/manage-application/generate-keys/revoke-oauth2-application/

**Comment by isharac** [comment]
Developer Portal makes a call to the Key Manager to create an OAuth client and obtain an access token.

**Comment by Mariangela** [comment]
@isharac , can you please provide more information in this regard. Is the entire content outdated or just a part? If only a section which section is it?

**Comment by isharac** [comment]
Not the whole content. But we need to replace 

the Developer Portal makes a call to the API Gateway, which in turn connects with the Key Manager to create an OAuth client and obtain an access token. Similarly, to validate a token, the API Gateway calls the Key Manager, which fetches and validates the token details from the database.

with 

Developer Portal makes a call to the Key Manager to create an OAuth client and obtain an access token. Token validation happens in the gateway itnself using the in0-memory data store.
