### ISSUE TITLE
Link not working on page 

### ISSUE THREAD

**Issue by lpastor74** [wso2/docs-apim#4165]
**Description:**

on page 
https://apim.docs.wso2.com/en/latest/api-analytics/getting-started-guide/

link in section API Gateway section, under note 
If you need to change the following default values of the Worker Thread Count, Queue Size or Client Flushing Delay, **see the Advanced configurations.** (not working)

**Comment by Mariangela** [comment]
Fixed this by adding an absolute link as the relative links did not work.
