### ISSUE TITLE
Formatting issue and missing example in monetization docs

### ISSUE THREAD

**Issue by dineshjweerakkody** [wso2/docs-apim#4170]
**Description:**
Example class name is missing in the [1] > 1.  c.
Code sample formatting is not there in the [1] > 2. b.

[1] https://apim.docs.wso2.com/en/3.2.0/learn/api-monetization/monetizing-an-api/#c-configure-wso2-api-manager

**Suggested Labels:**
API-M-3.2.0

**Comment by Mariangela** [comment]
@shilmyhasan , please advise as to what needs to go as the class name in [1] > 1. c.

[1] https://apim.docs.wso2.com/en/3.2.0/learn/api-monetization/monetizing-an-api/#c-configure-wso2-api-manager

**Comment by shilmyhasan** [comment]
It seems the above sample class had been removed from this commit https://github.com/wso2/docs-apim/commit/11bfc868be88e6d519defb0da613287a11217e56. we have to restore it back to the previous state
