### ISSUE TITLE
Secure vault configuring docs are incomplete

### ISSUE THREAD

**Issue by Rajith90** [wso2/docs-apim#420]
**Description:**
Configuring secure vault for APIM 3.0.0 is not correct. It points to old documentation.

We can refer the doc [1] 

[1] - https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/encrypting_plain_text/
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shaniR** [comment]
Content has been re-written https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/General/LoginsAndPasswords/working-with-encrypted-passwords/
