### ISSUE TITLE
Managing Users for Admin Portal page is partially broken with the latest Updated pack

### ISSUE THREAD

**Issue by nirmal070125** [wso2/docs-apim#4219]
**Description:**

https://apim.docs.wso2.com/en/3.2.0/administer/managing-users-and-roles/managing-users-for-admin-portal/
`Role Permissions` section is renamed to `Scope Assignments` in an update for 3.2.0 which invalidates some of the UI screen shots. And the UIs are not getting filtered as per the screen shot in Step 2.5 instead I see it like below;

![Screen Shot 2021-06-16 at 4 16 11 PM](https://user-images.githubusercontent.com/413016/122205727-31d3bc00-cebe-11eb-91ad-0c8734cc8ded.png)

And there's a caching issue, you have to restart after doing those changes in order for the user to login to the system.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.2.0 update level 38
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@nirmal070125 , I fixed the broken link mentioned on this page. However, I will request and SME to look into this issue.
https://github.com/wso2/docs-apim/pull/4229 
https://github.com/wso2/docs-apim/pull/4228

**Comment by Mariangela** [comment]
Going forward this will be tracked via A698
