### ISSUE TITLE
Doc Feedback: Instruction for port offset doesn't work

### ISSUE THREAD

**Issue by amuslimova** [wso2/docs-apim#422]
Location : https://apim.docs.wso2.com/en/latest/SetupAndInstall/DeployingWSO2APIManager/ThirdPartyKeyManager/configuring-wso2-identity-server-as-a-key-manager/
When trying to change offset in carbon.xml, it's getting rewritten to default '0' when server is started

**Comment by shaniR** [comment]
This has been fixed. Please refer to https://apim.docs.wso2.com/en/latest/InstallAndSetup/DeployingWSO2APIManager/DistributedDeployment/configuring-wso2-identity-server-as-a-key-manager/#step-2-optionally-configure-port-offset-for-wso2-is
