### ISSUE TITLE
Fix formatting for copyright text

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#4231]
**Description:**
Need to fix the formatting with regard to the footer copyright text. 

<img width="1680" alt="Screenshot 2021-06-17 at 14 57 17" src="https://user-images.githubusercontent.com/5195851/122370455-b2f18880-cf7c-11eb-97f6-a86b5273d267.png">

**Comment by Mariangela** [comment]
I had a call with Kasun in this regard and he suggested to right align the copyright text and have it in three lines. He also suggested to use a flex box to design this.

**Comment by Mariangela** [comment]
I had a discussion with Samuel and Ruthryi on this and they have concerns about the way in which the copyrights appear as there is too much of a whitespace on the left-side.

<img width="1671" alt="Screenshot 2021-06-22 at 18 45 10" src="https://user-images.githubusercontent.com/5195851/122954133-cf3a5e80-d39c-11eb-85f4-db607d4163e2.png">

**Comment by Mariangela** [comment]
I had a discussion with Sam and Ruthryi on this and they were -1 for 3lines and suggested going with 1 line and smaller font to squeeze the information in

**Comment by Mariangela** [comment]
I had a discussion with KasunTe and on this and he advised to have 3 lines and left- centre the alignment of the WSO2 API Manager documentation wording. Because docs too need to comply with the accessibility aspect.

**Comment by Mariangela** [comment]
It was decided to proceed with Kasun's recommendation at the PM - TW meeting.

**Comment by Mariangela** [comment]
@tmkasun , as discussed offline, please fix the alignment of the "WSO2 API Manager - Documentation" wording in the API-M 4.0.0 docs footer. As shown in the following image, which I captured during our meeting.

<img width="1343" alt="proposed" src="https://user-images.githubusercontent.com/5195851/123129935-f317a600-d469-11eb-894f-e2db5624fa34.png">

**Comment by tmkasun** [comment]
Hi @Mariangela ,

I think it's good to have 2 lines in the RHS so footer is less thicker , and also in mobile view we need to stack each lines one after the other ,

Example below in MS page

https://user-images.githubusercontent.com/3313885/123600700-8d823b80-d814-11eb-94c0-d0eba8e36303.mov

**Comment by Mariangela** [comment]
This has been fixed in 
- EI 7.1.0, EI 7.0.0
- APIM 4.0.0., 3.2.0, 3.1.0, 3.0.0
