### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by prasad4491** [wso2/docs-apim#4244]
Location : https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400/

## Step 2 - Upgrade API Manager to 4.0.0

Upgrade the WSO2 API Manager database from version 3.1.0 to version 4.0.0 by executing the relevant database script, from the scripts that are provided below, on the WSO2AM_DB database.

Postgres SQL  script  on the table AM_GW_API_DEPLOYMENTS missing vhost filed in table create schema

```
CREATE TABLE IF NOT EXISTS AM_GW_API_DEPLOYMENTS (
  API_ID VARCHAR(255) NOT NULL,
  REVISION_ID VARCHAR(255) NOT NULL,
  LABEL VARCHAR(255) NOT NULL,
  PRIMARY KEY (REVISION_ID, API_ID,LABEL),
  FOREIGN KEY (API_ID) REFERENCES AM_GW_PUBLISHED_API_DETAILS(API_ID) ON UPDATE CASCADE ON DELETE NO ACTION
);
```

It should be like below

```
CREATE TABLE IF NOT EXISTS AM_GW_API_DEPLOYMENTS (
  API_ID VARCHAR(255) NOT NULL,
  REVISION_ID VARCHAR(255) NOT NULL,
  LABEL VARCHAR(255) NOT NULL,
  VHOST VARCHAR(255) NULL,
  PRIMARY KEY (REVISION_ID, API_ID,LABEL),
  FOREIGN KEY (API_ID) REFERENCES AM_GW_PUBLISHED_API_DETAILS(API_ID) ON UPDATE CASCADE ON DELETE NO ACTION
);
```

**Comment by Mariangela** [comment]
@pubudu, please confirm.

**Comment by renuka-fernando** [comment]
Yes, it should be included as in the migration resource scripts [1].
@isharac, just coping this script from migration scripts to docs is right?

[1] https://github.com/wso2-extensions/apim-migration-resources/blob/master/migration-scripts/migration-3.2.0_to_4.0.0/postgresql.sql#L69-L76

**Comment by isharac** [comment]
yes, we can copy thr table from the dbscript in the migration resources.
