### ISSUE TITLE
SP key type and Application type mismatch when provisioning out-of-band OAuth clients 

### ISSUE THREAD

**Issue by dushansilva** [wso2/docs-apim#425]
Steps to reproduce 

1. Enable provisioning out-of-band OAuth clients feature by adding enable_map_auth = true to deployment.toml apim.devportal section
3. Create an application of JWT type
5. Create an sp OAuth key type
7. Map the keys of OAuth key type to Application of JWT

This should not be the case as several validation logic might failed due to this, SP key type and application type should be the same.

**Comment by Mariangela** [comment]
@tgtshanika , please share your views with regard to this Git issue.

**Comment by vithu30** [comment]
@dushansilva, if the client key and client secret is from different IdP (for instance, WSO2 IS), it will only have JWT / default token issuer types. 

In that case, is it ok to add a note as it will only applied if the SP is created in API Manager?
Appreciate your thoughts on this.

**Comment by dushansilva** [comment]
yeah in that case it's good to add a note

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
