### ISSUE TITLE
APIM 2.1.0 not updated("WSS API Advanced Throttling Policy details")

### ISSUE THREAD

**Issue by dumindurox777** [wso2/docs-apim#426]
**Description:**
"WSS API Advanced Throttling Policy" can we apply on apim-2.1.0. This feature is already in apim-2.6.0 and doc is updated for that. But for the apim 2.1.0 doc is not contain that "WSS Support" related details. I already test for apim-2.1.0 with steps on 2.6.0 doc it is working fine.

**Suggested Labels:**
apim,wss

**Suggested Assignees:**
@Mariangela

**Affected Product Version:**

apim-2.1.0

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Added this content in the following pages.

- https://docs.wso2.com/display/AM210/Create+a+WebSocket+API
- https://docs.wso2.com/display/AM220/Create+a+WebSocket+API
- https://docs.wso2.com/display/AM250/Create+a+WebSocket+API

Updated the content in APIM 2.6.0

- https://docs.wso2.com/display/AM260/Create+a+WebSocket+API

**Comment by Mariangela** [comment]
Added the content in for 3.0.0 with PR [2].

[1] https://apim.docs.wso2.com/en/latest/Learn/DesignAPI/CreateAPI/create-a-websocket-api/
[2] https://github.com/wso2/docs-apim/pull/438
