### ISSUE TITLE
Update grant handler class names in extension docs

### ISSUE THREAD

**Issue by dushaniw** [wso2/docs-apim#4273]
**Description:**
Update grant handler class names in https://apim.docs.wso2.com/en/latest/reference/customize-product/extending-api-manager/extending-key-management/writing-custom-grant-types/

**Comment by Mariangela** [comment]
@dushaniw , your issue does not give the fix. Do you know the exact fix for this? If yes, please provide.

**Comment by dushaniw** [comment]
`authorization_code` - `org.wso2.carbon.identity.oauth2.token.handlers.grant.AuthorizationCodeGrantHandler`
`password` - `org.wso2.carbon.identity.oauth2.token.handlers.grant.PasswordGrantHandler`
`refresh_token` - `org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler`
`client_credentials` - `org.wso2.carbon.identity.oauth2.token.handlers.grant.ClientCredentialsGrantHandler`
`urn:ietf:params:oauth:grant-type:saml2-bearer` - `org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler`

**Comment by dushaniw** [comment]
We no longer use customized grant types by default hence can remove the following.

```
Note that API Manager has already customized the Grant Type handlers for authorization_code , password , client_credentials and saml2-bearer grant types. If you require any additional functionality for these grant types, its advisable to extend the following grant handler implementations.
```

Instead add following
```
If you require any additional functionality for authorization_code , password , client_credentials, refresh_token and saml2-bearer grant types  grant types, its advisable to extend the following grant handler implementations.
```
