### ISSUE TITLE
[3.2.0] Wrong Analytics Worker Commands

### ISSUE THREAD

**Issue by athiththan11** [wso2/docs-apim#4275]
**Description:**

The Analytics Worker startup commands mentioned in [Active-Passive Deployment](https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-passive/#starting-the-cluster) doc space is wrong.

![Screenshot 2021-06-24 at 23 24 15](https://user-images.githubusercontent.com/29927177/123322513-0aca5980-d552-11eb-9d84-421559f2aef4.png)

The startup commands need to be correct as following

```sh
For Windows: worker.bat 
For Linux : ./worker.sh
```

**Affected Product Version:**

- API Manager 3.2.0
- Analytics

**Comment by Mariangela** [comment]
@fazlan-nazeem , please confirm.

**Comment by Mariangela** [comment]
Fazlan confirmed offline that the requested fix is correct.
