### ISSUE TITLE
[3.2.0] Missing Configurations in Analytics Space

### ISSUE THREAD

**Issue by athiththan11** [wso2/docs-apim#4283]
**Description:**

The `NLS_DATE_FORMAT` init SQL configurations are missing in the [API-M 3.2.0 Analytics Standard Setup Doc Space](https://apim.docs.wso2.com/en/3.2.0/learn/analytics/configuring-apim-analytics/#step-42-configure-the-analytics-dashboard) whereas the correct configurations are pointed in the [3.0.0 Doc Space](https://apim.docs.wso2.com/en/3.0.0/learn/analytics/configuring-apim-analytics/#step-4-configure-databases)

Update the mentioned Note element with the sample datasource configuration including the following

```yaml
connectionInitSql: alter session set NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'
```

**Affected Product Version:**

- API Manager 3.2.0 & Analytics

**Related Issues:**

- [#analytics-apim/issues/923](https://github.com/wso2/analytics-apim/issues/923)

**Comment by Mariangela** [comment]
@athiththan11 , need more clarification in this regard.

**Comment by athiththan11** [comment]
@Mariangela, in previous versions of the API Manager docs: [v3.0.0](https://apim.docs.wso2.com/en/3.0.0/learn/analytics/configuring-apim-analytics/#step-4-configure-databases), it was mentioned in a `Note` that the following configuration is required when configuring Oracle Datasource for Analytics. Further, it is described with an example having the following property in a sample datasource configuration.

```yaml
connectionInitSql: alter session set NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'
```

However, in the [v3.2.0](https://apim.docs.wso2.com/en/3.2.0/learn/analytics/configuring-apim-analytics/#step-42-configure-the-analytics-dashboard) documentation space, the explanation and the samples are missing. Even though the v3.2.0 docs is having a small `Note` describing the relevant property, it would be good to have an explanation with a sample Datasource configuration as written in the [v3.0.0](https://apim.docs.wso2.com/en/3.0.0/learn/analytics/configuring-apim-analytics/#step-4-configure-databases) docs. 

Please find the screenshots of both v3.0.0 and v3.2.0 docs spaces having the mentioned `Note:`

- **Screenshot of v3.0.0 Docs**
![image](https://user-images.githubusercontent.com/29927177/124869148-6ed33000-dfde-11eb-9942-0a9b1fa4dc2d.png)
- **Screenshot of v3.2.0 Docs**
![image](https://user-images.githubusercontent.com/29927177/124869237-8c07fe80-dfde-11eb-9466-f5cfe308493f.png)
