### ISSUE TITLE
[3.1.0] Wrong Passthrough Access Log Patterns

### ISSUE THREAD

**Issue by athiththan11** [wso2/docs-apim#4284]
**Description:**

The Passthrough Access Log patterns mentioned under [Monitoring HTTP Access Logs](https://apim.docs.wso2.com/en/3.1.0/administer/logging-and-monitoring/logging/monitoring-http-access-logs/#supported-log-pattern-formats-for-the-passthrough-transport) needs to be updated with the correct set of patterns and functionalities.

Following are the Synapse code base referring to the actual usage of the patterns
- API Manager v3.1.0: [wso2-synapse](https://github.com/wso2/wso2-synapse/blob/v2.1.7-wso2v147/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/Access.java#L788-L845)
- API Manager v3.2.0: [wso2-synapse](https://github.com/wso2/wso2-synapse/blob/v2.1.7-wso2v183/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/Access.java#L788-L845)

**Affected Product Version:**

- API Manager v3.1.0: [Docs](https://apim.docs.wso2.com/en/3.1.0/administer/logging-and-monitoring/logging/monitoring-http-access-logs/#supported-log-pattern-formats-for-the-passthrough-transport)
- API Manager v3.2.0: [Docs](https://apim.docs.wso2.com/en/3.2.0/administer/logging-and-monitoring/logging/monitoring-http-access-logs/#supported-log-pattern-formats-for-the-passthrough-transport)

**Comment by Mariangela** [comment]
@athiththan11 , can you please provide an example in order to provide more context.

**Comment by athiththan11** [comment]
@Mariangela, The attributes and the descriptions mentioned under [`Supported log pattern formats for the PassThrough transport`](https://apim.docs.wso2.com/en/3.1.0/administer/logging-and-monitoring/logging/monitoring-http-access-logs/#supported-log-pattern-formats-for-the-passthrough-transport) section is having few misleading points. I have compared the description along with the [source code](https://github.com/wso2/wso2-synapse/blob/v2.1.7-wso2v147/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/Access.java#L788-L845) and came up with the following table to represent all the elements and their usages

|Attribute|Description|Corrected|
|:------:|-----------|-------|
|%a|Remote IP address|User Agent|
|%A|Local IP address||
|%b|Bytes sent, excluding HTTP headers, or '-' if zero||
|%B|Bytes sent, excluding HTTP headers||
|%c|Cookie value||
|%C|Accept header||
|%e|Accept Encoding||
|%E|Transfer Encoding||
|%f||Referer|
|%h|Remote host name (or IP address if enableLookups for the connector is false)||
|%l|Remote logical username from identd (always returns '-')||
|%L|Accept Language||
|%k|Keep Alive||
|%m|Request method (GET, POST, etc.)||
|%n|Content Encoding||
|%r|Request Element||
|%s|HTTP status code of the response||
|%S|Accept Chatset|Accept Charset|
|%t|Date and time, in Common Log Format||
|%T|Time taken to process the request in seconds.|Content Type|
|%u|Remote user that was authenticated (if any), else '-'||
|%U|Requested URL path||
|%v|Local server name||
|%V|Vary Header||
|%x|Connection Header||
|%Z|Server Header||

Please validate the same and apply the changes to the documentation.

**Comment by Mariangela** [comment]
@athiththan11 , can this new table that you came up with be applied for 3.1.0, 3.2.0 and also 4.0.0 [1]

[1] https://apim.docs.wso2.com/en/latest/administer/logging-and-monitoring/logging/monitoring-http-access-logs/#supported-log-pattern-formats-for-the-passthrough-transport

**Comment by athiththan11** [comment]
@Mariangela, Yes, according to the [source code](https://github.com/wso2/wso2-synapse/blob/v2.1.7-wso2v227/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/Access.java#L788-L845) of API Manager v4.0.0, we can use the same as well. 
So, the mentioned table is applicable for all v3.1.0, v3.2.0, and v4.0.0 versions.

**Comment by athiththan11** [comment]
Hi @Mariangela 

It seems the information is miscommunicated. The docs are updated with the same tables that have been mentioned in the previous comments. Actually, the table contains the current description and the corrected description of each pattern. We need to update the previous existing tables in the Doc with the corrected descriptions. Shall we make the changes?
