### ISSUE TITLE
Invalid config chacaters in [[apim.gateway.environment]]

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/docs-apim#4289]
**Description:**

In [Exposing APIs via Custom Hostnames ](https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames/#step-1-define-the-custom-hostnames ) doc, Step-2 covers the configs which need to be added to `deployment.toml`.

```
[[apim.gateway.environment]]
name = "Default"
...
display_name = "US Region"
```

Why these `...` are added to the configs ? Is it to show that there are many more additional config elements than the listed elements?

The same config issue is in [Define the custom hostnames](https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames/#step-1-define-the-custom-hostnames) doc too.

**Affected Product Version:**

APIM 4.0.0

**Comment by Mariangela** [comment]
@Sarangan0219 , yes it is to show that there are much more additional config that come. Do you see an issue?

**Comment by Sarangan0219** [comment]
The config provided in the doc is the correct one. There are no more additional configs than the given config elements. Thus we can remove the `....`.

```
[[apim.gateway.environment]]
name = "Default"
display_name = "US Region"
type = "hybrid"
display_in_api_console = true
description = "Gateway environment deployed in the US region."
show_as_token_endpoint_url = true
service_url = "https://localhost:${mgt.transport.https.port}/services/"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint = "ws://localhost:9099"
wss_endpoint = "wss://localhost:8099"
http_endpoint = "http://localhost:${http.nio.port}"
https_endpoint = "https://localhost:${https.nio.port}"
websub_event_receiver_http_endpoint = "http://localhost:9021"
websub_event_receiver_https_endpoint = "https://localhost:8021"


```

Or else we can add the configs as below:
```

[[apim.gateway.environment]]
name = "Default"
....
websub_event_receiver_https_endpoint = "https://localhost:8021"
```

**Comment by Mariangela** [comment]
@Sarangan0219 , you refer to two different docs but you have pointed to the same page in your comment.
