### ISSUE TITLE
Config issues and missing content in analytics docs

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/docs-apim#4298]
### Description:

1. **auth_token** config should be changed in [Step-3](https://apim.docs.wso2.com/en/latest/api-analytics/getting-started-guide/#api-gateway). 

**_auth_token = “use token that you generate”_**  --> **_auth_token = "use token that you generate"_**

```
[apim.analytics]
auth_token = "<use token that you generate>"
```

2. In [Introduction to the API Analytics Dashboard](https://apim.docs.wso2.com/en/latest/api-analytics/viewing/analytics-pages-introduction/) there is no documentation for the analytics dashboard URL.  It  should be mentioned in the docs and there is no way for a user to view the stats without this URL 

- The dashboard URL- https://analytics.choreo.dev/ 
-  User can redirected to this portal using the **Insights** of https://console.choreo.dev too
![Screenshot from 2021-06-29 12-10-15](https://user-images.githubusercontent.com/60866295/123749390-01831900-d8d3-11eb-802e-5d79689e93a3.png)

**Comment by Mariangela** [comment]
@Sarangan0219 , issue part 1 is not clear. Can you recheck it what you are proposing please.

**Comment by Sarangan0219** [comment]
In the `deployment.toml` file the config values should be enclosed within **"<config_value>"**. 
In this config, the value is enclosed with **”<config_value>”**. toml files won't resolve this syntax.
