### ISSUE TITLE
Doc Feedback: APIM 4.0 Upgrading process 

### ISSUE THREAD

**Issue by saschagottfried** [wso2/docs-apim#4299]
Location : https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400/

The notes after "step 3" contain this information several time:

> Prior to WSO2 API Manager 4.0.0, the distributed deployment comprised of five main product profiles, namely Publisher, Developer Portal, Gateway, Key Manager, and Traffic Manager.

... and I notice Git conflict markers. Please review and fix. Thanks

**Comment by Mariangela** [comment]
@isharac , please clarify as to which part of the note needs to be kept and which part needs to be deleted. It looks like a merge conflict has not been fixed correctly.

**Comment by isharac** [comment]
Please review https://github.com/wso2/docs-apim/pull/4352
@Mariangela
