### ISSUE TITLE
Typos in architecture diagrams

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/docs-apim#4309]
### Description
In this [doc](https://apim.docs.wso2.com/en/latest/get-started/architecture/#architecture-and-key-components), under the tooling section, the **Intigration Studio** needs to be corrected as **Integration Studio**.

**Comment by Mariangela** [comment]
@samgnaniah , please fix this as you have the source file.

**Comment by samgnaniah** [comment]
This is fixed now with this PR: https://github.com/wso2/docs-apim/pull/4513
