### ISSUE TITLE
Doc Feedback: Micro Integrator ports have a bad config 

### ISSUE THREAD

**Issue by anasmohad** [wso2/docs-apim#4316]
Location : https://apim.docs.wso2.com/en/latest/install-and-setup/setup/reference/default-product-ports/

internal.http.api.port = http_port 

must to be changed to:

internal_http_api_port = http_port

**Comment by Mariangela** [comment]
@tharindu1st , please clarify.

**Comment by Mariangela** [comment]
Tharindu mentioned that Sajitha Liyanage will look into this and respond.

**Comment by sajithaliyanage** [comment]
@Mariangela we need to change this to `internal_http_api_port`. Please refer https://github.com/wso2/micro-integrator/blob/master/distribution/src/resources/config-tool/deployment-full.toml#L882
