### ISSUE TITLE
Doc Feedback: This doc is not up to date

### ISSUE THREAD

**Issue by bhathiya** [wso2/docs-apim#4317]
Location : https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways/

**Comment by Mariangela** [comment]
@bhathiya , can you please confirm whether the entire page is outdated or whether only a certain section is outdated.

**Comment by bhathiya** [comment]
We need to validate the entire doc.

**Comment by Mariangela** [comment]
Bhathiya mentioned today that Rashmin has started looking into this issue.

**Comment by Mariangela** [comment]
@rashm1n, please confirm whether this issue can be closed.

**Comment by bhathiya** [comment]
@Mariangela I don't see any updates on the page.

**Comment by Mariangela** [comment]
@rashm1n , please send your fix to the 4.0.0 branch as well, so that your change will appear in the latest APIM 4.0.0 docs.

**Comment by rashm1n** [comment]
@Mariangela . Ack. Will send a fix.

**Comment by Mariangela** [comment]
@rashm1n , please address the comments that I have added in [1]

[1] https://github.com/wso2/docs-apim/pull/4369

**Comment by Mariangela** [comment]
@rashm1n , pls note the following

- Step 1 width heigh ratio is not correct. Only define the width as a percentage to avoid image distortion.
-- No 8 second image
-- No9 image
-- No 10 second image

- Step 2 image is too large

**Comment by rashm1n** [comment]
@Mariangela issues have been fixed.

**Comment by bhathiya** [comment]
Some images are shrunk horizontally. Please check.
![image](https://user-images.githubusercontent.com/3960742/125891668-84beb965-89f0-4edc-8edf-66432cafe4c1.png)

**Comment by rashm1n** [comment]
> Some images are shrunk horizontally. Please check.
> ![image](https://user-images.githubusercontent.com/3960742/125891668-84beb965-89f0-4edc-8edf-66432cafe4c1.png)

@bhathiya the changes are not yet merged. This certain issue was fixed in the last commit.

**Comment by Mariangela** [comment]
@bhathiya , please confirm if we can close this issue.

**Comment by bhathiya** [comment]
+1.
