### ISSUE TITLE
Doc Feedback: Admin Services still configured in Carbon.xml

### ISSUE THREAD

**Issue by robbla** [wso2/docs-apim#432]
In the documentation the admin services are still configured in carbon.xml rather than in deployment.toml

Location : https://apim.docs.wso2.com/en/latest/Develop/wso2-admin-services/

**Comment by Mariangela** [comment]
Fixed in 
- https://github.com/wso2/docs-apim/pull/789
- https://github.com/wso2/docs-apim/pull/789/commits/15869f902b75b0479b51408fc9f55f9125a14c78
- https://apim.docs.wso2.com/en/latest/develop/wso2-admin-services/
