### ISSUE TITLE
Broken links in API Manager as Control Plane doc

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/docs-apim#4322]
**Description:**

JWT revocation links and images are broken in this [doc](https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane/?organizationId=azure#methods-to-detect-jwt-token-revocation)

**Affected Product Version:**

APIM 4.0.0

**Comment by Mariangela** [comment]
@Rajith90 , please confirm whether this is the image that needs to be added here. Also let me know how the image needs to be changed to capture the Choreo Connect story as opposed to WSO2 MGW.

![jwt-revocation](https://user-images.githubusercontent.com/5195851/124895722-6be63880-dffa-11eb-9612-7de86c2f2389.png)

**Comment by Rajith90** [comment]
The number 2 should be the APIM control plane instead of the, message broker and etcd.

**Comment by Mariangela** [comment]
@Rajith90 , how do we reword the other messaging in the image?

Please check and see if the suggestions in the following table is correct.


Current | Suggested change
-- | --
WSO2 MGW receives a notification with the newly revoked JWT's JTI claim | Choreo Connect receives a notification with the newly revoked JWT's JTI claim
Every new MGW that joins the cluster gets a list of all the revoked JTI's from the etcd | Every new Choreo Connect node that joins the cluster gets a list of all the revoked JTI's from the Control Panel
WSO2 MGW1 | Choreo Connect1
WSO2 MGW2 | Choreo Connect2
WSO2 MGW3 | Choreo Connect3
Pushed revoked JTI to etcd | Pushed revoked JTI to Control plane



- "WSO2 MGW receives a notification with the newly revoked JWT's JTI claim"
-

**Comment by Rajith90** [comment]
+1

**Comment by Mariangela** [comment]
Link Analysis:

  | Text | Link Working | Current link | Comment
-- | -- | -- | -- | --
1 | Choreo Connect release | Yes | https://github.com/wso2/product-microgateway/releases | Need to change link as it points to https://github.com/wso2/product-microgateway/releases
2 | steps here. | Yes | https://github.com/wso2/product-apim#installation--running | Points to GitHub. Need to add a link to docs
3 | The detailed explanation of subscription validation can be found here. | No (No such page in the docs) | https://apim.docs.wso2.com/en/4.0.0/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub-subscription-validation | Under concepts there is a page for "event-hub" ( https://apim.docs.wso2.com/en/4.0.0/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub) and another for "subscription-validation" (https://apim.docs.wso2.com/en/4.0.0/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/subscription-validation). Should we link to both pages here?
4 | distributed rate limiting | No | https://mg.docs.wso2.com/en/latest/publish/rate-limiting/distributed-throttling/#distributed-throttling | Needs to point to https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane/#distributed-rate-limiting
5 | resource level | No (No such page in the docs) | https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane/#subscription-level-throttling-api-subscriber | What page should this point to?
6 | subscription level | No | https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane/#subscription-level-throttling-api-subscriber | Needs to point to https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane/#subscription-level-throttling-api-subscriber
7 | application level throttling | No | https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane/#application-level-throttling-application-developer | Needs to point to https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane/#application-level-throttling-application-developer
8 | WSO2 Traffic Manager | No | https://apim.docs.wso2.com/install-and-setup/setup/distributed-deployment/product-profiles/ | Needs to point to https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/product-profiles/
9 | Find information on how to enable distributed rate limiting from here. | No | https://mg.docs.wso2.com/en/latest/publish/rate-limiting/distributed-throttling/#distributed-throttling | Needs to point to https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/rate-limiting/distributed-throttling/
10 | quick start guide | Yes | https://apim.docs.wso2.com/en/4.0.0/getting-started/quick-start-guide/ | Better to add the new link https://apim.docs.wso2.com/en/latest/get-started/api-manager-quick-start-guide/
11 | subscription-level throttling (API Publisher) | No (No such page in the docs) | https://apim.docs.wso2.com/deploy-and-publish/choreo-connect/rate-limiting/setting-throttling-limits/#subscription-level-throttling-api-publisher | What page should this point to?
12 | How to revoke tokens | No | https://apim.docs.wso2.com/en/4.0.0/design/api-security/rejecting-revoked-tokens | Should this point to https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/security/rejecting-revoked-tokens/. ??

**Comment by Mariangela** [comment]
@Rajith90 , please provide information on the links to add for rows 1,3,5, 11, 12 as described in the above table.

**Comment by Mariangela** [comment]
> @Rajith90 , please confirm whether this is the image that needs to be added here. Also let me know how the image needs to be changed to capture the Choreo Connect story as opposed to WSO2 MGW.
> 
> ![jwt-revocation](https://user-images.githubusercontent.com/5195851/124895722-6be63880-dffa-11eb-9612-7de86c2f2389.png)

Update:
I sent an email to marketing to get this image redrawn based on the proposed changes.

[1] [API-M 4.0] Redraw - Choreo Connect related image

**Comment by Mariangela** [comment]
I reminded Dinushatha regarding this he said he will send this image this Friday (27th Aug)

**Comment by Mariangela** [comment]
> @Rajith90 ,
> 
> * please provide information on the links to add for rows 1,3,5, 11, 12 as described in the above table.
> * Please confirm whether this image is correct
>   https://apim.docs.wso2.com/en/latest/assets/img/deploy/mgw/mgw_overview.png

@Rajith90 , we are still waiting for your reply.

**Comment by Rajith90** [comment]
1- https://github.com/wso2/product-microgateway/releases/tag/v0.9.0
3- https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/subscription-validation/
5- https://apim.docs.wso2.com/en/latest/design/rate-limiting/setting-throttling-limits/#advanced-rate-limiting-api-publisher
11- https://apim.docs.wso2.com/en/latest/design/rate-limiting/setting-throttling-limits/#subscription-level-rate-limiting-api-publisher
12-https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/security/rejecting-revoked-tokens/

**Comment by Mariangela** [comment]
Rajith confirmed that the image [1] is correct.

[1] https://apim.docs.wso2.com/en/latest/assets/img/deploy/mgw/mgw_overview.png

**Comment by Mariangela** [comment]
Updated image

![redraw-choreo-connect-diagram-v6](https://user-images.githubusercontent.com/5195851/158589074-b363519f-47ad-4acd-a31e-661604c26d3a.png)
