### ISSUE TITLE
Missing 'AWS Lambda as an endpoint feature' not supporting param mapping

### ISSUE THREAD

**Issue by binodmx** [wso2/docs-apim#4328]
**Description:**
As in [1], 'AWS Lambda as an endpoint feature' in API-M does not pass path params, query params, and headers to the AWS Lambda endpoint. So, user has to add those params in the payload. Because of that, in [2] it should be specifically mentioned that param mapping (path, query, header) is not yet supported and user has to put those params to the payload.

**Affected Product Version:**
3.1.0, 3.2.0, 4.0.0

[1] https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/mediators/AWSLambdaMediator.java#L131-L135
[2] https://apim.docs.wso2.com/en/latest/tutorials/create-and-publish-awslambda-api/#create-and-publish-an-aws-lambda-api

**Comment by Mariangela** [comment]
@sanjulamadurapperuma , can you please confirm whether this Git issue is correct, because I believe that you would have tested this feature to update the screenshots.

**Comment by sanjulamadurapperuma** [comment]
@Mariangela yes, I can confirm that this is correct. The InvokeRequest object implemented in the feature allows for payload-based parameters only and the user has no way (be it through the Publisher UI or a config file) to specifically send path params, query params and headers. 

+1 to add a note to inform the user that performing this edge case scenario is not available as @binodmx mentions.
