### ISSUE TITLE
APIM Documents not loading via mobile (redirect issues)

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#4354]
**Description:**
Dushan reported as follows:
![dushan1](https://user-images.githubusercontent.com/5195851/124908954-883ca200-e007-11eb-9e36-b1a12c254fd5.jpeg)

Corresponding email: APIM Documents not loading via mobile (redirect issues)

**Comment by Mariangela** [comment]
Tried to access the APIM 4.0 docs via chrome on an Android OS based mobile and it worked.
![mari1](https://user-images.githubusercontent.com/5195851/124909123-b6ba7d00-e007-11eb-8d3f-5fd9ccfd862c.jpeg)

**Comment by Mariangela** [comment]
Update on Jul 7, 2021
 
Lakindu confirmed that there was no downtime on the main site (apim.docs.wso2.com).

**Comment by Mariangela** [comment]
Dushan confirmed that he is using an iPhone 12 (Software version 14.6) on Safari and is facing this issue. 

I tried again using an iPhone 11 (Software version 14.6) on Safari. Initially, I was not able to access the apim docs site, on Safari, but at the same time it loaded perfectly on my Android phone. Later, the site loaded on Safari and I did not face any problems. 

![WhatsApp Image 2021-07-07 at 12 04 41 PM (1)](https://user-images.githubusercontent.com/5195851/124927648-803b2d00-e01c-11eb-9311-56944301c760.jpeg)

**Comment by Mariangela** [comment]
Dushan provided a phone screen recording on the error that he is running into.

https://wso2.zoom.us/rec/share/6JokO_ZPNOs_79a913M9IXe2G9TJjHrAExkPW0acD3KgNgq_EuFKCSFRA_VkJWs.sH0TFH6BPDNIHOHR Passcode: Nm^CeNC4

**Comment by Mariangela** [comment]
I got that error message (attached) a few times when I just aimlessly clicked the side menu (three lines/ Hamburger menu) multiple times as well. But for the majority of the testing period the message did not come when I navigated from one page to another. I felt like if I scrolled all the way to the top and pressed the hamburger menu the error did not come, but if I was in the middle of a page and clicked it, then it came.

![ce62ce4f-2507-415f-8bbf-2a2bdeaad9b3 (1)](https://user-images.githubusercontent.com/5195851/124928246-1707e980-e01d-11eb-8258-9c0127bd15e0.jpeg)

**Comment by Mariangela** [comment]
@erangatl , as discussed offline, please look into this issue.

**Comment by erangatl** [comment]
Could not reproduce in Android

**Comment by Mariangela** [comment]
Chanaka said that he has tested with iPhone 12Pro Chrome browser and Safari using [1] and suggested for Eranga to test on this.

[1] https://app-live.browserstack.com/

**Comment by Mariangela** [comment]
As this issue can not be reproduced, it was decided at the TW Product Management meeting to close this issue.
