### ISSUE TITLE
Doc Feedback: APIM 4.0 Page on deploying to integration Cloud?

### ISSUE THREAD

**Issue by Christopher-Davey** [wso2/docs-apim#4356]
Location : https://apim.docs.wso2.com/en/latest/integrate/develop/deploying-in-integration-cloud/

The Integration cloud service no longer exists and this also links to the Choreo page which is not helpful at this time.
I think this should either be removed or changed to reference WSO2 managed Services?

**Comment by Mariangela** [comment]
@nandika , what do you propose be done in this case? Should we remove this page or add a description in this page and redirect it to Choreo?

**Comment by nandika** [comment]
Removing this page is fine as we no longer have integration cloud

**Comment by Mariangela** [comment]
@Sanjeewa Malalgoda @Nandika Jayawardana , in addition to taking down this page [1] , which we have already done, do we have to also point to the Choreo page - https://wso2.com/choreo ?

[1] https://apim.docs.wso2.com/en/latest/integrate/develop/deploying-in-integration-cloud/

**Comment by Mariangela** [comment]
Nuwan said  -
+1 to put a redirect

anyone who has this link bookmarked will then be redirected to Choreo website
