### ISSUE TITLE
Redirect Integration Cloud content to Choreo

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-apim#4362]
There is a page for Integration Cloud content in our docs [1]. We need to redirect them to the Choreo landing page [2]. The best way seems to be the change the content in this page to explain that we now use Choreo and add a link to [2] here.

[1] - https://apim.docs.wso2.com/en/latest/integrate/develop/deploying-in-integration-cloud/#
[2] - https://wso2.com/choreo/

**Comment by Mariangela** [comment]
Duplicates https://github.com/wso2/docs-apim/issues/4356
