### ISSUE TITLE
update Configuring Transport Level Security docs

### ISSUE THREAD

**Issue by dushansilva** [wso2/docs-apim#4365]
Step 1 in [1] (Enabling SSL protocols and ciphers in ThriftAuthenticationService) must be removed as it is not relevant now for 3.1 and later versions

[1] - https://apim.docs.wso2.com/en/3.1.0/install-and-setup/setup/security/configuring-transport-level-security/#enabling-ssl-protocols-and-ciphers-in-thriftauthenticationservice

**Comment by Mariangela** [comment]
@dushansilva , do we need to do a similar config in the deployment.toml ? If yes, what is the config?

**Comment by dushansilva** [comment]
No config needed for deployment.toml

**Comment by HeshanSudarshana** [comment]
Closing the issue since the PRs are merged for 3.x docs and already removed from 4.0.0 docs.
