### ISSUE TITLE
Add Postgre 13.2 Compatibility in docs

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#4384]
**Description:**
Bhathiya reported as follows:
We tested APIM 3.2, APIM Analytics 3.2, and MI 1.2. We found 1 issue[1] with APIM and we will be fixing that with WUM. Once that's fixed we can say we officially support Postgre 13.2. 

We need to add this to our docs.

**Comment by Mariangela** [comment]
@bhathiya shall we mention the compatibility in [1] and [2] as follows. As in add on the new compatible version while maintaining the existing version?

APIM 3.2, APIM Analytics 3.2 - PostgreSQL 10, 13.2 [1]
MI 1.2.0 - PostgreSQL 12.2, 13.2 [2]


[1] https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/reference/product-compatibility/#tested-dbmss

[2] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/installation/install_prerequisites/#environment-compatibility
3.2.0 docs say we support PostgreSQL 10. So shall I keep that version and add 13.2 as well. Or do we only mention the latest version

**Comment by bhathiya** [comment]
Yes, +1.
