### ISSUE TITLE
Doc Feedback: add a separate topic on how to keep custom runtime artifacts in the gateway file system

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#4385]
Location : https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/

Additionally, we need to add the below note as a separate topic/ sub topic appropriately.

<img width="1041" alt="Screenshot 2021-07-16 at 07 30 07" src="https://user-images.githubusercontent.com/8057793/125880297-1f83d9ce-95ff-4e04-b77e-87fe97213ad9.png">

**Comment by bhathiya** [comment]
I think we should have a page/topic to talk about custom synapse files. @isharac @tharindu1st

**Comment by isharac** [comment]
> I think we should have a page/topic to talk about custom synapse files. @isharac @tharindu1st

+1 to have a separate page 
so that we can link it if there is any reference is needed.
fond a similar issue in [1].
[1] https://github.com/wso2/docs-apim/issues/4190
