### ISSUE TITLE
The link to "Publishing Analytics Events to External Systems" is broken

### ISSUE THREAD

**Issue by jyoakum** [wso2/docs-apim#4398]
Location : https://apim.docs.wso2.com/en/latest/api-analytics/viewing/view-overview-of-api-analytics/

The link to "[Publishing Analytics Events to External Systems](https://apim.docs.wso2.com/en/latest/api-analytics/samples/publishing-analytics-events-to-external-systems/)" is broken. It appears to repeatedly redirect to itself.

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/4404
