### ISSUE TITLE
apictl: example in the documentation desn't work

### ISSUE THREAD

**Issue by stefanonegri** [wso2/docs-apim#4433]
**Description:**
I tried to use the API definition in the example (OnlineStore here: https://apim.docs.wso2.com/en/latest/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach/) but it doesn't work; I tried to correct some obvious errors but never managed to make it running

**Suggested Labels:**
apictl

**Suggested Assignees:**

**Affected Product Version:**
wso2am-4.0.0.14
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@Chamindu36 , please provide some insights into this issue.

**Comment by Chamindu36** [comment]
@stefanonegri Can you please point the exact definition that you used to test this flow? Appreciate your help on this.

**Comment by stefanonegri** [comment]
hi Chamindu, I simply followed the documentation and used the api
definition mentioned as example.

Shall we have a video call/session? I can show you

Stefano


*Stefano Negri*
Director - Solutions Architecture
Mob.: +491729035969

*WSO2 Germany GmbH*
c/o Bird & Bird LLP, Maximiliansplatz 22, 80333, Munich, Germany
Sitz in München / Registered in Munich, Germany
Amtsgericht Registergericht München/ Commercial Register, Munich Local
Court, HRB 244666
Geschäftsführer / Managing Director: Charndika Arthanayake

**Comment by Chamindu36** [comment]
Hi @stefanonegri is this the definition[1] that you used? If yes, can you share the apictl command that you used to perform the task?

[1]. https://github.com/wso2/product-apim-tooling/blob/master/import-export-cli/integration/testdata/sample-api.yaml

**Comment by stefanonegri** [comment]
No, it was not.

this is the one that does not work:

openapi: 3.0.0 info: title: Online-Store version: v1.0.0 description: This
API contains operations related to the online shopping store.
x-wso2-basePath: /store/{version} x-wso2-production-endpoints: urls: -
http://products paths: /products: get: responses: "200": description:
successful operation /products/{productId}: get: parameters: - name:
productId in: path required: true schema: type: string security: - default:
- "read" responses: "200": description: successful operation components:
securitySchemes: default: type: "oauth2" flows: implicit: authorizationUrl:
"https://test.com" scopes: read: "" x-scopes-bindings: read: "admin"
*Stefano Negri*
Director - Solutions Architecture
Mob.: +491729035969

*WSO2 Germany GmbH*
c/o Bird & Bird LLP, Maximiliansplatz 22, 80333, Munich, Germany
Sitz in München / Registered in Munich, Germany
Amtsgericht Registergericht München/ Commercial Register, Munich Local
Court, HRB 244666
Geschäftsführer / Managing Director: Charndika Arthanayake

**Comment by Chamindu36** [comment]
@stefanonegri I see the issue here. It is just a template file to show how the wagger or open API definition should be specified before using them to create an API project. That may be the reason the apictl is unable to initiate the project with your definition. The full and proper definitions of that Online pet store API are attached here. Can you please try with one of the following?

Swagger PetStore Definition URL - https://petstore.swagger.io/v2/swagger.json
OpenAPI 3.0 PetStore Definition URL - https://petstore3.swagger.io/api/v3/openapi.json

Please use the following command to try this out 
`apictl init Petstore --oas https://petstore.swagger.io/v2/swagger.json`

Thanks

**Comment by stefanonegri** [comment]
Well, I think that if we put an example in the doc, it should not have
errors! And the example is different compared to those you provided in your
answer (which I tested already and they indeed work) as it includes the
WSO2 extensions (x-wso2...)



*Stefano Negri*
Director - Solutions Architecture
Mob.: +491729035969

*WSO2 Germany GmbH*
c/o Bird & Bird LLP, Maximiliansplatz 22, 80333, Munich, Germany
Sitz in München / Registered in Munich, Germany
Amtsgericht Registergericht München/ Commercial Register, Munich Local
Court, HRB 244666
Geschäftsführer / Managing Director: Charndika Arthanayake

**Comment by Chamindu36** [comment]
Hi @stefanonegri I am glad the latter one worked. We will discuss with the doc team and will do the necessary to address the confusions.

Thanks and regards

**Comment by stefanonegri** [comment]
thank you; please try to include a working example in the documentation...

*Stefano Negri*
Director - Solutions Architecture
Mob.: +491729035969

*WSO2 Germany GmbH*
c/o Bird & Bird LLP, Maximiliansplatz 22, 80333, Munich, Germany
Sitz in München / Registered in Munich, Germany
Amtsgericht Registergericht München/ Commercial Register, Munich Local
Court, HRB 244666
Geschäftsführer / Managing Director: Charndika Arthanayake
