### ISSUE TITLE
No information on changing default keystores using deployment.yaml

### ISSUE THREAD

**Issue by NipuniC** [wso2/docs-apim#444]
**Description:**

No information included on how to change default keystores using the deployment.toml in [1]

[1] https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/General/UsingAsymmetricEncryption/admin-configuring-keystores-in-wso2-products/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
AM-3.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ljuillerat** [comment]
Hi Nipuni,

Thanks for the issue.
As discussed before, the file is deployment.toml and not yaml

Regards,
Loïc

**Comment by abhigokhale** [comment]
We followed the instructions present in https://apim.docs.wso2.com/en/latest/Administer/ProductConfigurations/configuring-keystores-in-wso2-api-manager/ However, after changing the default keystore configuration in deployment.toml file its not getting reflected in the carbon.xml file. Do we need to update it in any other file?

**Comment by ljuillerat** [comment]
You have to add this is deployment.toml:

```
[keystore.primary]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[keystore.internal]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"
```
There are also some files that remained unchanged that you have to handle manually for now:
- repository/conf/broker.xml (not handled by toml)
- repository/resources/security/listenerprofiles.xml
- repository/resources/security/sslprofiles.xml

**Comment by Mariangela** [comment]
@bhathiya / @tharindu1st , please share your input.

**Comment by bhathiya** [comment]
We have it covered here.

https://apim.docs.wso2.com/en/latest/administer/product-security/configuring-keystores/configuring-keystores-in-wso2-api-manager/#configuring-keystores-in-wso2-api-manager

@NipuniC Is this what you were looking for?

**Comment by Krishanx92** [comment]
APIM-3.0.0 https://apim.docs.wso2.com/en/3.0.0/administer/product-security/configuring-keystores/configuring-keystores-in-wso2-api-manager/
APIM-3.1.0 https://apim.docs.wso2.com/en/3.1.0/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager/

Hence close the issue. If you have further questions regarding this doc please raised the issue.
