### ISSUE TITLE
Duplicate content in the migration document..

### ISSUE THREAD

**Issue by chaminda** [wso2/docs-apim#4445]
**Description:**
Same point mentioned twice under note section in the migration doc[1].

![image](https://user-images.githubusercontent.com/7115693/127801215-e3c01977-e418-4b1f-9808-913eb7038512.png)

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400/

**Comment by samgnaniah** [comment]
This is fixed now.
