### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by krishnilak** [wso2/docs-apim#448]
Location : https://apim.docs.wso2.com/en/latest/Learn/DesignAPI/CreateAPI/generate-rest-api-from-soap-backend/

Here this tutorial starts with one API (phone verification API ) and it explains some another API (weather API). For a newcomer, this will be  confusing

**Comment by shaniR** [comment]
refer to this https://apim.docs.wso2.com/en/latest/Learn/DesignAPI/CreateAPI/generate-rest-api-from-soap-backend/
