### ISSUE TITLE
[3.2.0] Updating the docs to mention "development of DAS message tracing" is deprecated

### ISSUE THREAD

**Issue by Chamindu36** [wso2/docs-apim#4491]
**Description:**
Documentation for the product should be updated as further development of  DAS message tracing is deprecated [1].

[1]. https://apim.docs.wso2.com/en/3.2.0/learn/api-gateway/message-tracing/#message-tracing

**Affected Product Version:**
APIM 3.2.0

**Comment by samgnaniah** [comment]
Closing this as we are tracking this via Internal JIRA.
