### ISSUE TITLE
Problem in "Configuring the Proxy Server" documents

### ISSUE THREAD

**Issue by amir-dh** [wso2/docs-apim#450]
**Description:**
I tried to run a standalone deployment behind a reverse proxy server. The configuration and tutorial in the provided [documents](https://apim.docs.wso2.com/en/latest/SetupAndInstall/DeployingWSO2APIManager/configuring-the-proxy-server-and-the-load-balancer/) are not complete since I did exactly like what it said but there are some problems.
Here is the `devportal` view:
![](https://user-images.githubusercontent.com/23727185/68851921-0ee29400-06ec-11ea-8576-3f6073b152bf.png)
When I click on the `Sign in` button, the `hostname` which should be `myDomain` name, changes to the `localhost`
This problem is the same for the `publisher portal` too.
![](https://user-images.githubusercontent.com/23727185/68851671-8d8b0180-06eb-11ea-8f2c-9ccede0bc8a5.png)

**Affected Product Version:**
WSO2 API Manager 3.0.0

**OS, DB, other environment details and versions:**    
Ubuntu 16.04 and Nginx as the reverse proxy server.

**Related Issues:**
https://github.com/wso2/product-apim/issues/6808

**Comment by shaniR** [comment]
just to confirm, was this the doc you followed? https://apim.docs.wso2.com/en/latest/InstallAndSetup/DeployingWSO2APIManager/configuring-the-proxy-server-and-the-load-balancer/

**Comment by hungtv-86** [comment]
@amir-dh  pls show config your nginx and i can fix it
