### ISSUE TITLE
Type/Docs - Documentation

### ISSUE THREAD

**Issue by lpastor74** [wso2/docs-apim#451]
**Description:**

on page  
https://apim.docs.wso2.com/en/latest/SetupAndInstall/DeployingWSO2APIManager/SingleNode/configuring-a-single-node/
the second passus is weird ..?

**"..The page: _Deploying API Manager using Single Node Instances was not found. Please check/update the page name used in the 'multiexcerpt-include macro...**

On same page step 4.
{.expand-control-image} Click here for more information. ?? Not working 

Almost all link on page point to 2.6 APIM docum

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/735
