### ISSUE TITLE
[4.0.0]Revamp Integration Quick Start Guide 

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#4529]
**Description:**
Below tasks should be carried out in integration [QSG](https://apim.docs.wso2.com/en/latest/get-started/integration-quick-start-guide/#step-1-set-up-the-workspace)

1. Revisit and fix samples.
2. Test end-to-end flow of QSG and fix.
3. Fix inconsistency in integration and streaming 
4. Fix typos in https://apim.docs.wso2.com/en/latest/use-cases/streaming-usecase/exposing-stream-as-managed-api-in-service-catalog/

**Comment by samgnaniah** [comment]
I've fixes some of 4 with https://github.com/wso2/docs-apim/pull/4530/files
