### ISSUE TITLE
APIM 4.0 docs - Need to update the token API endpoints

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/docs-apim#4547]
**Description:**
With the latest APIM 4.0, the token end points have been changed, For example
`https://<host>:<port>/token` has been changed to `https://<host>:<port>/oauth2/token` but this has not been reflected on the docs. 

Note that the ports mentioned in the example cURLs also need to be updated accordingly.

Bellow are some of the documentation links we need to fix this
 - https://apim.docs.wso2.com/en/latest/design/api-monetization/monetizing-an-api/
 - https://apim.docs.wso2.com/en/latest/reference/product-apis/admin-apis/admin-v2/admin-v2/#section/Authentication

**Comment by samgnaniah** [comment]
This seems to be fixed now so I'm closing this.
