### ISSUE TITLE
[4.0.0] Need to update doc with templated configs

### ISSUE THREAD

**Issue by msm1992** [wso2/docs-apim#4549]
**Description:**
Need to update doc[1] with below details once the fix for APIM 4.0.0 is synced to live.

* To control access only to the management console, add below config to deployment.toml:

```
[admin_console.control_access]
enable = true
allow = ["IP1", "IP2", "IP3"]
```
This will add a RemoteAddrValve Tomcat  valve in repository/conf/tomcat/carbon/META-INF/context.xml and it will only apply to the Carbon management console, and thereby all outside requests to the management console will be blocked.

* To control access to all web applications deployed in your server, add below config to deployment.toml:

```
[web_app.control_access]
enable = true
allow =  ["IP1", "IP2", "IP3"]
```
This will add a RemoteAddrValve Tomcat  valve in repository/conf/tomcat/context.xml and it will apply to each web application hosted on the Carbon server. Therefore, all outside requests to any web application will be blocked.

* You can also restrict access to particular servlets in a web application by adding below config to deployment.toml:

```
[[servlet_access_control_filter]]
filter_name = "Remote Address Filter"
allow_ip_regex = "127.0.0.1"
url_pattern = "/carbon/admin/login.jsp"
```
This will add Remote Address Filter to the web.xml file (stored in the <APIM-M_HOME>/repository/conf/tomcat/ directory) by mapping that filter to the servlet URL. In the Remote Address Filter that you add, you can specify the IP addresses that should be allowed to access the servlet.

The above example toml config illustrates how access to the management page (/carbon/admin/login.jsp) is granted only to one IP address:

[1]. https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/securing-api-m-web-portals/#restricting-access-to-web-portals

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
This seems to be fixed.
