### ISSUE TITLE
Doc Feedback:Suggest rewriting of this document

### ISSUE THREAD

**Issue by nadeesha5814** [wso2/docs-apim#455]
Location : https://apim.docs.wso2.com/en/latest/Learn/APIController/building-a-cicd-pipeline/

Document is all over the place and confusing, suggest a rewrite on the documentation with proper syntaxes and examples. A user who is new to WSO2 or even an existing user finds the document very confusing.

**Comment by Mariangela** [comment]
@nadeesha5814 , the updated content can be found in the following URL:

- https://apim.docs.wso2.com/en/latest/learn/api-controller/ci-cd-with-wso2-api-management/
- https://apim.docs.wso2.com/en/latest/learn/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach/
