### ISSUE TITLE
Add a document explaining the deployment synchronization

### ISSUE THREAD

**Issue by npamudika** [wso2/docs-apim#457]
There should be a document in API-M 3.0 doc space explaining the following.

- Say now we do not recommend to use SVN base deployment synchronizer.
- Explain the steps to move to NFS or Rsync like another deployment synchronizing mechanism for the existing users who uses SVN based deployment synchronizers.
- Explain the folders to be synced when running servers in product profiles.
- Explain what are the folders to be dep synced when using a custom theme.

**Comment by Mariangela** [comment]
> There should be a document in API-M 3.0 doc space explaining the following.
> 
> * Say now we do not recommend to use SVN base deployment synchronizer.

@npamudika , it looks like this point is already mentioned in the documentation in the form of a note in [1]. Please clarify whether this information is sufficient or whether any further information needs to be added to this.

[1] https://apim.docs.wso2.com/en/3.0.0/install-and-setup/deploying-wso2-api-manager/distributed-deployment/distributed-deployment-of-the-gateway/#step-4-start-the-gateway-nodes

**Comment by Mariangela** [comment]
@bhathiya, please provide information with regard to this Git issue, so that this doc gap can be filled.

**Comment by npamudika** [comment]
@Mariangela , it's good if we can have a separate doc page covering all the above mentioned information.

**Comment by nandika** [comment]
This requirement is no longer valid
