### ISSUE TITLE
Add a doc page for secure vault

### ISSUE THREAD

**Issue by npamudika** [wso2/docs-apim#458]
Now in API-M 3.0, the secure vault configurations has been changed with the new config modal.

We should have a similar doc like https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/encrypting_plain_text/

**Comment by shaniR** [comment]
Is the content the same?

**Comment by npamudika** [comment]
Yes, but pointing to our config catalog page [1] for the **list of configuration parameters**.

[1] https://apim.docs.wso2.com/en/latest/Reference/ConfigCatalog/

**Comment by tgtshanika** [comment]
The content has been updated https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/General/LoginsAndPasswords/working-with-encrypted-passwords/
