### ISSUE TITLE
Remove JDK 7 from installation pages and add JDK 8 and JDK 11

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/docs-apim#461]
Docs contain JDK 7 as the JAVA version. Please remove them and add JDK 8 and JDK 11 . 

ex: https://apim.docs.wso2.com/en/latest/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-linux-or-os-x/ 

This needs to be updated on all the pages in the installation guide

**Comment by Mariangela** [comment]
The documentation points off to the compatibility matrix, which mentions the correct JDK versions [1]. However, to avoid confusion I changed the examples from `jdk1.7.0_80` to `jdk1.8.0_xx`.


[1] https://apim.docs.wso2.com/en/latest/InstallAndSetup/ProductCompatibility/


jdk1.8.0_xx
