### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by rhoen** [wso2/docs-apim#4634]
The links in the navigation bar on the left do not work. I had to open the link in a  new tab in order to visit the next page. I am using Firefox Developer Edition 92.0b9

Location : https://apim.docs.wso2.com/en/latest/tutorials/scenarios/scenario1-create-rest-api/

![image](https://user-images.githubusercontent.com/9893527/132038602-70b85981-eabc-410e-baa3-12ff03b3b36e.png)

**Comment by samgnaniah** [comment]
I tried this out on this version of Firefox Developer Edition and wasn't able to reproduce this. It seemed to work fine for me.

Will investigate further.

**Comment by rosensilva** [comment]
This is not reproducible in Firefox 91.0.2 (64-bit) stable version. Hence this might be a temporary issue with  Firefox Developer Edition 92.0b9
