### ISSUE TITLE
Doc Feedback: Images in Connector pages are not displayed

### ISSUE THREAD

**Issue by arunans23** [wso2/docs-apim#4644]
Location : https://apim.docs.wso2.com/en/latest/reference/connectors/email-connector/email-connector-example/

The image links are broken. I observed this in other connector pages as well.

- https://apim.docs.wso2.com/en/latest/reference/connectors/gmail-connector/gmail-connector-example/
- https://apim.docs.wso2.com/en/latest/reference/connectors/amazonsqs-connector/amazonsqs-connector-example/
- https://apim.docs.wso2.com/en/latest/reference/connectors/bigquery-connector/bigquery-connector-example/

**Comment by Mariangela** [comment]
This issue has been duplicated in [1] and is fixed already for 4.0.0 and 4.1.0

[1] https://github.com/wso2/docs-apim/issues/5317
