### ISSUE TITLE
Broken Links - Message Store

### ISSUE THREAD

**Issue by himasha** [wso2/docs-apim#4698]
**Description:**
 All the message store examples such as in [1] (JDBC Message Store Example) are broken links.   Also need to remove the use of WSO2 MB as a message store in [2].

[1] https://apim.docs.wso2.com/en/latest/reference/synapse-properties/message-stores/jdbc-msg-store-properties/
[2] https://apim.docs.wso2.com/en/latest/reference/synapse-properties/message-stores/wso2mb-msg-store-properties/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
4.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Links in [1] are fixed now and we have decided to keep [2] since there might be some folks who are still using the old MB, which can still be used as a Message Store.
