### ISSUE TITLE
Broken links for API Authentication

### ISSUE THREAD

**Issue by fabiolgc** [wso2/docs-apim#470]
**Description:**
There are some links references to other documentation references that are broken. 
Under https://apim.docs.wso2.com/en/latest/Learn/APISecurity/api-authentication/ there are some links that references to Securing APIs using OAuth2 Opaque Access Tokens, Secure APIs Using JWT Tokens, Secure APIs Using API Keys, Secure APIs Using Mutual SSL, Secure APIs Using Basic Authentication that are showing page not found when clicking on those links - https://apim.docs.wso2.com/en/latest/page-not-found/

**Suggested Labels:**
I suggest correct the links to pint to the right documentation page.

**Affected Product Version:**
API Manager Documentation 3.0.0 
https://apim.docs.wso2.com/en/latest/Learn/APISecurity/api-authentication/

**Steps to reproduce:**
1 - Access this documentation link: https://apim.docs.wso2.com/en/latest/Learn/APISecurity/api-authentication/
2 - Click on "Securing APIs using OAuth2 Opaque Access Tokens" link. 

**Related Issues:**
The problem described above happens with other links on the same page:
Securing APIs using OAuth2 Opaque Access Tokens
Secure APIs Using JWT Tokens
Secure APIs Using API Keys
Secure APIs Using Mutual SSL

<img width="1439" alt="Screen Shot 2019-11-27 at 11 09 28 AM" src="https://user-images.githubusercontent.com/18014094/69730200-68908880-1106-11ea-93a7-c21862645788.png">
<img width="1440" alt="Screen Shot 2019-11-27 at 11 09 50 AM" src="https://user-images.githubusercontent.com/18014094/69730238-747c4a80-1106-11ea-84e1-d4fc1bb7fa07.png">
Secure APIs Using Basic Authentication

**Comment by shaniR** [comment]
The issue is fixed. Please feel free to reopen the issue if you encounter anymore issues.
