### ISSUE TITLE
[APIM 4] Broken Links - GraphQL Static Query Analyzer

### ISSUE THREAD

**Issue by himasha** [wso2/docs-apim#4702]
**Description:**
Following links in [1] are not working.
1. Query Depth Limitation
2. Query Complexity Limitation

[1] https://apim.docs.wso2.com/en/latest/design/rate-limiting/graphql-api/overview-query-limits-for-graphql/#static-query-analyzer

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
This is fixed now.
