### ISSUE TITLE
Update Distributed document for TM separated deployment

### ISSUE THREAD

**Issue by pubudu538** [wso2/docs-apim#4714]
**Description:**

We need to introduce a new pattern in addition to Simple Scalable deployment [1]. This pattern has 3 profiles such as TM,CP and GW. TM does not hold the event hub related changes. The event hub rest API goes to the CP profile. 

Task List:
1. Update pattern doc[1] to introduce a new pattern
2. APIM deployment will have 3 options.
- All in one
- Distributed deployment (TM in CP)[2]
- Distributed deployment (TM separated out from CP)

3. We need to have separate distributed guides for the above. Also, update images accordingly.

[1] - https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-overview/#simple-scalable-deployment
[2] - https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Samuel mentioned that this task has been completed. Therefore, I am closing this issue.
