### ISSUE TITLE
Doc Feedback: Image link broken 

### ISSUE THREAD

**Issue by arunans23** [wso2/docs-apim#4724]
Location : https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane/

Image is not show under "Methods to detect JWT token revocation" https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane/#methods-to-detect-jwt-token-revocation

**Comment by Mariangela** [comment]
## Related PR
https://github.com/wso2/docs-apim/issues/4322
