### ISSUE TITLE
Remove WSO2_STAT_DB  from the document, as APIM does not need this since 2.6.0

### ISSUE THREAD

**Issue by Arshardh** [wso2/docs-apim#476]
**Description:**
The documentation with the title: **Understanding the Distributed Deployment of WSO2 API-M** explains about the WSO2_STAT_DB. This is no longer required since APIM version 2.6.0. We need to remove this from the docs of APIM 2.6.0 and APIM 3.0.0.

**Affected Product Version:** 2.6.0, 3.0.0

**Comment by Mariangela** [comment]
Fixed in:
- API-M 3.0.0 
       - https://github.com/wso2/docs-apim/pull/804/commits/303fd66ef4755a4fd8c1b0b615f379a8b259f8b8
      - https://github.com/wso2/docs-apim/pull/804
      - https://apim.docs.wso2.com/en/latest/install-and-setup/deploying-wso2-api-manager/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m/

- API-M 2.6.0
      -https://docs.wso2.com/display/AM260/Understanding+the+Distributed+Deployment+of+WSO2+API-M
