### ISSUE TITLE
Need support to enable Monetization for APIs in APIM 260

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#4768]
**Description:**
We need to get the implementation details in place so that we can have similar content with regard to enabling monetization in API-M 2.6.0. Currently, this information is not available in API-M 2.6.0.

[1] https://docs.wso2.com/display/AM250/Enabling+Monetization+of+APIs

**Affected Product Version:**
APIM 2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruks** [comment]
@Mariangela can you please verify the progress of this?

**Comment by ruks** [comment]
Close the issue since there are no activities recently.
