### ISSUE TITLE
Missing Information in Deploy through Multiple API Gateways Doc

### ISSUE THREAD

**Issue by rashm1n** [wso2/docs-apim#4774]
**Description:** $Subject

### Solution

* Need to incoporate steps 1-3 in https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/#step-6-configure-and-start-the-profiles,  for the two gateway instances in the doc.
* Need to create sub-steps in the docs for more clarity

**Comment by rashm1n** [comment]
@Mariangela @tharindu1st

**Comment by Mariangela** [comment]
Had a discussion with Tharindu and Rashmin in this regard today.
