### ISSUE TITLE
Doc Feedback:Step 1.2 needs to be updated

### ISSUE THREAD

**Issue by Shenavi** [wso2/docs-apim#4906]
Location : https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker/

When following the documentation the linked website path points to the MG distribution not the choreo connect one. Hence the rest of the steps to setup choreo connect are obsolete.

**Comment by samgnaniah** [comment]
This is fixed now.
