### ISSUE TITLE
Doc Feedback: Links not working

### ISSUE THREAD

**Issue by Prabhashi** [wso2/docs-apim#4910]
Location : https://apim.docs.wso2.com/en/latest/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store/

Following links are not working and showing "Page not found" errors.
![image](https://user-images.githubusercontent.com/28176167/139014484-9c1387cd-c447-48ce-9d6f-a144aa5e2d94.png)

**Comment by samgnaniah** [comment]
These are fixed now.
