### ISSUE TITLE
Choreo Connect : Links not working

### ISSUE THREAD

**Issue by slahirucd7** [wso2/docs-apim#4928]
**Description:**
Some of the links in below web pages are broken in Choreo Connect docs.

> Link for the `disabling security` in below web page.
https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/api-authentication/

> Link for the `JWT generation configuration details` in below web page.
https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect/#jwt-generation-configuration-details

**Comment by Mariangela** [comment]
The Disabling Security link has been fixed in the following PRs

- https://github.com/wso2/docs-apim/pull/4958
- https://github.com/wso2/docs-apim/pull/4962

**Comment by samgnaniah** [comment]
This looks like it is fixed now so closing this.
