### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by acaciocintra** [wso2/docs-apim#493]
Location : https://apim.docs.wso2.com/en/latest/Learn/Extensions/adding-mediation-extensions/

The documentation links are broken and don't work. 
All pages has this problem

**Comment by dushaniw** [comment]
Hi @acaciocintra 

The documentation related to mediation extensions are available from [https://apim.docs.wso2.com/en/latest/Learn/APIGateway/MessageMediation/changing-the-default-mediation-flow-of-api-requests/]
