### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by acaciocintra** [wso2/docs-apim#494]
Location : https://apim.docs.wso2.com/en/latest/Learn/ConsumeAPI/ManageSubscription/subscribe-to-an-api/

I think that context /store was moved to /devportal. My version 3.0.0 dont has context /store, only /devportal

**Comment by Mariangela** [comment]
Thanks for reporting!

This has been fixed in 
https://apim.docs.wso2.com/en/latest/Learn/ConsumeAPI/ManageSubscription/subscribe-to-an-api/
