### ISSUE TITLE
Missing tomcat configs in the config catalog

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/docs-apim#4967]
**Description:**
The config catalog is missing the configurations related to [1]. Moreover, the web_app.listener configuration which was added from [2] should be added as well.

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/securing-api-m-web-portals/
[2] https://github.com/wso2/carbon-kernel/pull/3107

**Comment by Mariangela** [comment]
@HeshanSudarshana , is this applicable only for APIM 4.0.0 and 4.1.0 or it is applicable for older versions as well.

**Comment by HeshanSudarshana** [comment]
This is applicable for APIM 4.0.0 onwards.
