### ISSUE TITLE
Axis2.xml configuration reset at startup for api-devportal profile

### ISSUE THREAD

**Issue by Khelnor** [wso2/docs-apim#497]
I setup a WSO2 3.0.0 instance with the profile api-devportal.
When I launch the profilesetup.sh for this profile, axis2.xml file is modified correctly by commenting two transportSender:

`INFO - Disabled the <transportSender name="ws" class="org.wso2.carbon.websocket.transport.WebsocketTransportSender"> from axis2.xml file`
`INFO - Disabled the <transportSender name="wss" class="org.wso2.carbon.websocket.transport.WebsocketTransportSender"> from axis2.xml file`

But when I start the instance with the profile api-devportal, axis2.xml configuration is dropped and those two tags are uncommented.

**Comment by Mariangela** [comment]
@ruthryi , pls check if this is already there atm.
