### ISSUE TITLE
API Manager 3.0.0 - drop all changes in carbon.xml file during start server

### ISSUE THREAD

**Issue by igkononov** [wso2/docs-apim#498]
Hi,

I try to change some values in <APIManager_Home>/repository/conf/carbon.xml.
But after starting WSO2 server this file is overrode by default carbon.xml - all changes are dropped.

It looks strangely, because in API Manager 3.0.0 documentation I found, that it is possible to change this file.

Please, can you give explanation of this situation.

Thanks for your answer in advanced.

**Comment by shaniR** [comment]
https://apim.docs.wso2.com/en/latest/InstallAndSetup/DeployingWSO2APIManager/changing-the-hostname/ & 
https://apim.docs.wso2.com/en/latest/Reference/Guides/changing-the-default-ports-with-offset/
have been updated. Hence closing the issue. Feel free to re open the issue if you encounter any issues in the future.
