### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by Zgrrl** [wso2/docs-apim#4986]
Location : https://apim.docs.wso2.com/en/3.2.0/learn/api-gateway/message-tracing/
Hi,
I published soap service on api manager 3.2.0 and i'm try to see request and response on terminal like in document.
But there is only this information in output;
INFO {org.wso2.carbon.analytics.message.tracer.handler.util.HandlerUtils} -
 Massage Info: Transaction id=.....  Message direction=OUT 
 Server name=....  Timestamp=1636374681524  Service name=__SynapseService  Operation Name=mediate
How can i find soap body request and response ?

Thanks,

**Comment by Mariangela** [comment]
@Zgrrl , please join us via WSO2's official Slack channels for better communication. 
You can talk to our developers directly regarding issues or concerns about the products.

[wso2-apim.slack.com](https://wso2-apim.slack.com/) : [Join](https://join.slack.com/t/wso2-apim/shared_invite/enQtNzEzMzk5Njc5MzM0LTgwODI3NmQ1MjI0ZDQyMGNmZGI4ZjdkZmI1ZWZmMjNkY2E0NmY3ZmExYjkxYThjNzNkOTU2NWJmYzM4YzZiOWU?src=sidebar)

**Comment by Mariangela** [comment]
Hi @Zgrrl ,

As message tracing has been deprecated in API Manager 3.2.0, please use wire logs instead of message tracing. For more information, see [1].

[1] https://apim.docs.wso2.com/en/3.2.0/administer/logging-and-monitoring/logging/setting-up-logging/#enable-gateway-wire-logs
