### ISSUE TITLE
Doc Feedback: link is dead

### ISSUE THREAD

**Issue by robbla** [wso2/docs-apim#4998]
Location : https://apim.docs.wso2.com/en/latest/integrate/develop/advanced-development/applying-security-to-a-proxy-service/

the link in Be sure to configure a user store for the Micro Integrator and add the required users and roles.

https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/mi-setup/setup/user_stores/setting_up_a_userstore

is dead, resulting in a 

https://apim.docs.wso2.com/en/latest/page-not-found/

**Comment by Mariangela** [comment]
Hi @robbla ,

Thank you for reporting this issue.

We have fixed this issue in the APIM 4.0.0 and 4.1.0 docs via the following PRs and we have also improved the content in this page. The fix will appear live after the PRs are merged.
<google-sheets-html-origin><style type="text/css"></style>

https://github.com/wso2/docs-apim/pull/5333
--
https://github.com/wso2/docs-apim/pull/5334

Regards,

Mariangela

**Comment by Mariangela** [comment]
The fix is available now in the APIM docs [1].

[1] https://apim.docs.wso2.com/en/latest/integrate/develop/advanced-development/applying-security-to-a-proxy-service/
