### ISSUE TITLE
Postgre DB Docs are not Up-To-Date

### ISSUE THREAD

**Issue by athiththan11** [wso2/docs-apim#501]
The following [Postgre](https://apim.docs.wso2.com/en/latest/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-postgresql/) database-related configuration docs are not been updated to instruct APIM 3.0.0 users and those are still being referred to the older configurations (also other database vendor configurations).

Furthermore, able to notice a couple of typo errors on the same page. Refer to the attached screenshot.

<img width="1680" alt="APIM3 Docs Postgres" src="https://user-images.githubusercontent.com/29927177/70126105-4d8dbd80-169e-11ea-82a2-a5c430ef16fe.png">

[1]: [https://apim.docs.wso2.com/en/latest/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-postgresql/]( https://apim.docs.wso2.com/en/latest/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-postgresql/)

**Comment by shaniR** [comment]
@tgtshanika  can we review these documents during the hackathon?

**Comment by renuka-fernando** [comment]
Updated Doc: https://apim.docs.wso2.com/en/latest/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-postgresql/

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/563
