### ISSUE TITLE
Type mistake in Writing Custom Handlers

### ISSUE THREAD

**Issue by Thiyanwso2** [wso2/docs-apim#5024]
**Description:**
In the _**Writing Custom Handlers**_ section, for  _**Using APILogMessageHandler**_, there is a typo mistake in the log4j2.properties configs.

**Erroneous configuration**
_logger.log-msg-handler.name = org.wso2.carbon.apimgt.gateway.handlers.logging.APILogMessageHandler
logger.log-msg-handler.name = DEBUG_

**Correct configuration**
_logger.log-msg-handler.name = org.wso2.carbon.apimgt.gateway.handlers.logging.APILogMessageHandler
logger.log-msg-handler.level = DEBUG_

**Suggested Labels:**
apim, handlers

**Affected Product Version:**
APIM-3.2.0

[1] https://apim.docs.wso2.com/en/3.1.0/develop/extending-api-manager/extending-gateway/writing-custom-handlers/#using-apilogmessagehandler

**Comment by Mariangela** [comment]
Fixed in 3.1.0. This issue is not present in the 3.2.0, 4.0.0 and 4.1.0 docs.

**Comment by samgnaniah** [comment]
Closing this as this seems to be fixed now.
