### ISSUE TITLE
Configurations related to enabling Admin Services haven't been updated.

### ISSUE THREAD

**Issue by iloshinik** [wso2/docs-apim#504]
**Description:**
The documentation [1] is still referring to the old configuration which is used to enable admin services from the carbon.xml.
This should be updated to the latest configuration that needs to be done in the <API-M_HOME>/repository/conf/deployment.toml file. 
The following configuration should be explicitly added in the deployment.toml in order to enable admin services.

> **[admin_service.wsdl]**
> **enable=true**

[1]. https://apim.docs.wso2.com/en/latest/Develop/wso2-admin-services/

**Affected Product Version:**
wso2am-3.0.0

**Comment by Mariangela** [comment]
@iloshinik , the updated documentation can be found at
https://apim.docs.wso2.com/en/latest/develop/wso2-admin-services/
