### ISSUE TITLE
TM related steps on Migration steps are missing

### ISSUE THREAD

**Issue by dineshjweerakkody** [wso2/docs-apim#505]
**Description:**
In the APIM Migration guide [1], there are no steps or any comment related to Traffic Manager node. If user can copy the custom throttling plans to new version or have to recreate in the new version please mention it.

[1] https://docs.wso2.com/display/AM260/Upgrading+from+the+Previous+Release

**Affected Product Version:**
2.6.0

**Comment by Mariangela** [comment]
@vithu30 , please share your comments on this git issue.

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
