### ISSUE TITLE
Need to add the newly added gateway resource to docs

### ISSUE THREAD

**Issue by mushthaq33** [wso2/docs-apim#5060]
**Description:**
A new resource to Gateway REST API as a health check API is added to verify whether all the APIs are deployed or not

The new gateway resource has been added with the update 2829. It can be accessed in the following way.

Eg: curl -k "https://<GATEWAY-HOST>:9443/api/am/gateway/v2/server-startup-healthcheck" -H "Authorization: Basic <Base46 of admin username and password>"

This will return 500 if all the APIs have failed to get deployed and else it will return 200.

**Affected Product Version:**
APIM 4.0.0 

**Related Issues:**
https://github.com/wso2/product-apim/issues/11884

**Comment by samgnaniah** [comment]
This is now added to docs so I'm closing this issue.

https://apim.docs.wso2.com/en/latest/reference/product-apis/gateway-apis/gateway-v1/gateway-v1/#operation/undeployAPI
