### ISSUE TITLE
Typos related to API lifecycle 

### ISSUE THREAD

**Issue by suksw** [wso2/docs-apim#5064]
**Description:**
- typo here https://github.com/wso2/docs-apim/blob/7ff20fddf11a45afd334f8502def29df1d4cd831/en/docs/deploy-and-publish/publish-on-dev-portal/publish-an-api.md?plain=1#L19
- here `but it is not deployed` can be changed to `but it is not published` https://github.com/wso2/docs-apim/blob/7ff20fddf11a45afd334f8502def29df1d4cd831/en/docs/design/lifecycle-management/api-lifecycle.md?plain=1#L11

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/5090

**Comment by Mariangela** [comment]
This has been fixed in APIM 4.1.0 and 4.0.0.

[1] https://apim.docs.wso2.com/en/4.1.0/design/lifecycle-management/api-lifecycle/
[2] https://apim.docs.wso2.com/en/4.0.0/design/lifecycle-management/api-lifecycle/
