### ISSUE TITLE
Some parameters are missing in the Migrating the APIs and Applications to a Different Environment

### ISSUE THREAD

**Issue by menakaj** [wso2/docs-apim#507]
**Description:**
Some of the supported apim cli parameters are missing in the documentation.
Missing 
```  
--withKeys             Export keys for the application
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.6.0, APIM 2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
https://docs.wso2.com/display/AM250/Migrating+the+APIs+and+Applications+to+a+Different+Environment#Format-listAPI

**Related Issues:**

**Comment by Mariangela** [comment]
@menakaj , I updated based on your feedback. Is change applicable to APIM 2.6.0 and 3.0.0?

[1] https://docs.wso2.com/display/AM250/Migrating+the+APIs+and+Applications+to+a+Different+Environment#Format-listAPI
