### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by krishnilak** [wso2/docs-apim#508]
Location : https://apim.docs.wso2.com/en/latest/Learn/APISecurity/Authorization/role-based-access-control-using-xacml/

Internal links within this document are not working 
For example,  
1. Sharing the registry space for the steps.
2. Configuring an external LDAP or Active Directory User store.

**Comment by Meruja** [comment]
Fixed with wso2/docs-apim/pull/617/

**Comment by Mariangela** [comment]
This has been fixed.
