### ISSUE TITLE
[APIM 3.0.0] "Setting up logging" doc hasn't been updated  

### ISSUE THREAD

**Issue by deelaka96** [wso2/docs-apim#514]
**Description:**

The following documentation doesn't have the latest configurations 
https://apim.docs.wso2.com/en/latest/Administer/ProductAdministration/Monitoring/Logging/setting-up-logging/#configure-log4j-appenders

**Affected Product Version:**
3.0.0

**Comment by shaniR** [comment]
The document has been updated.Please feel free to re open the issue if you encounter any issues in the future.
