### ISSUE TITLE
Add health check info for ports 8099 and 9099

### ISSUE THREAD

**Issue by binodmx** [wso2/docs-apim#5180]
**Description:**
Pages regarding basic health checks ([1] and [2]) should be updated with the information that the command `curl -v http://<HOSTNAME>:<PORT>` can be used for the health check of ports 8099 and 9099. The response will be 200 OK but with an empty body.

[1] https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/deployment-best-practices/basic-health-checks/
[2] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-best-practices/basic-health-checks/

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
API-M 4.0.0, API-M 3.2.0

**Comment by Mariangela** [comment]
@binodmx , is this fix relevant in 4.1.0 as well?

**Comment by binodmx** [comment]
> @binodmx , is this fix relevant in 4.1.0 as well?

Added changes for 4.1.0.
