### ISSUE TITLE
Update docs for Inbuilt artifact synchronization with tenant lazy loading

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/docs-apim#5183]
**Description:**
Lazy loading of tenants in not possible with `data_retrieval_mode` set to `sync`. Users have to set `data_retrieval_mode = "async"` if they have enabled lazy loading for tenants.

This needs to be added as a note in [1]

[1] - https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster/#inbuilt-artifact-synchronization
**Affected Product Version:**
3.2.0

**Related Issues:**
APIMINTERNAL-1510

**Comment by Mariangela** [comment]
@ruthryi , I think this issue can be closed. Pls check and close it.
