### ISSUE TITLE
Minor formatting issue in 4.0.0 upgrade guide "!!! important"

### ISSUE THREAD

**Issue by lahirus** [wso2/docs-apim#5244]
**Description:**
"!!! important" is not formatted properly

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lahirus** [comment]
https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400/

**Comment by Mariangela** [comment]
This has been fixed in 4.0.0 and 4.1.0 docs via the above PRs.

**Comment by Mariangela** [comment]
This issue was not applicable to 3.2.0 docs.
