### ISSUE TITLE
Add password grant configs for MI OAuth HTTP endpoints

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-apim#5250]
**Description:**
Need to update [oauth-properties](https://apim.docs.wso2.com/en/latest/reference/synapse-properties/endpoint-properties/#oauth-properties) section with the following features released for MI version 4.0.0.34 and above.

https://github.com/wso2-support/wso2-synapse/pull/1710

**Comment by Mariangela** [comment]
@SanojPunchihewa , I do not have access to [1]. Please share the information in this ticket.

[1] https://github.com/wso2-support/wso2-synapse/pull/1710

**Comment by SanojPunchihewa** [comment]
Hi @Mariangela ,

We have already updated the EI 660 docs with these changes. We need to port the [Password grant type](https://docs.wso2.com/display/EI660/HTTP+Endpoint#HTTPEndpoint-Passwordgranttype), [Send additional parameters in the OAuth request body](https://docs.wso2.com/display/EI660/HTTP+Endpoint#HTTPEndpoint-SendadditionalparametersintheOAuthrequestbody) and [Define dynamic expressions](https://docs.wso2.com/display/EI660/HTTP+Endpoint#HTTPEndpoint-Definedynamicexpressions) sections to [oauth-properties](https://apim.docs.wso2.com/en/latest/reference/synapse-properties/endpoint-properties/#oauth-properties).

> * Is this relevant to 4.1.0 as well?

Yes, We need to add these to 4.1.0 docs as well
