### ISSUE TITLE
Update postman collection for APIM 4.0.0

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/docs-apim#5251]
**Description:**
Postman collection provided in the quick start section in https://apim.docs.wso2.com/en/latest/reference/product-apis/overview/#quick-start is outdated. Please update it with https://gist.github.com/chamilaadhi/7d37fd33bc6b152af02ab40c02056ba0

**Comment by Mariangela** [comment]
### Related to

https://github.com/wso2/docs-apim/issues/5445

**Comment by Mariangela** [comment]
Closing this issue as this issue has been duplicated and will be fixed in https://github.com/wso2/docs-apim/issues/5445
