### ISSUE TITLE
Links and Images are not working for Salesforce Inbound Endpoint Example

### ISSUE THREAD

**Issue by ramindu90** [wso2/docs-apim#5273]
**Description:**
Links are not working for Salesforce Inbound Endpoint Example and the same applies for the links referred via the page.
[sf-rest inbound endpoint configuration](https://apim.docs.wso2.com/en/4.0.0/reference/connectors/salesforce-connectors/sf-rest%20inbound%20endpoint%20configuration/) is not working. It should be pointed to https://apim.docs.wso2.com/en/latest/reference/connectors/salesforce-connectors/sf-inbound-endpoint-configuration/

Image in https://apim.docs.wso2.com/en/latest/reference/connectors/salesforce-connectors/sf-inbound-endpoint-configuration/ are not available.

**Comment by Mariangela** [comment]
Ramindu mentioned that not just this page but other pages under the salesforce section too have broken images.

**Comment by Mariangela** [comment]
On further investigation I figured that a majority of the images were broken due to the case of the file name also because certain pages were included pages where the images were not rendering properly as {{base_path}} does not work in included pages.
