### ISSUE TITLE
Unable to locate a toml file in path <API-M_HOME>/resources/conf/config.toml. Is this path correct?

### ISSUE THREAD

**Issue by thilinitm** [wso2/docs-apim#5311]
Location : https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway/

**Comment by Mariangela** [comment]
Hi @thilinitm ,

Thank you for your query. This is actually a bug in the API-M documentation. The correct path should be `<API-M_HOME>/repository/conf/deployment.toml`.
We have corrected this issue in [1].

Thank you.
Regards,

Mariangela

[1] https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway/
