### ISSUE TITLE
Doc Feedback: missing " in username password

### ISSUE THREAD

**Issue by robbla** [wso2/docs-apim#533]
Location : https://apim.docs.wso2.com/en/latest/Learn/Extensions/SAML2SSO/configuring-identity-server-as-idp-for-sso/

think the username and password should be between ""
   [database.shared_db]
   type = "mysql"
   url = "jdbc:mysql://localhost:3306/410_um_db"
   username = wso2carbon
   password = wso2carbon

**Comment by shaniR** [comment]
This has been fixed.
