### ISSUE TITLE
Doc Feedback: wrong deployment.toml

### ISSUE THREAD

**Issue by robbla** [wso2/docs-apim#534]
Location : https://apim.docs.wso2.com/en/latest/Learn/Extensions/SAML2SSO/configuring-identity-server-as-idp-for-sso/

Deployment.toml is not in datasources

The Identity Server has an embedded LDAP user store by default. As this is enabled by default. To change this to database user store, add the following to the **<IS_HOME>/repository/conf/datasources/deployment.toml**, follow the instructions in Internal JDBC User Store Configuration to disable the default LDAP and enable the JDBC user store instead.

**Comment by shaniR** [comment]
This has been fixed.
