### ISSUE TITLE
Doc Feedback: I get page not found when I try to view tenant theme in snapshot given below

### ISSUE THREAD

**Issue by thilinitm** [wso2/docs-apim#5344]
Location : https://apim.docs.wso2.com/en/latest/page-not-found/

<img width="1440" alt="Screenshot 2022-02-28 at 10 04 48" src="https://user-images.githubusercontent.com/98460047/155924797-14047039-7b08-4265-b5ad-b96cf7b6cbd6.png">

**Comment by Mariangela** [comment]
Hi @thilinitm ,

Thanks for reporting this issue. We have fixed this issue now.

Regards,

Mariangela
