### ISSUE TITLE
Missing instructions in Authorization Code Grant documentation

### ISSUE THREAD

**Issue by IsuruMaduranga** [wso2/docs-apim#5386]
**Description:**

[Authorization Code Grant](https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/grant-types/authorization-code-grant/) documentation does not contain guidance for setting up the playground application. Required instructions can be found under Identity server documentation [here](https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-playground2-webapp). Providing a link to it would be suffice.

**Affected Product Version:**
APIM-4.0.0
APIM-4.1.0-alpha
APIM-4.1.0-beta

**Comment by samgnaniah** [comment]
This link seems to be there:

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/19791901/156931657-7774873d-5cc8-4e08-91d0-57c26e7c61d6.png">

Closing this issue for now, please reopen if this is not sufficient.
