### ISSUE TITLE
Missing feature Downloading a Postman Collection of a GraphSQL Schema Avaiable in Docs

### ISSUE THREAD

**Issue by rashm1n** [wso2/docs-apim#5396]
**Description:**
* The feature, downloading a postman collections of a graph-sql schema is mentioned in the APIM-DOCS [1] , even though the feature is not currently present in the APIM pack.
[1] - https://apim.docs.wso2.com/en/latest/consume/invoke-apis/invoke-apis-using-tools/try-out-using-postman/

**Comment by Mariangela** [comment]
@HiranyaKavishani , has this feature been removed from APIM?
