### ISSUE TITLE
Websocket port not getting updated with port offset

### ISSUE THREAD

**Issue by Shenavi** [wso2/docs-apim#5403]
Location : https://apim.docs.wso2.com/en/latest/use-cases/streaming-usecase/create-streaming-api/create-a-websocket-streaming-api/

I am using the GA version and the websocket port does not get updated on the UIs when a port offset is given

**Comment by senthuran16** [comment]
The following configuration should be provided in the `deployment.toml` file in order to do this
```
[[apim.gateway.environment]]
ws_endpoint = "ws://localhost:9190"
```
* Note: `9190` = `default port 9090` + `port_offset`

@Mariangela let's add this as a note to the docs as discussed offline
