### ISSUE TITLE
"Changing to ibm db2" page should be updated

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/docs-apim#541]
**Description:**
This page needs to be updated -> https://apim.docs.wso2.com/en/latest/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-ibm-db2/

DB2 Express-C software is not available for Mac users and also DB2 Express-C software is an old software. 

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**
APIM 3.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by renuka-fernando** [comment]
Updated Doc:
https://apim.docs.wso2.com/en/latest/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-ibm-db2/
