### ISSUE TITLE
Inline issue in docs and Need to add links related to admin console

### ISSUE THREAD

**Issue by Tharanidk** [wso2/docs-apim#5420]
**Description:**
I tried to test "A read-only mode for API Publisher" 
(https://apim.docs.wso2.com/en/4.1.0/design/api-security/authorization/publisher-portal-in-read-only-mode/ ) , 

**Related Issues:**
01. Inline issue is found at the beginning
02. Also, the links for admin console related steps should be added to this.

**Comment by hasuniea** [comment]
fixed issue from https://github.com/wso2/docs-apim/pull/5421
