### ISSUE TITLE
Issue in adding policy specification in Operation Level Mediation Policy Support feature

### ISSUE THREAD

**Issue by Tharanidk** [wso2/docs-apim#5432]
**Description:**
As mentioned in the documentation https://apim.docs.wso2.com/en/4.1.0/deploy-and-publish/deploy-on-gateway/api-gateway/message-mediation/specifying-mediation-flow-based-on-policy/ , in the step 06 we need to provide the Policy Specification as below
![doc_specification](https://user-images.githubusercontent.com/42825038/157818447-7046134b-7256-4e51-930b-955c24974e4c.png)

But now providing policy specification is available as below. We need to fill details in a form.
![form](https://user-images.githubusercontent.com/42825038/157818621-60dd309e-ca71-4143-a3d4-4d6328062660.png)

**Comment by Tharanidk** [comment]
**Issue 02:**
In the doc [](https://apim.docs.wso2.com/en/4.1.0/deploy-and-publish/deploy-on-gateway/api-gateway/message-mediation/changing-the-default-mediation-flow-of-api-requests/#!) , Step 05 and step 06 need to be changes as there is no button available to edit Message Mediation as in below figure
![edit-mediation](https://user-images.githubusercontent.com/42825038/158113689-ef42dc93-13cf-440a-b1fd-d7bf152fee8c.png)

**Comment by samgnaniah** [comment]
Policy docs are now revamped and updated.

https://apim.docs.wso2.com/en/4.1.0/design/api-policies/overview/
