### ISSUE TITLE
[4.0.0] Missing config in Product REST APIs quick start documentation

### ISSUE THREAD

**Issue by wggihan** [wso2/docs-apim#5445]
**Description:**
Product REST APIs quick start consists of a postman collection.  
1. Invalid URL for generate access token request
2. Missing URL in Add API.

https://apim.docs.wso2.com/en/latest/reference/product-apis/overview/

**Affected Product Version:**
APIM 4.0.0

**Comment by bhathiya** [comment]
@Mariangela Please check.

**Comment by Mariangela** [comment]
@YasasRangika , can you please provide your feedback in this regard, and share the details that needs to go into the doc.

**Comment by YasasRangika** [comment]
Related to: https://github.com/wso2/product-apim/issues/12315

**Comment by Mariangela** [comment]
## Related to

https://github.com/wso2/docs-apim/issues/5251

**Comment by YasasRangika** [comment]
This will be fixed with https://github.com/wso2/product-apim/issues/12315
