### ISSUE TITLE
[APIM-4.1.0] Gateway Cluster - rate limiting with Redis

### ISSUE THREAD

**Issue by lkokila** [wso2/docs-apim#5471]
**Description:**
The following document [1] highlights that the feature (configuring the Redis server) should be used "when a clustered setup is not used". This might lead users to question the steps on configuring a cluster set-up, especially if they don't want to use Redis. This might be the most probable scenario for existing customers who plan migrations. It would be better to clarify the problem addressed by the feature, limitations and when to use the feature, in the document.

The document says "If you are using a clustered deployment, the counters are replicated across the cluster". While reading this I am interested to figure out how clustering can be configured and I get redirected to old Hazelcast based clustering documents which are not applicable anymore with the product as far as I know. 

[1]. https://apim.docs.wso2.com/en/4.1.0/design/rate-limiting/advanced-topics/configuring-rate-limiting-api-gateway-cluster/#configuring-rate-limiting-for-an-api-gateway-cluster

**Suggested Labels:**
APIM-4.1.0

**Affected Product Version:**APIM-4.1.0

**Comment by Mariangela** [comment]
@tharindu1st . @tgtshanika , @bhathiya , please share your thoughts in this regard.

**Comment by bhathiya** [comment]
@tharindu1st Here by "cluster", do you mean hazelcast cluserring? As per the doc, that's the 1st option, which is not correct right? Isn't Redis our recommendation now?
