### ISSUE TITLE
Create official doc pages for APIM Traffic Tool

### ISSUE THREAD

**Issue by rmsamitha** [wso2/docs-apim#548]
Description:

Create official doc pages for APIM Traffic Tool.
Reference content: https://github.com/wso2/product-apim-tooling/blob/master/apim-traffic-tool/README.md

Affected Product Version:
3.0.0

**Comment by Sarangan0219** [comment]
As of now, we don't have use-cases from customers to use this tool. Thus we have decided not to support the documentation about this tool.

If we decide to create a doc space for this tool in the future then refer to this [draft.](https://github.com/wso2/docs-apim/compare/3.2.0...Sarangan0219:apim_traffic_tool_3.2.0?expand=1)

**Comment by Mariangela** [comment]
@Sarangan0219 , based on your reply we will be closing this issue.
