### ISSUE TITLE
Deprecated doc search functionality still available in the 4.0.0 documentation

### ISSUE THREAD

**Issue by dumindurox777** [wso2/docs-apim#5505]
**Description:**
The doc: keyword search not working as mentioned in [1], As per the git issue[2] seems wso2 has deprecated this search functionality for 4.0 release [3]. You can find the reason to do so by Malintha's comment in that git issue. We even have removed this from the publisher search tooltip [3]. We have removed this from the API search functionality from consuming API documentation as well [4]. But seemed wso2 missed removing this information from [1].

**Suggested Labels:**
APIM-4.0.0

**Affected Product Version:**

APIM-4.0.0
U2 level 85

[1] https://apim.docs.wso2.com/en/latest/design/api-documentation/search-documentation/add-new-search-keyword/ 
[2] https://github.com/wso2/product-apim/issues/10855
[3] https://github.com/wso2/carbon-apimgt/pull/10306
[4] https://github.com/wso2/docs-apim/pull/3770

https://github.com/wso2/product-apim/issues/10855

**Related Issues:**
https://github.com/wso2/product-apim/issues/10855

**Comment by Mariangela** [comment]
@dumindurox777 , has this feature been removed in 4.0.0 or deprecated? because if it has been deprecated the docs need to be there with a banner notifying deprecation. And the About this release page needs to have an entry with regard to deprecation. Please advise

**Comment by Mariangela** [comment]
@msm1992 , you have removed content in [1] in the 4.0.0 docs. Is that feature removed or deprecated?

[1] https://github.com/wso2/docs-apim/pull/3770

**Comment by msm1992** [comment]
The feature is removed. It is no longer functional in APIM 4.0. We can remove the doc page.
