### ISSUE TITLE
Need to improve dynamic endpoints docs with pre defined set to header policy

### ISSUE THREAD

**Issue by chashikajw** [wso2/docs-apim#5522]
**Description:**

There is a pre-defined policy called "Set To Header" in the UI. Users can easily drag and drop that policy and set a value to the policy. This approach should mention in the docs.

Link: https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/message-mediation/adding-dynamic-endpoints/

**Comment by samgnaniah** [comment]
These docs have now changed and the new policy docs can be found here: https://apim.docs.wso2.com/en/latest/design/api-policies/overview/
