### ISSUE TITLE
[300][Improvement]The Role based access control model should be documented.

### ISSUE THREAD

**Issue by menakaj** [wso2/docs-apim#553]
**Description:**
In 3.0.0, since the UI uses rest API, the users need to have proper roles assigned to them. 

This highly affects users who are trying to integrate users in their user stores, where they have to manually assign Internal roles (Internal/publisher, Internal/creator, Internal/subscriber) to the users.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0-docs

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/615
