### ISSUE TITLE
Open API/Swagger archive sample

### ISSUE THREAD

**Issue by tgtshanika** [wso2/docs-apim#5532]
**Description:**
1. The master swagger file name in archive sample has to be renamed as 'swagger.json/yaml' instead of 'Swagger.json/yaml'[1]
2. A sample should be attached, so users can easily understand the expected format of the archive. Sample archive can be found here 
[dir.zip](https://github.com/wso2/docs-apim/files/8383150/dir.zip)
3. Should add a note to archive the swagger files without having hidden folders like __MACOSX

[1] https://apim.docs.wso2.com/en/latest/design/create-api/create-rest-api/create-a-rest-api-from-an-openapi-definition/

**Comment by Mariangela** [comment]
@tgtshanika , please let us know if this change is applicable to APIM 4.0.0 as well.
