### ISSUE TITLE
Broken link for APIM 4.1.0 Overview documentation

### ISSUE THREAD

**Issue by slahirucd7** [wso2/docs-apim#5624]
**Description:**
When we search WSO2 APIM in google and if we click the `Overview - WSO2 API Manager Documentation 4.1.0` it gives a page not found error.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/40932779/162982608-7fffe97f-8f75-4858-80a5-fd4ee598cbe4.png">

<img width="966" alt="image" src="https://user-images.githubusercontent.com/40932779/162982685-254ef677-8d38-4eb7-8e0d-7592b7c52b71.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
All 4.0.x links are now redirected to their respective pages in the latest documentation. Closing this as a result.
