### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by zhucj1028** [wso2/docs-apim#5626]
Location : https://apim.docs.wso2.com/en/latest/use-cases/examples/streaming-examples/publish-kafka-in-json-format/

![image](https://user-images.githubusercontent.com/46625432/163300865-fac13b9f-b785-4b11-8fc3-83cbb8188016.png)

ERROR ：Break points can only be applied for from or query output(insert, delete, update, update or insert into) statements

What is the reason for this, here is the example you provided

**Comment by Mariangela** [comment]
@senthuran16 , please provide feedback in this regard.

**Comment by Mariangela** [comment]
I am assuming that these changes are applicable to 4.0.0 as well. I have added the changes to 4.0.0 via the above PR. After the latter mentioned PR is merged I will send the fix to the other respective branches.

**Comment by Mariangela** [comment]
@zhucj1028 , it will be good if you can join us via WSO2's official Slack channels for better communication. 
WSO2's official Slack channel allows you to directly talk to our developers regarding issues or concerns about the products and also get feedback faster.

[wso2-apim.slack.com](https://wso2-apim.slack.com/) : [Join](https://join.slack.com/t/wso2-apim/shared_invite/enQtNzEzMzk5Njc5MzM0LTgwODI3NmQ1MjI0ZDQyMGNmZGI4ZjdkZmI1ZWZmMjNkY2E0NmY3ZmExYjkxYThjNzNkOTU2NWJmYzM4YzZiOWU?src=sidebar)
