### ISSUE TITLE
wrong port in example 

### ISSUE THREAD

**Issue by lpastor74** [wso2/docs-apim#5632]
**Description:**

on location 
https://apim.docs.wso2.com/en/latest/tutorials/integration-tutorials/sending-a-simple-message-to-a-service/#send-the-client-request

url is  http://localhost:8290/healthcare/querydoctor/surgery
by default is http://localhost:**8280**/healthcare/querydoctor/surgery

**Affected Product Version:**

documentation for v 4.1

**Comment by Nirothipan** [comment]
By default Micro Integrator starts with offset of 10, and so this should be 8290, the current one is correct AFAIU and I see the same in the embedded video.

**Comment by Mariangela** [comment]
Hi @lpastor74 , 

Based on @Nirothipan's comment it appears that the content in the documentation is correct. 
Therefore, I will be closing this issue.

Regards,

Mariangela Hills
