### ISSUE TITLE
Need to update doc to match the latest changes

### ISSUE THREAD

**Issue by chanaka3d** [wso2/docs-apim#5636]
**Description:**
The following document describes the compliance is only available for devportal. But from update level 86 onwards the same is true for publisher portals as well.

https://apim.docs.wso2.com/en/3.2.0/reference/accessibility-compliance/

**Affected Product Version:**
3.2.0 - update level 86

**Comment by Mariangela** [comment]
@chanaka3d , is this change applicable to any of the versions newer than 3.2.0, namely 4.0.0, 4.1.0 and 4.2.0?

**Comment by Mariangela** [comment]
@tmkasun , is this change applicable to 4.0.0, 4.1.0 and 4.2.0 docs?

**Comment by samgnaniah** [comment]
This is for 3.2.0 only.
