### ISSUE TITLE
The steps order is not clear in the section Develop an Integration From a Managed API

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/docs-apim#5655]
**Description:**
Step 6 [1], of this, asks to restart the APIM server. But I couldn't find that we stopped the server in a previous step. Also, it says "Start the API Manager runtime before starting the Micro Integrator". Since we didn't stop the APIM server before, we can just start the Micro Integrator by skipping Step 6.

We need to verify whether it is fine to remove Step 6 from this doc, by discussing with the feature owners

[1] https://apim.docs.wso2.com/en/4.1.0/tutorials/develop-an-integration-with-a-managed-api/#step-6-start-the-api-manager-runtime

**Comment by Mariangela** [comment]
@chashikajw , please share your input with regard to Wasura's comments.

**Comment by chashikajw** [comment]
Yes It is better to remove  step 6.
