### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by philipbarwi** [wso2/docs-apim#5695]
Location : https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410/

"If you have enabled any other feature related configurations at <API-M_4.1.0_HOME>/repository/conf/deployment.toml, make sure to add them in to <API-M_4.1.0_HOME>/repository/conf/deployment.toml file."

Should be 
"If you have enabled any other feature related configurations at <API-M_4.0.0_HOME>/repository/conf/deployment.toml, make sure to add them in to <API-M_4.1.0_HOME>/repository/conf/deployment.toml file."

**Comment by Mariangela** [comment]
Hi @philipbarwi ,

Thank you for reporting this doc issue. We have fixed this issue via the above mentioned PRs.
Regards,

Mariangela Hills
