### ISSUE TITLE
Tutorial Configure LDAP as Secondary User store is missing instructions

### ISSUE THREAD

**Issue by lianescafarate** [wso2/docs-apim#5765]
**Description:**
When trying to follow the instructions of tutorial https://lms.wso2.com/courses/take/wso2-api-manager-developer-fundamentals-v4-0/pdfs/25437384-practical-exercise-configure-ldap-as-secondary-user-store you cannot connect to the LDAP with the example information provided on the version 5.

I suggest to add extra steps on the tutorial to configure an LDAP server for completing this exercise.

**Affected Product Version:**
WSO2 API Manager 4.0.0

**OS, DB, other environment details and versions:**   
OS: MacOS Monterey version 12.3.1
WSO2 API Manager 4.0.0
WSO2 Identity Manager 5.11.0

**Steps to reproduce:**
After adding the new user store (step number 5) , when you try to list the users on the new domain, you'll likely see the following error:
"Error while listing users. Error: LDAP connection circuit breaker is in open state for 1555ms and has not reach the threshold timeout: 120000ms, hence avoid establishing the LDAP connection."

Also, if you try to add the new user (step number 6). you'll likely see the following error:
"Error while loading roles. Error: Error occurred while retrieving the userId of domain: <<name of your domain>> and propertyuid: <<name of your user>>"

**Possible solution:**
- Install WSO2 Identity Server
- Run it on a different port (offset 1)
- Access the file user-mgt.xml to check information regarding your LDAP server (Path: IS_HOME/repository/conf)
- Check user, password and usersearchbase data.
- Access your Api Manager console and add a new user store
- Fill out the information:
1) Domain name (e.g. employees)
2) Connection URL: ldap://localhost:10390
3) Connection name: uid=admin,ou=system //this information should be available on the user-mgt.xml file
4) Connection password: (e.g. admin) //this information should be available on the user-mgt.xml file
5) User Search Database: (e.g. ou=Users,dc=wso2,dc=org) //this information should be available on the user-mgt.xml file
6) User Entry Object Class: identityPerson
You don't need to change the following fields. Click on update and try to list/add the users again selecting your domain.

**Comment by npamudika** [comment]
Thanks @lianescafarate for the suggestions.

We have updated both APIM 4.0.0 and 4.1.0 training materials adding the steps to use WSO2 IS embedded LDAP as the secondary user store for API Manager.
