### ISSUE TITLE
[APIM-4.0.0][APICTL]-Wrong APICTL version is being downloaded for APIM-4.0.0

### ISSUE THREAD

**Issue by saranki** [wso2/docs-apim#5793]
**Description:**
In the [https://wso2.com/api-management/previous-releases/](https://wso2.com/api-management/previous-releases/ ) if we select the APIM version as **4.0.0** and download the APICTL tool, it is getting downloaded as **apictl-3.2.6-[OS]**. The APIM 4.0.0 doesn't support the previous versions of APICTL. Therefore, this has to be updated with the correct APICTL version packs. 

The correct apictl packs for APIM-4.0.0 are available at,
[1] https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller/#download-and-initialize-the-apictl
[2] https://github.com/wso2/product-apim-tooling/releases/tag/v4.0.0

**Affected Product Version:**
wso2am-4.0.0

**Steps to reproduce:**
1. Go to 
2. Select "Previous Releases" and select 4.0.0 for the APIM version
3. Click on tooling and click the relevant OS.
4. The downloaded pack will be **apictl-3.2.6-[OS]**.

**Comment by Mariangela** [comment]
The marketing team has been made aware of this issue via an email [1]. We will update this ticket as soon as the Marketing team reverts to us after making the fix in this regard.

Email: "Request to correctly update the APICTL 4.0.2 release artifacts in the website"

**Comment by wasuradananjith** [comment]
The artifacts are correctly updated by the Marketing team now. Hence, closing the issue.
