### ISSUE TITLE
Broken links on MI config catalog page

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-apim#5808]
**Description:**

The following links on the [Integration Server Configurations](https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi/#integration-server-configurations) page is not working,

- [using HashiCorp sercrets](https://apim.docs.wso2.com/en/latest/setup/security/using-hashicorp-secrets). should be https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/security/using-hashicorp-secrets/

- [installation and setup](https://apim.docs.wso2.com/setup/install_and_setup_overview) should be https://apim.docs.wso2.com/en/latest/install-and-setup/install-and-setup-overview/
- [external user store](https://apim.docs.wso2.com/en/4.1.0/install-and-setup/setup/mi-setup/setup/user_stores/setting_up_a_userstore).
- [RDBMS user store](https://apim.docs.wso2.com/en/4.1.0/install-and-setup/setup/mi-setup/setup/user_stores/setting_up_ro_ldap/#configuring-an-rdbms-user-store-optional).
- [configuring user stores](https://apim.docs.wso2.com/en/4.1.0/install-and-setup/setup/mi-setup/setup/user_stores/setting_up_a_userstore) should be https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/user_stores/setting_up_a_userstore/
- [securing the Management API](https://apim.docs.wso2.com/en/latest/setup/security/securing_management_api). should be https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/security/securing_management_api/
- [message builder](https://apim.docs.wso2.com/en/latest/setup/message_builders_formatters/message-builders-and-formatters) should be https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/message_builders_formatters/message-builders-and-formatters/
- [message formatting](https://apim.docs.wso2.com/en/latest/setup/message_builders_formatters/message-builders-and-formatters) should be https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/message_builders_formatters/message-builders-and-formatters/
- [tuning the default HTTP/S passthrough transport](https://apim.docs.wso2.com/en/latest/setup/performance_tuning/http_transport_tuning)
- [default HTTP/S passthrough transport in blocking mode](https://apim.docs.wso2.com/en/latest/setup/transport_configurations/configuring-transports/#configuring-the-httphttps-transport). should be https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports/#configuring-the-httphttps-transport
- [HTTP proxy profiles](https://apim.docs.wso2.com/en/latest/setup/configuring_proxy_servers/#configuring-proxy-profiles-in-wso2-micro-integrator)
- [VFS transport](https://apim.docs.wso2.com/en/latest/setup/transport_configurations/configuring-transports/#configuring-the-vfs-transport). should be https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports/#configuring-the-vfs-transport
- [MailTo transport](https://apim.docs.wso2.com/en/latest/setup/transport_configurations/configuring-transports/#configuring-the-mailto-transport) should be https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports/#configuring-the-mailto-transport

Most of the remaining transport related links on this page were also broken

**Comment by DinithiDiaz** [comment]
This issue has been addressed and resolved via https://github.com/wso2-enterprise/wso2-mi-internal/issues/18.
