### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#5810]
**Description:**

On this page:

  [https://apim.docs.wso2.com/en/3.2.0/learn/analytics/configuring-apim-analytics](https://apim.docs.wso2.com/en/3.2.0/learn/analytics/configuring-apim-analytics/#:~:text=WSO2%20API%20Manager%20Analytics%20provides,detailed%20analysis%20of%20the%20logs.)/

In the note that starts: "In your deployment, if the average TPS is more than 500", there is a link to:

  https://apim.docs.wso2.com/en/3.2.0/assets/attachments/persisted-aggr-mods/APIM_ACCESS_SUMMARY.siddhi

Which gives a 301 redirect to the location: 

  https://apim.docs.wso2.com/en/3.2.0/assets/attachments/persisted-aggr-mods/api-m_access_summary.siddhi

Which returns a 302 to:

  https://apim.docs.wso2.com/en/latest/page-not-found

**Comment by Mariangela** [comment]
On initial investigation it shows that the file is present, but the link is breaking as the file name is in caps. @lasanthaS , is it mandatory that this file is named in uppercase? If yes, then we will have to go with one of the following options:

1) ZIP the file so that when they unzip the file they have the file as it is.
2) Tell them to rename the file after downloading it.

I think, option (1) may be a better option. Please let me know your thoughts.

[1] https://github.com/wso2/docs-apim/tree/3.2.0/en/docs/assets/attachments/persisted-aggr-mods

**Comment by lasanthaS** [comment]
@Mariangela Let's allow this file to have the name in uppercase, as it won't be good to ask the user to rename or download a zip and extract.

**Comment by Mariangela** [comment]
I had a discussion with Lakindu and he added a rule to allow this [1] file, so now the link does not break.

[1] https://apim.docs.wso2.com/en/3.2.0/assets/attachments/persisted-aggr-mods/APIM_ACCESS_SUMMARY.siddhi

**Comment by Mariangela** [comment]
I checked and this attachment is not applicable to other doc versions.
