### ISSUE TITLE
Documentation Error in WSO2 API Manager Developer Fundamentals - V4.0 - API Management Profile

### ISSUE THREAD

**Issue by tadbow** [wso2/docs-apim#5835]
**Description:**
Given curl commands do not match what is need to get command to work correctly.
-In the Using Published API Practice Exercise
   -Page 5 step #9
   The curl command appears as below:
**curl** -k -H "Authorization: Bearer <access token>"-H"Content-Type: application/json" -X POST -d @data.jsonhttps://127.0.0.1:9443/api/am/publisher/v2/apisM

After review the v2 should actually be v3.  Once running with the correct parameters the command worked.

Also found later in the exercise some steps v2 worked when v3 did not work.

**Comment by npamudika** [comment]
For APIM 4.0.0 the correct versions of publisher and devportal rest APIs are v2 and v2 and for APIM 4.1.0 they are v3 and v2. Corrected all the places in the APIM 4.1.0 practical by modifying the version to v3 for publisher rest API.

**Comment by npamudika** [comment]
This is fixed in both APIM 4.0.0 and APIM 4.1.0 training materials.
