### ISSUE TITLE
<APIM_ANALYTICS_WORKER_HOME> missing in WSO2 API Manager Developer Fundamentals - V4.0 - API Management Profile

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/docs-apim#5882]
**Description:**

Could not find the directory <APIM_ANALYTICS_WORKER_HOME> which is mentioned in the tutorial WSO2 API Manager Developer Fundamentals - V4.0 - API Management Profile - [Practical Exercise: Managing Alerts with Real-Time Analytics](https://lms.wso2.com/courses/take/wso2-api-manager-developer-fundamentals-v4-0/pdfs/25437409-practical-exercise-managing-alerts-with-real-time-analytics)

**Comment by npamudika** [comment]
This is fixed in the APIM 4.1.0 practical exercise doc (APIM 4.1.0 Practical Exercise_Managing Alerts)

**Comment by npamudika** [comment]
This is fixed in APIM 4.0.0 training material as well.
