### ISSUE TITLE
key generation issue

### ISSUE THREAD

**Issue by asatiratnesh** [wso2/docs-apim#599]
After deployment of wso2 API manger 3.0.0 on the production server getting error for generating keys for application, it's working fine on local environment (localhost):

Below error is occure:

ERROR {org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl} - Error while generating keys for application f4178046-766f-483e-a5fb-a9988a2ff06e org.wso2.carbon.apimgt.api.APIManagementException: org.wso2.carbon.apimgt.impl.workflow.WorkflowException: Error occurred while executing SubscriberKeyMgtClient

suggest solution for key manager configuration on develyment.toml file to the production server.

**Comment by Mariangela** [comment]
@tharindu1st , please comment on this Git issue.

**Comment by tharindu1st** [comment]
Hi @asatiratnesh ,

Could you please provide the full log stack trace in order to give quick solution ?.

**Comment by Mariangela** [comment]
Hi @asatiratnesh,
As there has not been any response from you over the past 4 months after a WSO2 SME messaged in this regard, I am going to close this Git issue.

Please do feel free to re-open this Git issue if you are still facing an issue in this regard.
