### ISSUE TITLE
Doc Feedback: Left navigation arrows

### ISSUE THREAD

**Issue by nuwanbando** [wso2/docs-apim#6]
Location : https://apim.docs.wso2.com/en/next/Learn/APIPublish/create-and-Publish-an-API/

Left navigation expansion arrows can be moved to left - https://www.dropbox.com/s/oyd508h0ul0nwsv/Screenshot%202019-07-30%2011.41.28.png?dl=0

**Comment by Mariangela** [comment]
@erangatl , can you please provide your feedback in this regard.

**Comment by Mariangela** [comment]
@nuwanbando , can you please resend the image as the dropbox link results in a 404
