### ISSUE TITLE
Doc Feedback: Wrong statement on data format of error responses

### ISSUE THREAD

**Issue by dulanjal** [wso2/docs-apim#6040]
Location : https://apim.docs.wso2.com/en/latest/troubleshooting/error-handling/

AFAIK following statement is wrong with the APIM 4.x versions:
"When errors/exceptions occur in the system, the API Manager throws XML-based error responses to the client by default."

APIM returns error responses in JSON. Please check and update the 4.x documents accordingly.

**Comment by samgnaniah** [comment]
This is fixed now,.
