### ISSUE TITLE
Rest API version should be v0.15 in the APIM 3.0.0 documetaion

### ISSUE THREAD

**Issue by rizmir22** [wso2/docs-apim#607]
**Description:**
The APIMonetization documentation [1] has a cURL command at point 1 of the 4th step to get the Client ID and the Client Secret.
In that cURL command is mentioned as v0.14. But this version is incompatible with APIM 3.0.0 and it should be v0.15.

https://apim.docs.wso2.com/en/latest/Learn/APIMonetization/monetizing-an-api/#disable-monetization

**Suggested Labels:**
APIM , 3.0.0

**Suggested Assignees:**

**Affected Product Version:**
3.0.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Fixed in pls approve and merge https://github.com/wso2/docs-apim/pull/708
