### ISSUE TITLE
Add migration configs for IS-KM 5.10.0 to IS 5.11.0 migration

### ISSUE THREAD

**Issue by binodmx** [wso2/docs-apim#6071]
## Description:
While migrating a setup APIM 3.1.0 and IS-KM 5.10.0 as km to a setup APIM 4.1.0 and IS 5.11.0 as km, there are 2 scenarios to fail the migration giving `org.wso2.carbon.user.core.UserStoreException: 30012 - RoleExistingRole name` error. (This happens only when IS migration is done separately before the APIM migration as in [docs](https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110/).)

1. When there is an admin role of same name in both `Internal` and `Primary` domains. 
2. When the `create_admin_account=false` config is not added to deployment.toml.

### Fix for case 1
Mention following steps to do before the migration.

1. Download the [wso2is-migration-1.0.192.zip](https://github.com/wso2-extensions/identity-migration-resources/releases/download/v1.0.192/wso2is-migration-1.0.192.zip)
2. Add the following line to the deployment.toml of the 5.11.0 pack.
```
[super_admin]
admin_role = "<<NEW-ADMIN-ROLE-NAME>>"
create_admin_account = false
```
3. Then in the migration client need to add the admin role name of the current version to the parameter `currentAdminRoleName` under the `GroupsAndRolesMigrator`
```
name: "GroupsAndRolesMigrator"
 order: 4
 parameters:
    currentAdminRoleName: "<<CURRENT-ADMIN-ROLE_NAME>>"
```

### Fix for case 2
Mention specifically to add following config to deployment.toml before the migration.

```
[super_admin]
create_admin_account = false 
```

**Comment by samgnaniah** [comment]
This seems to be fixed so I'm closing this. Please reopen if that is not the case.
