### ISSUE TITLE
Fix the documentation to refer to the APIM IS migration client during IS as KM migration

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/docs-apim#6090]
**Description:**
Our migration document currently points to the IS documentation to run the IS migration for the IS as KM scenario. Hence the users will be using the IS migration client for the purpose. This needs to be fixed to refer to the APIM IS migration client.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeepoornima** [comment]
Hi Team,

This issue can see on both APIM 400 and 410 documents. Please fix both doc spaces. 

Thanks,
Nadee

**Comment by tharikaGitHub** [comment]
Hi Nadee,

    This is not affecting 4.1.0 as the documentation correctly points to the APIM identity migration client. So we will be fixing this in 4.0.0 docs.

Thanks,
Tharika

**Comment by tharikaGitHub** [comment]
Closing this issue as the fix is merged.
