### ISSUE TITLE
[APIM 3.2.0] - Update doc on added feature

### ISSUE THREAD

**Issue by inuri2000** [wso2/docs-apim#6109]
**Description:**
Enabling per api logging feature was front ported to APIM 3.2.0 from APIM 3.1.0 [1]. The 3.2.0 documentation needs to be updated with this added features similar to [1]. 

[1]  https://apim.docs.wso2.com/en/3.1.0/administer/logging-and-monitoring/logging/setting-up-logging-per-api/

**Suggested Labels:**
apim

**Affected Product Version:**
3.2.0 

**Related Issues:**
https://github.com/wso2/api-manager/issues/119

**Comment by inuri2000** [comment]
HI Team,
Kind reminder on this.

Thankyou,
Inuri.

**Comment by inuri2000** [comment]
Hi @ruthryi ,
As discussed offline a few weeks ago, the rendering issue on the doc is still not working as expected,
![image](https://user-images.githubusercontent.com/31123177/187117599-2efcc443-d80e-437a-936d-bf142b438e36.png)
Appreciate if you could kindly look into this at your earliest convenience as customers are struggling to use the feature without the proper documentation. 

Thankyou,
Inuri.

**Comment by shavinsenadheera** [comment]
Hi @ruthryi,

It seems this page [1] is still not working as expected. Highly appreciate it if you could look into this.

[1] - https://apim.docs.wso2.com/en/3.2.0/administer/logging-and-monitoring/logging/setting-up-logging-per-api/

Thanks & Regards,
Shavindu
