### ISSUE TITLE
[URGENT] Doc Feedback: All the links pointed to REST API Specs are broken

### ISSUE THREAD

**Issue by pandulakb** [wso2/docs-apim#6210]
Location : https://apim.docs.wso2.com/en/latest/reference/product-apis/overview/
Location : https://apim.docs.wso2.com/en/4.0.0/reference/product-apis/overview/

All the links pointed to REST API Specs are broken.
Please fix this with highest priority, as customer is waiting for these specs.

**Comment by ruthryi** [comment]
Closing this, since it was not reproduced. Both pages/links are working.

Thanks,
Ruthryi
