### ISSUE TITLE
WSO2 API Manager 3.0.0 - Integration with third party Authorization Server

### ISSUE THREAD

**Issue by igkononov** [wso2/docs-apim#622]
Hello,
To whom it may concern,

Please, can you help me.
In WSO2 API Manager 3.0.0 there is now explanations or examples about possible ways for adding integration API Manager 3.0.0 with third party Authorization Server (e.g. Auth0).

Can you add this information to documentation?

Thanks in advance

**Comment by tgtshanika** [comment]
Hi @igkononov,

In API Manager, it is possible to plug an external IDP as a key manager using extension points. But unfortunately, the documentation with the sample IDP integration extension is under maintenance. We are in the process of updating the document with relevant sample implementation and will update this issue once the documentation is live.

**Comment by chamilaadhi** [comment]
@igkononov you could find sample integration with Okta in https://github.com/wso2-extensions/apim-keymanager-okta/tree/OKTA-OAuth-Client-2.0.0

**Comment by Mariangela** [comment]
This link is now available in [1].

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/deploying-wso2-api-manager/distributed-deployment/configure-a-third-party-key-manager/
