### ISSUE TITLE
Documentation issue: Amazon SQS Connector

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/docs-apim#6272]
We were trying to send messages to the FIFO queues using the WSO2 SQS connector. 

As instructed in the latest wso2 connector doc[1], We were testing by configuring the version to **2009-02-01** at the connector init operation.

Then we onserved the following issue although we have set the **messageGroupId** property at the send operation.
{
   "ErrorResponse":{
      "Error":{
         "Type":"Sender",
         "Code":"MissingParameter",
         "Message":"The request must contain the parameter MessageGroupId.",
         "Detail":null
      },
      "RequestId":"09321846-df42-5c15-8cb1-43db57d8860a"
   }
}

Then we test the issue by configuring the version as 2012-11-05[2] at the init operation of the SQS connector. Then we were able to successfully send the message

We could see that it has instructed us to use 2012-11-05 as the version when using FIFO queues in the previous wso2  SQS connector docs[3]. 

Therefore, could you please take the necessary actions to correct this documentation gap to avoid this kind of issue in the future?

[1] https://apim.docs.wso2.com/en/latest/reference/connectors/amazonsqs-connector/amazonsqs-connector-config/

[2] https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/Welcome.html

[3] https://docs.wso2.com/display/ESBCONNECTORS/Working+with+Messages+in+Amazon+SQS#WorkingwithMessagesinAmazonSQS-sendMessage

**Comment by samgnaniah** [comment]
This is fixed now as per the internal ticket. Please reopen if something else needs to be done here.
