### ISSUE TITLE
[Migration-Doc] - Issue with Oracle script provided for APIM component migration.

### ISSUE THREAD

**Issue by inuri2000** [wso2/docs-apim#6279]
**Description:**
HI Doc team,
This issue was discussed on [1], please refer if needed.

**Change  1:** 
The oracle script provided in APIM 2.6.0 - 3.2.0 [2]  is dropping the primary key of  AM_API_COMMENTS table and adding it back but not as a primary key. This is failing migrations when customers try to migrate to later versions. 

```
ALTER TABLE AM_API_COMMENTS
DROP COLUMN COMMENT_ID
/

ALTER TABLE AM_API_COMMENTS
ADD COMMENT_ID VARCHAR(255) DEFAULT (SYS_GUID()) NOT NULL
/
```
Hence, we need to add the below command to the script [2]  too.
```
ALTER TABLE AM_API_COMMENTS
    ADD CONSTRAINT add_pk PRIMARY KEY (COMMENT_ID)
/
```
**Change 2:**
We also noticed that the same is done for AM_API_RATINGS  tables too. Hence this below command should be added to the oracle script of both documents [2] and [3] .

```
ALTER TABLE AM_API_RATINGS
    ADD CONSTRAINT add_pk PRIMARY KEY (RATING_ID)
/
```

Thankyou,
Inuri.

[1] https://github.com/wso2-enterprise/wso2-apim-internal/issues/717

[2] https://apim.docs.wso2.com/en/3.2.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320/#step-2-upgrade-api-manager-to-320
[3] https://apim.docs.wso2.com/en/4.0.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400/#step-3-migrate-api-m-database

**Suggested Labels:**
priority/High

**Comment by samgnaniah** [comment]
Fixed.
