### ISSUE TITLE
Instructions to run profile optimization missing in the distributed deployment guide doc

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/docs-apim#6304]
**Description:**

In this https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/product-profiles/#method-2-optimizing-while-starting-the-server section, You won't be able to start the nodes by just copy and paste the given command. It will throw errors and some nodes won't even start. You need to run the profile optimizer first and that instruction is missing in this section.

Add something similar to below at the start of this section 
```
Run profile optimization for each node as mentioned in https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/distributed-deployment/product-profiles/ before starting the server. Back up the deployment.toml before running the optimizer and replacing it once optimization is completed.
```

This needs to be fixed in both docs in both 4.0.0 and 4.1.0

https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated/#step-7-start-the-api-m-nodes

https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/#step-7-start-the-api-m-nodes

**Comment by rmsamitha** [comment]
@chamilaadhi This [method-2 ](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/product-profiles/#method-2-optimizing-while-starting-the-server) is intended to start the servers while profile-optimizing the server pack. In the doc page it has mentioned as below.
![image](https://github.com/wso2/docs-apim/assets/2484781/f5e1a8c3-5d7c-4381-a1c3-ca3bf5412a2b)

And the command you have to run is:
sh <PRODUCT_HOME>/bin/api-manager.sh --optimize -Dprofile=<preferred-profile> --skipConfigOptimization

 Option "--skipConfigOptimization" will ensure, the maually done configs will not be overridden by optimization process which is triggered by --optimize option.

**Comment by rmsamitha** [comment]
I am closing this issue based on above comment and please reopen or reply-back if further confusions exists.
