### ISSUE TITLE
Add missing registry indices db script to documentation

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/docs-apim#6315]
Add missing indices 
- REG_RESOURCE_TAG_IND_BY_REG_TAG_ID to REG_RESOURCE_TAG
- REG_RESOURCE_PROPERTY_IND_BY_REG_PROP_ID to REG_RESOURCE_PROPERTY

related: https://github.com/wso2/carbon-kernel/pull/3169

**Comment by samgnaniah** [comment]
Closing this as we have merged the associated PR.
