### ISSUE TITLE
[APIMv4.1] Images are not rendering

### ISSUE THREAD

**Issue by dinusha92** [wso2/docs-apim#6322]
**Description:**

In VFS transport parameters documents, the images are not getting rendered.
https://apim.docs.wso2.com/en/latest/reference/synapse-properties/transport-parameters/vfs-transport-parameters/

But the same thing is available on EI 7.2.0 https://ei.docs.wso2.com/en/7.2.0/micro-integrator/references/synapse-properties/transport-parameters/vfs-transport-parameters/

Can you please fix it on APIM 4.1.0 ?

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Fixed with the above PRs.
