### ISSUE TITLE
[APIM 4.1.0] - Upgrading from ESB to MI Documentation issue

### ISSUE THREAD

**Issue by inuri2000** [wso2/docs-apim#6323]
**Description:**
HI Team,
In the "Migrating from WSO2 ESB 5.0.0 to WSO2 API-M 4.1.0" documentation [1] , under the "Migrating user stories" section, 
There is a link to database migration scripts under step 1 of this section and that link seems to be broken. It is redirecting to "Page not found". 

Kindly look into this at your earliest convenience.

Thankyou,
Inuri.
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-from-wso2-ei/upgrading-from-esb-5.x.x/#migrating-the-user-store
**Suggested Labels:**
API-M-4.1.0

**Comment by samgnaniah** [comment]
This is fixed now.
