### ISSUE TITLE
Monetization Doc Changes

### ISSUE THREAD

**Issue by ramindu90** [wso2/docs-apim#6356]
**Description:**
I followed the [monetization](https://apim.docs.wso2.com/en/latest/design/api-monetization/monetizing-an-api/) and noticed the following as the needed improvements/ corrections so that it is easy to follow. And some of the information are invalid with Stripe UIs as well. 

In https://apim.docs.wso2.com/en/latest/design/api-monetization/monetizing-an-api/

In https://apim.docs.wso2.com/en/latest/design/api-monetization/monetizing-an-api/#monetize-an-api in "Let's use the [wso2-am-stripe-plugin](https://github.com/wso2-extensions/wso2-am-stripe-plugin/releases/download/v1.3.1/org.wso2.apim.monetization.impl-1.3.1.jar) to monetize an API in the following example scenario." Lets mention in a `Note` that this scenario can be tried out using `test data` by turning on the toggle button 
![Screenshot 2022-10-19 at 12 18 54 PM](https://user-images.githubusercontent.com/10056966/196617212-afff7bd5-84ea-4a0c-ac46-dfbafb0fd006.png)

Some information can be changed/ improved in `(A) - Configure the billing engine`.   

`1) Create an account for the Tenant Admin.`
  b) Click on Developers > API keys > Reveal test key to obtain the keys. For more information refer to [Obtain the keys](https://stripe.com/docs/keys#api-keys)
![Screenshot 2022-10-20 at 9 35 42 AM](https://user-images.githubusercontent.com/10056966/196854027-21d9e404-4236-43fd-a1a7-f2f6923f32a4.png)
`3) Enable Connect and create a [connected account](https://stripe.com/docs/connect/quickstart#create-account) in Stripe.`
 a.0) Click on settings and then select `connect` section `settings`
![Screenshot 2022-10-20 at 9 15 30 AM](https://user-images.githubusercontent.com/10056966/196851914-39a113b0-ef73-4f48-a9a0-74b9796e94dd.png)
 a.1) edit `Appearance` section in Branding section and click on "Save Branding Changes"
![Screenshot 2022-10-19 at 12 33 09 PM](https://user-images.githubusercontent.com/10056966/196620354-fb95be77-3bf4-4c89-a7ce-fc60d8006097.png)
 b) `enable OAuth for Standard Accounts` by scrolling further more
![Screenshot 2022-10-19 at 12 28 26 PM](https://user-images.githubusercontent.com/10056966/196619017-df4217f2-4d77-42cf-9482-7d896c27fe21.png)
 c) Click `connect` and then click on `Create`
![Screenshot 2022-10-19 at 12 20 02 PM](https://user-images.githubusercontent.com/10056966/196617353-a409d929-3d90-4033-b4a4-33aa10b3341f.png)
 d) Continue
![Screenshot 2022-10-19 at 12 29 10 PM](https://user-images.githubusercontent.com/10056966/196619127-565954ff-de8a-43c5-9a89-744e1bfd0d29.png)
 e) copy the URL pops up next in
![Screenshot 2022-10-19 at 12 30 12 PM](https://user-images.githubusercontent.com/10056966/196619341-31f31319-5ca1-48d0-894a-7d61019148f5.png)
 f) Enter it in the browser to onboard the application and click on `skip this form` if you are on `test mode`
![Screenshot 2022-10-19 at 12 31 01 PM](https://user-images.githubusercontent.com/10056966/196619666-a1dffae0-cacf-4723-b58b-9e10a3cf20a4.png)
 g) Refresh https://dashboard.stripe.com/test/connect/accounts/overview to see the newly created account
![Screenshot 2022-10-19 at 12 36 59 PM](https://user-images.githubusercontent.com/10056966/196620540-b6dd3bb3-3e6d-4f03-bbb6-d0e519aadb13.png)

Some information can be changed/ improved in `(B) - Configure WSO2 API Manager`

4) Optionally, configure WSO2 API Manager to work with Choreo Analytics.
 a) Enable analytics by referring to https://apim.docs.wso2.com/en/latest/api-analytics/getting-started-guide/#step-2-register-your-environment
 b) Can add an additional note which says `analytics_access_token` is the one generated in the step `a` 

In `Step 1 - Create a subscription policy` Better if we can give them a sample configuration as well for `2` then its easier to go with the flow.
 2) Create a subscription policy.
![Screenshot 2022-10-19 at 1 04 53 PM](https://user-images.githubusercontent.com/10056966/196626604-d5dc71d6-e10b-451f-98fd-9c6d9ec7f71c.png)

In `Step 2 - Enable monetization`
 3) << This step is missing
     Click on **subscription** and select the policy created in `Create a subscription policy` and click **save**
![Screenshot 2022-10-19 at 1 16 09 PM](https://user-images.githubusercontent.com/10056966/196628713-13175f15-79db-402e-b096-bf319d9a7e37.png)
 
 5) Enter the connect ID as the connected account key and click Save. You could find the ConnectID: you could find the connect ID when you click on the created account. And simply click “Copy ID” when you click on the created account. And simply click “Copy ID”
![Screenshot 2022-10-19 at 1 09 07 PM](https://user-images.githubusercontent.com/10056966/196627191-95d3dd9c-e274-40f0-8b9d-f51af924dc9e.png)
 6) Additionally, if you refresh the page the policy section has to be shown as below << new step to verify
![Screenshot 2022-10-19 at 1 10 46 PM](https://user-images.githubusercontent.com/10056966/196627571-1969cddb-d51e-4729-a24f-35e45df449d6.png)

In `Step 4 - Send usage data to the billing engine`

 3) Publish usage data to the Stripe billing engine
      URL should be changed to https://localhost:9443/api/am/admin/v3/monetization/publish-usage. (v1 to v3)

**Comment by RusJaI** [comment]
Fixed this with PR : https://github.com/wso2/docs-apim/pull/6818
