### ISSUE TITLE
[2.x] Change host name docs typo

### ISSUE THREAD

**Issue by menakaj** [wso2/docs-apim#636]
**Description:**
In the **Change Host Name** doc page [1] , the second point should be corrected as follows

`
Open the <APIM_HOME>/repository/conf/api-manager.xml file and set the properties as shown below
`
[1] https://docs.wso2.com/display/AM210/Changing+the+Hostname
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM Docs 2.1.0, 2.2.0, 2.5.0, 2.6.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@npamudika , can you please share your feedback on this Git issue.

**Comment by npamudika** [comment]
The file name should be corrected as <APIM_HOME>/repository/conf/carbon.xml instead of <APIM_HOME>/repository/conf/api-manager.xml

**Comment by Mariangela** [comment]
Changed [1] to [2]. Did not change the file name based on Naduni's comment. This change was made in 2.1.0, 2.2.0, 2.5.0, 2.6.0


[1] Open the <API-M_HOME>/repository/conf/carbon.xml file and set the HostName and MgtHostName property  as shown below.
[2] Open the <API-M_HOME>/repository/conf/carbon.xml file  and set the following properties as shown below.

https://docs.wso2.com/display/AM210/Changing+the+Hostname
https://docs.wso2.com/display/AM220/Changing+the+Hostname
https://docs.wso2.com/display/AM250/Changing+the+Hostname
https://docs.wso2.com/display/AM260/Changing+the+Hostname
