### ISSUE TITLE
Doc Feedback: Not able to connect to www.mocky.io through devportal

### ISSUE THREAD

**Issue by parveen02** [wso2/docs-apim#638]
Location : https://apim.docs.wso2.com/en/latest/GettingStarted/quick-start-guide/

Hi,
I am testing the API publishing as given in this link using www.mocky.io but I have got stuck at "Step 3: Invoke the API". In 3rd step, I should have got json response as { "hello" = "world" } but I am getting below response. 
PS: I have already imported certification from https://localhost:8243/

<am:fault xmlns:am="http://wso2.org/apimanager">
  <am:code>101503</am:code>
  <am:type>Status report</am:type>
  <am:message>Runtime Error</am:message>
  <am:description>Error connecting to the back end</am:description>
</am:fault>

**Comment by Mariangela** [comment]
@tharindu1st , can you please comment on this Git issue.

**Comment by bhathiya** [comment]
We should use http instead https, in the QSG. @Mariangela shall we fix it please?

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/710 by changing the endpoint https://www.mocky.io/v2/5185415ba171ea3a00704eed to http://www.mocky.io/v2/5185415ba171ea3a00704eed
