### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by erangatl** [wso2/docs-apim#641]
**Description:**
https://apim.docs.wso2.com/en/next/Develop/ProductAPIs/restful-apis/

![image](https://user-images.githubusercontent.com/20179540/72249319-1f958480-361f-11ea-9d7b-586d4d373871.png)

**Comment by Mariangela** [comment]
@erangatl , this is related to 3.1.0. We will fix this.

**Comment by erangatl** [comment]
> @erangatl , this is related to 3.1.0. We will fix this.

3.1.0 docs are also visible to customers, [https://support.wso2.com/jira/browse/TMGDCSUB-15](url) and incomplete docs can lead them to confusions.

Is there a way to hide incomplete docs or shall we not publish them, until they are reviewed?

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/704
