### ISSUE TITLE
Documentation Gap on Adding an API to External Stores for APIM 4.2.0

### ISSUE THREAD

**Issue by piyumaldk** [wso2/docs-apim#6426]
**Description:**
In [our documentation for 4.1.0](https://apim.docs.wso2.com/en/latest/deploy-and-publish/publish-on-dev-portal/publish-to-multiple-external-api-stores/), in point 7, we give a sample of code to add as external-api-stores.xml. But if we follow the documentation and try to add an API to another devportal, in gives below error.
`Error while updating external developer portals!! [Internal server error] The server encountered an internal error. Please contact administrator. `

**Solution**
Since if we try to access the devportal using http, it gives below error,
```
Bad Request
This combination of host and port requires TLS.
```
We should update point 7's content as below changing http to https. After that, adding an API to an external devportal works fine as mentioned in the documentation.
```
<ExternalAPIStores>
    <StoreURL>https://localhost:9443/devportal</StoreURL>
        <ExternalAPIStore id="DeveloperPortal2" type="wso2" className="org.wso2.carbon.apimgt.impl.publishers.WSO2APIPublisher">
            <DisplayName>DeveloperPortal2</DisplayName>
            <Endpoint>https://localhost:9444/devportal</Endpoint>
            <Username>admin</Username>
            <Password>admin</Password>
        </ExternalAPIStore>
</ExternalAPIStores>
```

**Comment by Tharanidk** [comment]
Update 2023-02-15:

- Started working on the issue by installing the necessary packages.
- Fix is done.
