### ISSUE TITLE
Documentation on import/export throttling (rate limiting) policies should be revamped to be consistant with the apictl docs

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/docs-apim#6441]
**Description:**
The documentation on throttle policies in [1] should be completely revamped to match with other apictl documentation. Changes that need to be done are listed as follows.
- The main thing is, we should use the naming "Rate Limiting" instead of "throttling" in the topics of this documentation, because during the internal discussions we decided that (If you note the apictl commands you can see we have used "rate-limiting" not "throttling").
- The documentation should be moved to [2] under the topic "Manage Environments Using the CLI" because this feature is done mainly for apictl purposes. Hence, the overall documentation should be restructured in a format similar to what have done in [3] by creating a seperate section as "Manage Rate Limiting Policies" under "Manage Environments Using the CLI".
![image](https://user-images.githubusercontent.com/25246848/202086704-73474c01-3d04-4498-855e-4c119a0023c0.png)
- We do not need to mention the Admin REST APIs in the document because we usually have the REST API docs separately here [4]. Mentioning the GET, POST methods and their responses are completely redundant and breaks the consistency of apictl documentation.

[1] https://apim.docs.wso2.com/en/4.2.0/design/rate-limiting/throttle-policy-import-export/
[2] https://apim.docs.wso2.com/en/4.2.0/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller/
[3] https://apim.docs.wso2.com/en/4.2.0/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products/
[4] https://apim.docs.wso2.com/en/4.2.0/reference/product-apis/admin-apis/admin-v2/admin-v2/

**Comment by samgnaniah** [comment]
This is fixed now.
