### ISSUE TITLE
Documentation Gap on Add Custom Attributes to Applications for APIM 4.2.0 with Tenant-specific Configuration

### ISSUE THREAD

**Issue by piyumaldk** [wso2/docs-apim#6451]
**Description:**
In the 4.2.0 documentation, [this](https://apim.docs.wso2.com/en/4.2.0/consume/manage-application/advanced-topics/add-custom-attributes-to-applications/#:~:text=Enter%20/_system/config/apimgt/applicationdata/tenant%2Dconf.json%20in%20the%20navigation%20bar%20and%20click%20Go.) path has given but this is not available in 4.2.0 Management Console.

**Solution**
Instead doing step 3 and 4, we should add below configuration to the Advanced Configurations of the Admin Dashboard (After logged in as the right tenant). 

Example for configuration
```
"ApplicationConfigs": {
   "Attributes" : [
       {
           "Attribute" : "External Reference Number",
           "Required" : true,
           "Description" : "Sample description"
       },
       {
           "Attribute" : "Tenant Billing tier"
       }
   ]
}
```
We can found Advanced Configurations under the Advanced menu of the Admin Dashboard **[/admin/settings/advanced]**. After saving the config, you can see the newly added attributes will be shown in the DevPortal for the respective tenant.

**Comment by chamilaadhi** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/6792
