### ISSUE TITLE
Add instructions for adding registry configs

### ISSUE THREAD

**Issue by binodmx** [wso2/docs-apim#6526]
**Description:**
deployment.toml configs for configuring registry nested properties has been fixed in wso2am-3.2.0 and public branches. We have to update the migration docs according to this [comment](https://github.com/wso2-enterprise/wso2-apim-internal/issues/983#issuecomment-1316410785). Also, configuring registry properties in public is changed and we should update the docs according to this [comment](https://github.com/wso2-enterprise/wso2-apim-internal/issues/1092#issuecomment-1318036209).

**Comment by ThijsFTW** [comment]
Link to comments are broken (404).

**Comment by chamilaadhi** [comment]
This descripition is not clear enough. please provide more detail on what to add and where to add it
