### ISSUE TITLE
Documentation on OLTP Tracing under OpenTelemetry is not clear

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/docs-apim#6527]
**Description:**
More information with an example should be added to [1].

**Related Issues:**
- https://github.com/wso2/api-manager/issues/1118

[1] https://apim.docs.wso2.com/en/4.2.0/observe/api-manager/traces/monitoring-with-opentelemetry/#enabling-otlp-tracing

**Comment by shnrndk** [comment]
Since vendor specifications will change, adding this to our documentation is not very useful.
