### ISSUE TITLE
Documentation on URL mapping mediation policy is out dated

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-apim#6536]
**Description:**

The [Mapping the Parameters of your Backend URLs with the API Publisher URLs](https://apim.docs.wso2.com/en/4.2.0/design/api-policies/regular-gateway-policies/mapping-the-parameters-of-your-backend-urls-with-the-api-publisher-urls/) doc has old content with **message mediation**. We need to update the steps and screenshots with the new **API Policies** related steps.

**Comment by chamilaadhi** [comment]
@IsuruMaduranga . We will have to create a policy using the https://apim.docs.wso2.com/en/latest/design/api-policies/create-policy/ feature. Also URL for the backend provided in this doc is not working. it is available in https://github.com/wso2/docs-apim/blob/master/en/docs/assets/attachments/learn/APIGateway/MessageMediation/Response_API.xml
