### ISSUE TITLE
Unable to scroll down left side menu

### ISSUE THREAD

**Issue by chanaka3d** [wso2/docs-apim#6537]
**Description:**
The following URL's left menu items are not accessible with scrolling.

https://apim.docs.wso2.com/en/4.2.0/reference/product-apis/gateway-apis/gateway-v2/gateway-v2/#tag/Get-API-Info

bottom most items are hidden from the screen

https://user-images.githubusercontent.com/3424539/207856585-6f8c7a70-1639-4f7a-b0d8-99a0d84e58f0.mov

Version 108.0.5359.98 (Official Build) (arm64)
MAC OS Monetary
Version 12.4

**Comment by ruthryi** [comment]
The user has to collapse the first menu item to see the items below. Hence, closing this issue.
