### ISSUE TITLE
Making mandatory to add 'character set latin1' when making the APIM mysql 8 database

### ISSUE THREAD

**Issue by GihanAyesh** [wso2/docs-apim#6542]
**Description:**
Currently in the [Change to MySQL](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql/#:~:text=create%20database%20%3CDATABASE_NAME%3E%20character%20set%20latin1%3B) page, it shows in an info box that for Windows users it is required to add character set latin1 when creating the databases. However, for MySQL 8 it is necessary to add the part to create the apim_db database. 

**Solution:**
In the [Change to MySQL](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql/#:~:text=create%20database%20%3CDATABASE_NAME%3E%20character%20set%20latin1%3B) page, change the info box to warning box and inform that for MySQL 8 it is mandatory to add 'character set latin1'

For [Tested DBMSs](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/reference/product-compatibility/#tested-dbmss:~:text=8%20and%2011-,Tested%20DBMSs%C2%B6,-The%20WSO2%20API) page also this change need to be added which is already done to [IS documentation](https://is.docs.wso2.com/en/latest/deploy/environment-compatibility/#tested-dbmss:~:text=To%20use%20MySQL,character%20set%20latin1%3B)
_create database apim_db character set latin1;_

**Comment by Camille0183** [comment]
> **Description:** Currently in the [Change to MySQL](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql/#:~:text=create%20database%20%3CDATABASE_NAME%3E%20character%20set%20latin1%3B) page, it shows in an info box that for Windows users it is required to add character set latin1 when creating the databases. However, for MySQL 8 it is necessary to add the part to create the apim_db database.
> 
> **Solution:** In the [Change to MySQL](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql/#:~:text=create%20database%20%3CDATABASE_NAME%3E%20character%20set%20latin1%3B) page, change the info box to warning box and inform that for MySQL 8 it is mandatory to add 'character set latin1'
> 
> For [Tested DBMSs](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/reference/product-compatibility/#tested-dbmss:~:text=8%20and%2011-,Tested%20DBMSs%C2%B6,-The%20WSO2%20API) page also this change need to be added which is already done to [IS documentation](https://is.docs.wso2.com/en/latest/deploy/environment-compatibility/#tested-dbmss:~:text=To%20use%20MySQL,character%20set%20latin1%3B) _create database apim_db character set latin1;_
