### ISSUE TITLE
Remove related doc content when removing the deprecated profiles

### ISSUE THREAD

**Issue by rmsamitha** [wso2/docs-apim#6596]
**Description:**
Remove related doc content when removing the deprecated profiles (via https://github.com/wso2/api-manager/issues/967 )
In the docs, there are places mentioned on the deprecated profiles. They need to be removed too.

**Related Issues:**
Related to https://github.com/wso2/api-manager/issues/967

**Comment by Tharanidk** [comment]
Remove the note under the below section related to publisher and devportal.
![Screenshot from 2023-01-17 13-07-59](https://user-images.githubusercontent.com/42825038/212837369-dffa5c5b-0922-4ce8-9439-1fb95818c55a.png)

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/product-profiles/#profile-startup-commands

**Comment by Tharanidk** [comment]
Change the sample output related to another profile as the publisher is removed now.
![Screenshot from 2023-01-17 13-10-41](https://user-images.githubusercontent.com/42825038/212838046-7319caa0-24e7-43d7-8437-6fe52a0de193.png)

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/product-profiles/#method-2-optimizing-while-starting-the-server

**Comment by Tharanidk** [comment]
The first sentence in the Tip should be changed as the api-devportal profile is removed.
![Screenshot from 2023-01-17 13-18-00](https://user-images.githubusercontent.com/42825038/212839458-aa32c8ed-10d5-49fc-87bc-19bef907730a.png)

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/product-profiles/#running-the-api-m-profiles
