### ISSUE TITLE
[APIM 3.0] Whitelisting Host Names for API Store Documentation is not related

### ISSUE THREAD

**Issue by Prabhashi** [wso2/docs-apim#662]
**Description:**

In APIM 3.0 we are not doing hostname whitelisting as mentioned in this documentation[1]. Hence this[1] documentation is not related.

[1] https://apim.docs.wso2.com/en/next/Administer/ProductSecurity/whitelisting-host-names-for-api-store/

**Comment by Mariangela** [comment]
@tharindu1st , can you please share your views.

**Comment by tharindu1st** [comment]
+1 for removing since this was related to jaggery based store ui

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/709
