### ISSUE TITLE
Update documentation details for Third Party APIs

### ISSUE THREAD

**Issue by Tharanidk** [wso2/docs-apim#6628]
**Description:**
When creating a Third Party API, we cannot create third party Async APIs as mentioned in the documentation https://apim.docs.wso2.com/en/4.2.0/deploy-and-publish/publish-on-dev-portal/third-party-api-support/#creating-a-third-party-api.
It can also be done as same as rest APIs. the documentation details should be changed.

Also, change this bullet point to '2' (it should be number 2 as number 1 already exists).

**Affected Product Version:**
APIM 4.2.0

**Comment by Mariangela** [comment]
@Tharanidk , I have the following concerns:

1. Step 1 "A regular API ...." and step 2 "In addition to the streaming APIs......" do not sound like they are part of a sequence. It sounds like they are 2 methods in which 3rd party APIs can be created. Please clarify this.
2. If we cannot create third party Async APIs, it sounds like step 2 should be removed all together. OR are you trying to say that we can not create 3rd party Async APIs from scratch BUT we can only import it?
3. "You can use the new default property thirdParty to search for APIs that are from a third-party." This line sounds like it should be reworded and come under a section that says "Searching for Third party APIs".

@ruthryi , please incorporate the changes when @Tharanidk replies to this message.



[1] https://apim.docs.wso2.com/en/4.2.0/deploy-and-publish/publish-on-dev-portal/third-party-api-support/#creating-a-third-party-api

**Comment by Tharanidk** [comment]
Hi @Mariangela ,
1. Yes, they are two methods of creating 3rd party APIs, so can we add something like bullet points without adding numbers for this? 

2. Regarding the other point I had a call with @HeshanSudarshana there's nothing to fix because this document has mentioned creating Third party AsyncAPIs when importing a definition only. 

Thanks and Regards,
Tharani.
