### ISSUE TITLE
Some configurations not working as expected when configuring Federated SSO with OIDC 

### ISSUE THREAD

**Issue by BLasan** [wso2/docs-apim#6656]
Followed the doc mentioned below.
[1]https://apim.docs.wso2.com/en/latest/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-oidc/#configure-the-identity-server

**Comment by msm1992** [comment]
Following things should be updated in the doc.

1. In IS configurations,  include a step to add `groups` claim to `openid` OIDC claim.
<img width="350" alt="Screenshot 2023-02-08 at 14 27 43" src="https://user-images.githubusercontent.com/28379317/217482463-42e58b62-d543-4e44-95b3-cb1ebc13d591.png">

2. Step 3 under [configuring SP](https://apim.docs.wso2.com/en/4.2.0/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-oidc/#step-1-configure-the-service-provider) should be updated as below. Also update the screenshot accordingly.
```
Expand the Claim Configuration section. Add http://wso2.org/claims/groups as mandatory claim.
```
Under same step add a new instruction to map http://wso2.org/claims/username claim as the subject claim URI.

<img width="1217" alt="Screenshot 2023-02-08 at 14 33 10" src="https://user-images.githubusercontent.com/28379317/217483742-394cd660-69a0-4186-ac0b-8ba9661a8150.png">

3. Add a new step under [configuring IDP](https://apim.docs.wso2.com/en/4.2.0/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-oidc/#step-1-configure-the-identity-provider) to add a role mapping as below.

<img width="1264" alt="Screenshot 2023-02-08 at 14 37 01" src="https://user-images.githubusercontent.com/28379317/217484609-af159a26-f8b4-44b1-9b47-d64633b49296.png">
