### ISSUE TITLE
Publisher console test not working as expected in DS

### ISSUE THREAD

**Issue by BLasan** [wso2/docs-apim#6659]
To reproduce create an API with subscriptions & working endpoints and then deploy it to the gateway. Then try to invoke the API via publisher test console. Will be getting the following error.

` "NetworkError when attempting to fetch resource."`

 If we check the network requests it shows "CORS missing Allow header" in OPTION method. But the curl invocation from the terminal works fine without any error.

**Comment by ruthryi** [comment]
Closing this since this does not have a doc impact at the moment
