### ISSUE TITLE
Change steps of the 'Enabling Notifications' document

### ISSUE THREAD

**Issue by Tharanidk** [wso2/docs-apim#6663]
**Description:**
The step 02 and step 03 in the [document ](https://apim.docs.wso2.com/en/latest/design/api-versioning/enabling-notifications/#enabling-notifications)'Enabling Notificatios' should be removed as `NotificationsEnabled` property should be set to 'true' from the Admin portal.

Step 04 should be changed as below.
`Go to 'Advanced configurations section' of the Admin Portal` (https://apim.docs.wso2.com/en/latest/administer/advanced-configurations/).

**Affected Product Version:**
APIM 4.2.0

**Comment by RusJaI** [comment]
PR : https://github.com/wso2/docs-apim/pull/6803
