### ISSUE TITLE
Configuration instructions and Screen shots are outdated for forgerock 7.2.0

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/docs-apim#6669]
**Description:**

The forgerock 7.2.0 is the latest Forgerock version and the configuration steps has some major changes in the below steps and new screen shots are added delow.

Step 1.1 - Configure OAuth 2.0 Provider

Step 5.
Here an Oauth provider is not attached to the Realm by default in the latest versions. So we first need to go to Realm -> Services and add Oauth2 provider as a new service as follows.
<img width="1271" alt="Screenshot 2023-02-08 at 15 45 55" src="https://user-images.githubusercontent.com/24529961/217501353-9eed2e8c-d90b-4df5-aff9-896ca90b933f.png">

Step 1.2 - Configure an OAuth 2.0 client

Step 1.
Here the scopes needed for DCR should be added to default scopes as well as given below.
<img width="740" alt="Screenshot 2023-02-08 at 15 51 17" src="https://user-images.githubusercontent.com/24529961/217502571-b23f27b5-febc-4391-9f14-4996ece59277.png">

Thanks.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamilaadhi** [comment]
Fixed from https://github.com/wso2/docs-apim/issues/6669
