### ISSUE TITLE
[4.1.0] WSO2AM Stripe plugin version needs to be updated to the latest version

### ISSUE THREAD

**Issue by IsuruMaduranga** [wso2/docs-apim#6671]
## Description

The latest release of WSO2AM Stripe plugin contains a crucial fix related to invoicing[1][2]. Correct version needs to be added to the docs ASAP.

Location - https://apim.docs.wso2.com/en/latest/design/api-monetization/monetizing-an-api/#b-configure-wso2-api-manager
<img width="1440" alt="Screenshot 2566-02-09 at 16 46 39" src="https://user-images.githubusercontent.com/36605514/217798502-7feeef44-0de8-42f6-9fdb-7bb9d354ca25.png">

Highlighted version needs to be changed to `org.wso2.apim.monetization.impl-1.3.3.jar` with the new download link https://github.com/wso2-extensions/wso2-am-stripe-plugin/releases/download/v1.3.3/org.wso2.apim.monetization.impl-1.3.3.jar

## Affected Product Version
APIM-4.1.0

## Related Issues
[1] https://github.com/wso2/api-manager/issues/1284
[2] https://github.com/wso2-extensions/wso2-am-stripe-plugin/issues/41

**Comment by Mariangela** [comment]
@IsuruMaduranga , is this only applicable to 4.1.0 or is this applicable for 4.2.0 as well

**Comment by IsuruMaduranga** [comment]
Hi @Mariangela,

This will be applicable to 4.2.0 as well because we'll use the same stripe plugin as far as I know.
Moreover, it needs to be mentioned that following jars needs to be added too from v1.3.2 upwards. I just noticed this part is still missing from the docs.

[elasticsearch-java-8.x.x.jar](https://repo1.maven.org/maven2/co/elastic/clients/elasticsearch-java/8.3.1/elasticsearch-java-8.3.1.jar)
[elasticsearch-rest-client-8.x.x.jar](https://repo1.maven.org/maven2/org/elasticsearch/client/elasticsearch-rest-client/8.3.1/elasticsearch-rest-client-8.3.1.jar)
[httpasyncclient-4.x.x.jar](https://repo1.maven.org/maven2/org/apache/httpcomponents/httpasyncclient/4.1.5/httpasyncclient-4.1.5.jar)
[jakarta.json-api-2.x.x.jar](https://repo1.maven.org/maven2/jakarta/json/jakarta.json-api/2.1.1/jakarta.json-api-2.1.1.jar)
[Parsson-1.x.x.jar](https://repo1.maven.org/maven2/org/eclipse/parsson/parsson/1.1.1/parsson-1.1.1.jar)

This is for supporting ELK based analytics monetization[1]. ( There should be a seperate section explaining ELK-based analytics for APIM which is still missing in docs for some reason. Should we create an issue for this as well? @AnuGayan  )

[1] https://docs.google.com/document/d/1VGYS7WFQpVHSYyGhPuwHVdQbvSpnF1WTTPL9RXe_zc8/edit#

Thanks,
Isuru

**Comment by Mariangela** [comment]
@IsuruMaduranga , please provide information (links to new JARs) based on our offline discussion a short while ago.

**Comment by IsuruMaduranga** [comment]
Hi @Mariangela,

Due to couple of reasons we decided to release new 1.4.0 version. The documentation needs to be changed as follows.

### Update

_"In this example scenario, you need to add the [org.wso2.apim.monetization.impl-1.3.3.jar](https://github.com/wso2-extensions/wso2-am-stripe-plugin/releases/download/v1.3.3/org.wso2.apim.monetization.impl-1.3.3.jar) JAR into the latter mentioned lib folder"_

### to

_"In this example scenario, you need to add the [org.wso2.apim.monetization.impl-1.4.0.jar](https://github.com/wso2-extensions/wso2-am-stripe-plugin/releases/download/v1.4.0/org.wso2.apim.monetization.impl-1.4.0.jar) and [jakarta.json-api-2.1.1.jar](https://repo1.maven.org/maven2/jakarta/json/jakarta.json-api/2.1.1/jakarta.json-api-2.1.1.jar) JAR into the latter mentioned lib folder ( org.wso2.apim.monetization.impl is dependent on jakarta.json-api )"_

### Remove
"Note_ that this JAR has been derived by building the [wso2-am-stripe-plugin repository](https://github.com/wso2-extensions/wso2-am-stripe-plugin)"

### Instead add following as a separate note
_"You can find source code of org.wso2.apim.monetization.impl in [wso2-extensions/wso2-am-stripe-plugin](https://github.com/wso2-extensions/wso2-am-stripe-plugin) repository"_

Thanks,
Isuru

**Comment by Mariangela** [comment]
> wso2-extensions/wso2-am-stripe-plugin

The fixes related to this:

- https://github.com/wso2/docs-apim/pull/6672
- https://github.com/wso2/docs-apim/pull/6673
- https://github.com/wso2/docs-apim/pull/6674

**Comment by Mariangela** [comment]
> Due to couple of reasons we decided to release new 1.4.0 version. The documentation needs to be changed as follows.

The fixes related to the problem mentioned [here](https://github.com/wso2/docs-apim/issues/6671#issuecomment-1425630200)

- https://github.com/wso2/docs-apim/pull/6688 
- https://github.com/wso2/docs-apim/pull/6687 
- https://github.com/wso2/docs-apim/pull/6686

**Comment by Mariangela** [comment]
I am closing this issue as this has been fixed in 4.1.0, 4.2.0 and master
