### ISSUE TITLE
Customize API lifecycle docs outdated

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#670]
**Description:**
Need to update the steps in https://apim.docs.wso2.com/en/latest/Learn/DesignAPI/LifecycleManagement/customize-api-life-cycle/

**Comment by vithu30** [comment]
Fixed in 3.1.0 doc space via #951

**Comment by vithu30** [comment]
Fixed in 3.0.0 doc space via https://github.com/wso2/docs-apim/pull/967
