### ISSUE TITLE
Scope details are missing in the RESTful APIs in apim 3.0.0. 

### ISSUE THREAD

**Issue by Senthuran100** [wso2/docs-apim#671]
**Description:**
In APIM 3.0.0 documentation[1] the scope details for the Rest API(Publisher API v1, Publisher API v0.15, Developer Portal API v1, Developer Portal API v0.15) are not mentioned. But in APIM 2.6.0 documentation scope details are mentioned clearly. 

**Affected Product Version:**
APIM 3.0.0

[1] https://apim.docs.wso2.com/en/latest/Develop/ProductAPIs/restful-apis/

**Comment by Mariangela** [comment]
@ruthryi , can you pls comment.

**Comment by ruthryi** [comment]
The API-M 3.0 REST API docs are automatically generated from the Swagger definitions. Swagger UI currently does not support scope descriptions. We will update it once that feature is rolled out.

**Comment by Mariangela** [comment]
I will close this Git issue for now as this is not something that will be able to immediately address due to the restrictions that Ruthryi mentioned.
