### ISSUE TITLE
A few issues identified when trying out the Streaming Integrator Quick Start Guide

### ISSUE THREAD

**Issue by RukshiW** [wso2/docs-apim#6732]
**Description:**
The following are a few issues encountered when trying out [1].

1. In the **Before you begin** section, there is a single link to download the Streaming Integrator server and tooling. However, while downloading the Streaming Integrator server from that page is quite straightforward, downloading the tooling is not. We might need an additional note there to say that to download the tooling, you need to click the **Tooling** link after clicking **Downloads** and agreeing to the terms and conditions.

2. Step 3, sub-step 2 has a tip that states "Use admin as the username and password." for the Streaming Integration Studio, but this tool does not at any point prompt the user to enter credentials.

3. Suggesting to change the "Click on **Deploy** and then **Deploy To Server** to deploy the Siddhi Application in Streaming Integrator." as follows:

    "To deploy the Siddhi application in the Streaming Integrator, click **Deploy** and then click **Deploy to Server**.

     For more information, see [2].

4.  "Add the Streaming Integrator server details by clicking on Add New Server." is wrong. **Add New Server** is a label and it is not clickable. Instead, there should be a step to add server details and then click **Add**.

5. In **Step 4 - Test your Siddhi application**, the user is instructed to copy the file to `/users/foo/files` (which is the correct location because it matches with the location in the Siddhi file). Why does step 3.1 mention a different location in an information note ("In this example, the file is located in the /Users/foo directory."). This creates a confusion because by the time the user reaches the step  4.1: "Copy the sampledata.xml file in the /Users/foo/files directory.", he/she might ignore it believing that this is already done, without realising that the location that is previously mentioned is slightly different.

6. `<SI_HOME>/conf/server/deployment.toml` is should be changed to `<SI_HOME>/conf/server/deployment.yaml`?

7. For the Siddhi application to be successfully deployed as an Asynchronous API in the API Manager, the *.jks files in the API Manager and the Streaming Integrator Tooling should be the same.

    The following files should be copied from the API Manager:
     - `wso2am-4.1.0/repository/resources/security/wso2carbon.jks`
     -  ` wso2am-4.1.0/repository/resources/security/client-truststore.jks files`
 
    Then they should be pasted in the following directories:
      - wso2si-4.1.0/resources/security
      - wso2si-tooling-4.1.0/resources/security

8. In **Step 4 - Invoke the managed API via Developer Porta**, the user is instructed to issue a wscat command. Thereshould be a prerequisite/step before that to install wscat via the `npm install -g wscat` command.

[1] https://apim.docs.wso2.com/en/latest/get-started/streaming-quick-start-guide/
[2] https://developers.google.com/style/procedures#steps-with-goals

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by SanojPunchihewa** [comment]
**[Developer Comment] Progress Update**

- Locally set up SI, SI tooling and APIM and follows the Streaming Integrator Quick Start Guide.
- Updated the docs with the issues mentioned above.
- Instead of copying the jks files, importing the public certificate of APIM to the SI trust store will also work
- In addition to the above fixed the following,
  - Update the `Setup and Install` link to point to SI instead of APIM.
  - Add a note about setting a port offset if both SI and APIM are in the same instance.
