### ISSUE TITLE
Extending API Lifecycle page is outdated

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#674]
**Description:**
The Extending API Lifecycle page is outdated en/docs/Learn/DesignAPI/LifecycleManagement/extending-the-api-life-cycle.md

**Comment by vithu30** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/957 in 3.1.0 doc space

**Comment by vithu30** [comment]
Fixed in 3.0.0 doc space via https://github.com/wso2/docs-apim/pull/967
