### ISSUE TITLE
Cannot Create the Token for NTLM Grant Type to Generating Keys

### ISSUE THREAD

**Issue by chamikasudusinghe** [wso2/docs-apim#6745]
**Description:**

In order to generate an access token with NTLM, we must have an NTLM token. To generate the NTLM token, specific sample should have been available in the pack. But the sample was not available in the said directory, which is <APIM_HOME>/samples/NTLMGrantClientWithHandshake.

Documentation: https://apim.docs.wso2.com/en/4.2.0/design/api-security/oauth2/grant-types/ntlm-grant/

**Comment by chamilaadhi** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/6779
