### ISSUE TITLE
Image missing 4.2.0

### ISSUE THREAD

**Issue by lahirus** [wso2/docs-apim#6753]
**Description:**
Image missing after the text "The AsyncAPI Generation form appears."

https://apim.docs.wso2.com/en/4.2.0/develop/streaming-apps/working-with-the-async-api-view/#!

**Affected Product Version:**
4.2.0 docs

**OS, DB, other environment details and versions:**

**Comment by ruthryi** [comment]
This has now been fixed with https://github.com/wso2/docs-apim/pull/6765
