### ISSUE TITLE
Doc Feedback: Use of the word 'API' in simple letters.

### ISSUE THREAD

**Issue by lakshikap** [wso2/docs-apim#681]
The abbreviation 'API' has been written as 'api' in many places in the APIM docs. Two such places are given below.

Location : https://apim.docs.wso2.com/en/latest/WIP/configuring-api-security-audit/
Top most topic..

See the first note (same repeated) - https://apim.docs.wso2.com/en/latest/Learn/Analytics/AnalyzingAPIMStatisticsWithBatchAnalytics/viewing-api-statistics/

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/707
