### ISSUE TITLE
Update WSO2 IS Connector artifacts in 4.2.0 docs

### ISSUE THREAD

**Issue by rmsamitha** [wso2/docs-apim#6866]
**Description:**
Need to update WSO2 IS Connector artifacts in 4.2.0 docs in both [1] and [2].

1. Replace the wso2is-extensions-1.6.8.zip with the attached 
[wso2is-extensions-1.6.8.zip](https://github.com/wso2/docs-apim/files/10966076/wso2is-extensions-1.6.8.zip)

2. Change jar version numbers mentioned in the doc pages [1][2] to 1.6.8 from 1.4.2/1.6.7/1.2.10.

i.e.
    wso2is.key.manager.core-1.6.8.jar
    wso2is.notification.event.handlers-1.6.8.jar

Need to change the version numbers in this screenshot from 1.6.7/ 1.2.10 to 1.6.8
<kbd>
<img width="837" alt="image" src="https://user-images.githubusercontent.com/2484781/224939661-2241762a-07e3-41b5-9b07-b8ea128c706a.png">
</kbd>

[1] https://apim.docs.wso2.com/en/4.2.0/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/#step-4-configure-wso2-is-with-wso2-api-m
[2] https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-wso2is-connector/#step-1-configure-wso2-is 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruthryi** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/6864/files

**Comment by ruthryi** [comment]
- https://github.com/wso2/docs-apim/pull/6864
