### ISSUE TITLE
Outdated documentation for JVM metrics

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/docs-apim#689]
**Description:**
API-M 3.0.0 onwards we do not support JVM metrics, however this content is still available in the docs[1].

[1].https://apim.docs.wso2.com/en/latest/Learn/Analytics/MonitoringWithWSO2CarbonMetrics/using-jvm-metrics/

**Comment by tharindu1st** [comment]
@Mariangela @shaniR  Can you please remove this doc from latest and 3.0.0 doc space.
