### ISSUE TITLE
Confusions in Certificate Bound Access Tokens doc

### ISSUE THREAD

**Issue by msm1992** [wso2/docs-apim#6935]
**Description:**
- As of now APIM supports certificate bound access token validation only.
- It seems the documentation[1] is misleading and gives the impression that APIM supports certificate bound access token generation as well. 

[1].  https://apim.docs.wso2.com/en/latest/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens/

**Affected Product Version:**
APIM 4.1.0

**Comment by ruthryi** [comment]
Fixed with the following: 

- https://github.com/wso2/docs-apim/pull/6936
- https://github.com/wso2/docs-apim/pull/6937
- https://github.com/wso2/docs-apim/pull/6938
- https://github.com/wso2/docs-apim/pull/6939
