### ISSUE TITLE
Create an MI Doc Site

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apim#6947]
**Description:**
Create a separate MI Doc Site. It should reuse the content in the APIM repo.

**Comment by Mariangela** [comment]
The following PR contains the content for the MI site. The site will go live only after @chanaka3d updates the build script to support two sites from one GitHub Repo.

https://github.com/wso2/docs-apim/pull/7038

**Comment by DinithiDiaz** [comment]
Closing this issue as this has already been addressed via https://github.com/wso2-enterprise/wso2-mi-internal/issues/3.

MI doc space is now live: https://mi.docs.wso2.com/
