### ISSUE TITLE
Doc Feedback: Broken references

### ISSUE THREAD

**Issue by gspadotto** [wso2/docs-apim#6950]
Location : https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-best-practices/performance-test-results-mi/

At the end of the page, "Results" paragraph, image links are broken.

**Comment by gspadotto** [comment]
@chamindi-a is this hard to fix?

**Comment by chamindi-a** [comment]
@gspadotto : I appreciate you bringing this issue to our attention. It's a relatively straightforward fix. The images have already been rectified in the staging environment, and we will soon apply these corrections to the live link.
