### ISSUE TITLE
Add tested Identity Providers in Documentation

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/docs-apim#6956]
**Description:**
In [MI Dashboard Config Catalog](https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi-dashboard/#single-sign-on),
add the tested and verified Service providers in the Documentation

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by SanojPunchihewa** [comment]
The PR [1] should be backported to **4.0.0**, **4.1.0** and **4.2.0** as well

[1] - https://github.com/wso2/docs-apim/pull/6973

**Comment by ruthryi** [comment]
Done : 
https://github.com/wso2/docs-apim/pull/6974
https://github.com/wso2/docs-apim/pull/6975
https://github.com/wso2/docs-apim/pull/6976
