### ISSUE TITLE
Update doc links and content associated with tooling from .com and the mailer

### ISSUE THREAD

**Issue by samgnaniah** [wso2/docs-apim#7008]
Most links are outdated in the tooling download page and mailer.

**Web page**: https://wso2.com/api-manager/tooling/
**Issue 1**: The Documentation link in this page loads up the 4.0.0 docs. It should be 4.2.0 as the description indicates.

**Mailer**:
<img width="446" alt="image" src="https://user-images.githubusercontent.com/19791901/236124168-398cb36a-a6d0-4636-9b14-ddbd04008e76.png">

**Issue 2**: It downloads Integration Studio version 8.2.0 but it says I've got MI 4.1.0 tooling in the mailer. The mailer is either outdated or just not in sync with the physical download.

**Issue 3**: The Quick Start Guide link in the mailer takes you to the SI tooling page in the docs. I'm downloading Integration Studio, not SI. This is the where that link goes: https://apim.docs.wso2.com/en/4.1.0/develop/streaming-apps/streaming-integrator-studio-overview/?utm_source=mailer&utm_medium=email&utm_campaign=mailer_SI_ty

**Issue 4**: The Documentation link takes me to the MI QSG. Strangely, it is the 4.1.0 version again here. Link: https://apim.docs.wso2.com/en/4.1.0/get-started/integration-quick-start-guide/?utm_source=mailer&utm_medium=email&utm_campaign=mailer_microintegrator_ty

**Comment by Mariangela** [comment]
Reported this issue on Discord [1], because the marketing team needs to be notified regarding this issue.
[1] https://discord.com/channels/955510916064092180/1195815890336370888

**Comment by iwantha** [comment]
This is done

**Comment by Mariangela** [comment]
@iwantha , thanks for fixing this.

I checked this. Issue 1 is fixed.
I am unable to confirm whether issue 2,3&4 is fixed because I never got a mailer even though I gave my email address. 
@iwantha , is the user still supposed to get a mailer when they download Integration Studio version 8.2.0?

**Comment by Mariangela** [comment]
@samgnaniah, can you please check if you still get a mailer when you try to download Integration Studio version 8.2.0. please.

**Comment by Mariangela** [comment]
When I checked with Iwantha, he mentioned that thank you emails have been removed from product download submissions. Hence Issues 2,3&4 is not valid anymore.

**Comment by Mariangela** [comment]
Therefore this issue can be closed as the other relevant sections have been fixed.

**Comment by Mariangela** [comment]
**Assignee**
@iwantha @Mariangela 

**Status**
Fixed

**Note to Reviewer**
Please close this issue as it is fixed.
