### ISSUE TITLE
Monetization with Elasticsearch is not documented

### ISSUE THREAD

**Issue by lasanthaS** [wso2/docs-apim#7011]
**Description:**
The monetization support via Elasticsearch is not documented in APIM docs[1]. The required configurations can be found at [2].

[1]https://apim.docs.wso2.com/en/latest/design/api-monetization/monetizing-an-api/
[2] https://github.com/wso2-extensions/wso2-am-stripe-plugin/pull/38

**Affected Product Version:**
APIM 4.2.0

**Comment by Jaiya94** [comment]
Need the doc for APIM 4.1.0 as well.

**Comment by ruthryi** [comment]
Please find the draft doc I have created based on the content in the PR: 

https://docs.google.com/document/d/1wjeftiQ2GCkACWsAo10OojbG1HshnXbzy54JbMTmv64/edit#heading=h.f4ik0ck0k1kz
