### ISSUE TITLE
Getting Started Guide for REST APIs is not present

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/docs-apim#718]
**Description:**
The following sections are not present in APIM-3.0.0 REST APIs doc space.
[Getting started](https://docs.wso2.com/display/AM260/apidocs/publisher/index.html#guide)
[Configuring the REST API](https://docs.wso2.com/display/AM260/apidocs/publisher/index.html#configuring-rest-api)

**Comment by Mariangela** [comment]
This has been fixed in 3.1.0 in https://github.com/wso2/docs-apim/pull/1130

**Comment by Mariangela** [comment]
This has been fixed in the 3.0.0, 3.1.0 and 3.2.0 docs.
