### ISSUE TITLE
Doc Feedback: Unclear sentence

### ISSUE THREAD

**Issue by bhathiya** [wso2/docs-apim#720]
Location : https://apim.docs.wso2.com/en/latest//Learn/APISecurity/OAuth2/hashing-oauth-keys/

`Run the following command based on the database engine CONN_APP_KEY constraint from the IDN_OAUTH2_ACCESS_TOKEN table.`

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/728
