### ISSUE TITLE
No distributed/clustered deployment documentation

### ISSUE THREAD

**Issue by danijelt** [wso2/docs-apim#722]
**Description:**
There is no documentation for clustering/distributed setup for API Manager 3.0.0.
Instructions from previous versions can't be used because v3.0.0 uses deployment.toml file.

Following the distributed setup link [on this page](https://apim.docs.wso2.com/en/latest/InstallAndSetup/DeployingWSO2APIManager/DistributedDeployment/distributed-deployment-of-api-manager/) gives 404 error.

**Affected Product Version:**
WSO2 API Manager 3.0.0

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/735

After the PR is merged the changes will be available in [1]. [1] https://apim.docs.wso2.com/en/latest/InstallAndSetup/DeployingWSO2APIManager/DistributedDeployment/deploying-wso2-api-m-in-a-distributed-setup/
