### ISSUE TITLE
Facing MySQL connection issue when we provide database password with special characters

### ISSUE THREAD

**Issue by akurathimohan** [wso2/docs-apim#726]
**Description:**
Facing MySQL connection issue when database password contains special character like **ampersand symbol (&)**

**Affected Product Version:**
API-Manager 3.0

**OS, DB, other environment details and versions:**    
MySQL 5.7

**Steps to reproduce:**
I have provided database configurations in deployment.toml  like below

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/apim_db"
username = "root"
password = "password&"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/shared_db"
username = "root"
password = "password&"

**Error Log**
ERROR {org.wso2.carbon.user.core.common.DefaultRealm} - nullType class java.lang.reflect.InvocationTargetException org.wso2.carbon.user.core.UserStoreException: nullType class java.lang.reflect.InvocationTargetException

ERROR - DataSourceServiceComponent Error in intializing system data sources: Error in initializing system data sources: Error in initializing system data sources at '/home/wso2carbon/wso2am-3.0.0/repository/conf/datasources/master-datasources.xml'

**Comment by Mariangela** [comment]
@tharindu1st or @bhathiya , can you please provide feedback on this Git issue.

**Comment by tharindu1st** [comment]
Hi @akurathimohan ,
This was already going to address on https://github.com/wso2/product-apim/issues/7171

**Comment by Mariangela** [comment]
Closing this Git issue as it will be addressed in https://github.com/wso2/product-apim/issues/7171
