### ISSUE TITLE
Images and icons are missing in documentation pages

### ISSUE THREAD

**Issue by ecostanzi** [wso2/docs-apim#743]
**Description:**
Images are missing from documentations. 

![wso2 images](https://user-images.githubusercontent.com/3602612/75142473-76e54500-56f3-11ea-8b08-62deb8f2a253.PNG)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Go to https://apim.docs.wso2.com/en/latest/learn/design-api/publish-api/publish-an-api/ and notice images are missing.

One example of image that cannot be found:
https://apim.docs.wso2.com/en/latest/assets/img/Learn/publish-api-requirements.png

**Related Issues:**

**Comment by shaniR** [comment]
Hi ecostanzi, 
Images are now visible. The icons will be fixed soon.

**Comment by shaniR** [comment]
Hi ecostanzi,
The icons are fixed as well. Sorry for the inconvenience caused, and thank you for reporting.
