### ISSUE TITLE
Setting up Email Login docs is incomplete

### ISSUE THREAD

**Issue by CrowleyRajapakse** [wso2/docs-apim#749]
**Description:**
Need to add and change the following details in the deployment.toml file when configuring email login.
Doc Link: [Email Login](https://apim.docs.wso2.com/en/latest/administer/product-security/logins-and-passwords/maintaining-logins-and-passwords/#setting-up-an-e-mail-login)

`[tenant_mgt]
enable_email_domain= true

[apim.throttling.policy_deploy]
username = "$ref{super_admin.username}@carbon.super"

[apim.throttling]
receiver_username = "$ref{super_admin.username}@carbon.super"

[apim.throttling.jms]
username="admin!wso2.com!carbon.super"
password = "$ref{super_admin.password}"
`

**Suggested Labels:**
APIM 3.1 

**Affected Product Version:**
APIM 3.1 

**Related Issues:**
product-apim: https://github.com/wso2/product-apim/issues/7175

**Comment by Mariangela** [comment]
@bhathiya , please confirm.

**Comment by Mariangela** [comment]
@CrowleyRajapakse , can you provide more information on as to what each of the configuration is used for, so that the user can be more informed when updating the configs.
```
[tenant_mgt]
enable_email_domain= true

[apim.throttling.policy_deploy]
username = "$ref{super_admin.username}@carbon.super"

[apim.throttling]
receiver_username = "$ref{super_admin.username}@carbon.super"

[apim.throttling.jms]
username="admin!wso2.com!carbon.super"
password = "$ref{super_admin.password}"
```
