### ISSUE TITLE
Choreo Based Analytics Documentation is not up to date

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/docs-apim#7505]
**Description:**
The Choreo based analytics documentation is not up to date with the latest Choreo screenshots [1]. Therefore it can be a bit tricky to find the place where we have to generate an on-prem keys to configure APIM analytics.

This document should be updated with the latest Choreo screenshots and steps.

[1] https://apim.docs.wso2.com/en/latest/api-analytics/choreo-analytics/getting-started-guide/#step-2-register-your-environment

**Comment by ashera96** [comment]
Already fixed in Master, 4.4.0 & 4.3.0.
Sent the following PRs to fix in 4.2.0, 4.1.0 & 4.0.0.

- https://github.com/wso2/docs-apim/pull/8671
- https://github.com/wso2/docs-apim/pull/8672
- https://github.com/wso2/docs-apim/pull/8673
