### ISSUE TITLE
Link broken in "Log in to the Developer Portal using Social Media" page

### ISSUE THREAD

**Issue by chanaka3d** [wso2/docs-apim#752]
**Description:**
"Configure WSO2 Identity Server as a Key Manager with API Manager" link in the following doc is broken.

https://apim.docs.wso2.com/en/latest/learn/consume-api/customizations/log-in-to-the-dev-portal-using-social-media/#log-in-to-the-developer-portal-using-social-media

The broken link points to https://apim.docs.wso2.com/SetupAndInstall/DeployingWSO2APIManager/ThirdPartyKeyManager/configuring-wso2-identity-server-as-a-key-manager/

correct link
https://apim.docs.wso2.com/en/latest/install-and-setup/deploying-wso2-api-manager/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/

**Comment by shaniR** [comment]
it is fixed now. Fixed with this https://github.com/wso2/docs-apim/commit/e846f3d11a94bcaa14f9fe2320c1a1a3c7ef963a
