### ISSUE TITLE
Link not working on 

### ISSUE THREAD

**Issue by lpastor74** [wso2/docs-apim#758]
### Description:

Link to documenation is  not working 
### Steps to reproduce:
go to 
https://apim.docs.wso2.com/en/latest/getting-started/overview/#analytics
and clik on link **_Working with Analytics_**.
### Content Positioning in Documentation:

- Link:
https://apim.docs.wso2.com/en/latest/getting-started/overview/#analytics

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/772/commits/ff6d771b69ae151bcf33a3abf4455901d02e7d23

https://github.com/wso2/docs-apim/pull/772
