### ISSUE TITLE
Dead link on "Configuring a Third-Party Key Manager"

### ISSUE THREAD

**Issue by wx-yz** [wso2/docs-apim#760]
### Description:
Go to https://apim.docs.wso2.com/en/latest/getting-started/overview/, under Key Manager section, click on "Configuring a Third-Party Key Manager". This goes to a dead link

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/772/commits/ff6d771b69ae151bcf33a3abf4455901d02e7d23

https://github.com/wso2/docs-apim/pull/772
