### ISSUE TITLE
Dead link on "Configuring WSO2 Identity Server as the Key Manager"

### ISSUE THREAD

**Issue by wx-yz** [wso2/docs-apim#761]
### Description:
Go to https://apim.docs.wso2.com/en/latest/getting-started/overview/, under Key Manager section, click on " Configuring WSO2 Identity Server as the Key Manager". This goes to a dead link

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/772/commits/475980cb6a6cd02f0872cfc4d91b4adf506deb56
https://github.com/wso2/docs-apim/pull/772
