### ISSUE TITLE
Dead link on " configuring WSO2 API Manager Analytics" 

### ISSUE THREAD

**Issue by wx-yz** [wso2/docs-apim#762]
### Description:
Go to https://apim.docs.wso2.com/en/latest/getting-started/overview/, Then go to API Gateway section, and click on " configuring WSO2 API Manager Analytics". This points to a dead link

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/772
