### ISSUE TITLE
Dead link on "Working with Throttling" 

### ISSUE THREAD

**Issue by wx-yz** [wso2/docs-apim#763]
### Description:
Dead link on "Working with Throttling" section on https://apim.docs.wso2.com/en/latest/getting-started/overview/#traffic-manager

### Content Positioning in Documentation:

- Link: https://apim.docs.wso2.com/en/latest/getting-started/overview/#traffic-manager

- Heading (& Step):
1. Under Traffic Manager, click on "Working with Throttling"

- Any other reference:

---

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/772/commits/475980cb6a6cd02f0872cfc4d91b4adf506deb56
