### ISSUE TITLE
Specific DB configuration pages give 404 not found

### ISSUE THREAD

**Issue by wx-yz** [wso2/docs-apim#764]
### Description:
When navigating to specific DB pages in https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/overview/ it goes to 404

### Content Positioning in Documentation:

- Link: https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/overview/

- Heading (& Step):
1. Goto https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/overview/
2. Try navigating to any of the DB specific links

---

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/776
https://github.com/wso2/docs-apim/pull/776/commits/eb5955cf862d28c2c1450c1375557a0b2b918353
