### ISSUE TITLE
To update self-paced training documents

### ISSUE THREAD

**Issue by ankit-agrawal07** [wso2/docs-apim#765]
### Description:
The Link to download the self-paced training docs/presentation are pointing to an older version of APIM.
https://wso2.com/training/apim-self-paced

### Steps to reproduce:
Download the docs from the above URL

### Content Positioning in Documentation:

- Link: https://wso2.com/training/apim-self-paced

- Heading (& Step):

- Any other reference:

---

**Comment by Mariangela** [comment]
@YohannaFernando , please comment on this Git issue.

**Comment by YohannaFernando** [comment]
This is an outdated page.

Please check http://lms.wso2.com/ for all latest training material.

**Comment by Mariangela** [comment]
@ankit-agrawal07, thanks for reporting. As mentioned by Yohanna, please check http://lms.wso2.com/ for all latest training material.
