### ISSUE TITLE
Remove broken links for Broken SP links

### ISSUE THREAD

**Issue by nandika** [wso2/docs-apim#7668]
**Description:**
Per your sites instructions: https://wso2.com/analytics-and-stream-processing/install/yum/community/get-started/ However this URL does not work: [mmoser@corp.aires.com@ai-pit-linux ~]$ curl https://bintray.com/wso2/rpm/rpm/bintra-ws02-rpm.repo 

Since we no longer privde yum, we should remove these broken links.

**Comment by RusJaI** [comment]
### Update [2024-10-31]

APIM 4.4.0 - SI docs are removed from the doc space

currently yum links do not exist in other 4.x versions
