### ISSUE TITLE
Missing links on page 

### ISSUE THREAD

**Issue by lpastor74** [wso2/docs-apim#767]
### Description:
https://apim.docs.wso2.com/en/latest/InstallAndSetup/DeployingWSO2APIManager/DistributedDeployment/distributed-deployment-of-api-manager/

bottom links not working 

Understanding the Distributed Deployment of WSO2 API-M
Deploying WSO2 API-M in a Distributed Setup

**Comment by Mariangela** [comment]
Fixed in https://apim.docs.wso2.com/en/latest/install-and-setup/deploying-wso2-api-manager/distributed-deployment/distributed-deployment-of-api-manager/
