### ISSUE TITLE
Missing upgrade documentation to APIM 3.0

### ISSUE THREAD

**Issue by markokocic** [wso2/docs-apim#768]
The documentation page at https://apim.docs.wso2.com/en/latest/SetupAndInstall/UpgradingFromAPreviousRelease/upgrading-from-the-previous-release/ covers only upgrade to 2.6.0 from previous releases.

Can't find documentation how to upgrade from APIM 2.6.0 or earlier to APIM 3.0.0

**Comment by Mariangela** [comment]
Instructions on upgrading from APIM 2.6.0 or earlier to APIM 3.0.0 can be found in the following pages

- https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-process/
- https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300/
- https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300/
- https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-300/
- https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300/
- https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-300/
- https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-300/
- https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-191-to-300/
