### ISSUE TITLE
[Doc] The quick start guide needs to have information on running the end to end flow 

### ISSUE THREAD

**Issue by erandidesilva** [wso2/docs-apim#769]
Currently [1] contains only accessing the publisher and store. But ideally the quick start guide should be a walk through where it takes a user from creating, publishing and api to invocation. The current structure needs to be changed. Please update.

[1] https://docs.wso2.com/display/AM300/Quick+Start+Guide#QuickStartGuide-AccessingtheAPIPublisher

**Comment by Mariangela** [comment]
The revamped QSG for APIM 3.0.0 is available at
https://apim.docs.wso2.com/en/latest/getting-started/quick-start-guide/
