### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by Nethminiromina** [wso2/docs-apim#770]
Location: [https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mysql/#executing-db-scripts-to-create-tables-on-mysql-database](https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mysql/#executing-db-scripts-to-create-tables-on-mysql-database)

mb-store database script name is wrong. It should be `mysql-mb.sql`
![image](https://user-images.githubusercontent.com/26083113/75319295-63bcab80-5892-11ea-99bc-7d6e277f1311.png)

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/772
