### ISSUE TITLE
Remove page on how to configure WSO2 Micro Integrator to connect with WSO2 Message Broker 

### ISSUE THREAD

**Issue by viggnah** [wso2/docs-apim#7700]
We should remove this page as WSO2 MB is deprecated. Or is there any valid reason to still keep it?

Location : https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/brokers/configure-with-wso2-mb/

**Comment by ashera96** [comment]
Hi @viggnah,

We have removed this page from APIM 4.3.0, APIM 4.4.0 and master. Hence, closing this issue.
