### ISSUE TITLE
Doc Feedback: note about mb-db script needs to be updated

### ISSUE THREAD

**Issue by bhathiya** [wso2/docs-apim#771]
Location : https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mssql/

```
<API-M_HOME>/dbscripts/mb-store/mssql.sql is the script that should be used when creating the tables in WSO2_MB_STORE_DB database.
```

Here,

1) script path is incorrect.
2) We have to mention that MB db can be h2 even in production. if the user wants to change it to mysql, they should have seperate dbs for each APIM (Traffic Manager) node.

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/772
