### ISSUE TITLE
We should remove all unsupported DB pages

### ISSUE THREAD

**Issue by bhathiya** [wso2/docs-apim#773]
Location : https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/changing-default-databases/changing-to-ibm-informix/

Please remove H2, informix and derby pages.

**Comment by Mariangela** [comment]
@bhathiya , there is [1] and [2]. Should both pages be removed?
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/changing-default-databases/changing-to-embedded-h2/
[2] https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/changing-default-databases/changing-to-remote-h2/

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/776

https://github.com/wso2/docs-apim/pull/776/commits/3b82c8f80b5fdfeb9a0eae648064a46e4988b9e6

**Comment by bhathiya** [comment]
> @bhathiya , there is [1] and [2]. Should both pages be removed?
> [1] https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/changing-default-databases/changing-to-embedded-h2/
> [2] https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/changing-default-databases/changing-to-remote-h2/

yes
