### ISSUE TITLE
Issue in Configuring Identity Server as IDP for SSO

### ISSUE THREAD

**Issue by BLasan** [wso2/docs-apim#7768]
**Description:**
Given steps to configure IS as IDP for SSO are not clear and while logging it does not redirect to the login page. It's getting stuck on the following URL

`https://localhost:9443/oauth2/authorize?response_type=code&client_id=Unb1NTUkerbI8rlMkdaW9foKJl4a&scope=apim:admin%20apim:api_create%20apim:api_definition_view%20apim:api_delete%20apim:api_generate_key%20apim:api_import_export%20apim:api_list_view%20apim:api_manage%20apim:api_mediation_policy_manage%20apim:api_product_import_export%20apim:api_publish%20apim:api_view%20apim:app_import_export%20apim:client_certificates_add%20apim:client_certificates_manage%20apim:client_certificates_update%20apim:client_certificates_view%20apim:comment_manage%20apim:comment_view%20apim:comment_write%20apim:common_operation_policy_manage%20apim:common_operation_policy_view%20apim:document_create%20apim:document_manage%20apim:ep_certificates_add%20apim:ep_certificates_manage%20apim:ep_certificates_update%20apim:ep_certificates_view%20apim:gateway_policy_manage%20apim:gateway_policy_view%20apim:mediation_policy_create%20apim:mediation_policy_manage%20apim:mediation_policy_view%20apim:policies_import_export%20apim:pub_alert_manage%20apim:publisher_settings%20apim:shared_scope_manage%20apim:subscription_block%20apim:subscription_manage%20apim:subscription_view%20apim:threat_protection_policy_create%20apim:threat_protection_policy_manage%20apim:tier_manage%20apim:tier_view%20openid%20apim:api_view%20service_catalog:service_view%20service_catalog:service_write&state=%2F&redirect_uri=https://localhost:9443/publisher/services/auth/callback/login`

**Comment by SavinduDimal** [comment]
Related Documentation: https://apim.docs.wso2.com/en/4.3.0/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso/
