### ISSUE TITLE
Improving the note on "Configuring Identity Server as IDP for SSO"

### ISSUE THREAD

**Issue by lkokila** [wso2/docs-apim#7781]
**Description:**
The following document [1] explains about configuring SAML SSO for the API Manager portals (Publisher, Developer Portal, or Admin Portal) with WSO2 IS. 

These portals are already enabled with SSO by default (OIDC) (There's a note in the doc on this too). Therefore to configure SAML SSO using WSO2 IS, might need to have a specific requirement, otherwise it's redundant because SSO is enabled by default. 

A requirement might be if the user has other applications which does SSO through WSO2 IS and SAML, and if they need to include the API Manager portals also into the SAML SSO group. If there's no such requirement, they do not have to configure SAML SSO with WSO2 IS. 

It would be good if a note can be added to the "Configuring WSO2 API Manager apps as SAML 2.0 SSO service providers" explaining when this needs to be considered. 

Thanks,
Lashan

[1] https://apim.docs.wso2.com/en/3.2.0/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso/#configuring-wso2-api-manager-apps-as-saml-20-sso-service-providers

**Affected Product Version:** APIM-3.2.0 +

**Comment by RusJaI** [comment]
### Update [2024-11-11,12]

Master Fix : https://github.com/wso2/docs-apim/pull/8806
4.4.0 :  https://github.com/wso2/docs-apim/pull/8807
4.3.0 : https://github.com/wso2/docs-apim/pull/8808
4.2.0 : https://github.com/wso2/docs-apim/pull/8809
4.1.0:  https://github.com/wso2/docs-apim/pull/8813
4.0.0: https://github.com/wso2/docs-apim/pull/8815
3.2.0: https://github.com/wso2/docs-apim/pull/8816
