### ISSUE TITLE
Browsing latest APIM docs from docs.wso2.com gives a 404

### ISSUE THREAD

**Issue by wx-yz** [wso2/docs-apim#7788]
**Description:**
Latest APIM docs link gives a 404. See below

https://github.com/wso2/docs-apim/assets/57770159/0bc060b3-f30a-4911-ab2f-2813835953d4

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by DinithiDiaz** [comment]
Hi @wx-yz, 
I have informed the marketing team and requested them to update the link on the documentation portal.

Mail: "Request to fix invalid link on the Documentation Dashboard"

Thanks & Kind Regards,
Dinithi

**Comment by DinithiDiaz** [comment]
Closing the issue since it has been fixed now.
