### ISSUE TITLE
Configuring User Stores:primary/secondary docs need to be updated

### ISSUE THREAD

**Issue by shnrndk** [wso2/docs-apim#7798]
In the Configuring  secondary user stores docs [1] it should be updated. In Configuring secondary user stores via the management console in step 5 `Properties of userstores` do not work properly.

[1] https://apim.docs.wso2.com/en/4.3.0/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores/

**Comment by tharikaGitHub** [comment]
@shnrndk did we add the fix [1] to 4.3.0 branch as well? If not, let's add that and close the issue after merging the PRs.

[1] https://github.com/wso2/docs-apim/pull/7856

**Comment by shnrndk** [comment]
> @shnrndk did we add the fix [1] to 4.3.0 branch as well? If not, let's add that and close the issue after merging the PRs.
> 
> [1] #7856

[4.3.0] PR: https://github.com/wso2/docs-apim/pull/7855

**Comment by tharikaGitHub** [comment]
Closing the issue as the PRs are merged.
