### ISSUE TITLE
Instructions unclear when Creating a New Policy

### ISSUE THREAD

**Issue by shamin2021** [wso2/docs-apim#7801]
**Description:**
When trying to create a new policy in the publisher portal according to the [APIM docs ](https://apim.docs.wso2.com/en/4.3.0/design/api-policies/create-policy/) 
under Gateway Specific details the user is prompted to check either regular gateway and Choreo connect but now there is no option to select these since only the regular gateway is supported , therefore the docs should be updated accordingly.

Documentation instruction 
![image](https://github.com/wso2/docs-apim/assets/79569018/e05ed222-48d4-4cf2-882e-cd079165031f)

Steps in the Publisher portal when creating Policy 
![image](https://github.com/wso2/docs-apim/assets/79569018/91795014-e473-4293-b965-88bec05db2d4)

**Comment by HeshanSudarshana** [comment]
This issue is fixed from the PRs sent for the issue https://github.com/wso2/docs-apim/issues/7760.
