### ISSUE TITLE
Add the reason why we should add the role details in the Advanced settings in Self Sign Up Config

### ISSUE THREAD

**Issue by shnrndk** [wso2/docs-apim#7814]
In the enabling or disabling self sign up doc[1], we need to add a reason why we need to add a role Internal/subscriber.

[1] https://apim.docs.wso2.com/en/4.3.0/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup/#enabling-self-signup

Currently the doc[1] do not provide any reason why we add the role. The reason needs to be provided as since newly created user do not assigned any role he do not have necessary permissions to login, even though we can create a new user. By adding the internal/subscriber role, newly created user can login.

**Comment by ashera96** [comment]
Fix for 4.4.0: https://github.com/wso2/docs-apim/pull/8570
