### ISSUE TITLE
Add Note About The Certificate Hashing Algorithm in API Key Generation

### ISSUE THREAD

**Issue by hisanhunais** [wso2/docs-apim#7817]
**Description:**
With [1], the certificate hashing algorithm in API Key Generation has been changed to SHA256 by replacing SHA1. Need to add a note about this in [2].

[1] https://github.com/wso2/carbon-apimgt/pull/12365
[2] https://apim.docs.wso2.com/en/4.3.0/design/api-security/api-authentication/secure-apis-using-api-keys/

**Comment by HeshanSudarshana** [comment]
A special note is not required since an API Key created in APIM 4.2.0 is working on a migrated APIM 4.3.0 setup.
