### ISSUE TITLE
Websocket invocation doc does not have information on using query params for auth

### ISSUE THREAD

**Issue by Arshardh** [wso2/docs-apim#783]
**Description:**
From apim version 3.0.0 onwards users can provide the access token for a websocket api invocation as a query parameter named "access_token". We need to add this to the documentation as an alternative way to invoke websocket apis.

**Comment by Mariangela** [comment]
Fixed in 
- https://github.com/wso2/docs-apim/pull/782/commits/64b1b1e5990b470bd0304fcdcdfc17fd0553ea3b
- https://github.com/wso2/docs-apim/pull/782/
- https://apim.docs.wso2.com/en/latest/learn/tutorials/create-and-publish-websocket-api/#step-3-invoke-a-websocket-api
