### ISSUE TITLE
Add default ports to distributed deployment diagrams

### ISSUE THREAD

**Issue by gspadotto** [wso2/docs-apim#785]
### Description:
It would be nice to add the default communication ports among components 
in the diagrams describing the [distributed setup](https://apim.docs.wso2.com/en/latest/install-and-setup/deploying-wso2-api-manager/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/).
This would make it easier to understand which ports have to be open between specific components.

### Content Positioning in Documentation:
- Link:
    [Distributed Setup Docs](https://apim.docs.wso2.com/en/latest/install-and-setup/deploying-wso2-api-manager/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/)

---
#### Suggested Labels:
api-documentation, Distributed-Setup, Documentation, Priority/Low, trivial

**Comment by Mariangela** [comment]
@bhathiya, can you please provide your feedback and also a rough sketch of this information, so that we can get the image redrawn and added into the documentation.

**Comment by bhathiya** [comment]
@ruks will check.

**Comment by ruks** [comment]
Please find the required port and its client to server communication in a fully distributed deployment. All the ports are in default values and need to increment by the offset value. 
![APIM ports (1)](https://user-images.githubusercontent.com/1345278/77400041-9776ec80-6dd0-11ea-912d-e219668705db.jpg)


| Client | Server | Port | Description |
| --------------------- | --------------------- | ------------ | ------------ |
| Gateway | Key Manager  | 9443 | Token validation, token, revoke, authorize endpoint, block condition, revoke tokens |
| Gateway | Analytics Worker  | 7611 | Publisherlishing analytics events |
| Gateway | Analytics Worker  | 7711 | authenticate to Publisherlishing analytics events |
| Gateway | Traffic Manager  | 9611 | Publisherlishing throttling events |
| Gateway | Traffic Manager  | 9711 | authenticate to Publisherlishing throttling events |
|  | | | |
| Publisher | Traffic Manager  | 9443 | Deploying throttling policy via admin portal |
| Publisher | Traffic Manager  | 9611 | Publisherlishing events like block condition, token revocation |
| Publisher | Traffic Manager  | 9711 | authenticate to Publisherlishing events |
| Publisher | Gateway  | 9443 | deploy API artifacts |
| Publisher | Analytics Worker  | 7611 | Publisherlishing alert analytics events |
| Publisher | Analytics Worker  | 7711 | authenticate to Publisherlishing alert analytics events |
| Publisher | Analytics Worker  | 7444 | fetch all the generated alerts |
|  | | | |
| Dev Portal | Key Manager  | 9443 | Register auth app and generate app keys |
| Dev Portal | Gateway  | 8243 | token endpoint and revoke endpoint |
| Dev Portal | Analytics Worker  | 7611 | Publisherlishing alert analytics events |
| Dev Portal | Analytics Worker  | 7711 | authenticate to Publisherlishing alert analytics events |
|  | | | |
| Analytics Dashboard | Analytics Worker  | 9443 | deploy business rules |
| Analytics Dashboard | Publisher  | 9443 | Use admin and Publisherlisher rest APIs |
| Analytics Dashboard | Dev Portal  | 9443 | Use Dev Portal portal rest APIs |

**Comment by ruks** [comment]
@tharindu1st @fazlan-nazeem please review and provide feedback if it required any changes.

**Comment by fazlan-nazeem** [comment]
@ruks shall we use the default ports of analytics server. i.e the default port including the default offset?

**Comment by ruks** [comment]
@fazlan-nazeem please check the updated ports and missed ports. 

![APIM ports (2)](https://user-images.githubusercontent.com/1345278/77413462-6359f680-6de5-11ea-9e7f-8a3c224b6dd9.jpg)


## Open port among profiles
| Client | Server | Port | Description |
| --------------------- | --------------------- | ------------ | ------------ |
| Gateway | Key Manager  | 9443 | Token validation, token, revoke, authorize endpoint, block condition, revoke tokens |
| Gateway | Analytics Worker  | 7612 | Publisherlishing analytics events |
| Gateway | Analytics Worker  | 7712 | authenticate to Publisherlishing analytics events |
| Gateway | Traffic Manager  | 9611 | Publisherlishing throttling events |
| Gateway | Traffic Manager  | 9711 | authenticate to Publisherlishing throttling events |
|  | | | |
| Publisher | Traffic Manager  | 9443 | Deploying throttling policy via admin portal |
| Publisher | Traffic Manager  | 9611 | Publisherlishing events like block condition, token revocation |
| Publisher | Traffic Manager  | 9711 | authenticate to Publisherlishing events |
| Publisher | Gateway  | 9443 | deploy API artifacts |
| Publisher | Analytics Worker  | 7612 | Publisherlishing alert analytics events |
| Publisher | Analytics Worker  | 7712 | authenticate to Publisherlishing alert analytics events |
| Publisher | Analytics Worker  | 7444 | fetch all the generated alerts |
|  | | | |
| Dev Portal | Key Manager  | 9443 | Register auth app and generate app keys |
| Dev Portal | Gateway  | 8243 | token endpoint and revoke endpoint |
| Dev Portal | Analytics Worker  | 7612 | Publisherlishing alert analytics events |
| Dev Portal | Analytics Worker  | 7712 | authenticate to Publisherlishing alert analytics events |
|  | | | |
| Analytics Dashboard | Analytics Worker  | 9444 | deploy business rules |
| Analytics Dashboard | Publisher  | 9443 | Use admin and Publisherlisher rest APIs |
| Analytics Dashboard | Dev Portal  | 9443 | Use Dev Portal portal rest APIs |


## Open port for LB/User
| Server | Port | Description |
| --------------------- | --------------------- | ------------ |
| Key Manager | 9443 | Token endpoint and identity rest APIs/web apps |
| Gateway | 8243 | Gateway nio HTTPS |
| Gateway | 8280 | Gateway nio HTTP |
| Gateway | 8099 | Gateway WS  |
| Gateway | 9099 | Gateway WSS |
| Publisher | 9443 | Publisher portal, Admin and Publisher Rest API |
| Dev Portal | 9443 | Dev portal and Rest API  |
| Analytics Dashboard | 9643 | Analytics dashboard and business rule portals |

**Comment by fazlan-nazeem** [comment]
LGTM
