### ISSUE TITLE
Mention regarding the carbon.registry.database.connectionid.avoiddbcalls

### ISSUE THREAD

**Issue by shagihan** [wso2/docs-apim#793]
### Description:
There is an improvement created in order to reduce the number of DB calls during the registry caching. We have introduced a new System property **carbon.registry.database.connectionid.avoiddbcalls** which is to maintain the default behaviour. Shall we mention that in the docs.

**Comment by Mariangela** [comment]
@mushthaq33 , please confirm whether it is ok to add the following information as a subsection under [1].

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/perfromance-tuning-and-test-results/tuning-performance/#apim-level-settings

H2 APIM-level settings

H3 Registry Caching based configurations
Follow the instructions below to reduce the number of database calls during registry caching.

1. Add the following JVM parameter in the `<API-M_HOME>/bin/wso2server.sh` (for Linux/Mac OS) or `<API-M_HOME>/bin/wso2server.bat` (for Windows OS) file based on your OS and save the file.
   `
   -Dcarbon.registry.database.connectionid.avoiddbcalls=true
   `
2. Restart the WSO2 API Manager server.

**Comment by mushthaq33** [comment]
@Mariangela , Yes this place looks good to me.

**Comment by Mariangela** [comment]
Thanks, @mushthaq33 ! I will add this content.

**Comment by Mariangela** [comment]
@mushthaq33 , for which versions is this WUM update applicable for?

**Comment by mushthaq33** [comment]
@Mariangela, This is applicable for APIM version 2.6.0 from 2th Feb 2020

**Comment by Mariangela** [comment]
@mushthaq33 , thanks for your reply. Based on your reply I will not include this in API-M 3.0.0 and 3.1.0.

**Comment by Mariangela** [comment]
Added the information in https://docs.wso2.com/display/AM260/Tuning+Performance#TuningPerformance-RegistryCachingbasedconfigurations
