### ISSUE TITLE
Need to update Installation Options documentation

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/docs-apim#7941]
**Description:**
The installation options documentation[1] is outdated for APIM 4.3.0. This documentation should be updated with the latest resources.

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/install/installation-options/

**Comment by RusJaI** [comment]
### Update [2024-11-14]
In https://github.com/wso2/aws-apim/ and https://github.com/wso2/ansible-apim/ repos, there are no branches for APIM 4.3.0, 4.4.0. Hence this need to be verified whether which branch should be pointed in corresponding documentation branches.
Hence keeping this on hold

**Comment by RusJaI** [comment]
### Update [2024-11-20]
After a discussion with the team on 19th Nov, it was decided to remove aws-apim and ansible-apim references.
Further currently there are no 4.4 branches for kubernates and puppet apim repos. Hence the PRs were marked as drafts for now : 
4.4.0 : https://github.com/wso2/docs-apim/pull/8859
master : https://github.com/wso2/docs-apim/pull/8860
4.3.0 : https://github.com/wso2/docs-apim/pull/8861

**Comment by RusJaI** [comment]
### Update [2024-11-25]
4.4.0 branch was created for puppet-apim : https://github.com/wso2/puppet-apim/tree/4.4.x
it was mentioned that Kubernetes-apim repo is not being used for APIM 4.4.0 and instead, helm-apim is used. 
Need to update the doc accordingly

**Comment by RusJaI** [comment]
Updated 4.4.0 and master branch PRs.

Modified 4.3.0 doc by https://github.com/wso2/docs-apim/pull/8917
