### ISSUE TITLE
Add missing analytics migration steps to documentation from 2.6.0 to 3.0.0

### ISSUE THREAD

**Issue by kasun-bandara** [wso2/docs-apim#797]
**Description:**
This issue is occurring when someone uses external IDP in the analytics worker profile and use the password grant type in order to authenticate users. 
Previously "OAUTHAPP" table in the "dbAuthApp" DB used to store the client key and secret relevant to the particular auth app used by the APIM analytics. As per the recent change the client secret has been encrypted before stored in the database. So we cannot use the previous database without a migration. 

As a solution, we can delete the existing service providers in the external IDP side and delete the following entries in the"OAUTHAPP" table so that the analytics worker will create new service providers in the IDP and store the auth app information by encrypting client secret in the "OAUTHAPP" table.

Delete following service providers in external IDP side.
- identityuser_sec_sp_portal
- identityuser_sec_sp_status_dashboard
- identityuser_sec_sp_business_rules
- identityuser_sec_sp

Delete db entries related to the following client names in the "OAUTHAPP" table.
- sp
- sp_business_rules
- sp_portal
- sp_status_dashboard

**Suggested Labels:**
Analytics-3.0.0, API-M-3.0.0

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
wso2am-3.0.0 wso2am-analytics-3.0.0

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@TanyaM , please provide feedback on this Git issue.

**Comment by TanyaM** [comment]
I don't think we need to add this information in the migration docs, as this migration is only required by those who have extended an external IDP client. If required we can add a note and specify this info.
@fazlan-nazeem : Please add your thoughts.

**Comment by fazlan-nazeem** [comment]
The default product doesn't require the changes suggested above as Tanya has mentioned. This is only applicable to api-cloud and any other users who have customized the IDP. @kasun-bandara would you be able to track this in api-cloud migration run book? If you still require this in apim doc space we will have to add this under a separate tab without confusing the normal users.

**Comment by kasun-bandara** [comment]
@fazlan-nazeem Sure I'll track this in the api-cloud migration run book. 
This migration step may require for the users who use an external IDP, not only for those who use a custom IDP client as per my understanding and please correct me if I'm wrong. 

Since we haven't provide any information on using an external IDP for user authentication in the worker profile in the APIM analytics documentation, we may not need to add this information.
