### ISSUE TITLE
Correct the Download Instructions for API Manager in the Streaming Integration Quick Start Guide

### ISSUE THREAD

**Issue by ashanhr** [wso2/docs-apim#8001]
**Description:**

In the [Quick Start Guide - Streaming Integration](https://apim.docs.wso2.com/en/latest/get-started/streaming-quick-start-guide/), under the [Before you begin...](https://apim.docs.wso2.com/en/latest/get-started/streaming-quick-start-guide/#before-you-begin) section, it states:

> Optionally, download the API Manager distribution as a ZIP file by navigating to the [WSO2 API Manager product page](https://wso2.com/api-management/), clicking TRY IT NOW, and then clicking Zip Archive.

However, the [WSO2 API Manager product page](https://wso2.com/api-management/) does not contain a **TRY IT NOW** button. 

**Suggested Labels:**
type/docs

**Affected Product Version:**
4.3.0

**Comment by ashera96** [comment]
We are removing the Streaming Integrator QSG from 4.4.0 via [1].

1. https://github.com/wso2/docs-apim/pull/8531
