### ISSUE TITLE
Fix Broken Links in API Analytics Subsection of the Architecture Page

### ISSUE THREAD

**Issue by ashanhr** [wso2/docs-apim#8002]
**Description:**

In the [Architecture](https://apim.docs.wso2.com/en/latest/get-started/apim-architecture/) page, under the [API Analytics](https://apim.docs.wso2.com/en/latest/get-started/apim-architecture/#api-analytics) subsection of the [Management Plane](https://apim.docs.wso2.com/en/latest/get-started/apim-architecture/#management-plane) section, there are two broken links:

> - For information on the architecture, see [API Analytics Architecture](https://apim.docs.wso2.com/en/4.3.0/api-analytics/api-analytics-architecture/)
> - For information on working with Analytics, see the [API Analytics Getting Started Guide](https://apim.docs.wso2.com/en/4.3.0/api-analytics/getting-started-guide/)

These links are no longer valid and need to be updated to point to the correct pages.

**Suggested Labels:**
type/docs

**Affected Product Version:**
4.3.0

**Comment by Tharanidk** [comment]
This issue is not reproducing in any of the APIM 4.x versions
