### ISSUE TITLE
Address Callback URL Error When Running API Manager with Port Offset in Streaming Integration Guide

### ISSUE THREAD

**Issue by ashanhr** [wso2/docs-apim#8004]
**Description:**
When running the API Manager with a port offset as instructed in the [Step 1 - Expose as a service](https://apim.docs.wso2.com/en/latest/get-started/streaming-quick-start-guide/#step-1-expose-as-a-service) section of the [Quick Start Guide - Streaming Integration](https://apim.docs.wso2.com/en/latest/get-started/streaming-quick-start-guide/), the error "provided callback URL does not match with the registered one" occurs.

This issue can be resolved by following the steps in [Troubleshooting 'Registered callback does not match with the provided URL' error](https://apim.docs.wso2.com/en/4.1.0/troubleshooting/troubleshooting-invalid-callback-error/).

To prevent this issue, either:
1. Mention this troubleshooting step in the documentation.
2. Change the instructions to run the API Manager on default ports and use a port offset for the Streaming Integrator.

Providing one of these solutions will help users avoid encountering the callback URL error.

**Suggested Labels:**
type/docs

**Affected Product Version:**
4.3.0

**Comment by ashera96** [comment]
Closing this issue as it is no longer applicable. We have removed the SI documentation from the doc space.
