### ISSUE TITLE
Fix Broken Links in Create a GraphQL API Page

### ISSUE THREAD

**Issue by ashanhr** [wso2/docs-apim#8023]
**Description:**
On the [Create a GraphQL API](https://apim.docs.wso2.com/en/latest/design/create-api/create-a-graphql-api/) page, under section 6 b i ii of [Step 2](https://apim.docs.wso2.com/en/latest/design/create-api/create-a-graphql-api/#step-2-design-a-graphql-api), there are two broken links:

- [Adding Users](https://apim.docs.wso2.com/en/latest/design/administer/managing-users-and-roles/managing-users/)
- [Adding User Roles](https://apim.docs.wso2.com/en/latest/design/administer/managing-users-and-roles/managing-user-roles/)

**Suggested Labels:**
type/docs

**Affected Product Version:**
4.3.0

**Comment by rmsamitha** [comment]
4.3.0 fix: https://github.com/wso2/docs-apim/pull/8096
master fix: https://github.com/wso2/docs-apim/pull/8092
