### ISSUE TITLE
Content issues in 'Kerberos OAuth2 Grant'

### ISSUE THREAD

**Issue by lathlk** [wso2/docs-apim#808]
**Description:**
Need to update the 3rd step in [https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/grant-types/kerberos-oauth2-grant/#configuring-kerberos-grant-with-api-manager](https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/grant-types/kerberos-oauth2-grant/#configuring-kerberos-grant-with-api-manager) as below. 

1) Replace the 1st line attachment to 'org.wso2.carbon.identity.application.authenticator.iwa-5.3.13.jar' which can be found in [https://drive.google.com/file/d/1ICQhdTNvCasnHLW6HEG9sANS8WBIZJbx/view](https://drive.google.com/file/d/1ICQhdTNvCasnHLW6HEG9sANS8WBIZJbx/view)
2) Remove the 2nd line which is 'org.wso2.carbon.identity.idp.metadata.saml2_1.0.1.jar'.

Suggestions,

It's better if we can include the sample client information as in the identity server documentation [https://is.docs.wso2.com/en/latest/learn/kerberos-grant/#configuring-kerberos-grant-with-the-identity-server](https://is.docs.wso2.com/en/latest/learn/kerberos-grant/#configuring-kerberos-grant-with-the-identity-server) in step 6.

**Affected Product Version:**
3.0.0

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/821
