### ISSUE TITLE
Configuration missing for on demand loading

### ISSUE THREAD

**Issue by dushaniw** [wso2/docs-apim#8081]
**Description:**
Documentation is not updated for on demand loading feature  https://github.com/wso2/carbon-apimgt/pull/11651/files in 4.2, 4.3 and u2 updated 4.0 and 4.1.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RusJaI** [comment]
update [2024-11-20]
master fix : https://github.com/wso2/docs-apim/pull/8863

**Comment by RusJaI** [comment]
### Update [2024-11-21]

Added documentation for following U2 updated versions : 

APIM 4.1.0 : https://github.com/wso2/docs-apim/pull/8873
APIM 4.0.0 : https://github.com/wso2/docs-apim/pull/8874
