### ISSUE TITLE
Advance UI Customization Paths are Wrong

### ISSUE THREAD

**Issue by athiththan11** [wso2/docs-apim#8152]
## Description

The UI paths to the Devportal, Publisher, Admin Webapps under [this](https://apim.docs.wso2.com/en/latest/reference/customize-product/customizations/advanced-ui-customization/) has wrong paths specified. For example

- The path mentioned as `devportal/src/main/webapp/source` is not available in the WSO2 API Manager packs and has been replaced with `devportal/source` 

### Affected Product Version

- WSO2 API Manager v4.2.0
- WSO2 API Manager v4.3.0
- Have to verify previous versions of V4 as well

**Comment by msm1992** [comment]
- Already Fixed in master and 4.4.0 with https://github.com/wso2/docs-apim/pull/8251.
- Already fixed in 4.3.0 with https://github.com/wso2/docs-apim/pull/8252
- 4.2.0 : https://github.com/wso2/docs-apim/pull/8253
