### ISSUE TITLE
[DOC] Including details on tenant deletion

### ISSUE THREAD

**Issue by lkokila** [wso2/docs-apim#817]
**Description:**

The following documents [1][2] should be updated with the steps and the complications of deleting tenants in the API-Manager server. These should be updated with details on using the "TenantMgtAdminService" to delete the tenants instead of using "RemoteTenantManagerService". 

[1]. https://docs.wso2.com/display/AM260/Managing+Tenants
[2]. https://apim.docs.wso2.com/en/latest/administer/product-administration/multitenancy/managing-tenants/

This is further explained in the following issue [3] created in carbon-kernel. And the relevant steps are discussed in the following pull request [4]. 

[3]. https://github.com/wso2/carbon-kernel/issues/1967
[4]. https://github.com/wso2/carbon-kernel/pull/1923

**Affected Product Version:**

APIM-2.6.0
APIM-3.0.0

**Comment by Mariangela** [comment]
@lkokila , thanks for reporting! We need more clarification in this regard. We will reach out to you soon.

**Comment by vithu30** [comment]
The configuration to enable tenant deletion is not templated in `carbon.xml.j2` file in 3.x versions. Created [1] to track this. We need to update doc space of 3.x version after fixing this issue in 3.x version.

[1] https://github.com/wso2/product-apim/issues/9352

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
