### ISSUE TITLE
am_db reference in wso2am-3.0.0 and wso2am-analytics-3.0.0 

### ISSUE THREAD

**Issue by saranki** [wso2/docs-apim#818]
**Description:**
The AM_DB is the main data source used in the API Manager. This is referred to as "am_db" [1] in wso2am-analytics and the "apim_db"[2] in wso2am configurations documentations. Even though these 2 names are referring to the same database it might confuse users and may lead the users to create 2 different databases. 

[1] https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/#quick-setup
[2] https://apim.docs.wso2.com/en/latest/install-and-setup/setting-up-databases/changing-default-databases/changing-to-postgresql/

**Suggested Labels:**

wso2am-3.0.0
wso2am-analytics-3.0.0 

**Affected Product Version:**
wso2am-3.0.0
wso2am-analytics-3.0.0

**Comment by Mariangela** [comment]
@bhathiya / @tharindu1st , what is the correct or the best terminology, because when I did a search I noticed that both terms have been used in multiple pages in the documentation.

**Comment by fazlan-nazeem** [comment]
We can't get rid of those two terms as the config files in apim and apim analytics refers to them with those names. Maybe we can add a note saying that both are the same under configuring analytics documentation.
