### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by krishnia92** [wso2/docs-apim#8276]
Location : https://apim.docs.wso2.com/en/latest/get-started/api-manager-quick-start-guide/

1. Creating and publishing an API via the Publisher Portal of WSO2 API-M.
should be corrected as 

1. Creating an API via the Publisher Portal of WSO2 API-M.

Publishing part is specified as step 3

**Comment by ashera96** [comment]
We have revamped the quick start guide, and this issue is no longer applicable. Hence, closing the isssue.
