### ISSUE TITLE
"Monitor Integration Transaction Counts" page link doesn't work

### ISSUE THREAD

**Issue by lahirugmg** [wso2/docs-apim#8322]
**Description:**

Under "Deployment Best Practices" there is a link for "Monitor Integration Transaction Counts" and it goes to "page not found" page.

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-best-practices/changing-the-default-ports-with-offset/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 4.3.0 docs

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Tharanidk** [comment]
From 4.3.0 onwards, MI related documents are removed from APIM docs. Hence,  "Monitor Integration Transaction Counts" page navigation should be removed.
