### ISSUE TITLE
Doc Feedback: Removing SI references from APIM docs

### ISSUE THREAD

**Issue by viggnah** [wso2/docs-apim#8324]
Location : https://apim.docs.wso2.com/en/latest/get-started/streaming-quick-start-guide/

AFAIK we are no longer promoting SI as it's on the path to deprecation, so shouldn't we remove these references?

**Comment by ashera96** [comment]
This will be addressed via [1] for 4.4.0.

1. https://github.com/wso2/docs-apim/pull/8531
