### ISSUE TITLE
Need to add the chatacter case limitation details under the gov registry level when assigning roles to the Publisher Access Control roles list [APIM 4.x.x]

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/docs-apim#8330]
**Description:**
Need to add the character case limitation details under the gov registry level when assigning roles to the Publisher Access Control roles list. Currently, the gov registry is only supporting lower case roles under the API meta artifact properties.

**Affected Product Version:**
APIM 4.x.x

**Comment by RusJaI** [comment]
### Update [2024-11-18]
Added the following PRs : 
Master : https://github.com/wso2/docs-apim/pull/8826
4.4.0 : https://github.com/wso2/docs-apim/pull/8836
4.3.0 : https://github.com/wso2/docs-apim/pull/8837
4.2.0 : https://github.com/wso2/docs-apim/pull/8838
4.1.0 : https://github.com/wso2/docs-apim/pull/8839
4.0.0 : https://github.com/wso2/docs-apim/pull/8840
