### ISSUE TITLE
Typo in install-and-setup documentation

### ISSUE THREAD

**Issue by raymondsquared** [wso2/docs-apim#8333]
**Description:**
Typo on docker installation instruction on:
- https://apim.docs.wso2.com/en/latest/install-and-setup/install/installing-the-product/installing-in-containers/installing-si-using-docker/

**Suggested Labels:**
API-M-4.3.0

**Comment by ashera96** [comment]
Merged the 4.3.0 PR and closed the master PR as it is no longer applicable for APIM documentation.
