### ISSUE TITLE
User-info endpoint needs to be changed in the example section when the IS as configured as KM 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/docs-apim#8340]
**Description:**
Doc [1] example section should be changed from 
```https://localhost:9444/oauth2/userinfo?schema=openid```
to

```https://localhost:9444/keymanager-operations/user-info/claims/generate```

[1] https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-keycloak-connector/#step-2-configure-wso2-api-manager

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 4.x

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RusJaI** [comment]
### Update [2024-11-04]

Master branch PR : https://github.com/wso2/docs-apim/pull/8664
4.4.0 PR : https://github.com/wso2/docs-apim/pull/8665
