### ISSUE TITLE
Updating APIM 4.X.X documentation to include configuration for supporting Multiple Active Access Tokens.

### ISSUE THREAD

**Issue by SameeraSI** [wso2/docs-apim#8376]
**Description:**

The following configuration regarding Multiple Active Access Tokens is well-documented in the APIM 3.2.0 documentation[1]:
```
[oauth.jwt.renew_token_without_revoking_existing]
enable = true
allowed_grant_types = [“client_credentials”, “password”]
```

However, it appears that this configuration is not included in the APIM 4.X.X documentation, and the APIM 4.X.X documentation needs to be updated to include this configuration.

[1]https://apim.docs.wso2.com/en/3.2.0/learn/api-security/oauth2/multiple-active-access-tokens/

**Suggested Labels:**
APIM 4.0.0
APIM 4.1.0
APIM 4.2.0
APIM 4.3.0

**Comment by RusJaI** [comment]
### Uodate [2024-11-01]
Addressed via following Pull requests : 

- APIM 4.0.0 : https://github.com/wso2/docs-apim/pull/8618
- APIM 4.1.0 : https://github.com/wso2/docs-apim/pull/8619

**Comment by RusJaI** [comment]
The fix has been provided for a specific customer usecase. Hence currently it's available only in APIM 3.2.0 and 3.2.1.
Hence the documentation for 4.x versions is not applicable.

**Comment by iloshinik** [comment]
Hi @RusJaI,

This feature is available OOTB in the APIM 4.x.x versions. Hence, it is not only applicable to specific customers. Since many other customers are looking for the documentation for 4.x.x versions, appreciate if you could include this configuration in the latest doc space as well.

Thanks,
Iloshini

**Comment by SameeraSI** [comment]
Hi @RusJaI,

I created this doc issue [1] to improve the multiple-active-access-tokens documentation [2]. We would greatly appreciate it if you could take the necessary actions to address this issue as well.

[1] https://github.com/wso2/docs-apim/issues/8956
[2] https://apim.docs.wso2.com/en/4.2.0/design/api-security/oauth2/multiple-active-access-tokens/

Thanks,
Sameera
