### ISSUE TITLE
Doc Feedback: Missing config in ELK setup guide

### ISSUE THREAD

**Issue by viggnah** [wso2/docs-apim#8377]
Location : https://apim.docs.wso2.com/en/latest/api-analytics/on-prem/elk-installation-guide/

The following block should be present - 
```toml
[apim.analytics]
enable = true
type = "elk"
```
>![Screenshot 2024-09-12 at 3 11 20 PM](https://github.com/user-attachments/assets/d40711e0-b9ea-4e6e-8def-8ee6c5f3ff39)

It was correctly present in APIM 4.2.0 docs - 
>![Screenshot 2024-09-12 at 3 12 48 PM](https://github.com/user-attachments/assets/8b2cdaff-11b9-4df9-9c52-f7bbe94bd0de)

**Comment by ashera96** [comment]
Closing this issue since this is lready fixed in 4.3.0 and 4.4.0.
