### ISSUE TITLE
Bot Detection feature's use-case is not clear

### ISSUE THREAD

**Issue by nirmal070125** [wso2/docs-apim#839]
**Description:**

https://apim.docs.wso2.com/en/latest/learn/api-security/threat-protection/bot-detection/

It sounded like we can detect unauthorized API calls and gives the impression that this will detect DDoS attacks. But it seems it's rather different use-case.

"Bot detection doesn’t detect a scenario such as the one you mentioned. There is a service deployed in the gateway which will log and send events to analytics if it receives any traffic. This event can then be configured to send emails alerts and also shown in the bot detection dashboard in admin portal.

The idea behind this is, port scanning tools could detect an unadvertised service and if such a service receives traffic, it could possibly be a bot.

If you call the following URL. The bot detection log file will log information regarding the source.

Https://localhost:8243/service/*
" - @fazlan-nazeem 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
@fazlan-nazeem , we need more clarification in this regard. We will reach out to you soon.
