### ISSUE TITLE
One of the hyper links in the "Working with the Source Code" page does not work

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/docs-apim#840]
**Description:**
The third hyperlink of "Contributing to the Code Base" in the page "Working with the Source Code" (https://github.com/wso2/docs-apim/blob/master/en/docs/develop/working-with-the-source-code.md) directs to a dead link (https://github.com/wso2/docs-apim/blob/master/en/docs/develop/index) in GitHub.

**Affected Product Version:**
APIM 3.0

**Comment by Mariangela** [comment]
Fixed in:
- 3.1.0 - https://github.com/wso2/docs-apim/pull/841
- 3.0.0 - https://github.com/wso2/docs-apim/pull/842
