### ISSUE TITLE
Sublink in doc points to 4.20 instead of 4.30

### ISSUE THREAD

**Issue by Chilliwiddit** [wso2/docs-apim#8422]
**Description:**
The sublink "Add an API Category using the Admin Portal UI" in the "API Category based Grouping" doc points to the the 4.2.0 version instead of the 4.3.0 version of the sublink method.

**Suggested Labels:**
Incorrect link

**Steps to reproduce:**
Click the link "Add an API Category using the Admin Portal UI" and instead of being taken to the method a few lines down the page, you'll be redirected to the same method in the 4.2.0 version of the doc.

**Comment by msm1992** [comment]
Master doc PR : https://github.com/wso2/docs-apim/pull/8535
4.3.0 doc PR : https://github.com/wso2/docs-apim/pull/8536
4.4.0 doc PR : https://github.com/wso2/docs-apim/pull/8537
