### ISSUE TITLE
Fine Grained Access Control with OAuth Scopes¶ doc needs to be updated.

### ISSUE THREAD

**Issue by Chilliwiddit** [wso2/docs-apim#8427]
**Description:**
In the Fine Grained Access Control with OAuth Scopes doc, under the Local Scopes section the doc does not include that when creating the local scope there is a Scope Display name which is available for local scopes.

**Affected Product Version:**
APIM 4.4.0

**Comment by RusJaI** [comment]
### Update [2024-11-04]

Corresponding doc URL : https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes/

Since the existing behaviour leads to a confusion whether we need this field or not, a separate issue was opened to track it
