### ISSUE TITLE
Doc Feedback: replace store with devportal

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#843]
Location : https://apim.docs.wso2.com/en/latest/learn/consume-api/customizations/customize-the-api-store-and-gateway-urls-for-tenants/

We need to change the title "Customize the API Store and Gateway URLs for Tenants" to "Customize the API Developer Portal and Gateway URLs for Tenants" and all the other applicable places.

**Comment by Mariangela** [comment]
Created two sub-tasks to handle the following docs:
- Config Catalog - https://github.com/wso2/docs-apim/issues/851
- REST API - https://github.com/wso2/docs-apim/issues/852

**Comment by Mariangela** [comment]
Fixed for 3.1.0 in https://github.com/wso2/docs-apim/pull/848

**Comment by Mariangela** [comment]
Fixed for 3.0.0 docs in https://github.com/wso2/docs-apim/pull/853
