### ISSUE TITLE
Rest API version should be v0.16 in the APIM 3.1.0 documetaion 

### ISSUE THREAD

**Issue by chathuranga95** [wso2/docs-apim#846]
**Description:**
The RESTFUL API version should be changed from v0.15 to v0.16 for the product version: 3.1.0

**Affected Product Version:**
3.1.0

**Comment by Mariangela** [comment]
@chathuranga95 , don't you mean 3.1.0 instead of 3.0.1?

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/1130
