### ISSUE TITLE
Incorrect curl commands for import/export API Polices

### ISSUE THREAD

**Issue by RusJaI** [wso2/docs-apim#8466]
**Description:**
In the APIM 4.2.0 documentation the provided url in the curl command is incorrect in operation policy import/export flows. (It should be operation-policies/ instead of policies and better if could describe the params as well) Please check this in other 4.x docs as well.
 
<img width="1490" alt="Screenshot 2024-10-09 at 17 16 28" src="https://github.com/user-attachments/assets/a8579349-7799-4b45-acde-5594325d4c23">

**Suggested Labels:**

**Affected Product Version:**

APIM 4.2.0

**Comment by ashera96** [comment]
Closing since this is already fixed.
