### ISSUE TITLE
Doc should mention that the business plan that is to be changed to should be added as well to the API

### ISSUE THREAD

**Issue by Chilliwiddit** [wso2/docs-apim#8467]
**Description:**
In the doc for the APIM Publisher API (https://apim.docs.wso2.com/en/4.4.0/reference/product-apis/publisher-apis/publisher-v4/publisher-v4/#tag/Subscriptions/operation/changeSubscriptionBusinessPlan), it does not mention the fact that the business plan that is desired to be switched to should be also added to the API.

**Suggested Labels:**
-APIM
-Publisher API

**Affected Product Version:**
4.4.0

**Comment by PasanT9** [comment]
Those information need not be added under description of the REST API.
