### ISSUE TITLE
Better explanation of how disabling subscription requirement on a tenant and global level needed

### ISSUE THREAD

**Issue by Chilliwiddit** [wso2/docs-apim#8469]
**Description:**
In the Disable Subscription Requirement doc (https://apim.docs.wso2.com/en/4.4.0/design/advanced-topics/disable-subscriptions-for-an-api/) under the Prevent disabling subscription requirement for an API section, the proper explanation on how disabling subscription validation on a global and tenant level works is not properly explained.

Proper explanation:-
Allowing subscription validation disabling is set to false by default in each tenant-conf.json file but this is ignored. However, when subscription validation is enabled in the deployment.toml this is applied to all tenants excepted for tenants where allow subscription validation is set to true, allowing them to exempt from this global rule.

**Suggested Labels:**
-Publisher API

**Affected Product Version:**
4.4.0

**Comment by PasanT9** [comment]
Since this is a configuration which is applicable to all features no need to add separately for each feature.
