### ISSUE TITLE
Change the documenation on exporting an API, by specifying that the provider name is optional

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/docs-apim#847]
**Description:**
A fix has been made in https://github.com/wso2/carbon-apimgt/pull/8359 and https://github.com/wso2/product-apim-tooling/pull/193, to make --provider (-r) flag optional when exporting an API. 

Docs should change here: https://github.com/wso2/docs-apim/blob/master/en/docs/learn/api-controller/migrating-apis-to-different-environments.md#export-an-api

!!! info **Flags:** section should change like below by adding --provider as an optional flag 
    
            -    Required :  
                `--name` or `-n` : Name of the API to be exported  
                `--version` or `-v` : Version of the API to be exported   
                `--environment` or `-e` : Environment to which the API should be exported  
            -   Optional :  
                `--provider` or `-r` : Provider of the API        
                `--preserveStatus` : Preserve API status when exporting. Otherwise, the API will be exported in the `CREATED` status. The default value is `true`.  
                `--format` : File format of exported archive (JSON or YAML). The default value is YAML.
            
!!! example section should change like below (remove "-r admin" in the first example)
            ```go
            apictl export-api -n PhoneVerification -v 1.0.0 -e dev -k
            ```
            ```go
            apictl export-api -n PizzaShackAPI -v 1.0.0 -r Alice -e dev --preserveStatus=true --format JSON -k
            ```            

**Affected Product Version:**
APIM 3.1

**Related Issues:**
https://github.com/wso2/product-apim-tooling/issues/173

**Comment by Mariangela** [comment]
Fixed in 
- https://github.com/wso2/docs-apim/pull/873/commits/5c5af9f814e8214a97bf9adaeab3c389ca196848
- 3.1.0 Docs - https://apim.docs.wso2.com/en/next/learn/api-controller/migrating-apis-to-different-environments/#export-an-api

**Comment by malinthaprasan** [comment]
Tagging https://github.com/wso2/product-apim-tooling/issues/225
