### ISSUE TITLE
Change configurations in Generate SDKs in Developer Portal

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/docs-apim#849]
**Description:**
Change configurations in Generate SDKs in Developer Portal doc to following
[apim.sdk]
supported_languages = ["android", "java", "scala", "csharp", "dart", "flash", "groovy", "javascript"]

**Comment by Mariangela** [comment]
@kavishkafernando , is this applicable to 3.0.0 and 3.1.0 as well?

**Comment by kavishkafernando** [comment]
3.1.0 yes. Should be the same for 3.0.0 as well.

**Comment by Mariangela** [comment]
@erangatl , do you think you can test this for 3.0.0 as well, please?

**Comment by Mariangela** [comment]
Fixed in 
- 3.0.0 - https://github.com/wso2/docs-apim/pull/860
- 3.1.0 - https://github.com/wso2/docs-apim/pull/858
- Reviewed and updated the document as well.
