### ISSUE TITLE
Create new API - REST API's body is incorrect

### ISSUE THREAD

**Issue by chathuranga95** [wso2/docs-apim#850]
**Description:**

The create new API's body on [publisher API](https://apim.docs.wso2.com/en/next/develop/product-apis/publisher-v0.15/#/API%20(Individual)/post_apis) should be corrected. Suggestion: [This](https://docs.wso2.com/display/AM260/apidocs/publisher/#!/operations#APIIndividual#apisPost) previous version's payload can be used.

**Affected Product Version:**
3.1.0, 3.0.0

**Comment by Mariangela** [comment]
@chathuranga95 , is this applicable to 3.0.0 as well?

**Comment by chathuranga95** [comment]
> @chathuranga95 , is this applicable to 3.0.0 as well?

Yes.

**Comment by Mariangela** [comment]
Fixed in 3.0.0 in https://github.com/wso2/docs-apim/issues/1124 >> https://github.com/wso2/docs-apim/pull/1398

**Comment by Sarangan0219** [comment]
Fixed in 3.1.0 with https://github.com/wso2/docs-apim/pull/1911.

Hence this issue can be closed.
