### ISSUE TITLE
Remove `$` signs from commands that one can copy directly from docs

### ISSUE THREAD

**Issue by ashera96** [wso2/docs-apim#8517]
**Description:**

We have to check commands that one can directly copy from docs and execute. Those should not contain the `$` character as that would require the end user to remove that character before actually going ahead and using the command. Some sample scenarios that need to be fixed are:
- Step 6 under https://apim.docs.wso2.com/en/4.4.0/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects/#add-dynamic-data-to-operation-policies-in-an-api-project
- Note under step 5 https://apim.docs.wso2.com/en/4.4.0/install-and-setup/setup/security/configuring-transport-level-security/#disabling-weak-ciphers-for-the-tomcat-transport
- Step 3 under before you begin section of https://apim.docs.wso2.com/en/4.4.0/get-started/api-manager-quick-start-guide/ should be copiable. Should be changed from `sh api-manager.sh` to;
```
sh api-manager.sh
```

**Comment by msm1992** [comment]
4.4.0 : https://github.com/wso2/docs-apim/pull/8549
