### ISSUE TITLE
 Documentation change request regarding OS-level settings 

### ISSUE THREAD

**Issue by dinuka10** [wso2/docs-apim#8550]
Hi  Team,

We've encountered a few scenarios where customers have experienced issues after applying OS-level settings recommended in our documentation [1].

For instance, in one case, a customer set net.ipv4.tcp_tw_reuse to 1 on the OS hosting APIM, as suggested. This led to intermittent connection termination on the backend (Windows servers or Azure AKS) under high traffic conditions, specifically when new connections attempted to reuse TCP sockets still in the TIME-WAIT state from previous connections.

Since the issue doesn't occur with net.ipv4.tcp_tw_reuse set to 0, the customer incorrectly assumes it's a product-level problem with APIM.

To clarify this, its better if we can update the documentation to emphasize the following:

1. These settings are recommendations and not mandatory requirements for APIM.
2. They are OS-level configurations and not specific to APIM.
3. Customers should carefully consider obtaining advice from their specific OS vendor to understand the potential impact of these settings on their unique environments before applying them

[1] https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/deployment-best-practices/tuning-performance/#os-level-settings

[2] https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/deployment-best-practices/tuning-performance/#os-level-settings:~:text=net.ipv4.tcp_tw_reuse%20%3D%201

Thanks and regards,
Dinuka

**Comment by PasanT9** [comment]
Hi @dinuka10,

The point you made are already explained in the mentioned doc. Let me quote the doc.

`This section describes some recommended performance tuning configurations to optimize WSO2 API Manager. It assumes that you have set up the API Manager on Unix/Linux, which is recommended for a production deployment.`

`The values that WSO2 discusses here are general recommendations. They might not be the optimal values for the specific hardware configurations in your environment. WSO2 recommends that you carry out load tests on your environment to tune the API Manager accordingly.`

**Comment by PasanT9** [comment]
Will close the issue for now. Please reopen if you need to discuss this further.
