### ISSUE TITLE
Doc Feedback: Typo in documentation

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/docs-apim#868]
Location : https://apim.docs.wso2.com/en/latest/administer/product-security/multi-factor-authentication-mfa-for-publisher-and-developer-portals/

There is a typo in this documentation. Please refer the following screenshot.
![image](https://user-images.githubusercontent.com/19262008/76963092-7a609a80-6946-11ea-8757-e027fadff0d3.png)

**Comment by Mariangela** [comment]
Fixed in 
- 3.1.0 - https://github.com/wso2/docs-apim/pull/873/commits/e35e819cec1614369659878998375c9525eaadcb
- 3.0.0 - https://github.com/wso2/docs-apim/pull/871/commits/b1e9e754f137f6dbbc1b584a99b565016acf8d61

**Comment by Mariangela** [comment]
@bhathiya / @tgtshanika , any idea why this page is not listed on the left nav menu https://apim.docs.wso2.com/en/latest/administer/product-security/multi-factor-authentication-mfa-for-publisher-and-developer-portals/ ? Shall I add it to the left Navigation?
