### ISSUE TITLE
Doc Feedback: duplicate content

### ISSUE THREAD

**Issue by isharac** [wso2/docs-apim#870]
Location : https://apim.docs.wso2.com/en/latest/learn/design-api/advanced-topics/adding-an-api-state-change-workflow/

Configuring WSO2 E Step 2 and 3 explains the same thing.

**Comment by Mariangela** [comment]
Fixed in
- 3.0.0 - https://github.com/wso2/docs-apim/pull/871
- 3.1.0 - https://github.com/wso2/docs-apim/pull/873
