### ISSUE TITLE
Issues when changing the API-M version in the documentation using the dropdown list

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/docs-apim#8710]
### Description

- When in the latest version [1] we can not go to the 4.3.0 documentation by clicking `4.3.0` in the dropdown. It directs to the latest documentation

![image](https://github.com/user-attachments/assets/b080f72d-d09b-480c-ba7e-5ab311078a77)

- When in the older version of docs, we can not see the 4.4.0 version in the drop down.

![Screenshot 2024-11-06 at 16 39 25](https://github.com/user-attachments/assets/51b74341-4456-479b-845b-3f8762730f84)

[1] - https://apim.docs.wso2.com/en/latest/

**Comment by Tharanidk** [comment]
This issue is not reproducing.
