### ISSUE TITLE
Adding the steps needed to generate tokens with the correct scope when invoking the product APIs in API Manager 3.0

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/docs-apim#889]
**Description:**
$subject

We need to document the steps needed to generate an access token with the correct scope which is used when invoking the product APIs as in [1]

1) Obtain the consumer key and secret key pair by calling the dynamic client registration endpoint

curl -k -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d @payload.json https://localhost:9443/client-registration/v0.15/register

2) Obtain an access token with the correct scope needed to invoke the particular API resource by providing the consumer key and secret pair generated

curl -k -d "grant_type=password&username=admin&password=admin&scope=<correct_scope>" -H "Authorization: Basic basic64encoded<clientId:clientSecret>" https://localhost:8243/token

Also, we need to specify the scope mapping for each resource in the resource documentation as given in [1] under each resource (OAuth 2.0 Scope)

[1] [https://docs.wso2.com/display/AM260/apidocs/store/index.html#guide](https://docs.wso2.com/display/AM260/apidocs/store/index.html#guide)

**Affected Product Version:**
API Manager 3.0

**Comment by msm1992** [comment]
Fixed this in 3.0.0 with https://github.com/wso2/docs-apim/pull/2714. In 3.1.0 and 3.2.0 versions, this information is shown on the redocly api documentation page itself as below.

![auth](https://user-images.githubusercontent.com/28379317/102872812-4763ae00-4466-11eb-9592-8aaa5d7558d8.png)
