### ISSUE TITLE
FAQ section needs to be updated with latest config changes

### ISSUE THREAD

**Issue by pubudu538** [wso2/docs-apim#907]
**Description:**
At the moment FAQ has xml based configs. We should change those to toml based configs.

https://apim.docs.wso2.com/en/latest/reference/faq/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by vithu30** [comment]
The section is updated in 3.1, 3.2 and master. There is a section related to XMLInputFactory.properties needs to be updated in 3.0.0 docs, once [1] is fixed.

[1] https://github.com/wso2/product-apim/issues/9401
