### ISSUE TITLE
Sections in the Reference tab should be reviewed and properly formatted

### ISSUE THREAD

**Issue by npamudika** [wso2/docs-apim#909]
**Description:**
The following should be addressed.

- The 3 pages under "Guides" (https://apim.docs.wso2.com/en/latest/reference/guides/directory-structure-of-wso2-products/) contain formatting issues as below.
 ![Selection_061](https://user-images.githubusercontent.com/8363838/77524478-6a4c3c00-6ead-11ea-94ac-4f54afca7100.png)

- The pages under "Samples" (https://apim.docs.wso2.com/en/latest/reference/samples/) contain formatting issues as mentioned above and contains UI screenshots from older versions.

- The section "Other" (https://apim.docs.wso2.com/en/latest/reference/other/) is not required as it contains nothing useful.
 ![Selection_060](https://user-images.githubusercontent.com/8363838/77524611-a4b5d900-6ead-11ea-9769-9331e32ac95d.png)

**Comment by pubudu538** [comment]
@Jayanie is working on this issue.

**Comment by Jayanie** [comment]
The 2nd point has been mentioned in issue #1388
