### ISSUE TITLE
Home page is not responsive 

### ISSUE THREAD

**Issue by pahans** [wso2/docs-apim#93]
**Description:**
home page is not responsive for smaller screens.
![](https://www.evernote.com/l/AK9Ts2YL0INNwbl4VPCXC8J2s6qr-pKm0fYB/image.png)

In some resolutions, we can only see half of some buttons.
![](https://www.evernote.com/l/AK_aUcPm8UlCW7r2kiqK2QtDHIS3uT29jnQB/image.png)

**Comment by erangatl** [comment]
Related #91
