### ISSUE TITLE
adminServiceBaseUrl in the Analytics Dashboard needs to change when configuring with APIM distributed setup.

### ISSUE THREAD

**Issue by Gayanthakaushal** [wso2/docs-apim#937]
**Description:**
**adminServiceBaseUrl** in the Analytics Dashboard needs to change when configuring with APIM distributed setup.
In the APIM distributed setup, we have to remove this config and use publisher URL in the implementation.
(This configuration can find in the <wso2am-analytics-3.0.0>/conf/dashboard/deployment.yaml file.)
This point needs to address in the official document[1].

[1] - https://apim.docs.wso2.com/en/latest/learn/analytics/configuring-apim-analytics/

**Suggested Labels:**
APIM-3.0.0

**Comment by ruwiniwj** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/1114
