### ISSUE TITLE
APIM 3.0 Broken documentation link

### ISSUE THREAD

**Issue by himasha** [wso2/docs-apim#956]
Following link is broken. ' 'Learn -> Extensions -> Editing API Templates'

**Comment by Mariangela** [comment]
@tgtshanika , don't we need the content related to Editing API Templates [1] in 3.0.0 and 3.1.0?

[1] https://docs.wso2.com/display/AM260/Editing+API+Templates

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/1049
