### ISSUE TITLE
Links not working in "Production Deployment Guidelines" doc

### ISSUE THREAD

**Issue by rmsamitha** [wso2/docs-apim#960]
**Description:**

The links in below lines are not working. Need to fix the links to point to the expected page/section.

https://github.com/wso2/docs-apim/blame/master/en/docs/install-and-setup/deploying-wso2-api-manager/production-deployment-guidelines.md#L166-L167

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Mariangela** [comment]
Fixed in

https://github.com/wso2/docs-apim/pull/1378 | 3.0.0
-- | --
https://github.com/wso2/docs-apim/pull/1377 | 3.1.0
https://github.com/wso2/docs-apim/pull/1376 | master
