### ISSUE TITLE
Need to update product compatibility 

### ISSUE THREAD

**Issue by Krishanx92** [wso2/docs-apim#961]
**Description:**
We need to add the following tested versions to the doc[1] as well.

MySQL 5.7, 8
Oracle 12c and 19c
Microsoft SQL Server 2017
PostgreSQL 10
DB2 - need to verify

Tested WSO2 Products

IS -5.10.0
EI - 6.6.0

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/product-compatibility/#tested-operating-systems-and-jdks

**Comment by Mariangela** [comment]
Fixed in https://github.com/wso2/docs-apim/pull/1027
