### ISSUE TITLE
Adding profile optimization related configuration steps in the docs

### ISSUE THREAD

**Issue by rmsamitha** [wso2/docs-apim#984]
**Description:**
Profile optimization related steps has been removed from docs after the 2.2.0 docs.
i.e.
Steps are there in 2.2.0 - [1]
Removed in 2.5.0 - [2]

But these steps should be in the docs so that a user can manually do the profile optimization. (Required a doc for configuration changes only. Other steps such as .war deletion, are not required to be in the docs. ). This is required for K8s scenarios where configurations are maintained in a config map.

Anyway should highlight the fact that what we recommend is profile optimization via scripts. (not manually).

Steps related to each profile can be extracted from profileSetup.sh and profile related deployment.toml sample file.

Needs docs to be fixed in 2.5.0, 2.6.0, 3.0.0, 3.1.0.

[1] https://docs.wso2.com/display/AM220/Product+Profiles#KM
[2] https://docs.wso2.com/display/AM250/Product+Profiles

**Comment by Mariangela** [comment]
@lakwarus  , please clarify. I believe that these steps were initially taken off based on a discussion that I had with you and some others.

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
