### ISSUE TITLE
Update analytics geo location configuration related docs for APIM Analytics 2.6.0

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/docs-apim#985]
**Description:**
Need to update the analytics geo location related docs for APIM Analytics 2.6.0 version. Changes done in https://github.com/wso2/docs-apim/pull/902 and https://github.com/wso2/docs-apim/pull/913 should be considered when doing this change.

**Suggested Labels:**
Improvement

**Suggested Assignees:**
@Mariangela 

**Affected Product Version:**
API Manager Analytics 2.6.0

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
